### ISSUE TITLE
Misalignment with frozen columns

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#6560] opened 2018-09-25 09:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The issue was marked as solved and closed here: #5485 but it still persists for version 6.1.4, as also the table in the docs shows:

![image](https://user-images.githubusercontent.com/4947529/46006923-f6af5000-c0b8-11e8-97f7-87d9e32fefc1.png)

The problem is the scrollbar, it should appear outside the table border, and not inside.

EDIT: the bug persists with Google Chrome. With Firefox it seems ok, despite of a weird animation on the headers during the scroll

**Comment by JacobSiegle** [comment] 2018-09-25 13:01
I don't think your issue is the same bug as #5485 but is related. In #5485 the table would always render incorrectly. In the newer versions it only renders incorrectly when resizing happens. Maybe you can retest and see if that is the case for you also, because you mentioned Firefox works but it's not working correctly for me when resizing. Both Firefox and Chrome do work correctly first render.

**Comment by pierfreeman** [comment] 2018-09-25 13:11
Yes you are right, if I resize the window and then refresh the page, the table is rendered correctly. At least, on the primeNg doc website.

The table in my application still renders wrongly even at the first time with Chrome (you may not see the misaligned due to the dark colors, but there is):

![image](https://user-images.githubusercontent.com/4947529/46016369-e2794c00-c0d4-11e8-9d19-2121f2e70fc2.png)

With Firefox, everything is good, both at first render and after a window resize.

**Comment by pierfreeman** [comment] 2018-09-25 13:13
Yes you are right, if I resize the window and then refresh the page, the table is rendered correctly. At least, on the primeNg doc website.

The table in my application still renders wrongly even at the first time with Chrome (you may not see the misaligned due to the dark colors, but there is):

![image](https://user-images.githubusercontent.com/4947529/46016634-98dd3100-c0d5-11e8-8709-66167a3e6c77.png)

With Firefox, everything is good, both at first render and after a window resize.

**Comment by nikpundik** [comment] 2018-09-26 10:30
Couple of questions:

1) Why is it setting the maxHeight based on the outerWidth? 
https://github.com/primefaces/primeng/blob/f29be5ad062c22e47f74d0f10a7d0baa03bc1418/src/app/components/table/table.ts#L2023

2) About resizing or data changes, could it be related to this line in ngAfterViewChecked? Wrapping it in a setTimeout function updates height correctly
https://github.com/primefaces/primeng/blob/f29be5ad062c22e47f74d0f10a7d0baa03bc1418/src/app/components/table/table.ts#L1888

**Comment by JacobSiegle** [comment] 2018-09-26 13:40
1 - It's checking the view width because if the width is larger the the scroll container that means a scroll bar will exist on the bottom and if a scroll bar exists on the bottom it needs to offset the height to match up with the unfrozen part.

2 - Looking at ngAfterViewChecked I see it checks a var called initialized. When initialized is set setScrollHeight is not being called again. The issue with the responsiveness is that it needs to call setScrollHeight in case the view changed which caused it to not have the scrollbar anymore. They have something similar to the needed call in the file where they are subscribing to col changes and running setScrollHeight.

I don't know if fixing either of those will fix whatever is wrong with pierfreeman table because the primeNG docs example seem to work in the scenario he's saying his doesn't. I think we would need a stackblitz to look into why his doesn't work.

If you would like to try to PR a fix you can, I don't like PRing for turbo table.

**Comment by JacobSiegle** [comment] 2018-10-02 01:36
It also seems like if the table is hidden (maybe you show a loading screen) the scrollbar will be misaligned, wild guess that's pierfreeman issue.

**Comment by cagataycivici** [comment] 2018-10-12 20:18
I can't replicate this, I've merged @JacobSiegle's PR although not sure if it is related. Provide a stackblitz template please.

**Comment by JacobSiegle** [comment] 2018-10-12 20:28
1) https://www.primefaces.org/primeng/#/table/scroll
2) Go to the table labeled "Frozen Columns". 
3) Maximize your screen until the table frozen column has no scroll bar.
4) Scroll the entire table confirm all the rows line up.
5) Shrink the screen until the scrollbar appears.
6) Scrollbar should be misaligned on the table.
7) Reload the webpage at the same width
8) Scroll to the table again and see the scrollbar now works properly.
9) Maximize the table again until the scrollbar vanishes
10) Confirm the LHS frozen column is misaligned.

![untitled](https://user-images.githubusercontent.com/5766272/46892557-79fbd000-ce33-11e8-810b-efdc0c6e9b07.png)

**Comment by Calidus** [comment] 2018-12-04 13:35
This issues is still present in 7.0

**Comment by jpierrep** [comment] 2018-12-31 15:48
same problem  in version 7.0 at 2018-dec
![image](https://user-images.githubusercontent.com/12802225/50563283-4e81d680-0cfa-11e9-953a-ac2af858e768.png)

**Comment by filoberlini** [comment] 2019-01-03 09:35
there is a little error in table.ts:
 
 this.scrollBodyViewChild.nativeElement.style.marginBottom = this.domHandler.calculateScrollbarWidth() + 'px';

this piece of code should be instead       

 this.scrollBodyViewChild.nativeElement.style.paddingBottom = this.domHandler.calculateScrollbarWidth() + 'px';

**Comment by Relic** [comment] 2019-01-09 14:59
Can confirm what @filoberlini said.

Changing the style of the frozen table's ui-table-scrollable-body from using margin-bottom to using padding-bottom fixes this misalignment issue (and some other weird scrollbar/alignment issues I was running into).

**Comment by NickolayMitev** [comment] 2019-01-30 14:31
> A temporary workaround which worked for me was to inject DOCUMENT from @angular/common into the component, select **.ui-table-frozen-view > .ui-table-scrollable-body** and manually set **style["paddingBottom"] = style["marginBottom"]** and **style["marginBottom"] = "unset"** for the resulting selected elements in AfterViewInit.

@Relic can you give an example ?

**Comment by Relic** [comment] 2019-01-30 14:52
@NickolayMitev 

I was mistaken above - you don't even have to inject DOCUMENT into the component. That injection is used in serverside rendering.

This is all it took for me in the end:

`ngAfterViewInit() {
    const frozenBodyStyle = document.querySelector(".ui-table-frozen-view > .ui-table-scrollable-body")["style"];
    if (frozenBodyStyle["marginBottom"] !== "unset") {
      frozenBodyStyle["paddingBottom"] = frozenBodyStyle["marginBottom"];
      frozenBodyStyle["marginBottom"] = "unset";
    }
  }`

**Comment by nikpundik** [comment] 2019-02-11 12:11
Correct me if I'm wrong, but it seems that the problem is located here https://github.com/primefaces/primeng/blob/9cb6da52d6060e7cddcb6c80d3025949c1df1f25/src/app/components/table/table.ts#L2385

It's also happening in the stackblitz posted by @Calidus 
When `setScrollHeight` is called with `this.frozen` and `this.scrollableSiblingBody` existing, it misses the first branch because of this check `this.domHandler.getOuterWidth(this.scrollableSiblingBody) < this.domHandler.getOuterWidth(this.scrollableSiblingBody.children[0]` (inside table is not greater than its container). If we try to call this function with a timeout `setTimeout(() => this.setScrollHeight(), 500);` in https://github.com/primefaces/primeng/blob/9cb6da52d6060e7cddcb6c80d3025949c1df1f25/src/app/components/table/table.ts#L2232 it returns the correct outer width for the inner table (so that it can subtract the scrollbar width from the maxHeight) and it gets displayed correctly.

Any idea on why is not getting the correct width at the first call? (it turns out that the table width is exactly the same as its container)

**Closed** 2019-03-04 11:52 UTC
Labels: defect

**Comment by JacobSiegle** [comment] 2019-03-08 16:02
The fix only solves problems with the first render. It does not fix scrollbars appearing / disappearing.

First render - 
![first_render](https://user-images.githubusercontent.com/5766272/54039403-76713880-4188-11e9-9a92-cd0867a89627.png)

Opening a row to make the table have vertical scroll causes the RHS scrollbar to overlap the data - 
![cause_vertical_scroll](https://user-images.githubusercontent.com/5766272/54039442-930d7080-4188-11e9-8a18-bfbfe9fa1992.png)

Resizing the columns to fit the screen causes extra space to exist on the bottom of the table when the horizontal scrollbar is removed - 
![resize_columns](https://user-images.githubusercontent.com/5766272/54039645-14650300-4189-11e9-9586-333fd40302d7.png)

**Comment by JacobSiegle** [comment] 2019-03-08 16:13
My previous comment is incorrect. First render is broken in a different way. First render fails when you have a scrollable table that happens to not scroll due to lack of rows. The padding is always put onto the bottom of the table no matter what.

![first_render_broken](https://user-images.githubusercontent.com/5766272/54040385-d072fd80-418a-11e9-9baf-1a2388c459b7.png)

**Comment by JobayerAhmmed** [comment] 2019-07-17 08:53
> @NickolayMitev
> ```
> ngAfterViewInit() {
>     const frozenBodyStyle = document.querySelector(".ui-table-frozen-view > .ui-table-scrollable-body")["style"];
>     if (frozenBodyStyle["marginBottom"] !== "unset") {
>         frozenBodyStyle["paddingBottom"] = frozenBodyStyle["marginBottom"];
>         frozenBodyStyle["marginBottom"] = "unset";
>     }
> }
> ```

The code within ngAfterViewInit() didn't work for me. My table shows large amount of data (~15MB). So I added the following code after fetching data, not in ngAfterViewInit() and it worked.

`        setTimeout(() => {
            let frozenBody = document.querySelector(".ui-table-frozen-view > .ui-table-scrollable-body");
            if (frozenBody) {
              let frozenBodyStyle = frozenBody["style"];
              if (frozenBodyStyle["marginBottom"] !== "unset") {
                frozenBodyStyle["paddingBottom"] = frozenBodyStyle["marginBottom"];
                frozenBodyStyle["marginBottom"] = "unset";
              }
            }
          }, 0);`

**Comment by MdShahrukh** [comment] 2020-07-23 10:32
![Capture](https://user-images.githubusercontent.com/21266975/88276922-78945280-ccfd-11ea-9dd1-690a4d40f823.PNG)

When i am trying to use virtual scrollbar with frozen columns it is giving two scrollbars on both sides frozen side and scroll side as well.
Can anyone help me here ?

Attaching stackbiz https://stackblitz.com/edit/primeng-treetablescroll-demo-s5ckqt?file=src%2Fapp%2Fapp.component.html
