### ISSUE TITLE
p-table vertical scrollbar begins from <tbody> tag with fixed headers (instead of <thead>)

### ISSUE THREAD

**Issue by fperie** [primefaces/primeng#12274] opened 2022-11-22 16:37 UTC
### Describe the feature you would like to see added

Add a new parameter in `p-table` component to the vertical scrollbar covers only data part (and not the headers part).
On [scroll table demo page](https://primefaces.org/primeng/table/scroll), you can see the problem.

The actual display of the component :
![image](https://user-images.githubusercontent.com/1265267/203369294-d0a51428-09be-4e03-9e3c-f2904d5f32b0.png)

The expected result of the component :
![image](https://user-images.githubusercontent.com/1265267/203369719-611a7dd7-1955-414d-a2a8-601d4af58bee.png)

### Is your feature request related to a problem?

We have a display issue on the `p-table` component using fix headers.
The vertical scroll bar is going from top to bottom of the component, including headers.
Since the headers are in fix mode, this looks weird to us and we would like that the vertical scroll bar starts after the headers's <tr>.
Is there any way to do this ?

### Describe the solution you'd like

Add a new parameter in `p-table` component to the vertical scrollbar covers only data part.

### Describe alternatives you have considered

Contact the community.

**Comment by cetincakiroglu** [comment] 2022-11-23 06:38
Hi,

It's not a bug it's by design and intentional. Closing the issue, thanks for your support!

Regards

**Closed by cetincakiroglu** 2022-11-23 06:38 UTC
Labels: Resolution: By Design
