### ISSUE TITLE
Slider doesn't work on Mobile web.

### ISSUE THREAD

**Issue by kalandher** [primefaces/primeng#2766] opened 2017-05-13 20:18 UTC
Silder is not draggable, only you have to click on the bar where where you want it to be. its not smooth in mobile. is there any way to fix this?

Thanks

**Comment by sudheerj** [comment] 2017-05-14 05:55
Yes, the slider dragging handle is not draggable.It works through click on slider bar. It should work on dragging similar to PrimeFaces slider.

**Comment by sudheerj** [comment] 2017-05-24 12:32
Duplicate of https://github.com/primefaces/primeng/issues/2866

**Closed by sudheerj** 2017-05-24 12:32 UTC
