### ISSUE TITLE
Accessibility problem with radioButtons

### ISSUE THREAD

**Issue by Bart3k92** [primefaces/primeng#9837] opened 2021-01-29 17:41 UTC
There is a problem with traversing radiobuttons using the keyboard arrows with the screen reader enabled. The narrator dictates a double number of options. Each radio button fires twice before the focus moves on. Tested with windows 10 narrator. Can be tested on primeng documentation page.

[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Comment by yigitfindikli** [comment] 2021-02-15 13:35
duplicate of https://github.com/primefaces/primeng/issues/9834

**Closed by yigitfindikli** 2021-02-15 13:35 UTC
