### ISSUE TITLE
Empty tooltip

### ISSUE THREAD

**Issue by bojanidis10** [primefaces/primeng#1190] opened 2016-11-02 10:21 UTC
Currently when the value is not there the tooltip is still being displayed. There is no use from empty tooltip. Tooltip should not be shown at all, when the text is null or empty.

**Comment by mmikeyy** [comment] 2016-11-08 15:19
Totally agree. I have mentioned the problem before and there seems to be no interest. Perhaps they  don't see the point of a tooltip without text. When you have no tooltip to display, then just don't use the control is probably what they think.

But... the use case is very obvious. In a list, I highlight some values that have some characteristic. When the user sees a highlighted value, a tooltip explains the highlight. Most values have a tooltip with no text. However the tooltip keeps rendering with an awkward looking shape when it's empty.

It's easy to fix. Each time I upgrade Primeng to a new version, I visit the javascript for the component and make the two following changes:
`
Tooltip.prototype.show=function(){
  
  if(!this.text){ //added (if no text, then don't create tooltip container)
    return;        //added
  }                   //added
  this.create();
  
  
  Tooltip.prototype.hide=function(){
    if(!this.container){ // added (if container was not create, don't attempt to destroy it)
      return;   //added
    } //added
    this.container.style.display='none';
    document.body.removeChild(this.container);
    this.container=null;
  };
`

**Comment by dzhavat** [comment] 2016-11-18 19:29
Despair not! :) Just fixed it in PR #1361

**Comment by cagataycivici** [comment] 2016-11-21 16:10
Duplicate of #705

**Closed by cagataycivici** 2016-11-21 16:10 UTC
