### ISSUE TITLE
Datatable sorting should support immutable objects

### ISSUE THREAD

**Issue by otinanism** [primefaces/primeng#2529] opened 2017-04-15 16:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/77OG7zX3LToGoidKaKOS

**Current behavior**

I use ngrx in my ng2 app, I also freeze the store so any value in store is immutable. The datatable gets its value property from the store so it is an array of immutable objects.
When I try to sort a column I get the error:

 Cannot assign to read only property '1' of object '[object Array]'
    at Array.sort (native)
    at Array.sort (http://localhost:4200/polyfills.bundle.js:3189:15)
    at DataTable.sortSingle (http://localhost:4200/vendor.bundle.js:111326:28)
    at DataTable.sort (http://localhost:4200/vendor.bundle.js:111307:26)
    at Object.eval [as handleEvent] (ng:///DataTableModule/ColumnHeaders.ngfactory.js:290:27)
    at handleEvent (http://localhost:4200/vendor.bundle.js:12017:138)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13225:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:4200/vendor.bundle.js:12813:12)
    at dispatchEvent (http://localhost:4200/vendor.bundle.js:8991:21)
    at http://localhost:4200/vendor.bundle.js:9581:38
    at HTMLTableCellElement.<anonymous> (http://localhost:4200/vendor.bundle.js:35270:53)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5234:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:4327:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5233:36)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:5001:47)

**Expected behavior**

The datable should be able to sort using immutable objects.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

It seems that all components and features should support immutable data objects. Ngrx/store is used more and more with angular and this is a show-stopper.
**Please tell us about your environment:**

* **Angular version:** 2.0.X, 4.1.0-beta.1

* **PrimeNG version:** 4.0.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by eXxi** [comment] 2017-04-21 08:40
I think it is the same issue I am having with the new immutable option of the datatable component.
https://forum.primefaces.org/viewtopic.php?f=35&t=50408

**Comment by Abbraxar** [comment] 2017-05-02 08:13
The issue is still there with 4.0.0 release.
It's strange because because #2630 should have fixed it.
And what's this immutable flag ? Is it related to the problem ?
I have a template parse error when I try to use it despite it's in the doc.

**Comment by cagataycivici** [comment] 2017-05-02 11:03
Please try with 4.0, this should be fixed now.

**Closed by cagataycivici** 2017-05-02 11:03 UTC
