### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with input directives

### ISSUE THREAD

**Issue by nick1247** [primefaces/primeng#2307] opened 2017-03-15 17:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/wKUETJ?p=preview

**Current behavior**
I get the ExpressionChangedAfterItHasBeenCheckedError when using pInputTextarea with value

* **Angular version:** 4.0.0-rc.3

* **PrimeNG version:** 4.0.0-rc.1

**Comment by Danieleeee** [comment] 2017-03-24 20:57
Same for me.

**Comment by akorchev** [comment] 2017-03-24 21:24
Caused by this line: https://github.com/primefaces/primeng/blob/master/components/inputtextarea/inputtextarea.ts#L11

**Comment by akorchev** [comment] 2017-03-24 21:37
Can be fixed by using `ngDoCheck`: https://plnkr.co/edit/JJxhRWbS3iLKWXXzN3Y1?p=preview

**Comment by cagataycivici** [comment] 2017-03-27 11:15
The plunkr doesn't work, any idea why? I can't replicate it with current code and Angular 4 final. How can I get the error?

**Comment by akorchev** [comment] 2017-03-27 11:47
This is the error - it doesn't work because of the runtime exception. Here is a screenshot:

<img width="1023" alt="screen shot 2017-03-27 at 2 44 55 pm" src="https://cloud.githubusercontent.com/assets/454726/24354848/26c8e010-12fc-11e7-8f7f-f5492857fd30.png">

**Closed** 2017-03-27 12:01 UTC
Labels: defect

**Comment by doyo3141** [comment] 2017-04-28 18:10
I'm experiencing this error with dropdowns inside dialogs.  
Angular 4.0.0
Primeng 4.0.0-rc4

**Comment by mattpangaro** [comment] 2017-04-28 18:17
I had the same issue with rc4 but it appears to have been fixed in rc5.

**Comment by cagataycivici** [comment] 2017-04-28 18:18
Glad to hear.

**Comment by ahelord** [comment] 2017-05-22 18:43
@mattpangaro yes work for me in version 4.0.1
thanks
