### ISSUE TITLE
Visual bug on appendTo property 

### ISSUE THREAD

**Issue by gustavomerini** [primefaces/primeng#6918] opened 2018-11-27 12:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-mcc3mc / https://github-mcc3mc.stackblitz.io

**Current behavior**
suggestions display in the wrong position in mobile, notebooks(works normally in 1920x1080)

**Expected behavior**
it should display just like when not using appendTo prop.

**Minimal reproduction of the problem with instructions**

Just click on the dropdown to see the difference(using lower screen sizes)
example: 
![image](https://user-images.githubusercontent.com/31575444/49081534-50a1d280-f22e-11e8-87f8-1abe2216f041.png)

**What is the motivation / use case for changing the behavior?**

I have a modal where my user can select some stuffs in the p-autocomplete, my client complains that he needs to scroll down to see all the suggestions, so I decided to add appendTo property so that the overlay suggestions would appear outside the modal, so that the user won't need to scroll down to see the options, did that, worked properly but it has this visual bug on mobile/medium devices.

this issue is probably related to this bug: 
https://github.com/primefaces/primeng/issues/6073

**Please tell us about your environment:**

* **Angular version:** 7.X

In my project I use angular 6, but i tested in stackblitz with angular 7

* **PrimeNG version:** 7.X

In my project I use primeng 6, but i tested in stackblitz with angular 7

* **Browser:** [Chrome XX ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v8.12.0

**Comment by dhuebes** [comment] 2018-11-30 11:51
+1

**Comment by cesarkuehl** [comment] 2019-01-24 10:18
+1

**Comment by mertsincan** [comment] 2019-06-18 08:30
Duplicate of #7808

**Comment by mertsincan** [comment] 2019-06-18 08:30
Fixed for next version.

**Closed** 2019-06-18 08:30 UTC
