### ISSUE TITLE
Multiselect component with reactive forms

### ISSUE THREAD

**Issue by Mrtcndkn** [primefaces/primeng#2498] opened 2017-04-12 10:43 UTC
When multiselect component used with reactive forms it is not working.

**Comment by rklempert** [comment] 2017-04-27 17:24
Is this going to be resolved with 4.0.0-Final? Multiselect isn't closing when onBlur fires.

**Comment by spetex** [comment] 2017-05-19 08:27
There is no specification, what does not working. It is working for us. Make sure you FormGroup has a correct type for MultiSelect values. It must be an array not string.

**Comment by rklempert** [comment] 2017-05-19 14:36
What isn't working is after selecting a value, the dropdown modal isn't going away. It stays open and I have to click X to close it.  Clicking anywhere on the page or in another input isn't hiding the the list of values. The blur event isn't firing.

**Comment by rklempert** [comment] 2017-05-19 14:38
To add, if I remove formControlName attribute from it, everything works as expected.

**Comment by spetex** [comment] 2017-05-22 09:11
Do you have any errors in the console? Do you supply a correct model to the FormBuilder? Meaning the value for this field must be an array of strings since you can select multiple options. Maybe drop here some code. I have just finished a part of our app with this component with no problems, I believe we can find also a solution for you.

**Comment by rklempert** [comment] 2017-05-22 14:40
No errors in the console. The control works as expected in regard to setting the actual value. The only thing that is not happening is the control does not close if used with reactive forms and I have to click “X” to close it, and then it closes. If I click anywhere else on the page and then one of the checkboxes in the control, the control will close. I also noticed that p-calendar control isn’t working either. I have to select a date twice for it to close. All of this code used to work with Angular 2 and Prime 2, as soon as we upgraded to version 4, these 2 controls stopped working. With [(ngModel)] these controls work just fine.

We use it like this:
<p-multiSelect #msc *ngSwitchCase="'multiselect'" [inputId]="field.key" [formControlName]="field.key" [options]="field.options" [defaultLabel]="field.placeHolder" (onChange)="changeMultiselect($event)" maxSelectedLabels="1"></p-multiSelect>

Inside of a component that uses:
changeDetection: ChangeDetectionStrategy.OnPush


Robert Klempert | bswift
10 S. Riverside Plaza, Suite 1100
Chicago, IL 60606
312.373.3483 (direct)
877.9.BSWIFT (toll free)
rklempert@bswift.com<mailto:rklempert@bswift.com>
www.bswift.com<http://www.bswift.com/>

**Comment by rklempert** [comment] 2017-05-22 15:13
After setting change detection to Default, I noticed that the control is working correctly. It doesn’t seem to close itself when using “changeDetection: ChangeDetectionStrategy.OnPush”

Robert Klempert | bswift
10 S. Riverside Plaza, Suite 1100
Chicago, IL 60606
312.373.3483 (direct)
877.9.BSWIFT (toll free)
rklempert@bswift.com<mailto:rklempert@bswift.com>
www.bswift.com<http://www.bswift.com/>

**Comment by rklempert** [comment] 2017-05-22 15:18
The issue turns out to be related to ChangeDetectionStrategy.OnPush. Control works correctly with Default strategy. This problem exists for p-calendar and p-autocomplete controls as well, but there is an issue already created for those two controls.

**Comment by spetex** [comment] 2017-05-30 07:42
I am sorry, but I was unable to reproduce the same issue. Even with onPush detection strategy and Reactive Forms and the same version of ng & primeng the Multiselect and also Datepicker works as a charm.

**Comment by cagataycivici** [comment] 2017-06-22 13:47
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Closed by cagataycivici** 2017-06-22 13:47 UTC
Labels: defect
