### ISSUE TITLE
PickList shows unexpected behaviour with [metaKeySelection]='false'

### ISSUE THREAD

**Issue by twdnr** [primefaces/primeng#3182] opened 2017-06-22 16:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/JqlKYPbJA08rXnJmJQua?p=preview

Just click on the items without pressing any meta key.

Since #3169  has been closed I re-open this issue.

**!!! Possible Fix / solution !!!**
The onItemClick method in picklist.ts, the last `selectedItems.push(item);` (@ line 348, master, latest) will not clear the array. Therefore:
```
selectedItems.length = 0;
selectedItems.push(item);
```
might solve the problem. Please verify!

**Current behavior**
PickList even with [metaKeySelection]='false' allows to select multiple elements. De-selecting an element of a multi-element selection does not work. Even if you don't hold any meta/control-key every click will add an element to the selection. In fact, you can only add more elements to a selection.

**Expected behavior**
Only on element should be selectable at a time when [metaKeySelection]='false'.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
WebStorm (latest), Mac OS X (latest)

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.3, 4.1.0-rc.2

* **Browser:** Checked only Chrome, Safari on Mac OS X so far

* **Language:** TypeScript 2.3

* **Node (for AoT issues):** `node --version` =   8.1.2

**Comment by cagataycivici** [comment] 2017-06-23 12:14
Duplicate of #3169

**Closed by cagataycivici** 2017-06-23 12:14 UTC
