### ISSUE TITLE
Datatables , scrollable breaks with resizableColumns set to expand

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#2568] opened 2017-04-21 07:55 UTC
**I'm submitting a 
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

When doing a resize column option expand within a scrollable table , the resize breaks the scrolling and the table does not scroll no more

* **Angular version:** 4.0.X
* **PrimeNG version:** 4.0.X
* **Browser:** [all 

**Expected behavior**

The problem in my opinion is related to this code 

```
 else if(this.columnResizeMode === 'expand').....

 if(this.scrollable) {
      this.scrollBarWidth = this.scrollBarWidth||this.domHandler.calculateScrollbarWidth();
      this.el.nativeElement.children[0].style.width = parseFloat(containerWidth) + this.scrollBarWidth + 'px';
      let colGroup = this.domHandler.findSingle(this.el.nativeElement, 'colgroup.ui-datatable-scrollable-colgroup');
      let resizeColumnIndex = this.domHandler.index(this.resizeColumn);
      colGroup.children[resizeColumnIndex].style.width = newColumnWidth + 'px';
                }
```

Solution 

Omit this line and it will work 

```
   //  this.el.nativeElement.children[0].style.width = parseFloat(containerWidth) + this.scrollBarWidth + 'px';
```
this line is overwriting the scrollWidth breaking the scrollable

**Comment by huineng** [comment] 2017-04-21 07:56
https://github.com/primefaces/primeng/issues/1551

**Comment by bmstambaugh** [comment] 2017-04-26 19:44
Same issue, but to add once resized the column headers and the column cells no longer line up.

**Comment by cagataycivici** [comment] 2017-05-31 08:23
Duplicate of 1551

**Closed by cagataycivici** 2017-05-31 08:23 UTC
