### ISSUE TITLE
Support for Angular14

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#11643] opened 2022-06-22 05:19 UTC
### Describe the feature you would like to see added

as title

**Comment by sthompson-celerity** [comment] 2022-06-23 16:05
you should check existing issues before making a new one, this is a duplicate of #11586

**Comment by ces6jedi** [comment] 2022-06-27 13:33
+1

**Comment by yigitfindikli** [comment] 2022-07-01 11:52
Duplicate of https://github.com/primefaces/primeng/issues/11586

**Closed by yigitfindikli** 2022-07-01 11:52 UTC
