### ISSUE TITLE
Component: p-menu PrimeNg 16.1.0 regression MenuItem.id no longer assigned to MenuItemContent anchor tags

### ISSUE THREAD

**Issue by SaajRP** [primefaces/primeng#13481] opened 2023-08-10 19:41 UTC
### Describe the bug

As a result of the code merged to menu.ts for https://github.com/primefaces/primeng/pull/13372, the id defined against a MenuItem provided to p-menu is no longer assigned to the id of the anchor tag

https://github.com/primefaces/primeng/pull/13372/files#diff-6fb5eaf005117b0f3acb23845d35b567bb9e572bcdb8a957aeff8fbb791ffc80

### Environment

PrimeNg 16.1.0

### Reproducer

https://github.com/primefaces/primeng/pull/13372/files#diff-6fb5eaf005117b0f3acb23845d35b567bb9e572bcdb8a957aeff8fbb791ffc80

### Angular version

16.X.X

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

Inspect the HTML of one of the MenuItem elements, the anchor tag is not using the the defined id

<img width="1254" alt="primengMenuItemId" src="https://github.com/primefaces/primeng/assets/95288609/09e4a846-e13f-4038-b461-92ecbbb0d103">

### Expected behavior

The anchor tag for a given MenuItem should be using the defined id

**Comment by arkancrow** [comment] 2023-08-24 09:22
The issue is still present in the version 16.2.0.

**Comment by jerkovicl** [comment] 2023-09-21 10:19
Any updates on this ? This needs to be fixed

**Comment by dalenguyen** [comment] 2023-09-23 15:22
I created PR for this. Hopefully it will get feedback soon.

**Comment by cetincakiroglu** [comment] 2023-09-25 13:53
Hi,

This issue is a duplicate of https://github.com/primefaces/primeng/issues/13705 and it's fixed in here https://github.com/primefaces/primeng/commit/44a50758cb1320ed34f47cc5c79a86ae7516ca75

Closing the issue since it's duplicate and already fixed.

Thanks a lot for your effort and support!

**Closed by cetincakiroglu** 2023-09-25 13:53 UTC
Labels: Status: Needs Triage

**Comment by SaajRP** [comment] 2023-09-26 21:22
@cetincakiroglu the fix done against https://github.com/primefaces/primeng/commit/44a50758cb1320ed34f47cc5c79a86ae7516ca75 for https://github.com/primefaces/primeng/issues/13705

Does not actually replicate the old behaviour prior to PrimeNg 16.1.0. Prior to this the MenuItem.id was being assigned to the p-menuitem-link anchor tag element inside p-menu-content div within the menuItem li element

Looking at the fix that has been done, and confirming it in the below stackblitz instance, the MenuItem.id is now being assigned to the menuitem li element. This is a clear change in behaviour that needs to be documented in the Changelog, as for anyone upgrading from PrimeNg version <= 16.0.2 this maybe a breaking change for their application

https://stackblitz.com/edit/ykgezg?file=src%2Fapp%2Fdemo%2Fmenu-basic-demo.ts
<img width="1268" alt="image" src="https://github.com/primefaces/primeng/assets/95288609/09dfb26c-7a40-4ab2-9d56-e0d322abdd77">


N.b
For anyone needing some sort of identifier against the p-menuitem-link anchor tag, the MenuItem.automationId would be your best bet
<img width="1268" alt="image" src="https://github.com/primefaces/primeng/assets/95288609/8a5bbd72-3a44-4529-862c-849a84d06c9a">
