### ISSUE TITLE
Dropdown: Tab key not navigating between fields

### ISSUE THREAD

**Issue by fredzouza** [primefaces/primeng#13664] opened 2023-09-12 18:52 UTC
### Describe the bug

Using a angular app i upgrade primeng to version 16.3.1 and after that when i filling a form with dropdown fields i can't navigate between fields using tab key the focus get stucked on the dropdown, i have downgraded primeng to version 16.2.0 and the problem desapear.

### Environment

Angular app v 16.x.x, primeng 16.3.1

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome 116

### Steps to reproduce the behavior

Any form with many fields and at least one dropdown, click on the dorpdown and try to navigate betwwen fields using tab key.

### Expected behavior

navigate between fields

**Comment by lmormol** [comment] 2023-09-13 09:53
I confirm the issue with navigating through Dropdown by using TAB key, now we can observe a focus trap on that element.

**Comment by johanneszelger** [comment] 2023-09-13 11:53
Can confirm this as well. Broke one of our tests

**Comment by atamansv** [comment] 2023-09-25 13:30
This issue caused by this commit: https://github.com/primefaces/primeng/commit/b1efe18a85b7e0bb86ecbf93fe830ad2b67f86ff

**Comment by cetincakiroglu** [comment] 2023-10-26 19:42
issue is fixed in https://github.com/primefaces/primeng/commit/f52340b9daf5ea2ee921fc0906838b98007cd6ed

The fix will be available for the upcoming release next Wednesday. Closing the issue since it's fixed during the accessibility implementation of the dropdown component

**Closed by cetincakiroglu** 2023-10-26 19:42 UTC
Labels: Status: Needs Triage
