### ISSUE TITLE
Datatable with dynamic columns crashes with a "Cannot read property 'xxx' of undefined" for nested objects. 

### ISSUE THREAD

**Issue by bogandy99** [primefaces/primeng#1451] opened 2016-11-29 13:02 UTC
**I'm submitting a 
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Datatable with dynamic columns crashes with a "Cannot read property 'xxx' of undefined" for nested objects. 
The following example crashes if the fieldvalue for the column is land.landName as land in the second json object is missing (undefined). 
Sample json:
[
{
      "id": 48,
      "ZIP": "555",
      "city": "city1",
      "land": {
        "id": -1908176136,
        "landName": "land-name"
      },
    },
   {
      "city": "city2",
      "ZIP": "111",
      "id": 49
    }
]

**Expected behavior**
Not to crash when setting the fieldvalue as land.landName.

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE* 
A simple datatable:
 <p-dataTable
      [value]="zipList"
      scrollable="true" scrollHeight="70%" scrollWidth="75%"
      selectionMode="single" [(selection)]="selectedZip" (onRowDblclick)="rowDblClick($event)"
      [contextMenu]="cm">
      <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" [sortable]="col.sortable"></p-column>
        <footer><p-tabMenu [model]="items" [activeItem]="activeItem"></p-tabMenu></footer>
    </p-dataTable>
... 
    this.cols = [{field: 'city', header: 'City', sortable: true},
        {field: 'land.landName', header: 'Land', sortable: true},
        {field: 'ZIP', header: 'ZIP', sortable: true}];

**What is the motivation / use case for changing the behavior?**
Improve primeng datatable component so that it supports nested objects. 

**How to fix**
It seems that the issue is in the datatable.ts file, method resolveFieldData:
 resolveFieldData(data: any, field: string): any {
        if(data && field) {
            if(field.indexOf('.') == -1) {
                return data[field];
            }
            else {
                let fields: string[] = field.split('.');
                let value = data;
                for(var i = 0, len = fields.length; i < len; ++i) {
                    value = value[fields[i]];
                }
                return value;
            }
        }
        else {
            return null;
        }
    }

Here, a null/undefined check could be done so that the code doesn't fail if the 'value' variable is undefined. It would be great if on the 'else' case a check for '?' is made so as to support the standard notation: land?.landName. 
In this case, null/undefined check would be made only if the 'land' variable has been marked with a '?'.

**Workaround**
Probably instead of dynamic columns I could use static ones, but I would rather use the former as it's more.. well.. dynamic :-)

If there are any solutions to this problem please share.

**Comment by thrallala** [comment] 2016-11-29 16:33
I have changed the method you mentioned to:

```
resolveFieldData(data: any, field: string): any {
        if(data && field) {
            let fields: string[] = field.split('.');
            let value = data;
            for(var i = 0, len = fields.length; i < len; ++i) {
                let currentValue;
                if(fields[i].length > 0 && fields[i].indexOf('?') === fields[i].length-1) {
                    currentValue = value[fields[i].substring(0, fields[i].length-1)];
                    if(!currentValue) {
                        return null;
                    }
                }
                else {
                    currentValue = value[fields[i]];
                }
                value = currentValue;
            }
            return value;
        }
        else {
            return null;
        }
}
```

This works and if you don't specify parameters being optional it retains the old functionality (a.k.a. it crashes). My guess is this is a better solution than not letting the user know the data is somehow corrupt, by returning the first undefined/null in a chain by default, even without the "?".

So now if you do:
land?.landName - it just shows an empty field by returning null
land.landName - still crashes like before

I will try and submit a pull request for this fix tonight.

**Comment by cagataycivici** [comment] 2016-11-29 19:39
Isn't this duplicate of #1182?

**Comment by cagataycivici** [comment] 2016-11-29 19:50
Should be fixed via 1182.

**Closed by cagataycivici** 2016-11-29 19:50 UTC

**Comment by thrallala** [comment] 2016-11-29 20:24
yes, seems like a duplicate of #1182, though the fix was slightly different, both solutions are fine by me. Thanks!
