### ISSUE TITLE
Carousel error when numVisible greater than value.length

### ISSUE THREAD

**Issue by junyuan** [primefaces/primeng#8273] opened 2019-10-24 13:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-p1xt1q

**Current behavior**
Carousel crash when the value.length is less than configured numVisible

**Expected behavior**
Should display the array in Carousel without paginate

* **Angular version:** 8.X

* **PrimeNG version:** >=8.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   10.16.3

**Comment by sukhminderx** [comment] 2019-11-06 19:11
I resolved this one by this workaround:
```
getVisibleItems () { return this.socials.length < 4 ? this.socials.length : 4; }
[numVisible]="getVisibleItems()"
```
This will assign numVisible as 1 or 2 or 3 if the same number of items are present. If the items are >3, the numVisible is assigned for 4

**Comment by mertsincan** [comment] 2019-11-25 12:37
Duplicate of #8300

**Closed by mertsincan** 2019-11-25 12:37 UTC
