### ISSUE TITLE
Three state (indeterminate) checkbox - true, false or null

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#875] opened 2016-09-09 08:59 UTC
I suggest adding a `indeterminate` option to `Checkbox` component. It will be binary checkbox with additional state - indeterminate. Possible values: `true` | `false` | `null`.  

It will be useful for filter like `has` | `hasn't` | `i don't care`:
![image](https://cloud.githubusercontent.com/assets/3925630/18381412/bc556ae6-7684-11e6-8a22-b144ae76558b.png)

... or permissions table:
![image](https://cloud.githubusercontent.com/assets/3925630/18381045/e7d798bc-7682-11e6-8e05-a74dd03b5a1e.png)

**Comment by cagataycivici** [comment] 2016-09-19 17:00
Also requested by a PRO user today so will do for beta17.

**Comment by cagataycivici** [comment] 2016-09-25 14:23
Duplicate of #756

**Closed by cagataycivici** 2016-09-25 14:23 UTC
Labels: new feature
