### ISSUE TITLE
Component: DynamicDialog NullInjectorError: No provider for NameService!

### ISSUE THREAD

**Issue by Draganlazarev90** [primefaces/primeng#14730] opened 2024-02-06 13:38 UTC
### Describe the bug

Having a module with a service in providers array. Create a parent component that opens a dialog component with a child component that uses the service provided in the module, gives NullInjectorError instead of inheriting the service instance from the module.

### Environment

Primeng 17.5

### Reproducer

https://stackblitz.com/edit/7qkchf?file=src%2Fapp%2Fdemo%2Fdynamic-dialog-example-demo.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdemo%2Fdemo.service.ts,src%2Fapp%2Fdemo%2Fdemo.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fdemo%2Fdynamic-dialog-example-demo.html,src%2Findex.html,src%2Fapp%2Fdemo%2Ftest-child.component.ts,src%2Fapp%2Fdemo%2Fdialog.component.ts,src%2Fapp%2Fdemo%2Fdynamic-dialog-example-demo.scss

### Angular version

17.0.5

### PrimeNG version

17.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Create a module with providers array and provide a service
2. Create a parent component
3. Create a dialog component that will be opened from the parent
4. Create a child component nested in the dialog component, and have the child component use the service provided in the module

### Expected behavior

The child component should use the instance from the module providers array. Was working in v15 and prior

**Comment by Draganlazarev90** [comment] 2024-02-07 12:38
Might be related to https://github.com/primefaces/primeng/issues/14491

**Comment by Draganlazarev90** [comment] 2024-02-08 12:22
@mehmetcetin01140 @cetincakiroglu any update on this?

**Comment by cetincakiroglu** [comment] 2024-02-12 15:10
Related to #14491, duplicate issues for the same problem. Closing this one and adding #14491 to the milestone.

**Closed by cetincakiroglu** 2024-02-12 15:10 UTC
Labels: Status: Needs Triage

**Comment by cetincakiroglu** [comment] 2024-03-06 07:43
Hi,

After the investigation, we've found the issue caused by injection level difference. You're providing dialogService in the component level and demoService in the module level. Because of this, dialogService fails to find and inject DemoService. It works as expected if both of them are provided at the same level. That's why injecting the DemoService to the component.ts makes it work. Please see the example: https://stackblitz.com/edit/7qkchf-expefk?file=src%2Fapp%2Fdemo%2Fdemo.module.ts

To provide a better guide, we'll update the documentation of DynamicDialog and mention this use. Thanks a lot for reporting the issue!

I am closing the issue since the solution is provided.

**Comment by Draganlazarev90** [comment] 2024-03-06 09:59
Thanks a lot, that indeed solves the issue
