### ISSUE TITLE
PrimeNG 10.0.3 - Mobile/Touch screen - Swipe left and and Swipe right is not working in Galleria

### ISSUE THREAD

**Issue by noteme-io** [primefaces/primeng#9400] opened 2020-10-12 12:57 UTC
Current behavior
Mobile/Touch screen - Swipe left and Swipe right is not working in Galleria

Expected behavior
In Mobile/Touch screen, swiping images should work like Carousel

PrimeNG version: 10.0.3

**Comment by yigitfindikli** [comment] 2020-11-25 10:28
duplicate of https://github.com/primefaces/primeng/issues/9243

**Closed by yigitfindikli** 2020-11-25 10:28 UTC
