### ISSUE TITLE
p-multiselect not correctly work in form tag

### ISSUE THREAD

**Issue by gh-mohammadi** [primefaces/primeng#7007] opened 2018-12-15 09:18 UTC
hi 
i'm using primeng version 6.1.7
multiselect ngmodel not change after select items when using it in form tag

**Comment by JacobSiegle** [comment] 2019-01-03 14:16
It sounds like an issue with your code unless you can provide a stackblitz for the latest version of PrimeNG which can reproduce the issue. I've been using multiselect inside of form tags since the earliest version of PrimeNG without an issue. Please consider closing if you cannot provide a stackblitz.

**Comment by cagataycivici** [comment] 2019-01-07 10:40
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Closed by cagataycivici** 2019-01-07 10:40 UTC
