### ISSUE TITLE
Data table OnRowUnSelect does not appear to fire

### ISSUE THREAD

**Issue by garethlewis** [primefaces/primeng#702] opened 2016-08-05 15:54 UTC
When attaching the events for RowSelect and RowUnSelect, the RowUnSelect emitter is never called, making it very difficult to tell that I need to unselect  a previously selected item.

**Comment by cagataycivici** [comment] 2016-08-26 08:32
Duplicate of #783

**Closed by cagataycivici** 2016-08-26 08:32 UTC
Labels: review
