### ISSUE TITLE
Dropdown with delayed binding to [options] breaks label binding

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#378] opened 2016-05-19 00:19 UTC
Modifying your demo here:   http://www.primefaces.org/primeng/#/dropdown

With the following:
```
    this.cars = [];

    this.selectedCar = 'BMW';
    setTimeout(() => {  // simulate XHR

      this.cars.push({label: 'Audi', value: 'Audi'});
      this.cars.push({label: 'BMW', value: 'BMW'});
      this.cars.push({label: 'Fiat', value: 'Fiat'});
      this.cars.push({label: 'Ford', value: 'Ford'});
      this.cars.push({label: 'Honda', value: 'Honda'});
      this.cars.push({label: 'Jaguar', value: 'Jaguar'});
      this.cars.push({label: 'Mercedes', value: 'Mercedes'});
      this.cars.push({label: 'Renault', value: 'Renault'});
      this.cars.push({label: 'VW', value: 'VW'});
      this.cars.push({label: 'Volvo', value: 'Volvo'});
  }, 1000);
```

Breaks the binding to the label.  The UL highlights the correct LI but the label does not show the selectedCar.

Hack/Workaround: Adding an *ngIf="cars"  to the p-dropdown worksaround this problem but is not nice.

**Comment by brian428** [comment] 2016-05-26 06:09
For me, even using ngIf on the element doesn't work. Also, same problem appears to be happening with `MultiSelect`.

**Comment by cagataycivici** [comment] 2016-08-08 13:28
Duplicate of 610.

**Closed by cagataycivici** 2016-08-08 13:28 UTC
