### ISSUE TITLE
Add CHANGELOG.md to Git repo?

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#4107] opened 2017-10-05 19:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

Please consider adding a change log file to the Git repo. Currently, it is difficult to know what has changed between versions. The only option is to try searching the PrimeNG blog. It would be much more helpful to have a `CHANGELOG.md` file that documents what has been added/fixed over the version history.

**Comment by mkp05** [comment] 2017-11-13 09:56
Duplicate of #1675 ?

**Comment by tmc101** [comment] 2018-03-14 12:16
I need to upgrade from PrimeNG 4.3.0 to 5.2.3.

How do I find out if there have been any breaking changes?

Where is the Changelog.md?

This is what should be in the git repo:

https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by cagataycivici** [comment] 2018-10-18 07:34
https://github.com/primefaces/primeng/issues/1675

**Closed by cagataycivici** 2018-10-18 07:34 UTC

**Comment by cagataycivici** [comment] 2018-10-18 07:35
Here is the initial version, we'll add more info about breaking changes as well so it will be maintained/updated from now on.

https://github.com/primefaces/primeng/blob/master/CHANGELOG.md
