### ISSUE TITLE
wildcard not supported for file upload?

### ISSUE THREAD

**Issue by kamran-pervaiz** [primefaces/primeng#2732] opened 2017-05-09 09:13 UTC
hi guys,

I am using primeng for multiple file upload. below is my code.

```
<div *ngIf="model.id">
                    <p-fileUpload name={{model.id}} url={{documentUploadUrl}} (onUpload)="onUpload($event)" (onError)="onError($event)"
                                  multiple="multiple" accept=".*" maxFileSize="10000000">
                        <template pTemplate type="content">
                            <ul *ngIf="uploadedFiles.length">
                                <li *ngFor="let file of uploadedFiles">{{file.name}} - {{file.size}} bytes</li>
                            </ul>
                        </template>
                    </p-fileUpload>
</div>
```
When I use accept="*"  I get below error. I want the wildcard because clients can upload any file from image to pdf to an email etc. do i need to specify each extension ".txt,. png, .pdf"?
   
_<File Name> Invalid file type, allowed file types: *._

  ```
    "@angular/animations": "^4.1.1",
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/platform-browser": "^4.1.1",
    "@angular/platform-browser-dynamic": "^4.1.1",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "primeng": "^4.0.0",
    "rxjs": "^5.3.0",
    "zone.js": "0.8.5"
```

please let me know if this behavior is changed? It was working before but after upgrading its giving this error.

**Comment by sudheerj** [comment] 2017-05-09 13:31
Duplicate of https://github.com/primefaces/primeng/issues/2564

**Closed by sudheerj** 2017-05-09 13:31 UTC
