### ISSUE TITLE
rowspan is not working with frozen columns

### ISSUE THREAD

**Issue by chetanbissa27** [primefaces/primeng#8152] opened 2019-09-17 12:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
when I use rowspan for brand column without freezing it works but as soon go with freezing brand column rowspan not working. I have to give height to brand header to get expected behaviour.But there are some chances of changing height of scrollable header at runtime may due to large content.
Please refer below link for issue
https://angular-primeng-table-frozen-cols.stackblitz.io

With frozen column "Brand" height should be adjust according to scrollable header height.

**Expected behavior**
Freezed header column height should be adjust automatically and equal to scrollable header section

Angular version: 8.2.6
primeng: 8.0.3

**Comment by JacobSiegle** [comment] 2019-09-18 13:14
I can't get the stackblitz to load. Probably an error on their end can you clone it to make another link?

**Comment by chetanbissa27** [comment] 2019-09-18 13:37
https://stackblitz.com/edit/angular-primeng-table-frozen-cols

**Comment by JacobSiegle** [comment] 2019-09-18 13:52
I would recommend you "hack" it to work by adding an extra row in the frozen header - 
```
    <ng-template pTemplate="frozenheader" let-columns>
      <tr>
        <ng-container  *ngFor="let col of columns">
          <th>
              {{col.header}}
          </th>
        </ng-container>
      </tr>
      <tr>
          <th>
              &nbsp;
          </th>
      </tr>
    </ng-template>
```

The problem is that when using frozen it creates an entirely different table and attempting to sync up these two tables is difficult and very similar issues like this have been closed by the primeng team.

You should also make sure nothing can wrap in your frozen table.

**Comment by chetanbissa27** [comment] 2019-09-18 14:01
I did try this but it was not giving me proper height...Currently I am calculating height of scrollable header and applying to frozen header th.
`<ng-template pTemplate="frozenheader" let-columns>
      <tr>
        <ng-container  *ngFor="let col of columns">
          <th  [ngStyle]="getHeight()">
              {{col.header}}
          </th>
        </ng-container>
      </tr>
      
    </ng-template>

getHeight() {
    const ele = this.eleRef.nativeElement.querySelector('.ui-table-unfrozen-view .ui-table-thead');
    if (ele) {
        return {height: `${ele.offsetHeight}px`};
    } else {
      return {height: `2em`};
    }
  }

`

**Comment by chetanbissa27** [comment] 2019-09-18 14:03
I did this but this was not giving me properly height.. currently I am calculating height of scrollable header and applying to frozen header th.
eleRef: ElementRef;

This.eleRef.

**Comment by JacobSiegle** [comment] 2019-09-18 14:54
Can you provide an example with the height misaligned when adding an extra col? It seems to work fine to me. You should ensure you content does not wrap as I mentioned previously. If you need wrapping that's an entirely different hackfest to attempt to figure out - 
![image](https://user-images.githubusercontent.com/5766272/65159635-088cb000-d9fa-11e9-8b9d-fc066aa29c58.png)

**Comment by chetanbissa27** [comment] 2019-09-18 14:57
In my use case there are chances of contents wrapping depends on resolution and content length.

**Comment by cagataycivici** [comment] 2019-10-07 10:48
Please use forum for support requests and questions.

**Closed by cagataycivici** 2019-10-07 10:48 UTC
