### ISSUE TITLE
InputNumber thousand separator not working for numbers with four digits in the integral part of the number with "es-CL" locale

### ISSUE THREAD

**Issue by rsanhueza-indra** [primefaces/primeng#10175] opened 2021-04-28 13:52 UTC
Are we having a fix for this bug any time soon?  [bug inputNumber thousand separete](https://github.com/primefaces/primeng/issues/9713)

**Comment by yigitfindikli** [comment] 2021-04-30 07:26
Duplicate of https://github.com/primefaces/primeng/issues/9713

**Closed by yigitfindikli** 2021-04-30 07:26 UTC
