### ISSUE TITLE
PrimeNGConfig.setTranslation not compiling

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#13382] opened 2023-07-26 21:56 UTC
### Describe the bug

Code in the the following user documentation will not compile

`https://primeng.org/configuration#set-locale`

Yields the following error:

```
Argument of type '{ accept: string; reject: string; }' is not assignable to parameter of type 'Translation'.
  Type '{ accept: string; reject: string; }' is missing the following properties from type 'Translation': pending, chooseYear, chooseMonth, chooseDate, and 18 more.ts(2345)
```

### Environment

Windows 10 Pro
@angular/core: ^16.1.0
primeng: ^16.1.0
typescript: ~5.1.3
Node: v16.17.1

### Angular version

16.1.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.17.1

### Expected behavior

I'm left with no example of 'Translation' class/interface.  This compiled under 16.0.0

**Comment by mlc-mlapis** [comment] 2023-07-27 07:16
It's a duplicate of https://github.com/primefaces/primeng/issues/13380.

**Comment by mlc-mlapis** [comment] 2023-07-27 16:34
@PHuhn It's already solved. You can close it.

**Closed** 2023-07-28 14:21 UTC
Labels: Status: Needs Triage
