### ISSUE TITLE
ConfirmDialogue ViewDestroyError on V9.0.0

### ISSUE THREAD

**Issue by SaaimaGul** [primefaces/primeng#8617] opened 2020-03-12 10:11 UTC
When p-confirmDialog component is placed on a page and I try to navigate to other page it gives error
ERROR Error: Uncaught (in promise): Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (core.js:30374)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:46938)
    at checkAndUpdateView (core.js:45952)
    at callWithDebugContext (core.js:47314)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:46876)
    at ViewRef_.detectChanges (core.js:32689)
    at ConfirmDialog.disableModality (primeng-confirmdialog.js:151)
    at ConfirmDialog.onOverlayHide (primeng-confirmdialog.js:221)
    at ConfirmDialog.ngOnDestroy (primeng-confirmdialog.js:227)
    at callProviderLifecycles (core.js:33675)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41224)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:485)
    at invokeTask (zone-evergreen.js:1596)

- Angular CLI: 9.0.3
- Node: 12.14.1
- OS: win32 x64
Angular: 9.0.3

**Comment by yigitfindikli** [comment] 2020-03-12 11:41
Fixed for 9.0.1. Duplicate of https://github.com/primefaces/primeng/issues/8585

**Closed by yigitfindikli** 2020-03-12 11:41 UTC

**Comment by SaaimaGul** [comment] 2020-03-13 06:43
Current version of PrimeNg is 9.0.0. I have seen [8585](https://github.com/primefaces/primeng/issues/8585) but can not understand how can i fix it. Please guide me in detail

**Comment by SaaimaGul** [comment] 2020-03-13 06:47
As in post mentioned to add _wSpyDisableModality = jest.spyOn(ConfirmDialog.prototype, 'disableModality').mockImplementation(() => {});
Where need to add this lines of code?

**Comment by SaaimaGul** [comment] 2020-03-16 07:14
I have solved the issue by Commenting d.detectChanges in ConfirmDialogBox.js

**Comment by CN91** [comment] 2020-08-31 10:10
I'm having this issue in 9.1.3; any idea how to fix? 

` ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (core.js:30534)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:47483)
    at checkAndUpdateView (core.js:46494)
    at callWithDebugContext (core.js:47865)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:47421)
    at ViewRef_.detectChanges (core.js:32883)
    at ConfirmDialog.disableModality (primeng-confirmdialog.js:304)
    at ConfirmDialog.onOverlayHide (primeng-confirmdialog.js:377)
    at ConfirmDialog.ngOnDestroy (primeng-confirmdialog.js:383)
    at callProviderLifecycles (core.js:33886)`

**Comment by saunandrea** [comment] 2020-09-17 21:11
I'm having this same problem in 9.1.3

```
        this.confirmationService.confirm({
            message: "If there are unsaved changes, they will be lost. Do you want to continue?",
            header: "Confirmation",
            icon: "pi pi-exclamation-triangle",
            accept: () => { this.router.navigate(["home"]); },
            reject: () => { }
        });
```

**Comment by joshmotto** [comment] 2021-01-28 21:08
Hi did you find a solution to this issue?
