### ISSUE TITLE
p-table - Table header and body cells width shifting with virtualscroll

### ISSUE THREAD

**Issue by mrdlink** [primefaces/primeng#9845] opened 2021-02-01 15:07 UTC
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This is a slightly altered version of the official primeng demo for `p-table` virtualscroll.
https://stackblitz.com/edit/p-table-virtual-scroll-non-matching-column-width?file=src/app/app.component.html

**Current behavior**
When I use a `p-table` and activate the virtualscroll like in the official demo and the dataset to display does not exceed the `scrollHeight` of the `p-table` then the width of the table header cells and the table body cells do not match anymore.
If the dataset however is large enough to exceed the `scrollHeight`, the widths are displayed equal again.

This issue still appears when using `colgroup`s.
If I force the vertical scrollbar to be visible all the time by `overflow-y: always` then the issue is fixed.

**Expected behavior**
When the given dataset count does not exceed the visible `scrollHeight` of the `p-table` then the table header (`<th>`) and table body (`<td>`) cells should have the same width, wether the vertical scrollbar is visible or not.

**What is the motivation / use case for changing the behavior?**
With the current behaviour you can't build dynamic table views where you don't know the count of datasets to display. The shift in width then is distracting and confusing to the user. 

**Please tell us about your environment:**
OS: Windows
Browser: Chrome
Angular Version: 11.1.0
PrimeNG Version: 11.2.0

**Comment by adama357** [comment] 2021-02-02 16:47
This is a duplicate of #9653

This bug also manifests _without_ virtual scroll: If scrollable is set but scrollHeight isn't, e.g., you want the table to have horizontal scroll but not vertical.

**Comment by yigitfindikli** [comment] 2021-02-16 13:15
Duplicate of https://github.com/primefaces/primeng/issues/9653

**Closed by yigitfindikli** 2021-02-16 13:15 UTC
