### ISSUE TITLE
In table component "p-tableHeaderCheckbox" does not work corrrectly when "lazy" is enabled

### ISSUE THREAD

**Issue by jesuspa17** [primefaces/primeng#10697] opened 2021-09-30 06:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When lazy is enabled on table component "p-tableHeaderCheckbox" is not selected or unselected correctly.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

https://user-images.githubusercontent.com/9388837/135402343-836d8dc8-9400-4c6a-be97-2ce25e7fcd2d.mp4

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 12.2.7

* **PrimeNG version:** 12.2.0

* **Browser:** all

 
* **Language:** TypeScript 4.2.4

* **Node version:** 14.15.3

**Comment by szandra-homonnai** [comment] 2021-09-30 09:45
I also run into this problem after upgrading to the lates version of PrimeNg. My temporary solution was using PrimeNg 12.0.2 as it contains the old version of p-table and not the new one with the breaking changes (which broke a other things, too). It's a bad solution, but I couldn't find a better one at the moment.

**Comment by jesuspa17** [comment] 2021-09-30 09:48
> I also run into this problem after upgrading to the lates version of PrimeNg. My temporary solution was using PrimeNg 12.0.2 as it contains the old version of p-table and not the new one with the breaking changes (which broke a other things, too). It's a bad solution, but I couldn't find a better one at the moment.

My workaround is to use version 12.1.0-rc.2

**Comment by rtv10dev** [comment] 2021-09-30 09:51
Hello!
I'm having the same problem with the latest version of PrimeNg

**Comment by efibn** [comment] 2021-10-21 07:57
Please fix this ASAP, this feature was working until the change.
Now it seems like a regression in this feature.
In Lazy table the "totalRecords" should hold the total number of available results (like 1 million).
And "rows" the number of records per page, so you cannot "control it with **totalRecords**"

**Please fix it**

**Comment by efibn** [comment] 2021-11-07 10:12
@yigitfindikli - PLEASE fix this, this is a major setback with the table lazy feature !
The p-tableHeaderCheckbox no longer works!!!

PLEASE!

**Comment by dorje42** [comment] 2021-11-08 10:01
Workaround is to use version 12.1.0-rc.2.
It whould be nicer, if we can use the latest version. A fix is reqested.

**Comment by alexliesenfeld** [comment] 2021-11-21 10:21
> Hi,
> 
> Thanks for the reports. We changed tableHeaderCheckbox check logic, now tableHeaderCheckbox control it with total records. So it's by design. But I'm gonna mark this issue as a discussion. Let's hear the community.

Not sure how this can be "by design" .. it's clearly a mistake to take the total count as a reference in a paginated, lazy loaded table, because such a table will almost never present all items at once. This behaviour renders this component useless.

**Comment by EzaBlade** [comment] 2021-11-23 09:37
@yigitfindikli - This is a major regression. I have many tables that are now unusable. If my users click the checkbox they then need to refresh the page to uncheck the row items.

**Comment by EzaBlade** [comment] 2021-11-23 16:19
> @yigitfindikli - This is a major regression. I have many tables that are now unusable. If my users click the checkbox they then need to refresh the page to uncheck the row items.

Having thought about the fact that totalRecords is now used (mentioned in an earlier comment by @yigitfindikli) I had a look at the array that is bound to the table selection property and found that it is initialized to the size of 'totalRecords' with elements where the data has yet to be loaded set to undefined: This is exactly how the example is set up for virtual scrolling.

This is how it looks in F12 - the later elements of the array are undefined because I have yet to scroll and fetch the data:-

![image](https://user-images.githubusercontent.com/1561611/143061758-3b7fe9c7-2e2d-4d77-89b2-c21e5ed37fea.png)



So to get mine working I simply keep track of the header checkbox state and splice in the new data on a virtual fetch in exactly the same way as the row data i.e.

```
updateDataRowsFromLoaded(event: LazyLoadEvent, loadedItems: IOracleRangeSpecification[]) {
        this.dataRows.splice(event.first, event.rows >= this.rows * 2 ? event.rows : this.rows * 2, ...loadedItems);
        this.dataRows = [...this.dataRows];

        if (this.headerCheckboxChecked === true){
            this.checkedRanges.splice(event.first, event.rows >= this.rows * 2 ? event.rows : this.rows * 2, ...loadedItems);
            this.checkedRanges = [...this.checkedRanges];
        }
    }
```
 
This has fixed the problem I had and has, in fact, improved the functionality.

Note: The above example code does not follow the PrimeNg exactly, as I found issues with the calculations it seems to make in certain circumstances. This is my own notes I made in my application (maybe @yigitfindikli would like to comment on this):- 

```
// Note -------------------------------------------------------------------------------------------------------
// Workaround for virtual scrolling with filtering in the PrimeNg table:-
// When loading a table of data with virtual scrolling the initial event.rows value is always (rows * 2).
// The first time virtual scroll fires the onlazyLoad event, event.rows changes to (rows * 3) and stays like this
// while scrolling down to the bottom. It reverts back to (rows * 2) when you scroll all the way back to the top.
// This seems to be the correct behaviour that enables virtual scrolling to be implemented.
//
// When filtering is used in conjunction with virtual scrolling the initial event.rows value is always (rows * 1),
// and then the same when returning to the top on scrolling.
// Therefore where the event.rows value is required I have implemented a check and forced the value to be as expected
// i.e. - const foo = event.rows >= this.rows * 2 ? event.rows : this.rows * 2
```

**Comment by AvshT** [comment] 2021-12-07 13:03
> @yigitfindikli - PLEASE fix this, this is a major setback with the table lazy feature ! The p-tableHeaderCheckbox no longer works!!!
> 
> PLEASE!

@yigitfindikli Maybe it's a minor bug ;-) Please consider this as a valid solution:

https://github.com/primefaces/primeng/commit/a9ba023e6598498e10cb5a392e65ac2655878102#r61494190

**Comment by jesuspa17** [comment] 2021-12-07 13:42
> > @yigitfindikli - PLEASE fix this, this is a major setback with the table lazy feature ! The p-tableHeaderCheckbox no longer works!!!
> > PLEASE!
> 
> @yigitfindikli Maybe it's a minor bug ;-) Please consider this as a valid solution:
> 
> [a9ba023#r61494190](https://github.com/primefaces/primeng/commit/a9ba023e6598498e10cb5a392e65ac2655878102#r61494190)

I just tested it and it works as expected :partying_face:

**Comment by ApplY3D** [comment] 2021-12-11 08:37
Guys, there is new issue #10951 opened by @mertsincan.
I have commited to it, so you can comment in new one😄

**Comment by mertsincan** [comment] 2021-12-14 11:42
Hi,

Fixed in https://github.com/primefaces/primeng/issues/10951. Also, I added a demo related to it on next version.

Best Regard,

**Closed by mertsincan** 2021-12-14 11:42 UTC

**Comment by Madushankumarasiri** [comment] 2022-10-17 06:39
This issue still exists in Primeng 12.2.3. Anyone noticed?

**Comment by BeniaminMakal** [comment] 2023-01-25 11:13
Yep, the issue still exists in Primeng 12.2.3.

**Comment by iRashwan** [comment] 2023-03-14 03:05
Just remove [lazy]="true" and it will work 😊

**Comment by FeedFestival** [comment] 2024-08-13 12:14
I faced this issue in 12.2.3, I found a workaround until this is fixed or you go to a later version.

```html
<p-table 
    #tableRef
    ....
    (onHeaderCheckboxToggle)="onHeaderCheckboxToggle($event)"
    
    ....
    <ng-template pTemplate="header"
        <p-tableHeaderCheckbox #tableHeaderCheckboxRef></p-tableHeaderCheckbox>
```

```typescript

@ViewChild('tableRef', { static: false }) private tableRef?: Table;
@ViewChild('tableHeaderCheckboxRef', { static: false }) private tableHeaderCheckboxRef?: any;

private allSelected = false;

onHeaderCheckboxToggle(event): void {

        if (event?.originalEvent?.skipNextToggleCallback) return;

        this.allSelected = !this.allSelected;
        this.tableHeaderCheckboxRef.checked = this.allSelected;

        if (!this.allSelected) {
            this.tableRef.toggleRowsWithCheckbox({ skipNextToggleCallback: true } as any, false);
        }
        
        // ...
}
```

Hope this helps.
