### ISSUE TITLE
Table:  Column resize not working with minimum width

### ISSUE THREAD

**Issue by yuvarajProl** [primefaces/primeng#11873] opened 2022-08-26 04:57 UTC
### Describe the bug

We have upgraded the primeng version in our application from "12.0.0" to "14.0.2." When the table header has "min-width: 200px," the data table column resizing functionality in the previous version (12.0.0) works perfectly.

My angular code for table heading:

<ng-container *ngFor="let col of columns">
<th [style]="{'min-width': '200px'}"
[pSortableColumn]="col.field" pReorderableColumn pResizableColumn >
<app-datatables-cell-header [data]="col"></app-datatables-cell-header>
</th>
</ng-container>

Primeng "14.0.2" upgrade broke the same code. We determine that the "min-width: 200px" directive from outside is the cause of this. I would like your assistance in figuring out how to utilise "min-width" for table headers "th" in primeng "14.0.2" Version.

Please use the pictures below as a guide.

![image](https://user-images.githubusercontent.com/111727865/186825053-1556bfbb-1e3b-4abf-9af9-2226c68f34c1.png)

Can you assist me to resolve this problem.

### Environment

Angular 14.1.1

### Angular version

14.1.1

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

14.17.0

**Comment by cetincakiroglu** [comment] 2022-09-02 11:46
Hi,

I've tried but cannot reproduce the problem, could you please share a reproducer by using PrimeNG Issue Template https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by yuvarajProl** [comment] 2022-09-07 12:15
Hi @cetincakiroglu ,

Can you please check following link

https://stackblitz.com/edit/github-nvaj19?file=src/app/app.component.html

**Comment by cetincakiroglu** [comment] 2022-09-07 14:18
Hi @yuvarajProl,

Great catch, thanks for your report it'll be fixed in the upcoming release!

**Closed** 2022-09-07 14:19 UTC
Labels: defect
