### ISSUE TITLE
angular universal support ?

### ISSUE THREAD

**Issue by itsmeprasanjit** [primefaces/primeng#1341] opened 2016-11-17 12:25 UTC
Are there any plans or roadmap for rendering primeng on the server so that it works with angular universal?Without universal the first page time is really slow and SEO does not work :(

**Comment by cagataycivici** [comment] 2016-11-18 07:59
Please use forum for questions;

http://forum.primefaces.org/viewforum.php?f=35

You can use AOT and lazy loading routes to speed it up.

**Comment by itsmeprasanjit** [comment] 2016-11-18 10:20
I am already using AOT and lazy loading. But it does not solve the problem of search engine optimization and Social media sharing of links.I just think making it compatible with angular universal  is the only thing missing to make this perfect UI framework for angular 2.

**Comment by cagataycivici** [comment] 2016-11-29 15:31
Do you know the steps to make PrimeNG support universal?

**Comment by inspirebrio** [comment] 2016-11-30 04:27
Primeng has already implemented the first step of not using client side libraries like jquery but charts are still there but thats fine we can avoid using charts. Next and the most important thing is avoid calling dom or browser specific events directly otherwise we cant render it on the server.

**Comment by itsmeprasanjit** [comment] 2016-11-30 11:56
Since we are already using primeng for quite a few websites of ours, trying a alternate approach is not possible and clients want SEO.
Maybe we can learn from angular/material2 team what they are doing cause even they were facing the same issues and are trying to fix them so that it can render on the server.
let us take button from primeng into consideration and why its not working on angular-universal
it gives an error of :ReferenceError: Event is not defined
The same problem is solved by angular material
[https://github.com/primefaces/primeng/blob/master/components/button/button.ts](url)
[https://github.com/angular/material2/blob/master/src/lib/button/button.ts](url)
[https://github.com/angular/material2/issues/306](url)

**Comment by DaSchTour** [comment] 2016-11-30 14:37
It's really funny. Angular 2 already misses a lot of important features that angular 1 had. And with angular universal you can use even less. I've the impression there is nothing left beside @Component 😆

**Comment by Quovadisqc** [comment] 2016-12-08 13:54
@cagataycivici 
As per angular-universal's documentation:
window, document, navigator, and other browser types - do not exist on the server - so using them, or any library that uses them (jQuery for example) will not work.

I could get some modules working ( DataGrid, Calendar ).
The only problem I encountered as of now was with the Button module. I also get problems with other modules but only because they use Button module themselves.

The problem is actually quite simple: the "Event" interface is a browser global and doesn't exist in a NodeJS environment.

Here is the commit that fixed the issue for material2:
https://github.com/angular/material2/pull/307/commits/76e4f565e859b395a8d131fd4b58954d079eb207

**Comment by tokyoite** [comment] 2017-01-03 16:15
Anybody hear any news on a fix for this?

**Comment by itsmeprasanjit** [comment] 2017-01-04 06:18
unfortunately primeng team has already started working on primeReact seems like this is not going to be implemented. Start using prerender.io if you want to save yourself :)

**Comment by Quovadisqc** [comment] 2017-01-04 16:23
@tokyoite There are a few "solutions".
1. Don't use components that are problematic (Growl, DataGrid, etc)
2. Use these components only in lazy-loaded modules so they are only executed client-side

**Comment by tokyoite** [comment] 2017-01-05 18:34
@Quovadisqc You're a life saver! Thank you Thank you Thank you :D

**Comment by vitthalr** [comment] 2017-01-12 14:19
@tokyoite I'm having the same issue that you have posted below, can you please throw some light, how you actually fixed it?: - 
http://forum.primefaces.org/viewtopic.php?f=35&t=48801&p=150912&hilit=universal+angular#p150912
![image](https://cloud.githubusercontent.com/assets/25004254/21893183/076b3474-d900-11e6-8ba9-8ed596367b16.png)

Will be a great help!!

Thanks a lot in advance

**Comment by vitthalr** [comment] 2017-01-12 14:33
Between, I'm trying to use "SliderModule" module
import {SliderModule} from 'primeng/primeng';

**Comment by cagataycivici** [comment] 2017-03-03 06:47
First we need to identify the componens that directly access browser objects like window on initialization I believe. Angulars renderer api (I think it has a new name in Angular 2) provides an abstraction so although we use it in many other parts, the parts that directly use window or similar should be replaced. So please create separate issues as this issue is too broad, a new issue can be, "Growl support for Angular Universal", then we'll do our best to provide support.

I don't think we can do anything for some components like charts and schedule though, but 90%+ can be universal friendly.

**Closed by cagataycivici** 2017-03-03 06:47 UTC

**Comment by cagataycivici** [comment] 2017-03-03 06:49
@itsmeprasanjit, primereact is an idea but it is not a top level project at PrimeTek right now, so our resources are dedicated to PrimeNG and PrimeFaces at the moment. We need to expand our team so a new members on our team will work on PrimeReact.

**Comment by tokyoite** [comment] 2017-03-03 21:24
I got this working a little while back and works like a charm. Thank you


________________________________

**Comment by cagataycivici** [comment] 2017-04-01 06:42
Cool, we will also start enhancements by mid april.

**Comment by tokyoite** [comment] 2017-04-04 18:52
@vitthalr, Sorry I missed your question :P. I hope you found a solution to your problem.

**Comment by kito99** [comment] 2017-04-27 18:51
@cagataycivici shouldn't you re-open this as a new feature so we can track your progress? ;-)

**Comment by cagataycivici** [comment] 2017-04-28 11:24
This is closed because we need to handle each case one by one such as "Growl doesn't support Universal" or "Universal support for Dropdown". I believe many already support it and we can tweak others that do not support it, feel free to point us to the created issues. Next week, we'll start issue tracker cleanup as well and add universal label to issues for better tracking.

**Comment by dockleryxk** [comment] 2017-08-22 18:52
@tokyoite how did you resolve this?

**Comment by tokyoite** [comment] 2017-08-22 19:15
Hi Richard,


Only import 'primeng' in modules that are lazy-loaded (credit to @Quovadisqc<https://github.com/Quovadisqc>). That fixed it for me 😉


________________________________
