### ISSUE TITLE
Table: When removing the filter constraint it should not filter when showApplyButton is visible

### ISSUE THREAD

**Issue by ymg2006** [primefaces/primeng#15032] opened 2024-03-13 11:22 UTC
### Describe the bug

Table: When removing the filter constraint it should not filter when showApplyButton is visible.
Remove Rule creates a backend request when apply is visible.
Attached images.
![Screenshot 2024-03-13 144422](https://github.com/primefaces/primeng/assets/844238/11f228ea-5763-4b0f-af8f-add81a29754e)
![Screenshot 2024-03-13 144504](https://github.com/primefaces/primeng/assets/844238/a5f4c457-9739-40e5-be70-edaf05c96a2d)

### Environment

developement environment

### Angular version

17.0.x

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

### Steps to reproduce the behavior

1. click to remove rule on any filter with showApplyButton
2. it will send request !!!!!!!!!!!!!!!!!!!

### Expected behavior

1. When show apply is visible, the responsibility for filtering is on the button so there is no need when removing a rule, it create a request.

**Comment by cetincakiroglu** [comment] 2024-03-19 11:29
Hi,

Remove rule filters the data again by the remaining filter constraints. So it re-filters the data both when you add a new rule and removing a rule. It's not a bug, it's made by design. 

Thanks for reporting, closing the issue since it's not a bug.

**Comment by ymg2006** [comment] 2024-03-19 19:49
> Hi,
> 
> Remove rule filters the data again by the remaining filter constraints. So it re-filters the data both when you add a new rule and removing a rule. It's not a bug, it's made by design.
> 
> Thanks for reporting, closing the issue since it's not a bug.

@cetincakiroglu the issue is not filtering, the issue is when the apply button is visible it makes a request. I copied this part of the code from the components codes. so either make them both filter without considering apply button visibility, or apply this to not create request.
To explain more. it is not an issue that filters it. the issue is when you have apply button it should wait until you press apply then filter.
Please understand the it well before closing it.

**Comment by cetincakiroglu** [comment] 2024-03-22 12:36
I got your point now, thanks for the explanation.

**Closed** 2024-03-22 12:37 UTC
Labels: Type: Bug, LTS-PORTABLE, Status: Needs Triage
