### ISSUE TITLE
p-password Component Bug

### ISSUE THREAD

**Issue by gh-mohammadi** [primefaces/primeng#10356] opened 2021-06-23 04:13 UTC
hi 
p-password component doesn't show pTemplate and it seems because of PrimeTemplate in SharedModule wasn't correct

**Comment by webnegar** [comment] 2021-06-23 08:12
also this [#10355](https://github.com/primefaces/primeng/issues/10355)

**Comment by yigitfindikli** [comment] 2021-06-24 08:03
Duplicate of https://github.com/primefaces/primeng/issues/10355

**Closed by yigitfindikli** 2021-06-24 08:03 UTC
