### ISSUE TITLE
Data table multiple range selection (shift + click by default)

### ISSUE THREAD

**Issue by uakennysoft** [primefaces/primeng#3155] opened 2017-06-20 12:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
shift+click on row is ignored by DataTable and works as simple click

**Expected behavior**
shift+click on row with index = X will select range from  selectedRowIndex or 0  to X 

**What is the motivation / use case for changing the behavior?**
it would be nice to support shift+click  in multiple selection mode

**Comment by cagataycivici** [comment] 2017-06-20 13:29
Duplicate of #1283

**Closed by cagataycivici** 2017-06-20 13:29 UTC
