### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#871] opened 2016-09-07 21:52 UTC
I'm trying to compile my application with AOT compiler but getting an error with `Primeng modules`.

> Error: Unexpected value 'ContextMenuModule' exported by the module 'SharedModule'   

My App `SharedModule `export `primeng modules` that my app require including 

> import { ContextMenuModule } from 'primeng/components/contextmenu/contextmenu';
> import { DataTableModule } from 'primeng/components/datatable/datatable';
> import { DialogModule } from 'primeng/components/dialog/dialog';
> import { SplitButtonModule } from 'primeng/components/splitbutton/splitbutton';
> import { TabViewModule } from 'primeng/components/tabview/tabview';
> import { TooltipModule } from 'primeng/components/tooltip/tooltip';

Any thoughts?

**Comment by moxival** [comment] 2016-09-08 06:01
@ammar91 is this happening with the beta 15?

**Comment by ammar91** [comment] 2016-09-08 09:07
@moxival Yes.

**Comment by moxival** [comment] 2016-09-08 15:45
@ammar91 we haven't taken the plunge in AOT yet so I can't really help, sorry. Maybe @cagataycivici can give some I insight?

**Comment by ammar91** [comment] 2016-09-13 16:18
@cagataycivici Could you please put your thoughts on this?

**Comment by sslee** [comment] 2016-09-14 12:30
Seems to have to do with not having a metadata.json file.
https://github.com/valor-software/ng2-bootstrap/issues/933

Probably just have to wait until they have time to do this.

**Comment by ammar91** [comment] 2016-09-15 11:06
Now that the Angular 2 officially released. It would be good to have it working in the next release.

**Comment by ammar91** [comment] 2016-09-17 14:10
Any chance of having it functional in beta 16?

**Comment by alinflorin** [comment] 2016-09-20 06:24
Will this be available in the next beta, or later?

**Comment by ammar91** [comment] 2016-09-26 21:25
@qdouble How does material 2 and other 3rd party packages run fine in AOT mode? I'm even able to compile my application in AOT mode if I remove PNG dependency, isn't that mean PNG not AOT compatible yet?

**Comment by qdouble** [comment] 2016-09-26 21:39
@ammar91 I'm not sure of every step 3rd party developers have to take...the main problem may be that a lot of these libraries were created before AOT was even a consideration and need to be updated.

As far as the png thing, link to a reproduction of it over on my repo and I can look at it, may need a loader or something else, I haven't dealt with that yet

**Comment by ammar91** [comment] 2016-09-26 21:39
According to this github issue https://github.com/angular/angular/issues/11889 , it looks like the 3rd party module must ship the metadata files.

**Comment by cagataycivici** [comment] 2016-09-27 11:01
We haven't managed to spare time to look into this yet, we'd appreciate feedback on how to add AOT compatibility.

**Comment by tpeter1985** [comment] 2016-09-28 11:29
angular/angular#11262

**Comment by ammar91** [comment] 2016-09-28 14:33
@cagataycivici Looks like these are the steps required to generate metadata files

https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.mtna6ixy8

**Comment by cagataycivici** [comment] 2016-09-30 10:48
Thanks we'll review after beta17.

**Comment by ammar91** [comment] 2016-10-02 19:33
@cagataycivici I'm able to successfully produce metadata files for primeng by following the guide above. 

I did make several changes along the way by looking at the error messages during compilation. Those are very minor and quick fixes which are mentioned here

https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.nq9gqm4o2

However, there are two main changes I needed to be done
1) Remove typings.json in favor of typescript 2.0, new way of defining type declaration files
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

2) Update webpack to webpack2 beta

3) Isolate the App Module and Entry file, otherwise webpack complain about Module error described here https://github.com/webpack/webpack/issues/2894

I created "aot" branch from the latest beta17 snapshot, but when I'm trying to push it return 403 forbidden error.

**Comment by ammar91** [comment] 2016-10-03 00:04
@cagataycivici I made a pull request. Please check https://github.com/primefaces/primeng/pull/1004

**Comment by cagataycivici** [comment] 2016-10-25 22:00
AOT support work has started and we definitely need feedback. As far as I understand metadata files are only required for non-ts files, from the docs;

> The "skipMetadataEmit" : true property prevents the compiler from generating metadata files with the compiled application. Metadata files are not necessary when targeting TypeScript files, so there is no reason to include them.

@ammar91's PR adds metadata files which we'd like to avoid maintaining, my initial idea is adding public properties to some of the template variables we have and also ship the ts files in the npm package because until now we only ship js. When the ts files of PrimeNG will be in npm and as a result in your app's node_modules, I'm hoping you will be able to compile your app with AOT without need for metadata files.

Feedback is welcome.

**Comment by nileshmali** [comment] 2016-10-26 04:47
Hi @cagataycivici,
We can check the way builds are done in https://github.com/angular/material2 this project.

**Comment by ammar91** [comment] 2016-10-26 10:29
@cagataycivici I agree, metadata.json should not be under version control. I believe you could generate those before publishing to npm. This is how ng-bootstrap and angular material doing as well.

**Comment by ammar91** [comment] 2016-10-26 11:14
Also, AMO shipping the ts files in npm package would not be an ideal solution.

**Comment by cagataycivici** [comment] 2016-10-26 12:07
My current decision is not to include ts and generate metadata.json files when publishing. I'd appreciate if you could point me to the process of generating these files.

**Comment by ammar91** [comment] 2016-10-26 12:43
@cagataycivici Sure, These are the steps for generating the files

1) Install angular compiler 

> npm install @angular/compiler-cli @angular/platform-server --save

2) Get tsconfig for AOT from the Angular doc
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

3) Add script in package.json
```
"scripts": {
    "ngc": "ngc -p ./tsconfig-aot.json"
  }
```

4) Changed the components template url (if they are not inline) from Absolute to Relative Path.

Eg:

```
@Component({
    templateUrl: 'components/blockui/blockui.html'
})
```

To 

```
@Component({
    templateUrl: './blockui.html'
})
```

5) Remove typings.json in favor of typescript 2.0, new way of defining type declaration files.
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

And add these in tsconfig so it looks for the typings file in the correct location

```
 "typeRoots": [
            "node_modules/@types"
        ],
  "types": [
            "node",
            "jquery",
            "fullcalendar"
        ]
```

You may notice core-js is not listed, that is because it may throw `duplicate identifier error` if you include in list.

6) Now finally run 

> npm run ngc


You may get several errors which are mostly related to access modifiers mentioned in the below article (3rd point,  that says private, protected accessors should be changed to public for any members accessed from template)

https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.9wzvvaym0

After fixing those, you should be able to successfully compile with ngc.

Hope that helps!

**Comment by cagataycivici** [comment] 2016-10-27 07:40
Thanks, I'll work on this soon.

**Comment by cagataycivici** [comment] 2016-10-27 22:23
Work has started, I'm doing an entire code review to remove "any" types and check aot compatibility. As a side note, I had to add "skipMetadataEmit" : false to get the metadata json files also somehow haven't done some steps like number 5 but it worked fine.

**Comment by cagataycivici** [comment] 2016-10-27 22:29
Quick question, does setting     "noImplicitAny" in tsconfig-aot.json as false have any impact on AOT metadata json files or ngFactory?

**Comment by cagataycivici** [comment] 2016-10-27 22:53
Alright, I've done the changes for AOT support, should we do a beta21 before RC to test it?

**Closed** 2016-10-27 22:53 UTC
Labels: enhancement

**Comment by ammar91** [comment] 2016-10-28 11:07
@cagataycivici That's Great, There should be no impact by setting "noImplicitAny" to false.
Looking forward to try this out. Thanks so much..

**Comment by Pilukina** [comment] 2017-03-03 12:08
hello @cagataycivici 

You said on this post that primeng is ready for aot.

Nevertheless, I cannot compile even with a simple import (not using any component on html) using the follow primeng version:
`"primeng": "^2.0.2",`

**module**
`import { CheckboxModule } from 'primeng/primeng';

@NgModule({
  imports: [ CommonModule, FormsModule, CheckboxModule ],
  declarations: [ LoginComponent ],
  exports: [ LoginComponent ]
})`

**component**
`import { CheckboxModule } from 'primeng/primeng';`

**tsconfig-aot.json**
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "stripInternal": true,
    "experimentalDecorators": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "module": "es2015",
    "moduleResolution": "node",
    "paths": {
      "@angular/core": ["node_modules/@angular/core"],
      "rxjs/*": ["node_modules/rxjs/*"]
    },
    "rootDir": ".",
    "outDir": "dist",
    "sourceMap": true,
    "inlineSources": true,
    "target": "es5",
    "skipLibCheck": true,
    "lib": [
      "es2015", 
      "dom"
    ]
  },
  "files": [
    "index.ts"
  ],
  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}
**rollup-config.json**
`import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'dist/index.js',
  dest: 'dist/bundles/xplainsnippets.umd.js', // output a single application bundle
  sourceMap: false,
  format: 'umd',
  moduleName: 'XplainSnippets',
  globals: {
    '@angular/core': 'ng.core',
    'rxjs/Observable': 'Rx',
    'rxjs/ReplaySubject': 'Rx',
    'rxjs/add/operator/map': 'Rx.Observable.prototype',
    'rxjs/add/operator/mergeMap': 'Rx.Observable.prototype',
    'rxjs/add/observable/fromEvent': 'Rx.Observable',
    'rxjs/add/observable/of': 'Rx.Observable'
  },
  onwarn: function(warning) {
    // Skip certain warnings

    // should intercept ... but doesn't in some rollup versions
    if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }
    // intercepts in some rollup versions
    if ( warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1 ) { return; }

    // console.warn everything else
    console.warn( warning.message );
  },
  plugins: [
      nodeResolve({jsnext: true, module: true}),
      commonjs({
        include: 'node_modules/rxjs/**',
      }),
      uglify()
  ]
}`

When running: `ngc -p tsconfig-aot.json && rollup -c rollup-config.js`

The terminal throws:
` ngc -p tsconfig-aot.json && rollup -c rollup-config.js

⚠️   'default' is imported from external module 'rollup' but never used

�   'CheckboxModule' is not exported by node_modules\primeng\primeng.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
dist\src\app\login\login.module.js (5:9)
3: import { FormsModule } from '@angular/forms';
4: import { LoginComponent } from './login.component';
5: import { CheckboxModule } from 'primeng/primeng';`


Please, could you inform me If there is something missed on my configuration? Mabe on the tsconfig-aot.json?

Thank you in advance.

**Comment by edwinquaihoi** [comment] 2017-03-06 01:56
Hi @cagataycivici I am facing the same issue as @Pilukina, is aot  in 2.0 branch? By the way PrimeNg is fantastic!

**Comment by dakotamurphyucf** [comment] 2017-03-14 02:56
@pauly815 @edwinquaihoi  
change import { CheckboxModule, DataTableModule, SharedModule, ... } from 'primeng/primeng'; 
to 
import {CheckboxModule} from  'primeng/components/checkbox/checkbox';
import {DataTableModule} from  'primeng/components/datatable/datatable';
import {SharedModule} from  'primeng/components/common/shared';
ect..

**Comment by Pilukina** [comment] 2017-03-14 06:02
Thank you so much for your answer. The bug is solved by primeng, they have included the needed .metadata.json for aot on version 2.0.3.

Nevertheless the components could be imported and compiled using both paths.

**Comment by mustafaekim** [comment] 2017-03-24 08:29
I could not success to AOT compile my ang2 app with primeNG modules.  I am getting the error below for all modules:

`'EditorModule' is not exported by 'node_modules\primeng\components\editor\editor.js'`

Anyone knows how we can overcome the issue?

**Comment by Pilukina** [comment] 2017-03-24 08:44
I'm using primeng v2.0.3, The node_modules\primeng\components\editor\editor.js exports exports.EditorModule = EditorModule; on line 139.
 I have checked the file editor.metadata.json (mandatory for aot compiling) is there.

Could you check which version of primeng are you using and if the metadata.json is included?

**Comment by mustafaekim** [comment] 2017-03-24 08:56
Hi Pilukina,

I am using 2.0.5, ngc compiles but rollup throws error. Sorry to missleading.

`'GrowlModule' is not exported by 'node_modules\primeng\components\growl\growl.js'
'ProgressBarModule' is not exported by 'node_modules\primeng\components\progressbar\progressbar.js'
'SharedModule' is not exported by 'node_modules\primeng\components\common\shared.js'
'EditorModule' is not exported by 'node_modules\primeng\components\editor\editor.js'
'ButtonModule' is not exported by 'node_modules\primeng\components\button\button.js'
'InplaceModule' is not exported by 'node_modules\primeng\components\inplace\inplace.js'
'InputTextModule' is not exported by 'node_modules\primeng\components\inputtext\inputtext.js'
'SpinnerModule' is not exported by 'node_modules\primeng\components\spinner\spinner.js'
'InputMaskModule' is not exported by 'node_modules\primeng\components\inputmask\inputmask.js'
'CalendarModule' is not exported by 'node_modules\primeng\components\calendar\calendar.js'
'ConfirmDialogModule' is not exported by 'node_modules\primeng\components\confirmdialog\confirmdialog.js'
'GrowlModule' is not exported by 'node_modules\primeng\components\growl\growl.js'
'ProgressBarModule' is not exported by 'node_modules\primeng\components\progressbar\progressbar.js'
'ConfirmationService' is not exported by 'node_modules\primeng\components\common\api.js'
�   'EditorModule' is not exported by node_modules\primeng\components\editor\editor.js`

**Comment by Pilukina** [comment] 2017-03-24 09:30
I'm afraid I can't help you. Nevertheless, I recommend you directly write a new topic on ngprime forum: https://forum.primefaces.org/viewforum.php?f=35
They helped me very soon. Good luck! :)

**Comment by Viehwoidler** [comment] 2017-03-24 13:32
Actually there is a workaround to specify the named exports in the rollup-config like this:
```javascript
plugins: [
  commonjs({
    include: 'node_modules/**',
    namedExports: {
      // Add every import you need from primeng to the list
      'node_modules/primeng/primeng.js': ['SharedModule', 'DataTableModule', 'DataTable']
    }
  })
]
```

**Comment by mustafaekim** [comment] 2017-03-24 14:05
Thanks, that solved the problem.

**Comment by dhakehurst** [comment] 2018-07-26 11:38
it solves the problem with a work around.

The primeng modules should 'export' stuff properly.

**Comment by Rambou** [comment] 2019-06-10 07:48
Could this be hot fixed please? PrimeNG is not properly exporting stuff.

**Comment by jrood** [comment] 2019-10-14 16:20
@cagataycivici can you please reopen this issue since it seems to still not be fixed?
