### ISSUE TITLE
FileUpload doesn't allow adding extra files into the queue list in advanced mode.

### ISSUE THREAD

**Issue by Zetsui** [primefaces/primeng#3529] opened 2017-07-28 19:23 UTC
**I'm submitting a bug report (possibly a feature request)**  (check one with "x")
```
[X] bug report => Search GitHub for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

While files are in the queue to be uploaded if you close the file explorer window and click the "Choose" button nothing happens.

**Expected behavior**

The file explorer window re-opens and the user can continue to add new files to the queue list.

**Minimal reproduction of the problem with instructions**

https://www.primefaces.org/primeng/#/fileupload
Can do it on your demo.  Under advanced click "Choose" and select 1 file.  Then try to click "Choose" again to add another file.

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.1.2

* **Browser:** [Chrome | IE]

**Comment by YvonneNeuland** [comment] 2017-08-01 17:45
I am also having this problem with the component.  I will note, that even though you can no longer use the choose button to open the file browser, you can still drag and drop files into the queue.

**Comment by fewal** [comment] 2017-08-17 11:57
Any news about this problem or workaround which allows user to add another file?

**Comment by charnpreetsingh** [comment] 2017-08-24 22:50
Confirmed bug still in primeng 4.1.3. Any update or workaround would be appreciated!

**Comment by dnguyen73** [comment] 2017-09-14 06:44
Still have same issue with 4.2.0-rc.1

**Comment by cagataycivici** [comment] 2017-10-02 08:07
Duplicate of https://github.com/primefaces/primeng/issues/3961

**Closed by cagataycivici** 2017-10-02 08:07 UTC
