### ISSUE TITLE
[Feature Request] Add support for row level editing for p-datatable

### ISSUE THREAD

**Issue by sharok** [primefaces/primeng#2208] opened 2017-03-03 04:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
Allow user to edit datatable at row level.
Example could be found [here](http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml)

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.1

**Comment by meanle11** [comment] 2017-05-23 02:05
I think editing on row is very necessary for the user. Because it brings a more friendly management over datatable, so I'm looking forward to it being updated soon.

**Comment by cagataycivici** [comment] 2017-06-20 13:54
Duplicate of #2048

**Closed by cagataycivici** 2017-06-20 13:54 UTC
