### ISSUE TITLE
Can filter feature be added to data grid please?

### ISSUE THREAD

**Issue by westlake91361** [primefaces/primeng#2470] opened 2017-04-07 19:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/77OG7zX3LToGoidKaKOS

**Current behavior**
No filter feature available with data grid.

**Expected behavior**
Be able to filter data like with data table.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
To provide user the capability to filter out data with data grid view.

**Please tell us about your environment:**
Windows 10, IntelliJ 2017.1

* **Angular version:** 2.0.X
Angular 4.0.0rc.3

* **PrimeNG version:** 2.0.X
PrimeNG 4.0.0 rc.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

* **Node (for AoT issues):** `node --version` =   6.9.5

**Comment by cagataycivici** [comment] 2017-06-22 13:33
Duplicate of #2457

**Closed by cagataycivici** 2017-06-22 13:33 UTC
