### ISSUE TITLE
Grid Layout of DataViewModule is not working

### ISSUE THREAD

**Issue by shashidhargm** [primefaces/primeng#5450] opened 2018-03-29 11:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When i use  like below it works perfectly
`<ng-template let-car pTemplate="listItem">`
But if i replace with gridItem then it displays nothing  
 `<ng-template let-car pTemplate="gridItem">`

**Expected behavior**
It should display provided data. 

**Minimal reproduction of the problem with instructions**
I followed primeng documentation. 

**What is the motivation / use case for changing the behavior?**
Nothing need to be changed. I just want my data to be displayed. 

**Please tell us about your environment:**
Ubuntu 16.04 LTS 64-bit, RubyMine, yarn, local server

* **Angular version:** 
5.2.9

* **PrimeNG version:** 
5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
7.10.0

**Comment by michaelsampietro** [comment] 2018-05-23 20:16
@shashidhargm The issue is with the documentation, it is missing one detail.

On the `<p-dataView>` tag you have to insert an attribute called "layout" and set it to "grid".

Here's an example:

```
<p-dataView #dv [value]="listaImagens['content']"
                        filterBy="brand"
                        [paginator]="true"
                        [rows]="10"
                        [lazy]="true"
                        (onLazyLoad)="getImagensProduto($event)"
                        [totalRecords]="listaImagens['totalElements']"
                        layout="grid"> ... </p-dataView>
```

This worked for me. Hope it helps!

**Comment by shashidhargm** [comment] 2018-05-28 05:54
@michaelsampietro, It worked. Thanks :+1:

**Comment by michaelsampietro** [comment] 2018-05-28 19:07
@shashidhargm Please, close this issue :)

**Closed** 2018-05-29 06:34 UTC

**Comment by nsksaisaravana** [comment] 2018-08-16 06:01
@michaelsampietro you saved my day.
