### ISSUE TITLE
[p-table]: Add rtl support for column resizing

### ISSUE THREAD

**Issue by Valamano** [primefaces/primeng#8283] opened 2019-10-29 08:02 UTC
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**Current behavior**
The column resize on rtl works incorrect

**Expected behavior**
The column resize should work like in ltr table

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

 
* **Language:** [TypeScript X.X | ES6/7 | ES5]

**Comment by mavm84** [comment] 2019-12-04 14:08
i have the same issue, the behavior when resizing on RTL is wrong.
when i try to increase the column size, it shrinks

**Comment by viceice** [comment] 2021-05-07 05:21
Duplicate of #7042

**Comment by mertsincan** [comment] 2022-11-09 19:47
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 19:47 UTC
Labels: enhancement
