### ISSUE TITLE
Bug in bootstrap theme for growl componemt

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1187] opened 2016-11-02 09:07 UTC
The background colour for growl message is always blue whether you show info, warning or error.
This happens in bootstrap theme but is working properly in omega theme.
Please resolve in next rc.

**Comment by ctrl-brk** [comment] 2016-11-02 15:40
That's becase .ui-growl-item-container.ui-state-highlight.ui-growl-message-... (success, error, etc) are not even defined in the bootstrap theme css. I have this issue reported already. I would say the Omega theme seems to be the one which gets most attention, not all of them.
[https://github.com/primefaces/primeng/issues/1143](https://github.com/primefaces/primeng/issues/1143)

**Comment by kcsahoo** [comment] 2016-11-02 16:28
Are you going to update the bootstrap theme with all the features of omega theme?
I can say this theme is more popular than omega.

**Comment by apiweb** [comment] 2016-11-17 01:53
Same mistake here.
It is always showing the blue background, even if the message is of success or error.

**Comment by mrgoos** [comment] 2016-11-30 07:40
Hey, I think that I have the same issue though it seems black to me and not blue.
Is that what you're experiencing?
<img width="308" alt="screen shot 2016-11-29 at 17 53 59" src="https://cloud.githubusercontent.com/assets/2561935/20743765/d306b2da-b6e0-11e6-8bef-b6fd612b66b6.png">

Also attaching developer tools inspect elements:
<img width="1088" alt="screen shot 2016-11-29 at 21 39 34" src="https://cloud.githubusercontent.com/assets/2561935/20743776/e272aaee-b6e0-11e6-8ca4-eb9f8e04a8fe.png">

I have opened a thread in the ultima-primeNG forum as well:
http://forum.primefaces.org/viewtopic.php?f=45&t=48333&sid=4f8b4d115c82ff3f0c76499fbf1d7d00

Also waiting for a solution.

**Comment by Mrtcndkn** [comment] 2016-12-05 19:27
Hi,

Duplicate of https://github.com/primefaces/primeng/issues/1143 

@mrgoos In ultima its designed according to the material specs so it's not a bug when you are using ultima.But you can always easily change it for example

`.ui-growl-item-container.ui-state-highlight.ui-growl-message-info {
    background: blue;
}`

**Closed by Mrtcndkn** 2016-12-05 19:27 UTC
Labels: review

**Comment by cagataycivici** [comment] 2016-12-13 11:22
We've decided to give colors to Ultima Growl as well in next version.

**Comment by mrgoos** [comment] 2016-12-13 11:51
Thanks a lot for this @cagataycivici
