### ISSUE TITLE
Calendar – please add support  for week numbers. Aka showWeekNumbers property.

### ISSUE THREAD

**Issue by sdaniil** [primefaces/primeng#6275] opened 2018-08-09 07:41 UTC
Calendar – please add support for week numbers. Aka showWeekNumbers property.

**Comment by JacobSiegle** [comment] 2018-08-09 12:31
Duplicate of https://github.com/primefaces/primeng/issues/6242. Please close.

**Closed** 2019-04-22 12:21 UTC
