### ISSUE TITLE
FileUploud with accept="image/png" failed

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#2897] opened 2017-05-26 14:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/MQ5FEOcKTMeRYf8MtBfs?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
select a png file on your computer

![screenshot 2017-05-26 16 12 16](https://cloud.githubusercontent.com/assets/21671762/26498102/1f12413e-422e-11e7-8db4-f1e1bd8a9fec.png)

**What is the motivation / use case for changing the behavior?**
limit uploud to PNGs no

* **Angular version:** 4.1
* **PrimeNG version:** 4.0

* **Browser:** [all ]
* **Language:** [all]

**Comment by cagataycivici** [comment] 2017-05-26 15:10
Duplicate of #2699

**Closed by cagataycivici** 2017-05-26 15:10 UTC

**Comment by cyberrranger** [comment] 2017-05-26 15:14
thx, i m searching 'FileUploud' and found nothing before i post my issue.

**Comment by cagataycivici** [comment] 2017-05-26 15:28
No problem.
