### ISSUE TITLE
ViewEncapsulation.ShadowDom breaks components 

### ISSUE THREAD

**Issue by irekBudzowski** [primefaces/primeng#9471] opened 2020-10-29 12:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-autocomplete-demo-aha9nr

**Current behavior**
Enabling ViewEncapsulation.ShadowDom in Angular's component, embedded prime's component doesn't work.

**Expected behavior**

ViewEncapsulation.ShadowDom in Angular's component should not break embedded prime component.

**Minimal reproduction of the problem with instructions**

Use  ViewEncapsulation.ShadowDom in components with embedded prime's component.

**What is the motivation / use case for changing the behavior?**

Possibility to use the library in microfrontends, where using ShadowDom is crucial.

* **Angular version:** 5.X

Angular version 10.X

* **PrimeNG version:** 5.X

PrimeNg version 10.X

**Comment by AKoempel** [comment] 2020-11-10 12:50
Same problem here. We want to use PrimeNG components inside WebComponents as well and the ViewEncapsulation.ShadowDom indeed breaks most components. I just looked at the p-calendar. Two functions of the Calendar are problematic:

- Calendar::bindDocumentClickListener: Clicks caught outside of the shadow dom always have the shadow root as event target to hide implementation details -> All clicks are considered to be outside of the calendar.
- Calendar::bindScrollListener: DomHandler::getScrollableParents fails executing getComputedStyle on the shadow root.

The only solution for me right now would be to fork PrimeNG and fix it or create a directive that overrides those functions of the component.

**Comment by irekBudzowski** [comment] 2020-11-10 17:29
Thank you @AKoempel. I will try to solve that with directive, as you proposed. Also with some components, I will migrate to material, they updated js recently and it works like a harm! Unless, of course, PrimeFaces will upgrade js in the library too.

**Comment by TiagoM-Leite** [comment] 2021-02-08 09:51
We're also using ViewEncapsulation.ShadowDom and, in our case, it was the behavior of any overlay panel. It appeared and disapeared right away when the user clicked on the component to show (e.g. a user clicks in a multiselect, options appear and disapear very quickly). As @AKoempel said, we ended up overidding "isOutsideClicked(event)" function in primeng-multiselect.js and primeng-dropdown.js

**Comment by TiagoM-Leite** [comment] 2021-02-22 10:28
Also, since v. 11.2.1, it's breaking with the following error:
"Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'"

The root cause seems to be this commit:
https://github.com/primefaces/primeng/commit/297beb06e8fc6ac525feab573bcbcf7bab52be16

For now, we're leaving on v. 11.2.0 (on which we had to create directives to override problematic functions in the component).

We're also leaving primeng in the near future, since we have to use shaddow dom and clearly primeng isn't compatible with it.

**Comment by raymatos** [comment] 2021-07-15 15:10
Is this still an issue?

**Comment by maitrungduc1410** [comment] 2021-07-22 04:56
@raymatos yes, it's still an issue, for all components has "dropdown": Dropdown, Calendar,..

**Comment by maitrungduc1410** [comment] 2021-07-23 10:19
Here's what I found: the issue caused by this line: 

https://github.com/primefaces/primeng/blob/master/src/app/components/dom/domhandler.ts#L175

PrimeNg uses `window['getComputedStyle'](node, null)`, and in the case of ShadowDOM it'll throw error because `node` (which is passed to `overflowCheck`) is not normal HTML Element

I manage to solve this issue, not much error:
- Step 1: Download these 2 files from PrimeNg to your project: [domhandler.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/dom/domhandler.ts) and [connectedoverlayscrollhandler.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/dom/connectedoverlayscrollhandler.ts)
- Step 2: update `domhandler.ts`, line 172:
```js
// from this
let parents = this.getParents(element);

// to this
let parents = this.getParents(element).filter(item => !(item instanceof ShadowRoot));
```
Explain: we filter out the shadow root when getting parents of `element`, so later params which is passed to `overflowCheck` will always an HTML Element

- Step 3: create a directive to override a behaviour of PrimeNG:
```js
@Directive({
  selector: '[bindScrollListener]',
})
export class bindScrollListenerDirective {
  constructor(
    @Host() @Self() @Optional() public hostSel: Dropdown) {

    // Nothing is changed here, I just simply use ConnectedOverlayScrollHandler from the 2 files we downloaded
    hostSel.bindScrollListener = () => {
      if (!hostSel.scrollHandler) {
        hostSel.scrollHandler = new ConnectedOverlayScrollHandler(hostSel.containerViewChild.nativeElement, (event: any) => {
          if (hostSel.overlayVisible) {
            hostSel.hide();
          }
        });
      }

      hostSel.scrollHandler.bindScrollListener();
    }

    // override PrimeNG to make it support ShadowDOM
    hostSel.isOutsideClicked = (event: any) => {
      const target = event.target.shadowRoot ? event.path[0] : event.target
      return !(this.hostSel.el.nativeElement.isSameNode(target) || this.hostSel.el.nativeElement.contains(target) || (this.hostSel.overlay && this.hostSel.overlay.contains(<Node> target)));
    }
  }
}
```

Finally register the directive in `declarations` in app.module and start using your component as usual:
```
<p-dropdown bindScrollListener ....>
```

-----------------------------

What I actually changed:
- Filter out Shadow Root element when getting parents of an element: https://github.com/primefaces/primeng/blob/master/src/app/components/dom/domhandler.ts#L172
- Make component `isOutsideClicked` supports ShadowDOM:
```js
hostSel.isOutsideClicked = (event: any) => {
  const target = event.target.shadowRoot ? event.path[0] : event.target
  return !(this.hostSel.el.nativeElement.isSameNode(target) || this.hostSel.el.nativeElement.contains(target) || (this.hostSel.overlay && this.hostSel.overlay.contains(<Node> target)));
}
```

P/s: for each component that has this issue you need to create a directive for it

--------------------------------
Hi @cagataycivici, I don't know if you aware of this issue, but if this one is fixed it'll make PrimeNg much better cuz it can run in all kind of encapsulation environments that Angular has. Also Shadow DOM is a common case when developers want to embed their Angular components into any other web app.

If my solution is valid, I'd happy to create a PR for that

**Comment by maitrungduc1410** [comment] 2021-07-26 09:41
Hi @yigitfindikli If you ever have time please help to look at this issue. Thank you

**Comment by maitrungduc1410** [comment] 2021-09-21 15:48
For anyone is having this issue, I've published a small lib with directives that fix this problem: https://github.com/maitrungduc1410/primeng-shadowdom-directives

**Comment by ContrRus** [comment] 2021-09-22 05:10
> For anyone is having this issue, I've published a small lib with directives that fix this problem: https://github.com/maitrungduc1410/primeng-shadowdom-directives

Hi @maitrungduc1410, thank you, I was waiting for some update here, I have a problem with filters in datatable, the **<p-columnFilter "></p-columnFilter>** element. In the library that you provided is there any solution for this element?

**Comment by maitrungduc1410** [comment] 2021-09-22 05:12
> > For anyone is having this issue, I've published a small lib with directives that fix this problem: https://github.com/maitrungduc1410/primeng-shadowdom-directives
> 
> Hi @maitrungduc1410, thank you, I was waiting for some update here, I have a problem with filters in datatable, the **<p-columnFilter ">** element. In the library that you provided is there any solution for this element?

It's PrimeNg table right?

**Comment by ContrRus** [comment] 2021-09-22 05:32
> > > For anyone is having this issue, I've published a small lib with directives that fix this problem: https://github.com/maitrungduc1410/primeng-shadowdom-directives
> > 
> > 
> > Hi @maitrungduc1410, thank you, I was waiting for some update here, I have a problem with filters in datatable, the **<p-columnFilter ">** element. In the library that you provided is there any solution for this element?
> 
> It's PrimeNg table right?

Yeah of course, below is my question for this issue on stackoverflow 
https://stackoverflow.com/questions/69117441/viewencapsulation-shadowdom-and-primeng-not-all-styles-are-presented

**Comment by maitrungduc1410** [comment] 2021-09-22 05:36
okay I'll update support for that too (if it's possible :D)

**Comment by maitrungduc1410** [comment] 2021-09-22 06:14
Hi @ContrRus , I just looked into the question you posted on StackOverflow, it seems not related to this Github issue, I posted my answer for your question

**Comment by Vishnuram1988** [comment] 2021-10-03 16:19
Hello Team,

@yigitfindikli , Would be really great if we could get the fix for this in upcoming primeng version. I think it is quite relevant now as we use micro front end architecture and we may need to integrate the angular micro front ends to existing web application as remote modules with shadow DOM encapsulation

**Comment by shahafm-netapp** [comment] 2021-11-03 07:16
> @yigitfindikli

the issue opened at Oct 29, 2020, more than a year ago, is there any ETA ?

**Comment by dmluzhin** [comment] 2021-11-12 10:19
Having the same problem in our team's project. Really waiting for this fix

**Comment by vanroda** [comment] 2021-11-15 11:31
@maitrungduc1410, thanks for the directives. Is it possible to add one for ConfirmPopup ?
I tried based on psdTooltipDirective but didn't work. Thank you

**Comment by maitrungduc1410** [comment] 2021-11-15 15:57
@vanroda  okay, I'll check and let you know

**Comment by maitrungduc1410** [comment] 2021-11-16 03:42
Hi @vanroda, please upgrade to version `0.0.5`, I added support for confirm popup component

**Comment by leopardy** [comment] 2021-12-10 18:41
I really wish this would be fixed in the newer version of primeng. It's been over a year. I too have my components break once I switch to ViewEncapsaulation.ShadowDom.
In the meantime, thank you @maitrungduc1410 for providing us some type of workaround. Could you tell me if your lib of directives is going to get DataView?
https://www.primefaces.org/primeng/showcase/#/dataview
Our grid layout breaks and displays our items vertically. Also, the p-paginator that comes as part of the DataView also breaks, we lose the p-paginator-first, p-paginator-prev, p-paginator-next, and p-paginator-last arrows.

**Comment by maitrungduc1410** [comment] 2021-12-11 09:53
@leopardy I'll check and let you know

**Comment by maitrungduc1410** [comment] 2021-12-11 10:19
@leopardy this issue only happens with "overlay" component, in your case there's no such component usage in DataView, I did check, and it's working fine inside ShadowDOM.

Remember that when working with ShadowDOM, global style defined in `styles.css` won't work (right under `src`). Instead you have to place css import in any component which is ShadowDOM encapsulated. Example:

```js

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.scss',

    // ---------------- IMPORT PRIMENG STYLE HERE
    "../../../../node_modules/primeicons/primeicons.css",
    "../../../../node_modules/primeng/resources/themes/saga-blue/theme.css",
    "../../../../node_modules/primeng/resources/primeng.min.css"
  ],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class AppComponent {
```

**Comment by Cichy3D** [comment] 2022-04-25 14:09
Hi!

While this error persists I've made quick and dirty hack to make it work.

Just add those lines to `main.ts`:

```
// solving PrimeNG ShadowDOM issue
(window as any).getComputedStyle_Original = window.getComputedStyle;
window.getComputedStyle = function (el, pseudo): CSSStyleDeclaration {
	if (el instanceof DocumentFragment) {
		if (el.children.length > 0) {
			(window as any).getComputedStyle(el.children[0], pseudo);
		}
		return {
			getPropertyValue: function () {
				return '';
			}
		} as any;
	}
	return (window as any).getComputedStyle_Original(el, pseudo);
};
```

**Comment by drekthral** [comment] 2022-08-02 15:25
Still not working in shadow dom. ＞﹏＜

**Comment by cagataycivici** [comment] 2022-08-02 16:51
Sorry right now, ShadowDOM is not supported and I'm not sure how it can be right now. Any ideas are appreciated considering the current design agnostic theming approach of PrimeNG.

For web components though, we'll create PrimeElements aka PrimeUI with lit or similar which will have a styling architecture suited for WC. PrimeNG supports NONE and EMULATED for now.

**Comment by drekthral** [comment] 2022-08-03 11:22
> Sorry right now, ShadowDOM is not supported and I'm not sure how it can be right now. Any ideas are appreciated considering the current design agnostic theming approach of PrimeNG.
> 
> For web components though, we'll create PrimeElements aka PrimeUI with lit or similar which will have a styling architecture suited for WC. PrimeNG supports NONE and EMULATED for now.

Any rough estimate when PrimeElements could be created?

**Comment by papb** [comment] 2022-08-18 00:48
> Any ideas are appreciated considering the current design agnostic theming approach of PrimeNG.

@cagataycivici What do you think of the approach by @maitrungduc1410 ?

> If my solution is valid, I'd happy to create a PR for that

As I understand, the root problem is with "overlay" behaviors of components. Other than that, simply using `styleUrls` in the component that has `encapsulation: ViewEncapsulation.ShadowDom` seems to be enough. However, of course overlays are a big part of primeng, so that needs fixing too, and that's what @maitrungduc1410 has done.

A quick guess from me (I haven't really looked well into how @maitrungduc1410 did it): solving this is probably just a matter of being careful to create all overlay elements also inside the shadow root, rather than appending `document.body` directly.

Thank you all!! This package is awesome :rocket:

**Comment by papb** [comment] 2022-08-18 22:03
For my case, the following patch seems to be enough for now:

```ts
import { DomHandler } from 'primeng/dom';

// Patch it to use `.parentElement` instead of `.parentNode`.
// See https://github.com/primefaces/primeng/blob/ddcc166fe48d336012f2dfa9a2deb6af08f98593/src/app/components/dom/domhandler.ts#L164-L166
DomHandler.getParents = function(element, parents = []) {
  const parent = element.parentElement;
  return parent ? this.getParents(parent, [...parents, parent]) : parents;
};
```

Many thanks to @maitrungduc1410!

**Comment by fabiocastagnino** [comment] 2022-10-11 16:11
the solution proposed seems good, can you apply it? can you share the ETA?

**Comment by cagataycivici** [comment] 2022-10-23 22:07
I'll discuss it with the team this week and respond. PrimeUI begins in december.

**Comment by mertsincan** [comment] 2022-11-09 20:05
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:05 UTC
Labels: pending-review

**Comment by tfuerholzer** [comment] 2023-02-03 10:07
In case anyone else lands here I found a solution specifically for using a `<p-table>` with `<p-columnfilter>` inside a shadow DOM :

```typescript
ColumnFilter.prototype.onOverlayAnimationStart = patchedOnOverlayStart
...

function patchedOnOverlayStart(event){
  switch (event.toState) {
    case 'visible':
      this.overlay = event.element;

      const sdr = document.body.querySelector('my-shadow-dom-component').shadowRoot
      // get an instance of your shadowRoot
      sdr.appendChild(this.overlay);
      ZIndexUtils.set('overlay', this.overlay, this.config.zIndex.overlay);
      DomHandler.absolutePosition(this.overlay, this.icon.nativeElement);
      this.bindDocumentClickListener();
      this.bindDocumentResizeListener();
      this.bindScrollListener();

      this.overlayEventListener = (e) => {
        if (this.overlay && this.overlay.contains(e.target)) {
          this.selfClick = true;
        }
      };

      this.overlaySubscription = this.overlayService.clickObservable.subscribe(this.overlayEventListener);
      break;

    case 'void':
      this.onOverlayHide();

      if (this.overlaySubscription) {
        this.overlaySubscription.unsubscribe();
      }
      break;
  }
}

```

Basically I override the `onOverlayAnimationStart` method which adds the Filter to the DOM to use my shadow DOM root instead of the root document.

The code otherwise the same as https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L4611

**Comment by aserec** [comment] 2023-12-12 19:03
The issue persists on version 17.0.0. In my case, it opens the calendar, but It cannot be interacted.
