### ISSUE TITLE
Dropdown: Key events not correctly working when filter is enabled

### ISSUE THREAD

**Issue by mrkshx** [primefaces/primeng#14189] opened 2023-11-23 10:54 UTC
### Describe the bug

When filter property is set to **true**, the key events "End" and "Home" are not working: 
Instead the option focus will be lost.

Pressing Keys "End" and "Home" when filter is enabled

https://github.com/primefaces/primeng/assets/57047227/c28650e7-7106-43d2-a616-7e8bcd3e06d4

Pressing Keys "End" and "Home" when filter is disabled

https://github.com/primefaces/primeng/assets/57047227/e141a28a-4c65-4b2c-9fb8-caca7f8256e8

### Environment

16.9.0

### Reproducer

https://stackblitz.com/edit/github-etxtni?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.12

### PrimeNG version

16.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Expected behavior

When filter is set to true, key event "End" and "Home" should move focus to first / last option like it is implemented when filter is disabled.

**Comment by cetincakiroglu** [comment] 2024-02-07 11:54
Hi,

When pressed in filter input, end and home keys should move the cursor to the start or the end. This functionality didn't exist in v16 because it lacked accessibility enhancements. We've introduced the keyboard support after the accessibility implementation for the input components in 16.5x. The behavior is correct and changes were made for the accessibility. When the user focuses on the list, the home and end keys move the focus to the first or the last element in the overlay. 

Closing the issue since it's not a bug, it's intended behavior in accessibility.

**Closed by cetincakiroglu** 2024-02-07 11:54 UTC
Labels: Type: Bug
