### ISSUE TITLE
p-dropdown: group is not working as expected

### ISSUE THREAD

**Issue by KaiLuettmann** [primefaces/primeng#11680] opened 2022-07-05 09:27 UTC
### Describe the bug

If you use the attribute [group]="true" in the p-dropdown, then the elements of the groups are containing the groups as well.

This behavior is also reproducible in the examples: https://www.primefaces.org/primeng/dropdown****

### Environment

Your example page

### Angular version

14.0.4

### PrimeNG version

14.0.0-rc.1

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

18.4.0

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng/dropdown
2. Open grouped dropdown
3. The group "Germany" contains the items "Germany", "USA" and "Japan"

### Expected behavior

The items in the groups should be like this

```
[
            {
                label: 'Germany', value: 'de',
                items: [
                    {label: 'Berlin', value: 'Berlin'},
                    {label: 'Frankfurt', value: 'Frankfurt'},
                    {label: 'Hamburg', value: 'Hamburg'},
                    {label: 'Munich', value: 'Munich'}
                ]
            },
            {
                label: 'USA', value: 'us',
                items: [
                    {label: 'Chicago', value: 'Chicago'},
                    {label: 'Los Angeles', value: 'Los Angeles'},
                    {label: 'New York', value: 'New York'},
                    {label: 'San Francisco', value: 'San Francisco'}
                ]
            },
            {
                label: 'Japan', value: 'jp',
                items: [
                    {label: 'Kyoto', value: 'Kyoto'},
                    {label: 'Osaka', value: 'Osaka'},
                    {label: 'Tokyo', value: 'Tokyo'},
                    {label: 'Yokohama', value: 'Yokohama'}
                ]
            }
        ]
```

**Comment by mertsincan** [comment] 2022-07-05 09:39
Thanks a lot for the report! Duplicate of https://github.com/primefaces/primeng/issues/11672

**Closed by mertsincan** 2022-07-05 09:39 UTC
