### ISSUE TITLE
p-calendar doesn't display correct date when utc="true" 

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#3611] opened 2017-08-08 20:52 UTC
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/heusWuPPLdRCOaG0u0AD/

**Current behavior**
When you select a date, the wrong value is shown in the field.

**Expected behavior**
The date selected will continue to be shown.

**Minimal reproduction of the problem with instructions**
See plunk

**What is the motivation / use case for changing the behavior?**
Visually the users need to see the date they chose, even if in UTC it's the day prior.

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
4.2.6

* **PrimeNG version:** 2.0.X
4.1.2

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   N/A

**Comment by mrbalcos** [comment] 2017-08-23 04:25
I was not able to replicate this issue, but I have another issue, using your plunker, timezone does not seem to be set to UTC even if UTC was set to true

**Comment by ericsvendsen** [comment] 2017-08-30 13:55
Looking at the source code for the calendar component, this is all the `UTC` property does:
```
if(this.utc)
    date = new Date(Date.UTC(dateMeta.year, dateMeta.month, dateMeta.day));
else
    date = new Date(dateMeta.year, dateMeta.month, dateMeta.day);
```
It creates a local `Date` object based on the UTC values for the year, month, and day you selected. So when you select a day (e.g. August 25), the component says "oh, you want the local date for 2017-08-25T00:00:00Z". I'm in EDT right now, so selecting the 25th renders `Thu Aug 24 2017 20:00:00 GMT-0400 (EDT)`, and that's what is displayed in the input.

I was hoping that enabling UTC would allow the component to accept a UTC date input and then output the UTC date value in the control.

**Comment by ericsvendsen** [comment] 2017-08-30 17:56
To be fair, I have since discovered that displaying a formatted date specific to a timezone won't be possible until Angular v5: https://github.com/angular/angular/issues/9324

It looks like he got his PR done though and it's ready to be merged: https://github.com/angular/angular/pull/18284. So hopefully PrimeNG will build this capability into their calendar component when the time comes.

**Comment by jonyadamit** [comment] 2017-10-19 16:18
Hey @cagataycivici , you closed my issue (https://github.com/primefaces/primeng/issues/4179) as duplicate of this. I hope you noticed I linked a PR for it.. (https://github.com/primefaces/primeng/pull/4180)

**Comment by cagataycivici** [comment] 2017-10-25 16:00
Merged PR from @jonyadamit https://github.com/primefaces/primeng/pull/4180

**Closed by cagataycivici** 2017-10-25 16:00 UTC
Labels: confirmed, defect
