### ISSUE TITLE
Dropdown Filter not working for simple arrays like string[]

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#10122] opened 2021-04-16 11:39 UTC
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-demo-f3wctg

**Current behavior**
Dropdown filter doesn't work when you use a string array instead of complex objects.

* **Angular version:** 11

* **PrimeNG version:** 11.3.2

**Comment by s4m0r4m4** [comment] 2021-04-19 00:41
I think this is a duplicate of #9941 ?

**Comment by eXpertise7** [comment] 2021-11-30 16:24
+1 @yigitfindikli fix it please guys

**Comment by lukasmatta** [comment] 2022-04-08 12:37
Hello,

I studied the source code, and found hacky solution to this problem. Basically, we assign a function to `filterBy` property manually. As `filterBy` accepts only string values we have to use `as any` type casting.

```
(this.dropdown.filterBy as any) = {
        split: (_: any) => [(item: any) => item],
};
```

Check out working demo:
[https://stackblitz.com/edit/primeng-dropdown-demo-hr7yfa](https://stackblitz.com/edit/primeng-dropdown-demo-hr7yfa)

**Comment by mertsincan** [comment] 2022-11-09 20:13
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:13 UTC
Labels: pending-review

**Comment by zygarios** [comment] 2023-08-22 15:50
It's still not working. Can you fix that bug?

**Comment by abigail-miller** [comment] 2023-10-12 20:09
Agree, still a bug, please fix

**Comment by manuelmolinaf** [comment] 2023-10-26 22:58
This is still happening form me in the latest version.

**Comment by julioc3sar1** [comment] 2023-11-09 18:45
any update for this? not working even with grouped options

**Comment by gquittet** [comment] 2023-12-19 10:56
The issue is back in the new versions.
