### ISSUE TITLE
Dialog/DynamicDialog: Opened dropdown options hidden while scrolling inside dialog

### ISSUE THREAD

**Issue by kkoripl** [primefaces/primeng#14519] opened 2024-01-10 12:06 UTC
### Describe the bug

When dialog has scroll inside and layover with a dropdown (like p-dropdown or p-autocomplete), then opened dropdown options are hidden while scrolling away from the dropdown. This happens even when the dropdown component is still fully visible in the dialog.

Reproduced at demo page code locally, when added multiple dropdowns into p-dialog of  https://primeng.org/dialog at 'Overlays Inside' part.

Locally reproduced exact same behaviour for DynamicDialog.

### Environment

Windows 10
Primeng: v16.9.2-lts + Angular: v16.2.12 - reproduced at Stackblitz with: Primeng: v17.3.1 + Angular: v17.0.5

### Reproducer

https://stackblitz.com/edit/6wqevt?file=src%2Fapp%2Fdemo%2Fdialog-overlays-inside-demo.ts

### Angular version

16.2.12

### PrimeNG version

16.9.2-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.0+

### Steps to reproduce the behavior

1. Go to given link and open the dialog
2. Open one of the dropdowns (best in the middle of the dialog)
3. Scroll in the dialog, but outside of opened dropdown

### Expected behavior

Options should be still visible till the dropdown is fully visible in the dialog.

**Comment by mertsincan** [comment] 2024-01-16 09:09
Duplicate of https://github.com/primefaces/primeng/issues/14518

**Closed by mertsincan** 2024-01-16 09:09 UTC
Labels: Status: Needs Triage
