### ISSUE TITLE
Closed ConfirmationDialog is not rejected

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#2757] opened 2017-05-11 22:22 UTC
Angular version: 4.0.0
PrimeNG version: 4.0.0

In this blog post I have described how to use `ConfirmationDialog` with guarded routes https://medium.com/@OlegVaraksin/displaying-primeng-confirmation-dialog-with-guarded-routes-f5d07e646b4a

Unfortunately, when you close the dialog by click on close icon, the `reject` method of `ConfirmationService` is not invoked. The `ConfirmationDialog` stops to work after that. It doesn't appear. If you don't call `reject`, the `Observable` gets created, but never closed because `observer.complete()` is not invoked.

I would do the following changes in the `confirmdialog.ts`:

```
<a *ngIf="closable"  [ngClass]="..." href="#" role="button" (click)="close($event)">
    <span class="fa fa-fw fa-close"></span>
</a>

...

close(event?: Event) {
    reject();
}

accept() {
    if(this.confirmation.acceptEvent) {
        this.confirmation.acceptEvent.emit();
    }
	
    this.hide();
    this.confirmation = null;
}

reject() {
    if(this.confirmation.rejectEvent) {
        this.confirmation.rejectEvent.emit();
    }
	
    this.hide();
    this.confirmation = null;
}

private hide(event?: Event) {
    this.visible = false;

    if(event) {
        event.preventDefault();
    }
}
```

Should I provide a patch?

**Comment by upmauro** [comment] 2017-05-18 14:01
@ova2 you should, why not? :)

**Comment by sudheerj** [comment] 2017-06-10 13:56
The same issue is already raised here https://github.com/primefaces/primeng/issues/921

**Comment by cagataycivici** [comment] 2017-06-12 07:45
Duplicate of #921

**Closed by cagataycivici** 2017-06-12 07:45 UTC
Labels: duplicate

**Comment by QuentinLeGoff** [comment] 2017-07-18 09:43
I think the escape button and the reject button should not have the same behavior because to click on the 'No' button means reject the action however escape the dialog means go back to the previous state.

So the escape button should not start the reject method. No ?
