### ISSUE TITLE
p-MultiSelect: Clear Button does not work

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#14585] opened 2024-01-18 15:03 UTC
### Describe the bug

When using `[showClear]="true"` clicking on the X to clear the selection of the MultiSelect no longer clears the selection. Instead, the dropdown is opened and closed.

![primeng](https://github.com/primefaces/primeng/assets/32487587/3dfd9c6e-a3b3-4854-8e01-6c38ab7d211b)

This issue is new with 17.3.3 and does not exist in 17.3.2.

While this is off-topic, and we are generally very happy with the product you provide, please try and improve your quality assurance mechanisms. The last few updates have introduced a lot of breaking bugs in the dropdown menus that have rendered parts of our application unusable and resulted in having to invest a lot of expensive time into trying to find these issues. And I am not talking about major or minor updates, but patch updates. It is a bad sign, if the team starts to talk about not updating PrimeNG unless absolutely necessary.

### Environment

n/a

### Angular version

17.1.0

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Set `[showClear]="true"` on your `<p-MultiSelect>`
2. Select Items from the Dropdown
3. Click on the X and see that the selection remains while the dropdown is opened and closed

### Expected behavior

The selection is cleared instead.

**Comment by adri95cadiz** [comment] 2024-01-18 16:02
I've also tested this in p-dropdown and p-calendar components, and both have the same problem; in version 17.3.3 as well as in version 17.3.2, for now I have downgraded to version 17.3.1 which doesn't have this issue.

**Comment by jacqueslareau** [comment] 2024-01-22 15:52
Experiencing the issue with p-dropdown

**Comment by denny99** [comment] 2024-01-23 07:17
Might be related to https://github.com/primefaces/primeng/issues/14606. ?

**Comment by cetincakiroglu** [comment] 2024-01-24 12:37
Hi @jpgoelz,

Could you please provide a stackblitz example, seems it works here https://stackblitz.com/edit/itiykk?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html

**Comment by cetincakiroglu** [comment] 2024-01-24 12:38
> I've also tested this in p-dropdown and p-calendar components, and both have the same problem; in version 17.3.3 as well as in version 17.3.2, for now I have downgraded to version 17.3.1 which doesn't have this issue.

Could you please create separate issues for other components by providing stackblitz examples so we can understand the issue and target them one by one?

**Comment by jacqueslareau** [comment] 2024-01-24 15:31
If you go on the primeng site directly (primeng.org) and click on Get Started, then select the Dropdown component, the first example on the site does not work.

But if you go directly to primeng.org/dropdown , it works.

I'm not sure how to replicate this.

**Comment by denny99** [comment] 2024-01-25 06:58
So then its fixed with https://github.com/primefaces/primeng/pull/14607

**Comment by jpgoelz** [comment] 2024-01-25 10:47
> This is replicate issue. The p-dropdown component does not work properly when the p-calendar is on the page.
> 
> https://stackblitz.com/edit/github-pmdtzh?file=src%2Fapp%2Fapp.component.html%3AL19,src%2Fapp%2Fapp.component.ts

Thank you for this. I was at a loss, as I could not replicate the issue myself, except for in our application. We do use calendar and dropdown as well.

@cetincakiroglu, I added a calendar to your working StackBlitz and the issue becomes visible for `p-multiSelect` as well:
https://stackblitz.com/edit/itiykk-x1yhiy?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html

**Comment by denny99** [comment] 2024-01-25 14:25
Overwrite the css in your angular global styles file. 

.p-icon-wrapper {
pointer-events: unset (!important depending on your setup) 
}

**Comment by psarno** [comment] 2024-01-25 18:27
This also impacts `<p-password [toggleMask]="true">` if a `<p-calendar>` is on the page.

You can not click the "eye" icon to mask/show the password.

**Comment by STotev** [comment] 2024-01-26 14:08
I can confirm the same behaviour for the dropdown. Though, it's hard to replicate it on stackblitz. Somehow it works there.

@denny99 workaround works for me, too.

**Comment by cetincakiroglu** [comment] 2024-02-01 10:50
Hi,

This issue is related with https://github.com/primefaces/primeng/issues/14606 and it was also replicated in dropdown component. The issue caused by possible CSS leak in the calendar component. We've fixed the issue by updating `p-icon-wrapper` style rule. Probably, it'll fix this issue too. I'm assuming that it's fixed and closing the issue. Please try with the upcoming release and let us know if the issue persists.

**Closed by cetincakiroglu** 2024-02-01 10:50 UTC
Labels: Resolution: Cannot Replicate
