### ISSUE TITLE
Component: Table ArrowUp/ArrowDown doesn't work with checkbox selection mode

### ISSUE THREAD

**Issue by gcannone** [primefaces/primeng#15272] opened 2024-04-15 10:05 UTC
### Describe the bug

When I configure table with checkbox selection mode, arrowUp/arrowDown keydown event perform scroll of table insted focus on previous/next row. With Prime NG 16.4.0 version, we were able to do this operation with keydown event on tr element, but with current version (17.12.0), keydown event on tr element is not raised when I press arrows. To fix this issue, it would be good if you restore this behavior (keydown event on tr also with arrow keys).

### Environment

We are using Prime NG 17.12.0 in Angular 17 application.

### Reproducer

https://stackblitz.com/edit/zk7vj7?file=package.json

### Angular version

17.3.1

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Select a row in a table with checkbox selection
2. Press arrow down/up key
3. Keydown event is not raised on tr element
4. Table perform scroll, insted focus on next/previous row

### Expected behavior

I expect that keydown event is raised on tr element, when I press arrows key. Alternatively, I exepect that also with checkbox selection, arrows keydown performs focus on next/previous element.

**Comment by cetincakiroglu** [comment] 2024-04-19 12:02
Hi,

We've made accessibility implementation during v16.5x and higher versions up to 16.9x. The mentioned behavior existed before the accessibility implementation. Now, you need to press the tab to navigate between checkboxes. ArrowDown keys still used to navigate rows if radio, single, or multiple selection is used (except checkbox). It's not a bug, closing the issue, thanks for reporting!

**Closed by cetincakiroglu** 2024-04-19 12:02 UTC
Labels: Status: Needs Triage
