### ISSUE TITLE
Component: KeyFilter

### ISSUE THREAD

**Issue by MeriemElouragini** [primefaces/primeng#13096] opened 2023-05-25 09:22 UTC
### Describe the bug

**pKeyFilter do not accept RegExp value.**

Template:
```
            <input type="text form-control"
            inputId="modelName" 
            pInputText 
            [pKeyFilter]="specialCharsRegExp" 
            formControlName="modelName" 
            tooltipEvent="focus" 
            required
            />
```

**With :**
`specialCharsRegExp: RegExp = /^[^<>\\/*'\"!;+?%=$#@={},~]+$/;
`

Output:

```
error TS2322: Type 'RegExp' is not assignable to type 'string'.
 [pKeyFilter]="specialCharsRegExp"
```

### Environment

Windows 10 Entreprise
Node : v18.13.0
Npm : 8.19.3

### Angular version

16.0.2

### PrimeNG version

16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.13.0

### Browser(s)

Chrome111.0.5563.111 (Build officiel) (64 bits)

### Expected behavior

pKeyFilter accept RegExp value

**Comment by cghislai** [comment] 2023-06-06 09:03
looks like a duplicate of  #13076

**Comment by mertsincan** [comment] 2024-12-16 11:38
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Closed by mertsincan** 2024-12-16 11:38 UTC
Labels: Status: Needs Triage
