### ISSUE TITLE
Unexpected "keyword" or "identifier" error in PrimeNG's p-toggleButton component with "onIcon" property

### ISSUE THREAD

**Issue by JuamBer** [primefaces/primeng#14267] opened 2023-12-03 09:53 UTC
### Describe the bug

I am experiencing an issue with the p-toggleButton component of PrimeNG in my Angular application. When passing a string to the "onIcon" property, if the string contains a space, the application throws an error stating "Unexpected keyword or identifier".

Here is the code I am using:
`<p-toggleButton onIcon="fas fa-check" offIcon="fas fa-times"></p-toggleButton>`

The error occurs when the string passed to "onIcon" contains a space, as in the above example. However, if I remove the space, the error disappears.
`<p-toggleButton onIcon="fasfa-check" offIcon="fas fa-times"></p-toggleButton>`

Has anyone else experienced this issue or have any suggestions on how to resolve it? Any help would be appreciated.

![Captura de pantalla 2023-12-03 104639](https://github.com/primefaces/primeng/assets/33964204/27ba138d-79b8-466e-b75d-9c028144257c)

### Environment

**Angular Version:** 17.0.0
**PrimeNg:** 17.0.0-beta.1
**Node.js:** 18.16.0
**Browser:** Google Chrome
**VSCode:** 1.84.2

### Angular version

17.0.0

### PrimeNG version

17.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Google Chrome

**Comment by SoyDiego** [comment] 2023-12-03 12:48
Hi @JuamBer, I have checked your problem but I cannot reproduce it and works fine for me.

I tried with your code with the only difference I'm using `primeicons` but have a space my classes too:

```js
<div class="card flex justify-content-center">
     <p-toggleButton onIcon="pi pi-check" offIcon="pi pi-times"></p-toggleButton>
</div>
```

And the code works perfecty with spaces.

![test togglebutton](https://github.com/primefaces/primeng/assets/19764334/da09054e-77e9-44bc-a8fa-dd3af0f098d5)

Can you try to reload your VScode, or delete node modules and reinstall again the dependencies.
If the problem persists, can you generate a stackblitz to see the problem?

Thanks

**Comment by cetincakiroglu** [comment] 2023-12-06 14:07
Hi,

The issue cannot reproducible in the latest PrimeNG and as you can see below, icon inputs accepts any kind of string value 

```
    /**
     * Icon for the on state.
     * @group Props
     */
    @Input() onIcon: string | undefined;
```

Closing the issue.

**Closed by cetincakiroglu** 2023-12-06 14:07 UTC
Labels: Status: Needs Triage

**Comment by Kisters-BS** [comment] 2024-02-23 09:25
I have got the same error. It seems that when separated by space the values are being interpreted as two separate properties. A fix is to use the property binding syntax with square brackets [] around the property name and bind the entire string as a single value.
For your example:
[onIcon]="'fas fa-check'"

**Comment by qaderHaddad** [comment] 2024-03-03 01:04
> I have got the same error. It seems that when separated by space the values are being interpreted as two separate properties. A fix is to use the property binding syntax with square brackets [] around the property name and bind the entire string as a single value. For your example: [onIcon]="'fas fa-check'"

For the time being, it seems like this is the solution for now. Thanks!

**Comment by zakharenkov** [comment] 2024-10-15 18:21
Strange behavior:
![111](https://github.com/user-attachments/assets/7db83c1c-7965-485b-8438-8261a47fda49)

primeicons: **7.0.0**
primeng: **18.0.0-beta.2**

**Comment by JoseAP89** [comment] 2026-01-22 07:45
I had the same issue, and I solved it by using property binding like this example:
```
                    <p-togglebutton 
                        [(ngModel)]="hasPaidInFull" 
                        name="paymentToggle"
                        [onLabel]="'Pago completo'" 
                        [onIcon]="'pi pi-lock'"  
                        offLabel="Con pago parcial" offIcon="pi pi-lock-open" 
                        ariaLabel="Do you confirm" 
                    />
```
