### ISSUE TITLE
Datatable cell navigation using keyboard

### ISSUE THREAD

**Issue by Nattujessy** [primefaces/primeng#2155] opened 2017-02-25 08:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi, i went through the cell editing in primeng 2.0. it has pretty screen.  
**Current behavior**
Pressing tab key is focusing on next cell. but when i press enter key after filling the value it losses its focus.
And am supposed to click(mouse click) the next cell. it gives a bad look while entering data.

**Expected behavior**
Navigate the cell using arrow keys (up-down, left-right). 
When i press enter key after changing the value it should be be focused on same cell(in cell edit mode).
when i press tab key it should focus on next cell(in cell edit mode).

  
**Please tell us about your environment:**

os: win32 x64
node: 6.9.5
* **Angular version:** 2.0.X

Angular: 2.4.0
* **PrimeNG version:** 2.0.X

primeng: 2.0.1
* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.5

**Comment by anirudh-jagithyala** [comment] 2017-02-27 19:05
is this an extension to #2124 ?? which is already on the enhancement list

**Comment by SnailCoil** [comment] 2017-03-27 21:43
This is the missing feature that caused me to choose another framework. I would love to switch to primeNG, but our clients really need keyboard navigation.

**Comment by cagataycivici** [comment] 2017-04-13 11:33
Duplicate of 2124

**Closed by cagataycivici** 2017-04-13 11:33 UTC
