### ISSUE TITLE
contextmenu: context sub menus not displayed 

### ISSUE THREAD

**Issue by greg9504** [primefaces/primeng#12276] opened 2022-11-23 17:43 UTC
### Describe the bug

When I use contextmenu component sometimes the submenus fail to display until change detection is triggered (pressing a key, move mouse over another component etc).  Unfortunately I can not provide a repo that reproduces the problem, as when I use the exact same code to produce the contextmenu in a simple application the problem does not exist.

However as shown in the gif below you can see when the mouse is moved to the menu item with a submenu, the submenu does not appear until I use the global debug ng object to manually trigger detectChanges() .  When I manually issue the markForCheck() (as the code in ContextMenuSub::ngOnInit ~line 120) the submenu does not appear.

![contextmenu_cd_problem2](https://user-images.githubusercontent.com/1952281/203609367-81c741bb-4f39-465b-9748-9132280817a4.gif)

Further I have cloned the repo and updated line 120 of contextmenu.ts:

// this.contextMenu.cd.markForCheck();
this.contextMenu.cd.detectChanges();

and after building and linking to this build of primeng  the submenus now appear correctly.

FWIW here is a stackblitz that shows how the menu is created and shown, but again the problem is not reproduced
https://angular-ivy-pf5ydn.stackblitz.io

### Environment

"dependencies": {
    "@angular-devkit/schematics": "^14.2.9",
    "@angular/cdk": "^14.2.7",
    "@angular/localize": "^14.2.10",
    "@babel/runtime": "^7.20.1",
    "@electron/remote": "^2.0.4",
    "@fortawesome/fontawesome-pro": "5.15.2",
    "@greg9504/ts-json-serializer": "1.3.0",
    "@ng-bootstrap/ng-bootstrap": "^13.1.0",
    "@ngrx/effects": "^14.3.2",
    "@ngrx/router-store": "^14.3.2",
    "@ngrx/store": "^14.3.2",
    "@popperjs/core": "^2.10.2",
    "@syncfusion/ej2-angular-buttons": "^20.3.56",
    "@syncfusion/ej2-angular-inputs": "^20.3.56",
    "@syncfusion/ej2-angular-layouts": "^20.3.56",
    "@syncfusion/ej2-angular-popups": "^20.3.56",
    "@syncfusion/ej2-angular-richtexteditor": "^20.3.56",
    "@types/lodash": "4.14.123",
    "angular2-draggable": "2.2.4",
    "better-sqlite3": "^7.5.0",
    "bootstrap": "^5.2.0",
    "chokidar": "^3.2.1",
    "d3": "3.5.17",
    "electron-devtools-installer": "3.0.0",
    "electron-log": "2.2.17",
    "electron-settings": "4.0.2",
    "electron-unhandled": "4.0.0",
    "element-resize-event": "2.0.9",
    "fast-isnumeric": "1.1.2",
    "flexlicensing": "file:plugins/native/flexlicenseing",
    "fs-extra": "9.0.0",
    "group-array": "0.3.3",
    "lodash": "4.17.11",
    "plotly.js": "2.8.3",
    "primeicons": "^6.0.1",
    "primeng": "file:../opensourcejs/primeng/dist/primeng-14.2.2.tgz",
    "save": "^2.4.0",
    "smooth-scroll-into-view-if-needed": "^1.1.23",
    "temp": "^0.9.4",
    "tslib": "^2.0.0",
    "typescript": "4.8.4",
    "typescript-collections": "1.3.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^14.1.0",
    "@angular-devkit/build-angular": "^14.2.9",
    "@angular-eslint/builder": "^14.1.2",
    "@angular-eslint/eslint-plugin": "^14.1.2",
    "@angular-eslint/eslint-plugin-template": "^14.1.2",
    "@angular-eslint/schematics": "^14.1.2",
    "@angular-eslint/template-parser": "^14.1.2",
    "@angular/animations": "^14.2.10",
    "@angular/cli": "^14.2.9",
    "@angular/common": "^14.2.10",
    "@angular/compiler": "^14.2.10",
    "@angular/compiler-cli": "^14.2.10",
    "@angular/core": "^14.2.10",
    "@angular/forms": "^14.2.10",
    "@angular/language-service": "^14.2.10",
    "@angular/platform-browser": "^14.2.10",
    "@angular/platform-browser-dynamic": "^14.2.10",
    "@angular/router": "^14.2.10",
    "@ngrx/store-devtools": "^14.3.2",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "^16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.36.2",
    "@typescript-eslint/parser": "^5.36.2",
    "devtron": "1.4.0",
    "electron": "^16.0.0",
    "electron-builder": "^22.13.1",
    "electron-reload": "^1.5.0",
    "electron-reloader": "1.2.3",
    "eslint": "^8.23.0",
    "eslint-plugin-import": "latest",
    "eslint-plugin-jsdoc": "latest",
    "eslint-plugin-ngrx": "^2.0.4",
    "eslint-plugin-prefer-arrow": "latest",
    "generate-license-file": "^1.1.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.15",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "make-dir-cli": "^1.0.0",
    "ncp": "^2.0.0",
    "ngrx-store-freeze": "0.2.4",
    "node-polyfill-webpack-plugin": "^1.1.4",
    "npm-run-all": "4.1.5",
    "npx": "10.2.0",
    "protractor": "~7.0.0",
    "rxjs": "7.5.7",
    "ts-node": "^10.4.0",
    "wait-on": "3.3.0",
    "webdriver-manager": "12.1.5",
    "zone.js": "~0.11.4"
  },

### Angular version

14.2.10

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.14.0

### Browser(s)

Electron 16.2.8

### Expected behavior

submenus to appear

**Comment by cetincakiroglu** [comment] 2022-11-24 09:23
Hi,

Cannot provide a solution since the problem is not reproducible, labeling the issue as "cannot replicate" and closing it. Please feel free to open a new issue when reproduction to work on is available.

**Closed by cetincakiroglu** 2022-11-24 09:23 UTC
Labels: Resolution: Cannot Replicate

**Comment by deardeerluluu** [comment] 2024-03-13 06:25
Seems that I met the same problem recently. Click on the item which has submenu fail to display, however MouseLeave then enter again and press 'Enter' can successfully show the submenu.
