### ISSUE TITLE
p-columnFilter overlay not Working on Mobile

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#10272] opened 2021-05-25 08:33 UTC
https://stackblitz.com/edit/primeng-tablefilter-demo-x6mj6j

**Comment by mertsincan** [comment] 2022-05-30 14:06
Maybe, Duplicate of [11567](https://github.com/primefaces/primeng/issues/11567)

**Comment by mateustormin** [comment] 2022-06-04 14:12
Dropdown is fixed but table filter is not don't even need a stackblitz, just go to showcase and try table with filter window

**Comment by mertsincan** [comment] 2022-11-09 20:19
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:19 UTC
Labels: enhancement
