### ISSUE TITLE
Component: Dropdown Auto Scroll- UI Issue

### ISSUE THREAD

**Issue by 1997Buhuti** [primefaces/primeng#17039] opened 2024-12-12 17:47 UTC
### Describe the bug

The issue occurs when using the dropdown component with virtual scroll support in PrimeNG. When typing in the filter, the suggestions should be displayed in the overlay panel. However, it seems that the height of the overlay panel is set to a very small amount, around 5px, which makes all the autocomplete suggestions appear to be missing.

As a quick fix downgrading to 17.18.12 solved the issue.

![image](https://github.com/user-attachments/assets/0f90bac5-f2a3-498e-9a48-005d92ea8416)

### Environment

17.18.13

### Angular version

18.2.12

### PrimeNG version

17.18.13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.16.0

### Browser(s)

chrome 131.0.6778.110

### Steps to reproduce the behavior

1. Start typing in the Autocomplete input field with virtual scroll enabled. 
2. Suggestions will appear as expected, but you cannot see them beacuse the height of the overlay panel is so small
3. Remove the input characters one by one until all characters are cleared. The suggestions disappear, which is expected at this point.
4. Start typing new characters in the input field again and remove them. The overlay panel remains hidden, failing to show the suggestions with proper.

### Expected behavior

![image](https://github.com/user-attachments/assets/2905b68c-0693-43fb-910c-90bbaab366fa)
It should display the overlay panel with correct hieght and values

**Comment by meursj** [comment] 2024-12-13 12:38
This seems some generic problem introduced in 17.18.13 with virtual scrolling. The list of options is not filled anymore on initial rendering.

See also the samples
[https://v17.primeng.org/autocomplete#virtualscroll](https://v17.primeng.org/autocomplete#virtualscroll)
[https://v17.primeng.org/dropdown#virtualscroll](https://v17.primeng.org/dropdown#virtualscroll)
[https://v17.primeng.org/multiselect#virtualscroll](https://v17.primeng.org/multiselect#virtualscroll)

Look like it works ok on the v18 version. But would be nice to have a fix in the v17 branch until v18/ v19 is more stable

**Comment by meursj** [comment] 2024-12-13 12:59
Duplicate of [https://github.com/primefaces/primeng/issues/16991](https://github.com/primefaces/primeng/issues/16991)

**Closed** 2024-12-17 11:37 UTC
Labels: Type: Bug
