### ISSUE TITLE
Slider component not working on touch screen

### ISSUE THREAD

**Issue by Emdee89** [primefaces/primeng#1816] opened 2017-01-15 20:39 UTC
**I'm submitting a bug report:**

Slider component cannot be used on mobile devices with touch screen. Functionality only working on desktop.

**What is the motivation / use case for changing the behavior?**
Business users need to utilize app with slider component also on the road using their mobile device.

**Please tell us about your environment:**
Win 7, Angular 2.4.1, PrimeNG 1.1.4

* **Angular version:** 2.0.X
Angular 2.4.1

* **PrimeNG version:** 2.0.X
PrimeNG 1.1.14

* **Browser:**
All
 
* **Language:** 
ES6

**Comment by rolandoldengarm** [comment] 2017-01-22 07:49
Yeah I can confirm this issue. Cannot use the slider on mobile. This is a very annoying bug! For now, we've hidden the controls on mobile.

**Comment by Emdee89** [comment] 2017-01-22 15:26
As temporary workaround I use a plain vanilla HTML slider as follows:
_<input type="range" data-show-value="true" data-popup-enabled="true" [(ngModel)]="adjustedCalculation.predictionYear" [max]="displayedCalculation.predictionYear + 10"
                            [min]="displayedCalculation.predictionYear - 10" style="width: 100%" />_

It works also on mobile devices with touch screen, however its appearance is not is not aligned with all other components. You could use CSS to customize the design to make it fit.

**Comment by grahambrown11** [comment] 2017-05-02 15:06
Any update on this bug @cagataycivici 
We have this component in prod and have a rise in mobile users, so would be super helpful if this can be addressed soon.
I see it is a similar issue that was reported on PrimeFaces (https://github.com/primefaces/primefaces/issues/585) and the solution was to include jQuery UI Touch Punch which converted touch events into mouse events. Obviously that cant be used in this library but surely a similar solution could work...?
I may have some time this week to branch and see if there is a quick fix.

**Comment by cagataycivici** [comment] 2017-05-02 15:29
We are currently busy witg issue reports of PrimeNG PRO users but this is in our radar.

**Comment by sudheerj** [comment] 2017-05-24 12:34
Duplicate of https://github.com/primefaces/primeng/issues/2866

**Closed by sudheerj** 2017-05-24 12:34 UTC
