### ISSUE TITLE
Component: Dropdown TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by mq321** [primefaces/primeng#14027] opened 2023-11-04 16:46 UTC
### Describe the bug

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at get inputClass [as inputClass] (primeng-dropdown.mjs:628:135)
    at Dropdown_span_2_Template (primeng-dropdown.mjs:50:96)
    at executeTemplate (core.mjs:12003:13)
    at refreshView (core.mjs:13498:13)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInEmbeddedViews (core.mjs:13606:13)
    at refreshView (core.mjs:13522:9)
    at detectChangesInternal (core.mjs:13437:9)
    at ViewRef$1.detectChanges (core.mjs:13914:9)
    at set disabled [as disabled] (primeng-dropdown.mjs:410:21)

### Environment

development

### Angular version

16.2.12

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Google Chrome

**Comment by ericvaroto** [comment] 2023-11-04 20:29
Hi, I'm getting the same error when my "optionValue" has a value

**Comment by ngadceser** [comment] 2023-11-05 06:16
I'm checking all the sub versions and they all have the same error as above.

**Comment by wadlieb** [comment] 2023-11-05 06:18
The issue is addressed here: https://github.com/primefaces/primeng/issues/13996#issuecomment-1792645352

**Comment by ngadceser** [comment] 2023-11-05 06:19
The LTS version is not throwing any errors.

**Comment by cetincakiroglu** [comment] 2023-11-06 07:30
Hi,

The issue is duplicate of https://github.com/primefaces/primeng/issues/13996#issuecomment-1792645352

Closing the issue.

**Closed by cetincakiroglu** 2023-11-06 07:30 UTC
Labels: Status: Needs Triage
