### ISSUE TITLE
Filter is not working in ListBox Component and Dropdown Component with SelectItem type

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#15864] opened 2024-06-19 12:11 UTC
### Describe the bug

When options are SelectItem type, filter is not working in ListBox and Dropdown Component.

Listbox options:
![imagen](https://github.com/primefaces/primeng/assets/46462037/7f5229b6-8158-4575-9560-9862c52cbb2a)

Filter options:
![imagen](https://github.com/primefaces/primeng/assets/46462037/7d2d5eb8-4661-4e20-9742-d900a31a5a8a)

### Environment

Ubuntu 20.04.6 LTS

### Reproducer

https://stackblitz.com/edit/j5s22b?file=src%2Fapp%2Flistbox-filter-demo.html

### Angular version

17.3.11 or 18.0.1

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Browser(s)

Firefox 126

**Comment by cetincakiroglu** [comment] 2024-07-04 08:38
Hi,

SelectItem type is not related to the listbox component's internal logic. To use filter functionality, you should provide a filterField or optionLabel property. 

I am closing the issue since it's not a bug.

**Closed by cetincakiroglu** 2024-07-04 08:38 UTC
Labels: Type: Bug

**Comment by AlbaSS18** [comment] 2024-07-04 11:02
Okey, thank you. In previous versions, `filterField` or `optionLabel` property with `SelectItem` was not necessary, so I don't understand because now it is necessary.

**Comment by quartelh** [comment] 2024-07-11 09:41
I am confused.
The behaviour for Dropdown is different than for ListBox.

See https://stackblitz.com/edit/j5s22b-iaamnd.

For Dropdown it just works and there is no need for `filterFields` or `optionLabel` property for the filter to just work with SelectItem.
