### ISSUE TITLE
Dropdown: "0" Value in optionValue, causes Label to be replaced by Placeholder 

### ISSUE THREAD

**Issue by eduardheller89** [primefaces/primeng#14715] opened 2024-02-05 15:40 UTC
### Describe the bug

When the value of the dropdown is 0, the placeholder value is still shown in the input. 

[This is the line causing the issue](https://github.com/primefaces/primeng/blob/20b5c1c28ed29fcf6daca0d1b662b82e30fb9476/src/app/components/dropdown/dropdown.ts#L934C9-L934C114)

`return this.modelValue() ? this.getOptionLabel(this.selectedOption) : this.placeholder || 'p-emptylabel';` 

this Line in component.ts causes '0' to be accepted as False. You should check for null or undefined. 

Thanks

### Environment

Win10/chrome 

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

1. Set Dropdown to a value in optionValue to 0. 
2. Set Dropdown placeholder 
3. Change the value of the dropdown in the ui to the corresponding value with Value 0
5. Placeholder still remains in the input

### Expected behavior

The optionLabel should show the Label of the optionValue with Value 0

**Comment by Cr3aHal0** [comment] 2024-02-05 22:07
Hi,

Not sure if this is by design or if more options should be available other than '0' such as true, false or empty string. If empty/null comparison is enough, the linked PR should be okay

**Comment by rosenthalj** [comment] 2024-02-06 09:17
This issue is the result of a condition that I did not consider when the code was changed for pull request #14665. 

I believe that 2 sets of changes need to be made to fix this issue.


Please see the annotated screenshot of pull request #14665 listed below

![Fix__14596_-_fixes_p-dropdown_logic_for_selectedOption_and_label_by_rosenthalj_·_Pull_Request__14665_·_primefaces_primeng](https://github.com/primefaces/primeng/assets/45439491/4c0a592f-a565-4ade-a45a-2c1dcbc865ca)

**Comment by Cr3aHal0** [comment] 2024-02-06 09:44
Hi rosenthalj,

I'll be investigating your suggestion, I did not encountered any incorrect behaviour while testing the change but i'll retry :)

**Comment by rosenthalj** [comment] 2024-02-06 10:10
Cr3aHal0,

When testing I would recommend that you try the following "filtering" cases:

1. A test case similar to  the last video in pull request #14665 comments. 
--- set options 0, 1, 2
--- select 0
--- enter 1 in the filter
2. A test case that enters a value that doesn't match any option
--- set options 0, 1, 2
--- select 0
--- enter "A" in the filter

**Comment by cetincakiroglu** [comment] 2024-02-07 06:38
Fixed in https://github.com/primefaces/primeng/pull/14719

**Closed** 2024-02-07 06:39 UTC
Labels: Type: Bug

**Comment by eduardheller89** [comment] 2024-02-07 11:02
Thank you for being fast with the issue. Thats great
