### ISSUE TITLE
Dropdown: aria-expanded attribute not present.

### ISSUE THREAD

**Issue by WTW-Steve-Martin** [primefaces/primeng#14850] opened 2024-02-21 10:59 UTC
### Describe the bug

The Axe Dev Tools for Accessibility is reporting that the 'Required ARIA attributes must be provided'.
![image](https://github.com/primefaces/primeng/assets/153538315/cf573b72-db0b-4a39-a44b-a3af542f925a)

The aria-expanded attribute is set on an element to indicate if a control is expanded or collapsed, and whether or not the controlled elements are displayed or hidden.

An appropriate attribute is required.

### Environment

Windows 10

### Angular version

17.2.1

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome and Edge

### Steps to reproduce the behavior

1. Install the `Axe Dev Tools for Accessibility` plug-in.
2. Visit the PrimeNG dropdown page (https://primeng.org/dropdown) on Chrome/Edge browser.
3. Scan the page with Axe

**Comment by TaneliTuomola** [comment] 2024-02-26 11:40
Same issue with TreeSelect and Calendar: https://github.com/primefaces/primeng/issues/14358

**Comment by cetincakiroglu** [comment] 2024-02-28 14:18
Hi,

Huge thanks for reporting the issue and raising other issues, this issue is a duplicate of https://github.com/primefaces/primeng/issues/14832 and it's fixed already. Closing this one.

**Closed by cetincakiroglu** 2024-02-28 14:18 UTC
Labels: Component: Accessibility
