### ISSUE TITLE
TabView attribute orientation does not work with PrimeNG 10

### ISSUE THREAD

**Issue by stedel** [primefaces/primeng#9288] opened 2020-09-17 08:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This [StackBlitz](https://stackblitz.com/edit/github-egqmoe?file=src%2Fapp%2Fapp.component.html) shows the problem with each non default orientation.

(based on https://stackblitz.com/github/primefaces/primeng-issue-template updated to Angular 10/PrimeNG 10)

**Current behavior**
The TabView `orientation` attribute does not change display of TabView headers, instead they always show on top.

**Expected behavior**
TabView attribute `orientation` should work as expected as mentioned in the [docs](https://www.primefaces.org/primeng/showcase/#/tabview) instead of just showing the default ´top´ value.

**Minimal reproduction of the problem with instructions**
See [StackBlitz](https://stackblitz.com/edit/github-egqmoe?file=src%2Fapp%2Fapp.component.html) example.

**What is the motivation / use case for changing the behavior?**
This configuration option is still documented at https://www.primefaces.org/primeng/showcase/#/tabview and should therefore be supported by the Framework as in older versions or should be removed from documentation, if its not planned to be supported in the future.

**Please tell us about your environment:**
Chrome, Firefox, IE11, Edge

* **Angular version:** 10.x
Most recent.

* **PrimeNG version:** 10.x
Most recent.

* **Browser:** [all desktop browsers ]
Tested in IE11, Firefox, Chrome and Edge Chromium.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all, tested with TypeScript 3.9.7

* **Node (for AoT issues):** `node --version` =   
12.18.4

**Comment by pmo1948** [comment] 2020-09-22 12:06
I second this issue. Looking forward to its being solved!

**Comment by pmo1948** [comment] 2020-10-07 10:25
![image](https://user-images.githubusercontent.com/69136429/95319383-75dadf80-08a0-11eb-8f00-81fbd6ac3062.png)

here is a visual of the issue (taken from stedel's stackblitz). all orientations just end up on top

**Comment by saramcicchi** [comment] 2020-12-15 16:28
I'm not sure why this is marked as an enhancement. It is a regression as this capability worked in version 9 and below. Would really appreciate this being fixed in version 10.

**Comment by JEEVANJGA** [comment] 2020-12-16 02:57
Are there any alternative solutions available to resolve this issue?

**Comment by JEEVANJGA** [comment] 2020-12-16 04:12
On checking following  [code comparison](https://github.com/primefaces/primeng/commit/e3156b688fd7c261ca76096ef36f98b200ebebbd)  

It is found that the code for the orientation attribute is removed.

if someone could update the issue and push the change at the earliest, would be really great.

**Comment by pmo1948** [comment] 2020-12-24 08:48
any updates?

**Comment by pmo1948** [comment] 2020-12-24 09:45
a workaround I did for now, that works for setting it to the right (but still requires fine tuning per use case)
on the `p-tabView` add `styleClass="orientation-right"` and then define in scss
```
:host ::ng-deep {
    .orientation-right{
        display: flex;

        .p-tabview-nav {
            flex-direction: column;
            width: 10%;
        }
    }
}
```

disclaimer - I work with rtl support, so it may be a matter of adding flow-direction to orientation class to get it in the direction you desire

**Comment by anaq1** [comment] 2020-12-30 08:11
I can confirm this bug in PrimeNG 11, we have to stop the update from version 9 because of this. Can somebody change the label? This is not an enhancement...

**Comment by ShashankHA** [comment] 2021-03-08 13:38
Is there any update on this issue, I have primeng 11 in my local, still this issue exists. @cagataycivici , @yigitfindikli  can you please check on this issue.

**Comment by ratbeard** [comment] 2021-09-30 17:45
This was a regression in our app as well when upgrading recently.  It looks like mention of this previously supported attribute was removed from the docs.

Here's a css workaround I did to get something that looked ok:

```
:host ::ng-deep .p-tabview {
	display: flex;
}
:host ::ng-deep .p-tabview-nav-container {
	width: 300px;
}
:host ::ng-deep .p-tabview-nav-container {
	flex: 1;
}
:host ::ng-deep .p-tabview-nav {
	flex-direction: column;
}
```

**Comment by mertsincan** [comment] 2022-11-09 20:03
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by saramcicchi** [comment] 2022-11-10 14:10
Hi @mertsincan, it looks like the input "orientation" has been removed from the TabView component entirely since this issue was opened. I think people would appreciate it being added back in again to enable vertical tabs. Can you please reopen?

**Comment by khocef** [comment] 2023-06-03 12:03
+1

**Comment by InFecTie** [comment] 2023-10-11 12:25
+1  please enable vertical tabs again..

**Comment by cetincakiroglu** [comment] 2023-12-28 06:50
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).

**Closed by cetincakiroglu** 2023-12-28 06:50 UTC
Labels: Type: Enhancement, Status: Needs Triage
