### ISSUE TITLE
Autocomplete suggestions panel does not hide when completeMethod is asynchronous.

### ISSUE THREAD

**Issue by Abbraxar** [primefaces/primeng#4268] opened 2017-10-25 14:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/UFCPkA3wGE0HsQ2ZQjoU?p=preview

**Current behavior**
The suggestions panel in autocomplete component needs two external clicks to hide.

**Expected behavior**
Clicking outside the suggestions panel or choosing an option from it must close the panel.

**Minimal reproduction of the problem with instructions**
There is two autocomplete components, one with synchronous completeMethod, the other with asynchronous completeMethod (setTimeout).
1. Click the dropdown icon of the second autocomplete component.
1. Click outside the suggestions panel.
1. Observe that it needs two click to close.

**Comment by cagataycivici** [comment] 2017-10-25 14:46
Duplicate of https://github.com/primefaces/primeng/issues/4162

**Closed by cagataycivici** 2017-10-25 14:46 UTC
