### ISSUE TITLE
DataTable Escape does not cancel edit

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#2996] opened 2017-06-05 20:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Issue is visible on the demo page:
https://www.primefaces.org/primeng/#/datatable/editable

**Current behavior**
Edit the value in a cell and press escape. The value you edited remains.

**Expected behavior**
Expected that the edit you made would not be committed, because escape triggers onEditCancel.

**Minimal reproduction of the problem with instructions**
See *Current Behavior*

**What is the motivation / use case for changing the behavior?**
The current behavior is wrong, right? As long as it behaves this way, it's impossible to cancel an edit.

**Please tell us about your environment:**

* **PrimeNG version:** 4.0.3

* **Browser:**
Chrome, IE11

**Comment by guntram** [comment] 2017-06-19 15:32
Did you set the event-listeners inside the DataTable?

```
 <p-dataTable
            ......
            [editable]="true"
            (onEditComplete)="onEditComplete($event)"
            (onEditCancel)="onEditCancel($event)"
            (onEditInit)="onEditInit($event)">
```
And `[editable]="true"` inside the p-column?

I cannot reproduce your issue on IE11 and Chrome@latest...
Everything is working as expected, except for no event is fired if the fieldUnderEdit is losing focus.

**Comment by daleclements** [comment] 2017-06-19 15:52
Maybe what I expect to happen isn't what is actually supposed to happen?

Since pressing escape triggers "onEditCancel" I thought that it would cancel the edit by default, out-of-the-box. Am I supposed to implement the cancel myself?

The reason I thought this is the name of the event. It's not named "onEscapePressed" or something else that would imply that implementation is up to me. "onEditCancel" tells me that it is an event that is fired when the edit is canceled, but the edit isn't actually cancelled when the event is fired right now, unless I manually cancel it in the handler. Does that make sense?

If I don't actually do anything in onEditCancel(event){ }, is it expected that the edit will be cancelled when Escape is pressed?

**Comment by guntram** [comment] 2017-06-19 16:29
The code handling the keydown strokes emits a blur event:
```
if (event.keyCode == 13) {
                this.onEditComplete.emit({ column: column, data: rowData, index: rowIndex });
                this.domHandler.invokeElementMethod(event.target, 'blur');
                this.switchCellToViewMode(event.target);
                event.preventDefault();
            }
            else if (event.keyCode == 27) {
                this.onEditCancel.emit({ column: column, data: rowData, index: rowIndex });
                this.domHandler.invokeElementMethod(event.target, 'blur');
                this.switchCellToViewMode(event.target);
                event.preventDefault();
            }
```
I tried to override this behavior by using my own edit template (only need this for one column/string), but it is more than just using the already implemented event emitters.
As i need only one cell to be editable, i can pretty easily hold a backup for this one chunk of data...

```
 onEditInit($event) {
        this.descriptionToEdit = UtilsService.getCloneFromObject($event.data.description);
    }

    onEditCancel($event) {
        $event.data.description = this.descriptionToEdit ? UtilsService.getCloneFromObject(this.descriptionToEdit) : "";
        this.descriptionToEdit = "";
    }
```
But the blur event will never save nor reset the field-data if i do not want to re-implement some functionality of the DataTable.

**Comment by daleclements** [comment] 2017-06-19 17:52
Okay I think I see. So actually preventing the edit from applying is something we need to implement ourselves manually by storing the initial value in our onEditInit handler and setting it back to it in the onEditCancel handler.

You mentioned event emission using our own edit templates but I'm not sure what you're saying. I did notice that when using a custom edit template, the onEditCancel event is not fired.

**Comment by guntram** [comment] 2017-06-19 18:02
For using an own template, you must emit these events in the wrapped input
for example.

```
<ng-template pTemplate="editor" let-row="rowData">
    <input ... (blur)="onBlur({$event: $event, data: row})" ...other
events.../>
</ng-template>
```
If you want to reimplement or make a pull request with a fix, you should
check out how it is handled inside of the DataTable class. It also includes
setting back to view mode after edit for example.

**Comment by cagataycivici** [comment] 2017-06-23 11:27
Duplicate of #2485

**Closed by cagataycivici** 2017-06-23 11:27 UTC
