### ISSUE TITLE
dialog’s contentStyle to fail to set the height.

### ISSUE THREAD

**Issue by qiyus** [primefaces/primeng#7308] opened 2019-03-01 02:02 UTC
[x] bug report
[ ] feature request
[ ] support request

Plunkr Case (Bug Reports)

Current behavior
The following statement in the positionOverlay() function of dialog.ts **this.contentViewChild.nativeElement.style.height = null;**
causes contentStyle to fail to set the height.

Expected behavior
contentStyle to success to set the height.

Angular version:
Angular 7.2.3

PrimeNG version:
PrimeNG 7.0.5

Browser:
Chrome

Language:
TypeScript 3.1.6

**Comment by sandipchitale** [comment] 2019-03-21 06:37
https://github.com/primefaces/primeng/blob/242dd1c3ea2efaa4623f300b96d1a79a7434d3ce/src/app/components/dialog/dialog.ts#L237 seems to be the cause.

**Comment by sandipchitale** [comment] 2019-03-21 07:43
I worked around it by using a template variable for dialog `#d` and then adding `(onShow)="adjustHeight(d)"` and then inside implementing 

`
import { Dialog } from 'primeng/dialog';
.
.
.
adjustHeight(d: Dialog) {
    setTimeout(() => {
      d.contentViewChild.nativeElement.style.height = '100%';
    }, 1000);
}
`

**Comment by qiyus** [comment] 2019-04-13 05:28
@sandipchitale 
Thank you very much. I need to constantly change scrollHeight when dialog resize.

**Comment by yigitfindikli** [comment] 2020-02-24 10:54
Fixed in https://github.com/primefaces/primeng/issues/8472 .

**Closed by yigitfindikli** 2020-02-24 10:54 UTC
Labels: LTS-FIXED-8.1.6, defect
