### ISSUE TITLE
label template for MultiSelect

### ISSUE THREAD

**Issue by spnm** [primefaces/primeng#4209] opened 2017-10-19 11:49 UTC
In MultiSelect we should have an option selectedLabelTemplate that we should define a template like this:
`selectedLabelTemplate = "<span>{0}</span>"`

As it is in:
`selectedItemsLabel {0} items selected`

**Comment by cagataycivici** [comment] 2017-10-20 08:18
Duplicate of #4209

**Closed by cagataycivici** 2017-10-20 08:18 UTC
Labels: new feature

**Comment by reinpeter** [comment] 2017-10-20 12:20
@cagataycivici  did you mark this ticket a duplicate of itself and close it?
