### ISSUE TITLE
Primeng Angular 4 - datatable filter problem

### ISSUE THREAD

**Issue by oixan** [primefaces/primeng#3004] opened 2017-06-06 15:32 UTC
I m using primeng datatable, with angular, 4 on my website.
I have datatable with filter enable and i notice a really weird behavor when typing on column filter.
This is a problem reproducible on the official https://www.primefaces.org/primeng/#/datatable/filter website.
I attached i short video to show the problem. ( https://www.screencast.com/t/mSTgtHyXYK6 - need flash though )
In that video I was just trying to type datatable but the word was always cut by datatable filter. 
Can i disable that? I just want type the whole word then trigger the filter.

**Comment by dzhavat** [comment] 2017-06-07 23:51
I'm experiencing the same issue. It will be amazing of you can fix it!

**Comment by Ketec** [comment] 2017-06-12 10:40
Same problem. It seems t be filling the filter field from a variable used to filter after it returns the filtered results, especially noticeable on tables with large number of rows.

**Comment by IngenieroLata** [comment] 2017-06-12 15:27
Same Problem over here, I was looking into some sort of performance issue while typing but nothing for sure.

**Comment by cagataycivici** [comment] 2017-06-28 09:36
Duplicate of #1813

**Closed by cagataycivici** 2017-06-28 09:36 UTC
Labels: review
