### ISSUE TITLE
onLazyLoad event not fired when a text filter is cleared out

### ISSUE THREAD

**Issue by jbgarr** [primefaces/primeng#4898] opened 2018-01-19 19:17 UTC
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the last character or the whole text string in a text filter is removed there is no onLazyLoad event fired.

**Expected behavior**
The onLazyLoad event should fire when a text filter is cleared.

**Minimal reproduction of the problem with instructions**
This bug is shown in the following Plunk: http://plnkr.co/edit/iJdn8ZKx5dqAs5o8aCjE?p=preview

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.1

* **Browser:** Tested in Chrome v63.0.3239.132 (Official Build) (64-bit) on macOS High Sierra

**Comment by ARandomDude** [comment] 2018-01-19 22:41
Seems to be the same issue as #4863.

**Comment by cagataycivici** [comment] 2018-01-22 14:40
Duplicate of 4863

**Closed by cagataycivici** 2018-01-22 14:40 UTC
Labels: defect
