### ISSUE TITLE
Problem menuBar on mobile

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#2944] opened 2017-05-31 16:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Current behavior**

When the page is displayed in a mobile, when clicking on the menuBar with subMenu these are not shown

**Expected behavior**
display the subMenu items when I press menu in my mobile

**Minimal reproduction of the problem with instructions**
html
<p-menubar [model]="items"></p-menubar>
TS
  this.items = [
            { label: 'Inicio', routerLink: ['/'], icon: 'fa-home' },
            { label: 'Aplications', icon: 'fa-search', items: [ 
                    {label: 'Author', routerLink: ['/author-list']}, //not apper in mobile
                    {label: 'Book', routerLink: ['/book-list']}, //not apper in mobile
                    {label: 'Passport', routerLink: ['/passport-list']}, //not apper in mobile
                   ]
            }
        ];

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment] 2017-06-23 08:31
Duplicate of #2931

**Closed by cagataycivici** 2017-06-23 08:31 UTC
