### ISSUE TITLE
Dropdown dynamic options and preselected item on event fired not work the first time but works in the next times

### ISSUE THREAD

**Issue by rsotolongo** [primefaces/primeng#12266] opened 2022-11-21 17:41 UTC
Describe the bug:

If dropdown options are assigned dynamically as a response of an event, the select option is always the first one the first time that event is fired and in all next execution, the selected option is correct. If an idle time is used, the behavior is the expected.

Environment:

Any browser/Stackblitz

Reproducer:

https://stackblitz.com/edit/primeng-dropdown-demo-n9ynk8

Angular version:

13.0.3 and 13.1.1 (two versions tested, could be more versions with the issue)

PrimeNG version:

13.0.4

Build / Runtime:

Angular CLI App

Language:

TypeScript

Node version (for AoT issues node --version):

19.1.0

Browser(s):

No response

Run the stackblitz example and click in the button to confirm that the preselection is wrong (always the first element of the list) but then the second time (and all other times after) the correct value is bind. Another "curious" fact is that if we comment the line for assign the preselected item and uncomment the setTimeout() line (meaning doing the assigment after a very short idle time), it works as expected.

Expected behavior:

The binded options and the preselected item should be the correct one without have to wait an idle time since the first time an event is fired.

**Comment by cetincakiroglu** [comment] 2022-11-22 14:59
Hi,

This is not a bug, there is an input property "autoDisplayFirst" which is set to "true" as the default value. That's why value is not displayed correctly in your case, autoDisplayFirst="false" solves the issue. 

Here is the refactored version of your example https://stackblitz.com/edit/primeng-dropdown-demo-6e4sxm?file=src%2Fapp%2Fapp.component.html

Closing the issue, thanks for your report!

Regards

**Closed by cetincakiroglu** 2022-11-22 14:59 UTC
Labels: Status: Needs Triage
