### ISSUE TITLE
TieredMenu: SubMenus are not uncovered on mouse hover anymore

### ISSUE THREAD

**Issue by Maran23** [primefaces/primeng#13455] opened 2023-08-07 16:54 UTC
### Describe the bug

Since the `TieredMenu` refactoring done in https://github.com/primefaces/primeng/commit/28989fd4cafe4ee5b7d805f5b059618f5fc1128b, it works a bit different now (16rc2 -> 16.0.0).
Before, all sub `MenuItem`s of a `TieredMenu` uncovered themself after hovering over the parent `MenuItem` when in `popup` mode.

### Environment

Doesn't matter in this case.

### Reproducer

See below

### Angular version

16.0.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

All

### Steps to reproduce the behavior

This can be easily reproduced by checking out the showcase.
https://www.primefaces.org/primeng-v15-lts/tieredmenu
https://primeng.org/tieredmenu

1. In the `Popup` section, click on the `Show` Button.
2. If you hover over all the `MenuItem`s like `File` or `Edit`, all sub `MenuItem`s will be uncovered in Version 15. This does not happen anymore in Version16, you need to click on the `MenuItem` to uncover all sub `MenuItem`s.

### Expected behavior

Sub `MenuItem`s uncover themself when you hover over the parent `MenuItem`.

NOTE: `autoDisplay` is `true` but it seems to not affect anything at all.
Before the refactoring this behaviour worked when the `TieredMenu` is a `popup` or `autoDisplay` was turned on AFAIK.

**Comment by rosenthalj** [comment] 2023-08-09 10:28
I believe that issue: "TieredMenu: On mobile tieredmenu requires double tap to open submenu #13433" can be fixed by updating  Maran23's pull request #13457 with the following one line change:

![](https://github.com/primefaces/primeng/assets/45439491/adab6800-d55c-4cea-8448-3484b8d7e6b4)

This proposed change incorporates part of @SoyDiego pull request #13458 to fix issue #13433

**Comment by Maran23** [comment] 2023-08-09 12:02
> I believe that issue: "TieredMenu: On mobile tieredmenu requires double tap to open submenu #13433" can be fixed by updating Maran23's pull request #13457 with the following one line change:
> 
> ![](https://user-images.githubusercontent.com/45439491/259375181-adab6800-d55c-4cea-8448-3484b8d7e6b4.png)
> 
> This proposed change incorporates part of @SoyDiego pull request #13458 to fix issue #13433

This looks good. I would suggest we first incorporate my PR and create a follow up with your fix? To keep every PR clean and simple. :)

**Closed** 2023-08-09 14:09 UTC
Labels: Type: Bug

**Comment by cetincakiroglu** [comment] 2023-08-09 14:15
Some of the component behaviors (focus, hover, mouse events etc.) are changing and will continue to change across the PrimeNG due to accessibility implementation. Since the accessibility implementation is a giant leap forward and includes a lot of refactoring and rework, some of the functionalities may unintentionally be broken. I see that the autoDisplay feature is broken with this update, we'll discuss it with the dev team and find a solution.

**Comment by Maran23** [comment] 2023-08-14 12:15
> This issue still occurs on menubar, worked fine before autoDisplay true does nothing currently

But this is a somewhat separate issue. My fix was only inside the `tieredmenu` code, not inside the `menu` component.

**Comment by MarcinBorowski95** [comment] 2023-08-30 13:25
Regression from 16.3.0 
This is once more an issue.
