### ISSUE TITLE
p-overlayPanel cannot contain text field in mobile web browsers

### ISSUE THREAD

**Issue by frauscher** [primefaces/primeng#11401] opened 2022-04-11 05:51 UTC
**I'm submitting a ...
```
[ x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-72ndt3
(the template sadly seems not to run on mobile devices)

**Current behavior**
This behavior happens on mobile devices! If an OverlayPanel contains an input element (like a text field), the OverlayPanel is closed when clicking into the text field. The behavior is caused by the `onWindowResize()` event handler method inside the `overlaypanel.ts`. When clicking into an input element, the mobiles keyboard is shown, causing a resize of the mobile browser window. The `onWindowResize()` event handler method is called, which closes the OverlayPanel, and the also the keyboard is hidden again, because the input element isn't focused anymore (due to it being hidden).

```
// overlaypanel.ts
onWindowResize(event) {
    this.hide();
}
// dropdown.ts
onWindowResize() {
    if (!DomHandler.isAndroid()) {
        this.hide();
    }
}
```

**Expected behavior**
The OverlayPanel acts similar to other components like the `p-dropdown` component, and does stay visible when clicking inside an input element like a text field.

**What is the motivation / use case for changing the behavior?**
Having a filter text box inside an OverlayPanel.

* **Angular version:** 11.2.14

* **PrimeNG version:** 11.3.1
Same behavior can be seen in the master branch.

* **Browser:** Mobile Chrome  | Android Web Browser | iOS Safari

**Comment by luismqoliveira** [comment] 2022-05-11 17:19
Im facing this issue too on Primeng 13. It's seems it's a simple fix.

**Comment by mertsincan** [comment] 2022-05-30 14:01
Duplicate of [11567](https://github.com/primefaces/primeng/issues/11567)

**Closed by mertsincan** 2022-05-30 14:01 UTC
