### ISSUE TITLE
DataTable Reorder and toggle bugs

### ISSUE THREAD

**Issue by Korozu** [primefaces/primeng#3646] opened 2017-08-11 09:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/8JPnCqOx9Hz5rRVcAxdF?p=preview

**Current behavior**

can't reorder column and button's column doesn't keep his initial width when toggling columns.

**Expected behavior**

I should be able to reorder the column, since i used the reorderableColumns attribute.
The button's column should keep his initial width.

**Minimal reproduction of the problem with instructions**

when i untoggle all togglable column the button's column takes the all place, and if i "retoggle" all column, the button's column doesn't keep his initial width.

**Comment by cagataycivici** [comment] 2017-10-02 14:12
Duplicate of https://github.com/primefaces/primeng/issues/3910

**Closed by cagataycivici** 2017-10-02 14:12 UTC
