### ISSUE TITLE
Multiselect Dropdown with Groups

### ISSUE THREAD

**Issue by karthik-dusk** [primefaces/primeng#5712] opened 2018-05-10 12:26 UTC
![howto](https://user-images.githubusercontent.com/5618488/39869489-54c922c4-547b-11e8-9cd5-638e03110260.png)

I want to achieve multi-select dropdow with groups as shown in the above pic.

**Comment by wvpelt** [comment] 2018-05-31 11:57
Hi, did you manage to get this done? I'm looking for the exact same thing

**Comment by bossqone** [comment] 2018-07-31 09:01
+1

**Comment by vipatel03** [comment] 2018-10-22 16:05
+1

**Comment by mperezguendulain** [comment] 2018-12-13 18:09
+1

**Comment by DesertFoxNV** [comment] 2019-01-29 00:17
One workaround would be to add a disabled item. Then use css to remove the empty checkbox, and custom templating.

CSS Example
`li.ui-state-disabled.ui-multiselect-item > div.ui-chkbox
{
	display: none !important;
}`

Template Example
`
<p-multiSelect [options]="cars" [(ngModel)]="selectedCars2" [panelStyle]="{minWidth:'12em'}">
    <ng-template let-car pTemplate="item">
        <img src="assets/showcase/images/demo/car/{{car.label}}.png" style="width:24px;display:inline-block;vertical-align:middle"/>
        <div style="font-size:14px;float:right;margin-top:4px">{{car.label}}</div>
    </ng-template>
</p-multiSelect>`

**Comment by adama357** [comment] 2019-03-19 15:07
Duplicate of #2622, except that issue also asks for a checkbox to check / uncheck an entire group (which would be helpful).

**Comment by soyiatgit** [comment] 2020-04-19 11:37
I too needed this multiselect with groups. I created a wrapper on top of multiselect. Have a look here.
https://medium.com/@saurabhatgate/grouped-multi-select-with-primeng-113616df9981

**Comment by mertsincan** [comment] 2022-11-09 14:50
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 14:50 UTC
Labels: new feature

**Comment by rinathakkar18492** [comment] 2023-05-17 14:07
I want p-multiselect with group label and search with group label and child items as well.
