### ISSUE TITLE
p-dropdown: Error when clicking clear button

### ISSUE THREAD

**Issue by alexthelion** [primefaces/primeng#14026] opened 2023-11-04 10:47 UTC
### Describe the bug

p-dropdown: Error when clicking clear button.
After click the dropdown become unresponsive.
It can be reproduced in primeng website.

### Environment

windows

### Reproducer

https://primeng.org/dropdown#filter

### Angular version

16.2.0

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.7.0

### Browser(s)

Chrome 118

### Steps to reproduce the behavior

1. click on x button (clear selection)

### Expected behavior

clear selected value

**Comment by maruthumj** [comment] 2023-11-05 07:50
@alexthelion this issue  is not reproducible when with the latest code in local. the issue might have  already fixed. I haveattached the video below. please check and confirm.

https://github.com/primefaces/primeng/assets/32091483/48a8a822-5015-4c46-a2aa-a4040f6e9a8b

**Comment by cetincakiroglu** [comment] 2023-11-06 11:57
Duplicate of https://github.com/primefaces/primeng/issues/13996

**Closed by cetincakiroglu** 2023-11-06 11:57 UTC
Labels: Status: Needs Triage
