### ISSUE TITLE
Life property to Messages components

### ISSUE THREAD

**Issue by comlabmohan** [primefaces/primeng#4888] opened 2018-01-19 13:37 UTC
**I'm submitting a new feature request ...**

**Current behavior**

Currently messages doesn't have auto disposable option with time seconds  

**Expected behavior**

<p-messages [(value)]="msgs"  [life]="1000" ></p-messages>

**What is the motivation / use case for changing the behavior?**

Having the requirement to display a messages with auto disposable after some time interval.

**Comment by davisb10** [comment] 2018-02-23 16:20
+1 I agree that this should be implemented as well. In most cases, Messages and Growl both have different uses. However the Messages component not having a 'timeout' is rather unfortunate.

@cagataycivici Is this something that could be implemented? Or are you open for the creation of a pull request for this feature?

**Comment by cagataycivici** [comment] 2018-03-26 15:20
Sounds good to me.

**Comment by TheParad0X** [comment] 2018-04-26 12:53
+1

**Comment by klaro00** [comment] 2018-04-26 12:58
+1

**Comment by Rotzbua** [comment] 2019-12-21 16:23
Doublicate of  #3232 .
Maybe should be rejected according to p-toast  #7139 @yigitfindikli .

**Comment by RedSerenity** [comment] 2021-09-13 21:23
It looks like there hasn't been any movement on this for awhile. I went ahead and created a directive to implement this functionality for my own project.

```typescript
import { AfterContentInit, Directive, OnDestroy } from '@angular/core';
import { Message } from 'primeng/api';
import { Messages } from 'primeng/messages';
import { Subscription } from 'rxjs';

@Directive({
	selector: 'p-messages[enableLife]'
})
export class PrimeMessagesLifeDirective implements AfterContentInit, OnDestroy {
	private msgSub: Subscription;

	constructor(private host: Messages) {}

	ngOnDestroy(): void {
		this.msgSub?.unsubscribe();
	}

	ngAfterContentInit(): void {
		if (this.host.messageService && this.host.enableService && !this.host.contentTemplate) {
			this.msgSub = this.host.messageService.messageObserver.subscribe((messages) => {
				if (!messages) { return; }

				if (messages instanceof Array) {
					messages.map(this.processMessages);
				} else {
					this.processMessages(messages);
				}
			});
		}
	}

	private processMessages(message: Message) {
		if (!message.life) { return; }

		setTimeout(() => {
			const index = this.host.value.indexOf(message);
			if (index !== -1) {
				this.host.removeMessage(index);
				this.host.cd.markForCheck();
			}
		}, message.life);
	}
}
```

```html
<p-messages enableLife></p-messages>
```

Hope this helps anyone wanting `life` on Messages. 😊

**Comment by yigitfindikli** [comment] 2022-02-03 12:03
Duplicate of https://github.com/primefaces/primeng/issues/3232

**Closed by yigitfindikli** 2022-02-03 12:03 UTC
