### ISSUE TITLE
Datatable : slow rendering of records in IE11

### ISSUE THREAD

**Issue by smtgpt62** [primefaces/primeng#2071] opened 2017-02-14 11:16 UTC
Hi, I am developing an angular app using primeng datatable . While rendering records in IE 11, it is taking 8 seconds for 200 records. Even on changing page of datatable , it is taking 8 sec . Can anybody please help me out in this performance issue.

**Comment by cagataycivici** [comment] 2017-02-21 14:20
We'll review. How many columns do you have?

**Comment by smtgpt62** [comment] 2017-02-21 16:08
My Datatable is having 18 columns.

**Comment by cagataycivici** [comment] 2017-02-21 16:24
And how many rows?

**Comment by smtgpt62** [comment] 2017-02-21 20:39
More than 200


On 21-Feb-2017 9:55 PM, "Çağatay Çivici" <notifications@github.com> wrote:

And how many rows?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/primefaces/primeng/issues/2071#issuecomment-281395109>,
or mute the thread

**Comment by stavn1** [comment] 2017-02-27 10:05
I have the same problem. The datatable is very slow to load on IE 11. The other browsers are fine.
I load 100 rows with 15 columns.
I have angular 2.4 and primeng 2.0.1.

**Comment by rupeshraut** [comment] 2017-05-01 14:02
Hello, I'm experiencing same issue with data table. My table has 6 columns and loading 50 records with pagination. My service is reading JSON file using http.get().

**Comment by cagataycivici** [comment] 2017-05-01 14:33
What areyour Angular and PrimeNG versions?

**Comment by rupeshraut** [comment] 2017-05-01 14:40
PrimeNG 4.0.0 and Agnular 4.1.0

**Comment by mscu** [comment] 2017-06-11 12:09
same issue here, just 3 columns with 150 entries and the performance in IE is really bad

**Comment by cagataycivici** [comment] 2017-06-20 13:04
Duplicate of #3101

**Closed by cagataycivici** 2017-06-20 13:04 UTC
