### ISSUE TITLE
p-calendar preventing calendar automatic closing with [hideOnDateTimeSelect]="false" not working for selectionMode="range"

### ISSUE THREAD

**Issue by vladimirturkovic** [primefaces/primeng#14989] opened 2024-03-08 11:35 UTC
### Describe the bug

p-calendar preventing calendar automatic closing with [hideOnDateTimeSelect]="false" not working for selectionMode="range"

### Environment

-

### Angular version

18.0.0

### PrimeNG version

17.7.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

chrome

### Steps to reproduce the behavior

1. add [hideOnDateTimeSelect]="false" and selectionMode="range" 2. select range date on calendar 3. calendar should stay opened

### Expected behavior

When using [hideOnDateTimeSelect]="false" and selectionMode="range" after selecting range date, calendar should stay opened

**Comment by ziembar** [comment] 2024-04-10 15:48
Experiencing the same thing...

**Comment by FalcaoCamilla** [comment] 2024-04-11 14:51
Looks like there's an onDateSelect() function where a check is done to trigger hideOverlay(). In the case of the range, the hideOnDateTimeSelect property is not checked and hideOverlay is called whenever the second value is entered. This has not been resolved in the current versions.

**Comment by brenosilveira** [comment] 2024-04-11 14:54
W
![Screenshot_20240411_115313_Outlook](https://github.com/primefaces/primeng/assets/47336657/2e957559-22f1-4f85-b19a-ba87cdc57ed5)
hen the p-calendar is set to "range" hideOnDateTimeSelect = false is simply ignored, causing the calendar to be closed when clicking on the second date.

**Comment by Xylios13** [comment] 2024-04-17 08:01
I've taken the liberty of creating a stackblitz that reproduces the error:
https://stackblitz.com/edit/github-naqavf-ypnqp4?file=src%2Fapp%2Fapp.component.html

**Comment by El-Tommy** [comment] 2024-05-07 19:02
In version 17.16 the problem still persists.

**Closed** 2024-05-30 07:40 UTC
Labels: Type: Bug
