### ISSUE TITLE
p-spinner does not show 0 values since PrimeNG 8.0.0

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#7859] opened 2019-06-27 09:20 UTC
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-primeng-spinner

**Current behavior**
When changing a number value to 0 (zero) in a p-spinner, it does not display anything instead of 0.

**Expected behavior**
I would expect that 0 is displayed in the p-spinner. With PrimeNG 7.x it works fine.

**Minimal reproduction of the problem with instructions**
See test case here https://stackblitz.com/edit/github-primeng-spinner

* **Angular version:** 8.X

* **PrimeNG version:** 8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 74

**Comment by mertsincan** [comment] 2019-07-02 06:52
Duplicate of https://github.com/primefaces/primeng/issues/7815

**Closed by mertsincan** 2019-07-02 06:52 UTC
