### ISSUE TITLE
Dropdown value is not cleared when options change

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8806] opened 2020-04-30 10:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-options-changed-value-not-cleared

**Current behavior**
If a dropdown has a selected item and it's options change so that selected item is not longer present, the dropdown keeps previous value and "clear" button is not hidden:

![image](https://user-images.githubusercontent.com/580460/80701294-db53c480-8ae7-11ea-8a50-3cea2d54a84c.png)

**Expected behavior**
The dropdown value has to be cleared (with "change" event fired) and "clear" button hidden.

* **Angular version:** 9.1.1
* **PrimeNG version:** 9.0.6

**Comment by anothergitdev** [comment] 2020-05-02 04:40
This should be handled in dropdown module itself when we change option list, selectedItem should re initialize or set to null so that ngModel changes to new value.
You can still `this.selectedCity = null;` in your onClick() event when setting new options list for workaround.

**Comment by dmytro-gokun** [comment] 2020-06-05 08:01
The problem still exists in 9.1.0

**Comment by yigitfindikli** [comment] 2022-05-06 09:03
Fixed in https://github.com/primefaces/primeng/commit/ed3b3088a67f8f1e59f365b240d4df1b78e2ebaa

**Closed by yigitfindikli** 2022-05-06 09:03 UTC
Labels: enhancement

**Comment by pete-mcwilliams** [comment] 2022-05-13 10:34
I'm seeing a regression issue probably caused by this change in version 13.4.0

If you set the options and ngModel value in ngOnInit then you now have to issue this.changeDetectorRef.detectChanges(); after setting the options and before setting the value, or the value never shows as selected.
