### ISSUE TITLE
Error thrown when resizing columns of a p-table with virtual scrolling

### ISSUE THREAD

**Issue by eronyck** [primefaces/primeng#8896] opened 2020-05-27 12:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After I upgraded primeng to 9.1.0, if [virtualScroll]="true" is set to a p-table with resizable columns, when I try to resize a column an error is thrown:

zone-evergreen.js:172 Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at Table.setScrollableItemsWidthOnExpandResize (primeng-table.js:1597)
    at Table.onColumnResizeEnd (primeng-table.js:1568)
    at ResizableColumn.onDocumentMouseUp (primeng-table.js:3080)
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:481)
    at invokeTask (zone-evergreen.js:1596)
    at HTMLDocument.globalZoneAwareCallback (zone-evergreen.js:1622)
    at Table.setScrollableItemsWidthOnExpandResize (primeng-table.js:1590)
    at Table.onColumnResizeEnd (primeng-table.js:1568)

**Expected behavior**
The columns should be resized without errors.

**Minimal reproduction of the problem with instructions**
The error is generated in Table.setScrollableItemsWidthOnExpandResize, because scrollableBody and scrollableBodyTable variables are undefined due to querying for ui-table-scrollable-body class instead ui-table-virtual-scrollable-body that I actually see in the DOM.

![primeng-code](https://user-images.githubusercontent.com/23700531/83018814-8fd0ff80-a02e-11ea-8131-d8bcfade655d.png)

![primeng-table](https://user-images.githubusercontent.com/23700531/83018481-120cf400-a02e-11ea-9fca-56b27af9a6dd.png)

* **Angular version:** 5.X
9.0.5

* **PrimeNG version:** 5.X
9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by jacqueslareau** [comment] 2020-05-27 14:15
duplicate of #8885

**Comment by yigitfindikli** [comment] 2020-11-23 13:37
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Closed by yigitfindikli** 2020-11-23 13:37 UTC
