### ISSUE TITLE
ngFor/ngIf not working for generate a list of tabPanel

### ISSUE THREAD

**Issue by stephanecot** [primefaces/primeng#2000] opened 2017-02-06 10:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

My problem is simple. I have the following code, to generate a liste of tabPanel with a list of objets.
```
@Input()
perimeters: BeneficiaryPerimeter[];

<div class="panel-body" *ngIf="perimeters?.length > 0">
<p-tabView orientation="left">
   <p-tabPanel [header]="perimeter.name" *ngFor="let perimeter of perimeters">
           {{perimeter}}
   </p-tabPanel>
</p-tabView>
</div>
```

It generates the following error:
**EXCEPTION: Error in ./TabPanel class TabPanel - inline template:1:56 caused by: Expression has changed after it was checked. Previous value: 'none'. Current value: 'block'.**

This code is working:

```
<p-tabView orientation="left">
    <p-tabPanel [header]="perimeters[0].name">
             {{perimeters[0]}}
      </p-tabPanel>
</p-tabView>
```

This code is not working:
```
<p-tabView orientation="left">
     <p-tabPanel [header]="perimeters[0].name" *ngIf="perimeters[0]">
             {{perimeters[0]}}
       </p-tabPanel>
</p-tabView>
```

**Please tell us about your environment:**
* **Angular version:** 2.4.6

* **PrimeNG version:** 2.0.0-rc3

* **Browser:** [Chrome 56]

**Comment by upmauro** [comment] 2017-02-15 14:08
I tried simulate but here worked. Can you make a plunkr?

Just to know:

> The error look about our NgIf expression - the first time it runs, [style.display] is 'none', then ngAfterContentInit() runs and changes the value to something other than 'block'.

But I can not simulate the problem.

**Comment by stephanecot** [comment] 2017-02-15 21:34
I have found the "problem"

https://plnkr.co/edit/DEJXu5rQhtfgvvzoJcM1?p=preview

I have two level of tabView:

`<p-tabView>
    <p-tabPanel header="Tab1">
          <p-tabView orientation="left">
              <p-tabPanel header="{{data.var1}}" *ngFor="let data of datas">
               Content 1
              </p-tabPanel>
          </p-tabView>
     </p-tabPanel>
</p-tabView>`

With only one level, it's working (like you had tested), but in my case, with a second 'level', I can reproduce the problem.

**Comment by m-tomczyk** [comment] 2017-04-11 13:59
I can confirm that this bug exists but for me it looks like *ngFor is the cause. For example:

```
<p-tabView>
<p-tabPanel *ngFor="let tab of tabs" header="someheader"></p-tabPanel>
</p-tabView>
```
is invalid while adding at least one static tab:

```
<p-tabView>
<p-tabPanel header="dummy"></p-tabPanel>
<p-tabPanel *ngFor="let tab of tabs" header="someheader"></p-tabPanel>
</p-tabView>
```
makes it work as expected.

**Comment by Arsenal83** [comment] 2017-05-17 05:35
see this post on forum: 
https://forum.primefaces.org/viewtopic.php?p=153436#p153436
its working!

**Comment by cagataycivici** [comment] 2017-06-19 13:30
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Closed by cagataycivici** 2017-06-19 13:30 UTC

**Comment by scottieslg** [comment] 2017-07-07 18:05
This is still a problem with *ngIf

Here's a plunkr that reproduces the problem:

http://plnkr.co/edit/BLg0fYTAe62CyKtUlaFS?p=preview

**Comment by ikuriel** [comment] 2017-08-15 20:30
Yes, still a problem latest version 4.1.3

**Comment by ikuriel** [comment] 2017-08-15 20:39
the @m-tomczyk 's solution works, but only if you add the tab at the first place, in my case i need the static tab at the last, and error persists

**Comment by ikuriel** [comment] 2017-08-15 20:41
the @Arsenal83 quoted solution, works!!

**Comment by slugworth** [comment] 2017-10-13 15:23
@ikuriel that solution only works if you always intend to load the component with the first tab selected. This is still broken.

**Comment by jaxiell** [comment] 2017-11-01 03:53
i found the solution to sovle this error. you can add code like below.
 <p-tabPanel *ngFor="let x of xxx; let i = index ;" [selected]="i == 0? true:false" [header]=" headerxxxx">
 </p-tabPanel>

**Comment by lxyangfan** [comment] 2017-11-06 06:26
@jaxiell saved my day!! Works for me!

**Comment by luigiw** [comment] 2018-02-09 17:36
@jaxiell this solution fixes the error but also breaks lazy loading, now all tabs will be loaded even though I have <ng-template pTemplate="content"> wrapping up the content, I think this is still a bug.
