### ISSUE TITLE
p-confirmDialog component with problem in safari version 15.2(17612.3.6.1.6)

### ISSUE THREAD

**Issue by marcojunio** [primefaces/primeng#10988] opened 2021-12-21 14:51 UTC
Hello everyone,  with a new version safari we have problems in p-dialog component some lines appear with example equal in images.
it's probably some problem with webkit.

[Image for exmaple](https://imgur.com/a/iuv6CH1)

**Comment by cetincakiroglu** [comment] 2021-12-27 11:38
@marcojunio @frcandia 

Hi, this problem is probably caused by Safari or Mac version differences since there aren't any classes to affect the component in such a way, we checked in different versions on 2019 & 2021 M1 (BigSur & Monterey - 15,13,12,11) included your's mentioned, however, we couldn't catch this bug.

**Closed** 2021-12-27 11:39 UTC
Labels: pending-review
