### ISSUE TITLE
feat(Calendar): Add an input mask and key validation according to date format a.k.a. DateMask

### ISSUE THREAD

**Issue by mlakhara** [primefaces/primeng#3133] opened 2017-06-19 06:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Calendar Input allows for all the keys to be entered, leading to invalid date strings and major UX issue as users are not able to enter the dates using keyboard and they have to rely on the mouse point and click action to do this.

**Expected behavior**
The calendar should have an input mask that allows the user only to enter date according to the format set in the configuration.  This would be similar to the inputmask component that is available in the library.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Allows users to enter the dates using keyboard

**Please tell us about your environment:**
NA
* **Angular version:** 2.0.X
NA

* **PrimeNG version:** 2.0.X
NA

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
NA
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]: TS

* **Node (for AoT issues):** `node --version` =   NA

**Comment by cagataycivici** [comment] 2017-06-22 15:53
Duplicate of #1426

**Closed by cagataycivici** 2017-06-22 15:53 UTC
