### ISSUE TITLE
Dropdown: The arrow keys up and down stopped responding to change the selected option 

### ISSUE THREAD

**Issue by Alhajras** [primefaces/primeng#15406] opened 2024-04-30 09:26 UTC
### Describe the bug

I used to use PrimeNG `15`, but when I upgraded to `16.7.0` the drop-down stopped responding to my keyboard  (up and down)

### Environment
```
{
  "name": "frontend",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "scripts": {
    "ng": "ng",
    "docs-build": "typedoc --tsconfig tsconfig.docs.json",
    "docs-open": "xdg-open docs/index.html",
    "serve": "ng serve",
    "build": "ng build",
    "analyze-production-bundle": "ng build --configuration production --stats-json && webpack-bundle-analyzer dist/stats.json",
    "test": "ng test --watch=false",
    "coverage": "ng test --code-coverage --watch=false",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "16",
    "@angular/cdk": "16",
    "@angular/common": "16",
    "@angular/compiler": "16",
    "@angular/core": "16",
    "@angular/forms": "16",
    "@angular/platform-browser": "16",
    "@angular/platform-browser-dynamic": "16",
    "@angular/router": "16",
    "angular-plotly.js": "5",
    "font-awesome": "4.7.0",
    "fork-awesome": "1.2.0",
    "global": "^4.4.0",
    "karma-spec-reporter": "^0.0.36",
    "lodash-es": "^4.17.21",
    "marked": "^4.3.0",
    "ngx-markdown": "16",
    "ngx-papaparse": "^7.0.0",
    "pako": "2.1.0",
    "plotly.js-basic-dist": "*",
    "primeflex": "2.0.0",
    "primeicons": "6",
    "primeng": "16",
    "rxjs": "7",
    "three": "0.156.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "16",
    "@angular-devkit/build-angular": "16",
    "@angular-eslint/builder": "16",
    "@angular-eslint/eslint-plugin": "16",
    "@angular-eslint/eslint-plugin-template": "16",
    "@angular-eslint/schematics": "16",
    "@angular-eslint/template-parser": "16",
    "@angular/cli": "16",
    "@angular/compiler-cli": "16",
    "@types/jasmine": "~4.3.1",
    "@types/lodash-es": "^4.14.176",
    "@types/marked": "^4.0.8",
    "@types/node": "*",
    "@types/offscreencanvas": "^2019.7.0",
    "@types/pako": "2.0.2",
    "@types/plotly.js-basic-dist": "*",
    "@types/three": "^0.156.0",
    "@typescript-eslint/eslint-plugin": "6.4",
    "@typescript-eslint/parser": "6.4",
    "eslint": "8",
    "eslint-config-standard-with-typescript": "39",
    "eslint-plugin-decorator-position": "5",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jasmine": "^4.1.3",
    "eslint-plugin-jquery": "^1.5.1",
    "eslint-plugin-jsdoc": "40.3.0",
    "eslint-plugin-local-rules": "^1.3.2",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-rxjs": "5",
    "jasmine-core": "4",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-firefox-launcher": "^2.1.0",
    "karma-jasmine": "5",
    "karma-jasmine-html-reporter": "^2.0.0",
    "karma-jasmine-order-reporter": "^1.1.0",
    "karma-junit-reporter": "^2.0.1",
    "openapi-typescript": "~6.5.0",
    "prettier": "^2.4.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typedoc": "^0.25.2",
    "typescript": "5.0",
    "webpack-bundle-analyzer": "^4.5.0"
  }
}
```

### Angular version

17

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19

### Browser(s)

Chrome 119.0.6045.199

### Steps to reproduce the behavior

Just add a drop-down menu and try using the keys up and down

**Comment by cetincakiroglu** [comment] 2024-05-03 09:38
Hi,

This issue is duplicate of https://github.com/primefaces/primeng/issues/14953

I'm closing the issue and we'll address https://github.com/primefaces/primeng/issues/14953 in the 17.16.0 release today

**Closed by cetincakiroglu** 2024-05-03 09:38 UTC
Labels: Type: Bug, Resolution: Duplicate, Component: Accessibility, LTS-16-PORTABLE

**Comment by a-hulman** [comment] 2025-12-29 11:43
Same issue here, up/down not responding.
