### ISSUE TITLE
Dropdown up/down arrow issue

### ISSUE THREAD

**Issue by hakim-dc** [primefaces/primeng#8110] opened 2019-09-02 08:05 UTC
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
PrimeNG Dropdown doesn't scroll down or up itemslist when we use down or up arrow button  **when virtualscroll is activated**

**Please tell us about your environment:**
Window, VS code, Angular cli

* **Angular version:** 5.X
8.0.3

* **PrimeNG version:** 5.X
8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment] 2019-09-05 11:50
Duplicate of #7963

**Closed** 2019-09-05 11:49 UTC
