### ISSUE TITLE
Blinking table header with Virtual Scrolling (v. 12+)

### ISSUE THREAD

**Issue by RieseIch** [primefaces/primeng#10895] opened 2021-11-30 07:50 UTC
Virtual scrolling worked fine up to version 12.
Starting from version 12, the table header blinks or moves while scrolling. This makes it impossible to use the Virtual Scrolling functionality.

Blinking is reproduced even in demo examples on your site (see [https://primefaces.org/primeng/showcase/#/table/flexscroll](https://primefaces.org/primeng/showcase/#/table/flexscroll))

**Comment by yigitfindikli** [comment] 2021-11-30 08:41
Duplicate of https://github.com/primefaces/primeng/issues/10630

**Closed by yigitfindikli** 2021-11-30 08:41 UTC
