### ISSUE TITLE
AutoFocus for Dropdown: Does not work inside dialogComponent.

### ISSUE THREAD

**Issue by ravikumar1243** [primefaces/primeng#14010] opened 2023-11-03 05:57 UTC
### Describe the bug

If AutoFocus is used for Dropdown inside a dialog, focus is not applied to the element.

For Text Box AutoFocus is working fine.
If Dropdown is not in dialog - AutoFocus is working fine.

### Environment

Any Environment.

### Angular version

16.2.11

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.9.3

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Add p-dropdown inside p-dialog
2. Set [autofocus]=true to p-dropdown
3. Focus is not on dropdown.

### Expected behavior

Focus should be on p-dropdown

**Comment by cetincakiroglu** [comment] 2023-11-03 06:08
The autofocus [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) is a Boolean attribute indicating that an element should be focused on page load, or when the [<dialog>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) that it is part of is displayed.

That's why it doesn't work with dialog. It's not a bug you can find a workaround by timeout and focus manually on the dropdown when the dialog opened.

Closing the issue since it's not a bug or defect.

**Comment by ravikumar1243** [comment] 2023-11-03 14:46
> The autofocus is a Boolean attribute indicating that an element should be focused on page load. That's why it doesn't work with dialog. It's not a bug, you can find a workaround by timeout and focus manually on the dropdown when the dialog opens.
> 
> Closing the issue since it's not a bug or defect.

Hi,

I tried all the ways including timeout and set the focus manually. It is not working.

As I explained before - autofocus is working fine for textbox inside p-dialog.

Here is the stackblitz url: https://stackblitz.com/edit/primeng-dialog-demo-14g5tl?file=src%2Fapp%2Fapp.component.html 

Thanks in advance.

**Comment by ChristianCodeCamp** [comment] 2024-03-01 09:27
Also doesn't work for us, it does work if you put in a random input with autofocus.

**Closed** 2024-04-18 09:37 UTC
Labels: Type: Bug
