### ISSUE TITLE
Table: scrollHeight flex doesn't work in Firefox

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9060] opened 2020-07-21 13:57 UTC
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablescroll-demo (official example)

**Current behavior**

If the button "View" in the section "Flexible Viewport" gets clicked, a dialog opens. The table inside the dialog has the scrollHeight=flex and gets shown correctly in Chrome and Edge, but not in Firefox. Here the header is scrolling too. 

**Expected behavior**

Only the table body should get scrolled in Firefox.

**Comment by DotNet-appseite** [comment] 2020-09-03 18:03
you can use this workaround till it got fixed.
`
:host ::ng-deep {

   .p-datatable-scrollable-wrapper, .p-datatable-scrollable-view {
    overflow-y: auto;
  }
}
`

**Comment by yigitfindikli** [comment] 2020-11-23 14:43
duplicate of https://github.com/primefaces/primeng/issues/8986

**Closed by yigitfindikli** 2020-11-23 14:43 UTC
