### ISSUE TITLE
Table text is getting selected when resizing the new table in IE11

### ISSUE THREAD

**Issue by krishna217** [primefaces/primeng#5593] opened 2018-04-20 04:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/table/colresize. Open this link IE11

**Current behavior**

When trying to resize the table columns in IE11 all the text in the table is getting selected.
Also borders are also not visible in IE11

**Expected behavior**
Table text should not be selected when trying to resize the table columns. Also borders should be visible.

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/#/table/colresize. Open this link IE11

**What is the motivation / use case for changing the behavior?**
Table behavior should be consistent across the browsers.

**Please tell us about your environment:**
Windows 7

* **Angular version:** 5.2.7

* **PrimeNG version:** 5.2.4

* **Browser:** IE11
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   8.9.1

**Comment by Dragsaw** [comment] 2018-05-04 09:07
Duplicate of #5446

**Closed** 2018-05-04 13:04 UTC
