### ISSUE TITLE
datatable multiselect with shift

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#3234] opened 2017-06-28 13:29 UTC
[X] bug report => Search github for a similar issue or PR before submitting

https://www.primefaces.org/primeng/#/datatable/selection

i can mult select with ctrl () but not with shift (to select all entries between my first und last selection).

Regards
Patrick

**Comment by cagataycivici** [comment] 2017-06-28 15:04
Duplicate of #1283

**Closed by cagataycivici** 2017-06-28 15:04 UTC
