### ISSUE TITLE
Add template support for dropdown label

### ISSUE THREAD

**Issue by washingtonphp** [primefaces/primeng#3803] opened 2017-08-31 19:50 UTC
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
Currently, we have the option to customize the dropdown items, but no way to customize the dropdown label.

**Expected behavior**
Please add template support fot label, that way i cam use something like this (note **label** usage in pTemplate)

```
<p-dropdown [options]="cars" [(ngModel)]="selectedCar">
    <ng-template let-car pTemplate="label">
        <div class="ui-helper-clearfix" style="position: relative;height: 25px;">
            <img src="assets/showcase/images/demo/car/{{car.label}}.gif" style="width:24px;position:absolute;top:1px;left:5px"/>
            <div style="font-size:14px;float:right;margin-top:4px">{{car.label}}</div>
        </div>
    </ng-template>
</p-dropdown>
```

**What is the motivation / use case for changing the behavior?**
Even in the primeng documentation for dropdown, the customized one doesn't display the label when selected.

* **PrimeNG version:** 4.1.3

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment] 2017-10-20 07:58
Duplicate of https://github.com/primefaces/primeng/issues/3742

**Closed by cagataycivici** 2017-10-20 07:58 UTC
