### ISSUE TITLE
PrimeNG filter - parent node is getting selected after clearing filter when only one child node is selected

### ISSUE THREAD

**Issue by rthota90** [primefaces/primeng#11925] opened 2022-09-13 05:58 UTC
### Describe the bug

Parent node is getting selected after clearing filter

step 1: search for exact value using filter inbox then select a value. By doing this search value and node will get selected.
step 2: clearing filter text , after this it still shows parent node selected  even though there are other values which are not selected yet. 

example which is available in PrimeNG - http://primefaces.org/primeng/treeselect

### Environment

[PrimeNg.docx](https://github.com/primefaces/primeng/files/9553912/PrimeNg.docx)

I am sharing an example from PrimeNg site, even I have same issue in my application there I am using angular 8 and 
primeNG -  "primeng": "^9.1.0",

### Angular version

8

### PrimeNG version

9.1.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Edge

### Steps to reproduce the behavior

attached document to reproduce. 
[PrimeNg.docx](https://github.com/primefaces/primeng/files/9553931/PrimeNg.docx)

### Expected behavior

after clearing filter it should select parent node until all child nodes are selected.

**Comment by cetincakiroglu** [comment] 2022-09-15 09:03
Hi,

Good catch, thanks for reporting!

**Comment by cetincakiroglu** [comment] 2022-11-08 09:38
Hi,

Closing the issue since it is a duplicate of https://github.com/primefaces/primeng/issues/11815 

Thanks for reporting the issue!

**Closed by cetincakiroglu** 2022-11-08 09:38 UTC
Labels: duplicate
