### ISSUE TITLE
Bug: The scrollable functionality is broken in 4.1.0 and 4.1.1

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#3454] opened 2017-07-19 15:24 UTC
The scrollable functionality is broken in 4.1.0 and 4.1.1
Was working upto 4.1.0-rc.2    
Code snippet:
<p-dataTable #dt [value]="rowData" reorderableColumns="true" [globalFilter]="gb" [contextMenu]="cm" selectionMode="single" exportFilename="models"
                 [(selection)]="modelAdded" (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)"
                 scrollable="true" scrollHeight="700px">

**Comment by ctrl-brk** [comment] 2017-07-19 15:44
What do you mean "broken"? Works for me.

**Comment by kcsahoo** [comment] 2017-07-19 16:18
The datarow columns do not align with header row column headings.
The widths are different.

**Comment by ctrl-brk** [comment] 2017-07-19 18:13
Do you have any hidden columns? There's an issue with them.

**Comment by kcsahoo** [comment] 2017-07-20 05:35
Yes , Id column 
There is was a related defect listed in 4.1.1 but it did not appear in released version.

**Comment by kcsahoo** [comment] 2017-07-20 08:50
I tested commenting out the hidden column.
But still the problem exists.
It works fine with version 4.1.0-rc.2 and I am stuck with this.
rc.3 broke multi-selection with checkboxes which has been fixed in 4.1.0

**Comment by kcsahoo** [comment] 2017-07-20 08:56
I am using width in columns like

<p-dataTable #dt [value]="rowData" reorderableColumns="true" [globalFilter]="gb" [contextMenu]="cm" selectionMode="single" exportFilename="models"
                 [(selection)]="modelAdded" (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)"
                 scrollable="true" scrollHeight="700px">
        
        <p-footer>To select options for a model, right click anywhere on the desired row to get the context menu and click the desired option.</p-footer>
        <p-column [style]="{'width':'2%'}" selectionMode="single"></p-column>
        <p-column field="id" header="Model Id" hidden="hidden"></p-column>
        <p-column field="projectCode" header="Project Code" [sortable]="true" [style]="{'width':'18%'}"></p-column>
        <p-column field="name" header="Name" [sortable]="true" [style]="{'width':'25%'}"></p-column>
        <p-column field="configuratorName" header="Conf. Name" [sortable]="true" [style]="{'width':'25%'}"></p-column>
        <p-column field="modelCode" header="Model Code" [sortable]="true" [style]="{'width':'8%'}"></p-column>
        <p-column field="bodyType" header="Body Type" [sortable]="true" [style]="{'width':'8%'}"></p-column>
        <p-column field="bodyTypeCode" header="Body Type Code" [sortable]="true" [style]="{'width':'8%'}"></p-column>
        <p-column field="isActive" header="Is Active?" [sortable]="true" [style]="{'width':'6%'}">
            <ng-template let-model="rowData" pTemplate="body">
                <p-checkbox name="isActive" value="model.isActive" [(ngModel)]="model.isActive" label="" binary="true" disabled="true"></p-checkbox>
            </ng-template>
        </p-column>
    </p-dataTable>

**Comment by kcsahoo** [comment] 2017-07-21 13:17
Identified exact issue.
If I display the hidden column, the alignment is correct.
Issue #3471 is same.

**Comment by cagataycivici** [comment] 2017-08-23 08:58
Duplicate of 3471

**Closed by cagataycivici** 2017-08-23 08:58 UTC
