### ISSUE TITLE
Dialog positioning improvement

### ISSUE THREAD

**Issue by maplion** [primefaces/primeng#2795] opened 2017-05-16 16:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
OR
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

Note: I will potentially add a demo later; do not have time at the moment.

**Current behavior**

I have a responsive dialog that loads content dynamically and the same component is reused for many different viewings (accessed from buttons on a data table). It loads the first time, centered from its top left corner to bottom right, receives its data asynchronously, and then is off center. It remembers where it was and the data it had prior, so if I view another set of data, it is properly centered horizontally, but depending on what data it got back previously, it changes its position vertically. The result is a dialog that moves all over the place depending on what content was loaded previously.

Is there a way to center the dialog after the content loads?

Current workaround is to set the dialog with a static width and height, making it not responsive.

**Expected behavior**

Either center after content is loaded or be able to control / set the dialog to center after it has loaded.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Viewing data based on table rows (pop-up dialogs triggered from a button within the row of the data grid).

**Please tell us about your environment:**

Windows 10, Visual Studio Code, NPM

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0-rc3

* **Browser:** [Chrome XX | Firefox XX | IE XX ]

 
* **Language:** [all | TypeScript 2.3.2 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by dhniels** [comment] 2017-05-23 19:27
I'm having this same problem as well.

**Comment by huineng** [comment] 2017-05-29 09:26
i solved this by adding a little time out , this gave some time to do the dimension recalculation 

```
 setTimeout(() => {
                this.dialog.showDialog = true;
            }, 0);
```

**Comment by stephanecot** [comment] 2017-05-29 09:30
I can't do that in my case, because it's an action in the dialog.

**Comment by SIlver--** [comment] 2017-05-30 14:05
Having the same issue. When I change the width and height attributes with the dialog open, it does not recenter.

**Comment by saximoer3** [comment] 2017-06-09 09:02
i solved this by using 2 ways, but i think there should be better ways.
1.  wait until the data of content loaded, then 
                       setTimeout(() =>{
                            this.display = true;
                        },10);

2.  i give the dialog a static position after it show.

HTML:    <p-dialog [(visible)]="display" (onShow)="onShow()"> (i put i on the top)

TS:                 
               import {ElementRef} from '@angular/core';

               constructor(private el: ElementRef,) { }

               onShow() {
                        setTimeout(() =>{
                                this.el.nativeElement.children[1].childNodes[0].style.left = '200px';
                                this.el.nativeElement.children[1].childNodes[0].style.top = '20px';
                         },10);
                }

**Comment by dhniels** [comment] 2017-06-21 23:26
id like to see a more ideal, built-in solution to this from the PrimeNG team. Loading dynamic content in a dialog seems like a pretty common use case.

**Comment by dhniels** [comment] 2017-06-21 23:29
@saximoer3 , i like your 3rd solution but couldnt get it to work. my dialog is still cutting off at the bottom of the window. could you provide a plunker example?

**Comment by cagataycivici** [comment] 2017-06-23 08:22
I'll add alwaysCenter property to center it ngAfterViewChecked. So when something changes, after dom is ready, we'll recenter. Should solve it, hopefully without side effects, default value will be false though.

**Comment by saximoer3** [comment] 2017-06-23 12:56
@dhniels 
i couldnt get it to work too. i use the 2nd way now. When loading dynamic content, it should wait until well done.  so i remove it.

**Comment by dhniels** [comment] 2017-06-23 15:03
@cagataycivici thank you so much! i know many people will be happy about this new feature!

**Comment by negberts** [comment] 2017-06-24 10:01
I am using setTimeout(this.dialog.center.bind(this.dialog), 0); in the complete part of the HTTP observable. It centers nicely then.

**Comment by cagataycivici** [comment] 2017-06-29 12:43
Ok now Dialog centers itself after its content is ready, I've also realized that this fixes some positioning issues in the demos like DataGrid demo where content is dynamic.

**Comment by dhniels** [comment] 2017-06-29 15:33
Awesome! Do we need to update the PrimeNG version or set an attribute or does it just work by default now?

**Comment by cagataycivici** [comment] 2017-06-29 16:57
Should work just bu default after 4.1.RC3 (tomorrow)

**Comment by bakasmarius** [comment] 2017-08-04 13:31
Still does not seem to work in 4.1.2.
Anyone else still having the same problems, or is it just me?

**Comment by ivanhosgood** [comment] 2017-08-29 00:09
I can confirm that this still does not work on 4.1.2.
Timeout is useful for a static dialog but in my scenario the dimensions change depending on the quantity of data which changes over time. Currently hiding and re-displaying the dialog helps but this  hack results in flickering

**Comment by jacqueslareau** [comment] 2017-10-16 20:41
I think this issue needs to be reopened. Dimensions almost always changes with async data. @cagataycivici

**Comment by dhniels** [comment] 2017-11-11 00:40
@jacqueslareau agreed. all my dialogs are loaded dynamically and this responsive setting thats been added just simply doesnt work.

**Comment by nikolatzotchev** [comment] 2017-11-13 20:55
+1

**Comment by rickymodalku** [comment] 2017-11-21 06:43
+1

**Comment by lasimone** [comment] 2017-11-21 14:10
+1

**Comment by vertexportus** [comment] 2017-12-12 19:42
+1

**Comment by bakasmarius** [comment] 2017-12-26 20:23
@cagataycivici may we know your thoughts about this?

**Comment by rich4756** [comment] 2018-02-06 22:48
Can we please reopen this?

**Comment by dhniels** [comment] 2018-02-07 00:10
@rich4756 9 months since this issue was opened, i think its safe to say @cagataycivici and the PrimeNG team are ignoring this.

**Comment by dhniels** [comment] 2018-02-07 00:12
I was working on a new dialog today and have run into this issue again. It's truly shocking this is still an issue 9 months later and that this was even closed in the first place.

**Comment by noamichael** [comment] 2018-02-13 15:01
I agree with @dhniels . Can we get an ETA?

**Comment by cagataycivici** [comment] 2018-02-13 18:36
Reopened due to community request, will be reviewed for 5.2.1. Regarding issue tracker in general, we are doing everything we can, we've reviewed/resolved 3788 issues so far and there are 533 open where most of them are feature requests. PRs will definitely help in general, let's improve it together.

**Comment by thenninger** [comment] 2018-03-01 21:20
Was this suppose to be added to 5.2.1? It's still closed - sorry just confused. I'm experiencing centering issues with the confirm dialog as well.

**Comment by cagataycivici** [comment] 2018-03-02 18:00
I forgot to reopen after my previous comment.

**Comment by cagataycivici** [comment] 2018-03-04 18:30
My test is this;

```xml
<p-dialog header="Godfather I" [(visible)]="display" modal="modal" [responsive]="true" [width]="300" [minWidth]="200">
           <p>Unrelated content.</p>
           <p *ngIf="displayDynamic" style="height:100px">
               Dynamic Content
           </p>
           <ul>
               <li *ngFor="let item of items">{{item}}</li>
           </ul>
           <p-footer>
                <button type="button" pButton icon="fa-search" (click)="displayDynamic = !displayDynamic" label="Toggle"></button>
                <button type="button" pButton icon="fa-check" (click)="add()" label="Add"></button>
           </p-footer>
    </p-dialog>
```

So one button toggles the visibility of a p element with 100px height and other ones adds items to the list displayed by the list. These two buttons are used to change the content of the dialog dynamically.

I've seen the issue where the dialog position stays same in this case and can think of a way to take this.

If at **ngAfterViewChecked** callback of dialog.ts itself, we call positionOverlay() function, then after the change detection runs and view is updated, dialog realigns itself. My concern here is that this function is called many many times by Angular so we need to do this if dialog is visible. If it is hidden then it is positioned already after it gets shown so both cases are covered.

I've committed the change, please test it with 5.2.1 due March 7th and drop a comment here about the results. The change fixes the issues of my test case and hopefully yours.

**Comment by dhniels** [comment] 2018-03-07 23:31
Just installed 5.2.1 and from a quick test it appears to be working! hooray!

**Comment by negberts** [comment] 2018-03-08 09:15
I'm getting seasick now...  See attachment.. (https://github.com/primefaces/primeng/files/1792475/ice_video_20180308-101247.zip)

**Comment by dhniels** [comment] 2018-03-08 21:10
@negberts mine is doing this as well in one place when i open a dropdown. it starts twitching up and down like that.

here is @negberts video but in gif format for convenience of viewing it directly on here:

![ice_video_20180308-101247](https://user-images.githubusercontent.com/7034022/37176737-7ee49f16-22da-11e8-9462-9832a3156701.gif)

**Comment by dhniels** [comment] 2018-03-09 20:33
Heres another example: (dont know if it matters but the dropdown uses append to body)

![mar-09-2018 13-31-07](https://user-images.githubusercontent.com/7034022/37228556-4a85129a-239e-11e8-9db9-b40ce0aa6ca0.gif)

**Comment by cagataycivici** [comment] 2018-03-09 20:59
Is this on 5.2.2? It seems we should avoid reposition when content does not change. Will check it now.

**Comment by dhniels** [comment] 2018-03-09 21:06
@cagataycivici yes, 5.2.2

**Comment by cagataycivici** [comment] 2018-03-09 21:06
Reopening

**Comment by cagataycivici** [comment] 2018-03-09 21:28
I don't have solution for the side effects of the repositioning after afterViewChecked, new idea was to check the height at on show and at afterViewChecked, check to see if height is different means the content has changed dynamically, if so then reposition;

```
        else if(this.visible) {
            this.zone.runOutsideAngular(() => {
                setTimeout(() => {
                    let height = this.domHandler.getOuterHeight(this.containerViewChild.nativeElement);

                    if(height !== this.currentHeight) {
                        this.currentHeight = height;
                        this.positionOverlay();
                    }
                }, 100);
            });
        }
```

It fails without setTimeout as Angular's ngAfterViewChecked is somewhat broken, it gets invoked before the dom update is finished so I can't check the new height without it, ngZone is there to avoid recursive calls, since setTimeout will call ngAfterViewChecked again.

This is the only potential solution to reposition.

Another workaround is fixing the content section;

```
<p-dialog [contentStyle]="{'max-height': '400px'}"
```

So that dynamically changed content does not change the coordinates of the dialog, a scrollbar will display for longer content.

Wdyt?

Maybe we can do the automatic positioning a property like autoAlign="true|false"?

**Comment by dhniels** [comment] 2018-03-09 21:45
I dont mind the idea of fixing the height of the content section, although it doesnt seem to work with vh or percent units. i use a max-height currently in vh in all our modals to allow overflow but allowing it to grow responsively with the screen size.

are there any downsides to the first solution that you can see? it appears that the dialog currently recenters when i click. im wondering why the dropdown is causing this however, if it is appended to the body? shouldnt the dialog only consider the content inside of `.ui-dialog-body`?

i wonder if adding a property is necessary with dynamic content. would you ever want the dialog to have the ability to grow beyond the viewport and NOT center? that seems odd to desire that behavior. seems to me that it should be the default behavior, not attached to a property...

**Closed** 2018-03-09 21:57 UTC
Labels: enhancement

**Comment by cagataycivici** [comment] 2018-03-09 22:01
Ok, I've changed the auto align behavior to check the height instead. It is on by default but can be turned off with [autoAlign]="false". Also added a doc and released 5.2.3.

**Comment by dhniels** [comment] 2018-03-09 22:03
Good idea. i think that will work.

**Comment by cagataycivici** [comment] 2018-03-09 22:07
5.2.3 is released now.

**Comment by dhniels** [comment] 2018-03-09 22:23
youre the man @cagataycivici ! i think that worked. Specifically test vh units - a case where if the top value is being calculated on subpixels, ex. between 38.5px and 39px. Im worried it might cause that issue where it "twitches" back and forth between the whole and half pixel. im wondering if thats whast causing @negberts issue....

**Comment by Treynis** [comment] 2018-03-09 22:32
With [autoAlign] = "false" problem with shaking inside of a dialog is gone. Thanks!

**Comment by cagataycivici** [comment] 2018-03-10 10:38
Thank you, since it is stable now I can add maximize minimize like PrimeFaces has😉

https://www.primefaces.org/showcase/ui/overlay/dialog/minMax.xhtml

**Comment by negberts** [comment] 2018-03-11 10:42
Works like a charm!

**Comment by jonbarthol** [comment] 2018-04-05 20:35
Thanks. It's nice to have a workaround. However, it's unfortunate that you have to set [autoAlign]="false" as @Treynis stated above. Doing this does not allow the dialog to recenter itself after the height is dynamically changed.

There is an "off by one pixel" problem with either Angular or the browser that causes the height of the containerViewChild to vary by one pixel every time ngAfterViewChecked is called. This only seems to be a problem when the viewport height is an odd number of pixels. @cagataycivici what do you think of changing the "if" condition in ngAfterViewChecked from: 

if(height !== this.currentHeight)

to:

if(height < this.currentHeight - 1 || height > this.currentHeight + 1)

This would resolve the "off by one pixel" problem. Thanks.
