### ISSUE TITLE
DataTable still propagating endless onLazyLoad events - previous case #1434

### ISSUE THREAD

**Issue by davisruk** [primefaces/primeng#1502] opened 2016-12-05 23:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN

**Current behavior**

Same as #1434 which was marked as fixed for 1.0.1. A Datatable with lazyLoad=true and a filter with a value propagates endless onLazyLoad events when the Datatable's underlying data array is altered e.g. items added or removed. The problem is in the ngDoCheck function where the lazyLoad check still calls the filter function:
`            if (this.hasFilter()) {
                if (this.lazy) {
                    //prevent loop
                    if (this.stopFilterPropagation)
                        this.stopFilterPropagation = false;
                    else
                        this.filter();
                }
                else {
                    this.filter();
                }
`
**Expected behavior**

The component should create one onLazyLoad event. Removing the call to this.filter within the lazyLoad check fixes the problem.
`            if (this.hasFilter()) {
                if (this.lazy) {
                    //prevent loop
                    if (this.stopFilterPropagation)
                        this.stopFilterPropagation = false;
                    //else
                        //this.filter();
                }
                else {
                    this.filter();
                }
`
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

See previous case (#1434)
**Please tell us about your environment:**

See previous case (#1434)
* **Angular version:** 2.0.X

See previous case (#1434)
* **PrimeNG version:** 2.0.X

1.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 See previous case (#1434)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
See previous case (#1434)
* **Node (for AoT issues):** `node --version` =   
See previous case (#1434)

**Comment by no0dles** [comment] 2016-12-15 10:57
same issue here, lazy loading and filters are enabled. 

Without a filter value everything works fine, but after setting a filter value it loads the filtered content once and as soon as you try to navigate to the second page the loop begins. It also resets the "first" value to 0.

**Comment by crimpphantom** [comment] 2016-12-21 14:19
I have add an example for this issue: http://plnkr.co/edit/3643a4

**Comment by cagataycivici** [comment] 2017-01-11 17:54
Fix checked in.

**Closed** 2017-01-11 17:54 UTC
Labels: defect

**Comment by shajeeck** [comment] 2017-04-10 17:15
Filter on primeng datatable with lazy load is looping the lazyload! Any help?

primeng - 4.0.0 RC 2
Angular - 4.0.0

**Comment by shalaby** [comment] 2017-04-17 12:20
@cagataycivici same here as @shajeeck

**Comment by shalaby** [comment] 2017-04-18 09:02
but when enabling immutable mode on the table the problem is solved :) #2044

**Comment by michelebroggi** [comment] 2017-05-10 13:37
With [immutable]="true" property the event it's called twice.
Please fix this issue.

Thanks

**Comment by cagataycivici** [comment] 2017-05-12 08:25
[immutable] is removed in 4.0, please see the blog post for details.

https://www.primefaces.org/primeng-4-0-final-released-morpheus/
