### ISSUE TITLE
Problem using p-dropdown in modal - List  show in other page

### ISSUE THREAD

**Issue by gzayat** [primefaces/primeng#10612] opened 2021-09-12 16:58 UTC
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

![erro](https://user-images.githubusercontent.com/35319782/132996176-613d887d-c78d-4347-9296-8944245ac692.png)

**Current behavior**
The p-dropdown component list when used in dropdown menu ie MODAL, it does not load on another page or on the back page.

**Expected behavior**
The list should load where the modal is opening

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
When using the p-dropdown in modal it loads on another page, this does not happen in primeng 12.0.2 version<

**Please tell us about your environment:**
* **Angular version:** 12.1.X

* **PrimeNG version:** 12.1.X

* **Browser:** [Chrome  93.0.4577.63]
 
* **Language:** [ES6 | ES5]

* **Node (for AoT issues):** `node --version` =   14.7

**Comment by slamj1** [comment] 2021-10-03 00:21
I can confirm this bug within a Bootstrap modal (v4), introduced in 12.1.x and still exits in 12.2.0. The rewrite of the overlay service in 12.1 may have something to do with it.

@gzayat, if you want to continue to use 12.1.x / 12.2.0, a quick fix for this is as follows:

1) Add a div tag with a template reference variable just below your p-dropdown and add an [appendTo]="pDropDown" to your control. Example:

```
<div class="col-md-12">
    <div class="form-group">
         <label for="selectedSupportOption">Support Type </label><br />
              <p-dropdown [panelStyle]="{'top':'1px', 'left':'1px'}" [appendTo]="pDropDown" [options]="supportOptions" [(ngModel)]="selectedSupportOption" [style]="{'width':'100%', 'font-size':'16px'}" id="supportOptionsDropdown" name="supportOptionsDropdown"></p-dropdown>
              <div #pDropDown id="pDropDown"></div>
     </div>
</div>
```

2) Now, create a style file for your component and add the following:

```
:host ::ng-deep #pDropDown > div.ng-trigger-overlayAnimation {
    top: unset !important;
    left: unset !important;
}
```
This is just a temporary fix, pending them addressing this in the library.

Cheers,
@slamj1

**Comment by waratah** [comment] 2022-01-10 22:15
In my case I had to add 'body' to all my dropdowns because the whole screen moved to the right when a dropdown was opened.  so it definitely is not the default.   I also had to tweak the pagination drop down to append to body.

Is this the case you are talking about?

**Comment by mertsincan** [comment] 2022-11-09 20:23
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:23 UTC
