### ISSUE TITLE
DataTable fields filter: possibility to add custom filter field

### ISSUE THREAD

**Issue by vadimzham** [primefaces/primeng#1448] opened 2016-11-29 10:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

DataTables now have good feature - possibility to define custom element of global filter. Would be good if column filters will have feature to define custom element, like in global filter.
I think, best way will be through adding `filterElement` attribute.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Sometimes developer need to customize filter of any columns. Also sometimes developer needs to use dedicated search window. That feature will allow to use it.

**Comment by cagataycivici** [comment] 2016-11-29 19:44
Duplicate of #196

**Closed by cagataycivici** 2016-11-29 19:44 UTC
