### ISSUE TITLE
Timepicker dropdown of a p-calendar component visibility bug.

### ISSUE THREAD

**Issue by AchilleasAchilleopoulos** [primefaces/primeng#7456] opened 2019-03-27 14:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Timepicker dropdown fails to appear on modal p-dialog revisit, but seems to exist and provide functionality.

**Expected behavior**
Timepicker dropdown appears normally, every time I reopen the modal p-dialog.

**Minimal reproduction of the problem with instructions**
Clicking on a button brings up a modal p-dialog component. On that component, there are two p-calendar components with the [timeOnly] property set to true. Clicking on the calendar input box brings up the timepicker dropdown, as normal. Now, provided that I don't click anywhere else (e.g. the timepicker dropdown is still there) and exit the modal dialog (by clicking on the x at the top right corner), every time I reopen the dialog, the timepicker dropdown that was previously open becomes invisible, but still able to modify the input value (I can still find where the buttons were supposed to be by looking at the cursor changes and change the values). However, if I navigate back and forth the two calendar components using Tab (and Shift+Tab respectively), the dropdowns reappear as normal.

**Environment:**
Windows 8.1 Enterprise, Visual Studio Code 1.28.1, NPM 5.6.0

* **Angular version:** 6.1.10

* **PrimeNG version:** ^6.1.4

* **Browser:** Chrome 73.0 | Firefox 66.0 | Opera 58.0
 
* **Language:** TypeScript 2.7.2

**Comment by JacobSiegle** [comment] 2019-04-01 14:05
This is a duplicate of example PR https://github.com/primefaces/primeng/pull/7468 which links to issue https://github.com/primefaces/primeng/issues/6921.

**Comment by AchilleasAchilleopoulos** [comment] 2019-04-02 14:42
It seems like it, thank you for your time. And now, we wait...

**Comment by Bischof-sum** [comment] 2019-08-08 09:08
This also happens when adding additional timepickers to the footer of a p-calendar component. 
I created an example to show this behavior: https://stackblitz.com/edit/github-jxmrqa
Is there any kind of workaround for this bug?

**Comment by cagataycivici** [comment] 2020-03-20 15:47
Duplicate of 6921

**Closed by cagataycivici** 2020-03-20 15:47 UTC
