### ISSUE TITLE
InputNumber suffix block entering fraction digits in field

### ISSUE THREAD

**Issue by bartez** [primefaces/primeng#14769] opened 2024-02-08 20:00 UTC
### Describe the bug

When I provide suffix for input number with mode=decimal then I cannot provide fraction digits. After enter dot and provide fraction digit the field will cleared. 

`    <p-inputNumber suffix="Mg" mode="decimal" [maxFractionDigits]="5">
`

But when I set **minFractionDigits** more than 0 then problem is gone.

`  <p-inputNumber suffix="Mg" mode="decimal" [minFractionDigits]="2" [maxFractionDigits]="5">
`

### Environment

Error repeated regardless of environment settings. Also repeats on sample code in documentation

### Reproducer

https://stackblitz.com/edit/gv83do?file=src%2Fapp%2Fdemo%2Finput-number-numerals-demo.html

### Angular version

17.0.9

### PrimeNG version

17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

1. Try enter value with fraction digits eg. 1.234 in field is 
2. After enter dot and number will clear form value.

The sample video describing steps:
https://github.com/primefaces/primeng/assets/1591522/8fa99b46-ca8d-4a09-af2d-14550c9b1737

### Expected behavior

Values after the decimal point should be able to be entered.

**Comment by erber014** [comment] 2024-02-13 13:08
Hi, I can confirm I have the same issue. There is an issue when mode="currency" also as the currency mode uses prefixes/suffixes
https://github.com/primefaces/primeng/issues/14227

**Comment by ldesgrange** [comment] 2024-06-21 13:23
This seems to be a recurrent breakage:
- same issue existed ans was fixed in v12: https://github.com/primefaces/primeng/issues/9275
- and again in v14: https://github.com/primefaces/primeng/issues/11630
And I confirm having the same issue in v17 too.

**Comment by KevinHetzelGFL** [comment] 2024-06-28 08:55
Same issue in 17.18.2

**Comment by tarockx** [comment] 2024-09-03 08:43
Using v17.18.9 and I can confirm the issue is still present: if minFractionDigits is set to 0 and you use a suffix typing the number correctly is almost impossible, the cursor starts jumping around or not responding at all.

**Comment by mertsincan** [comment] 2024-12-25 13:19
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Closed by mertsincan** 2024-12-25 13:19 UTC
Labels: Status: Needs Triage
