### ISSUE TITLE
Calendar - when using monthNavigator/yearNavigator and binding a date - current month/year is based on today vs. the bound date

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#6261] opened 2018-08-07 18:15 UTC
Latest version 6.1.0

I have a control, ie.

```
<p-calendar showButtonBar="true" [required]="true" [showIcon]="true" [showOnFocus]="false" formControlName="termStartDate" [monthNavigator]="true" [yearNavigator]="true" [yearRange]="getYearRange()"></p-calendar>
```

When I use [monthNavigator]="true" [yearNavigator]="true"  and bound a date - let's say today is August 2018 but the formControlName value is December 2017.

When opening the calendar, the date is in the dropdown is 'August'  '2018' instead of 'December 2017'

If I remove the [monthNavigator]="true" [yearNavigator]="true"  then it functions correctly.

**Comment by oliverfrost** [comment] 2018-08-08 11:34
Duplicate of: [6209](https://github.com/primefaces/primeng/issues/6209)

**Comment by cagataycivici** [comment] 2018-08-12 07:43
Duplicate

**Comment by billysvensson** [comment] 2018-08-12 17:09
If you close this one, then please open #6209. This issue is not resolved.

**Comment by cagataycivici** [comment] 2018-08-14 11:15
Replicated

**Closed** 2018-08-14 11:36 UTC
Labels: defect

**Comment by OleksandrLazorenko** [comment] 2018-08-17 09:56
Does it work as intended? I've created https://stackblitz.com/edit/angular-ffnp7w with version 6.1.2.
When i open calendar i see that dropdowns synced correctly, however see next problems:
1. when i change month - year jumps to current year
2. when i change year - month jumps to current month
3. navigation arrows use current date, not model that i've provided

**Comment by haripalpatil** [comment] 2019-07-04 17:47
> Does it work as intended? I've created https://stackblitz.com/edit/angular-ffnp7w with version 6.1.2.
> When i open calendar i see that dropdowns synced correctly, however see next problems:
> 
> 1. when i change month - year jumps to current year
> 2. when i change year - month jumps to current month
> 3. navigation arrows use current date, not model that i've provided

Did you get fix or workaround for this issue? Please let me know

**Comment by alanjsp** [comment] 2019-07-24 09:01
Try adding [defaultDate]="date" to your html. Provided, date will be the value same as that of ngModel

**Comment by alanjosephk** [comment] 2019-07-24 09:08
Try adding [defaultDate]="date" to your html. Provided, date will be the value same as that of ngModel

**Comment by ryan1509** [comment] 2019-12-08 11:03
@alanjosephk Thanks, this is working.
