### ISSUE TITLE
Checkbox multiselection doesn't work

### ISSUE THREAD

**Issue by dloprodu** [primefaces/primeng#3067] opened 2017-06-12 12:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Current behavior**
I'm using checkbox inside ngFor with reactive form. The goal is to have a list of languages selected (**languagesSelected**).

The problem is that the list always maintains the last selection

`
<template ngFor let-item [ngForOf]="languages">
    <div>
        <p-checkbox name="languages" 
                              [label]="item.desc"                                        
                              [value]="item.val"
                              formControlName="languagesSelected"
                              >
        </p-checkbox>
    </div>
</template>
`

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.1

* **PrimeNG version:** 4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by fibinger** [comment] 2017-06-15 12:29
I think it's a duplicate of #2906. We're all waiting for solving this issue.

**Comment by cagataycivici** [comment] 2017-06-23 11:28
Duplicate of #2906

**Closed by cagataycivici** 2017-06-23 11:28 UTC
