### ISSUE TITLE
MultiSelect and Dropdown with filter input, autoclose with keyboard

### ISSUE THREAD

**Issue by nev-21** [primefaces/primeng#10634] opened 2021-09-20 18:09 UTC
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
on android device, when a multiselect or dropdown is opened, the keyboard appear and the page scoll up, at the same time the dropdown hides. And it is necesary to open it again.

**Expected behavior**
The multiselect or dropdown with filter must be visible wherever it is opened, even if the page is scrolled up.

**Minimal reproduction of the problem with instructions**
create a page with vertical scrolling (loreipsum....) with many text paragraphs, and just put a multiselect or dropdown with filter at the bottom.
When open that page on android device, and open the multiselect while it is at the bottom, the keyboard appear, it is scrolled up, and then it hides.

**What is the motivation / use case for changing the behavior?**
Bad UX 

**Please tell us about your environment:**
Android

* **Angular version:** 5.X
Angular 12.1

* **PrimeNG version:** 5.X
Primeng 12.0.0

* **Browser:** [Chrome for android| FireFox for android | Opera mobile android]
 
Thank you so much

**Comment by nev-21** [comment] 2021-09-20 18:16
**Workaround**

The problem is in bindScrollListener method in the primeng-multiselect.js and primeng-dropdown.js files
It detects the scroll when the keyboard appears, and then hides the dropdown. 
There was an easy solution:

node_modules\primeng\esm2015\dropdown\dropdown.js
```js
   bindScrollListener() {
        if (!this.scrollHandler) {
            this.scrollHandler = new ConnectedOverlayScrollHandler(this.containerViewChild.nativeElement, () => {
                if (this.overlayVisible) {
                    // this.hide()    <------------ comment or erase this
                    this.onWindowResize(); //  <----------- this method doesn't hide the dropdown on android
                }
            });
        }
        this.scrollHandler.bindScrollListener();
    }            
```

Thanks for your help, I hope this code help to fix the bug

**Comment by mertsincan** [comment] 2022-05-30 14:04
Duplicate of [11567](https://github.com/primefaces/primeng/issues/11567)

**Closed by mertsincan** 2022-05-30 14:04 UTC

**Comment by MostafaGamal84** [comment] 2024-01-04 12:35
Great its work 
Thanks
