### ISSUE TITLE
changing the focus to options after pressing down arrow key in dropdown with filter

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#3146] opened 2017-06-19 15:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
 When filtering is done the user has to move away from the keyboard to click the final selection in the drop down control. 

**Expected behavior**
This is mostly usability case. When the user finished typing the filters in a dropdown it would be great to change the focus if the user pressed down arrow key to go over the remaining options and selecting the final option by arrow keys, if they wish. 

**What is the motivation / use case for changing the behavior?**
It would be a better user experience to not to have to move their hands from keyboards to click, but just use the arrow keys if desired after filtering is done.

**Comment by cagataycivici** [comment] 2017-06-23 12:07
Duplicate of #3135

**Closed by cagataycivici** 2017-06-23 12:07 UTC
