### ISSUE TITLE
beta-19 CalendarModule crashes when ngModel already has a value

### ISSUE THREAD

**Issue by supermafete** [primefaces/primeng#1093] opened 2016-10-21 11:02 UTC
Hi there. Angular 2.0.1 with ancular-cli project. PrimeNG-beta19.

Trying out the new native CalendarModule for beta 19 I found that when ngModel already has a date we got this:

component
```
export class UsersComponent extends CSBaseComponent implements OnInit {
  date: string = "10/10/2016"
...
```
template
`<p-calendar [(ngModel)]="date" [showIcon]="true"></p-calendar>`

error
> error_handler.js:45EXCEPTION: Error in ./Calendar class Calendar - inline template:38:58 caused by: this.value.getDate is not a function

If date is not initialized with a value, then the Module works well. Also happens when you modify the model assigning a date, for example, when you select a registry in your datatable that has a date on it and you want to assign that date to the calendar module.

**Comment by sslee** [comment] 2016-10-21 16:16
'date' need to be a Date object now, but there is an issue where preloaded values are not being displayed on the input line.

**Comment by supermafete** [comment] 2016-10-22 07:10
Switched to a Date object doesn't display the data neither. 

I saw your issue #1098. Did you refer to that one? I don't think the problem is the format. As you said, it won't display any initial data, no matter what format you choose.

**Comment by sslee** [comment] 2016-10-22 12:59
Yeah, you're right. I had accidentally switched back to beta17 somehow, that's why the date was displaying. A temporary fix for this is to use a view child and call the appropriate methods.

```
@ViewChild(Calendar) calendar:  Calendar;

ctrl: FormControl;

ngOnInit() {
    this.ctrl = <FormControl>this.form.get(this.ctrlKey);
}

ngAfterViewInit() {
    if (this.calendar && this.ctrl.value) {
        this.calendar.updateInputfield();
    }
}
```

**Comment by cagataycivici** [comment] 2016-10-23 08:45
Duplicate of 108.

**Closed by cagataycivici** 2016-10-23 08:45 UTC

**Comment by garthmason** [comment] 2016-10-28 05:49
I'm still seeing this issue in Beta 20.
I've switched to using a Date object, so don't get an error - but the initial data still won't display. 
Currently using the ViewChild workaround as described by @sslee

**Comment by supermafete** [comment] 2016-10-29 19:06
I suppose we have to wait for next updates. I was seeing #108 forum posts and this was supposed to be fixed in 0.8.0 :(

**Comment by openorganize** [comment] 2016-11-07 23:32
I'm seeing this issue in RC3.

**Comment by victorcarvalhosp** [comment] 2016-11-27 21:56
I'm having this issue yet...
