### ISSUE TITLE
Calendar: Component doesn't blur out after selecting date, and Clicking on input when calendar is open does not hit close event for the calendar.

### ISSUE THREAD

**Issue by arjun-cloudoffis** [primefaces/primeng#15858] opened 2024-06-18 11:13 UTC
### Describe the bug

Here I am facing 2 issues with primeng calendar.

1. On selecting a date from primeng calendar, the input will hit close event, but when user switch tabs back and forth the calendar would open again. 

https://github.com/primefaces/primeng/assets/117264483/8eade434-5c47-456c-94cc-7c94c1af99ff

2. On clicking the input of already opened calendar, it does not close the calendar.

https://github.com/primefaces/primeng/assets/117264483/7e2c6185-64f5-408a-b654-1f541deb9989

### Environment

Angular application with Primeng 17.12.0 and Angular version 17.0.8.

### Reproducer

https://stackblitz.com/edit/glwia5?file=package.json

### Angular version

17.0.8

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

 20.10.0

### Browser(s)

Chrome

**Comment by cetincakiroglu** [comment] 2024-07-04 09:13
Hi,

Thanks for reporting the issue, this is not a bug, it's made by design. Selection is not an action that results in blur. You need to take the focus out of the component to make it blurred, which is possible by clicking outside or focusing on another element in the document.

This is not a bug, it's intentional behavior. Closing the issue.

**Closed by cetincakiroglu** 2024-07-04 09:13 UTC
Labels: Status: Needs Triage
