### ISSUE TITLE
Custom filtering for DataTable

### ISSUE THREAD

**Issue by Wozbo** [primefaces/primeng#4003] opened 2017-09-20 20:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, the filter match mode seems to be a very small set of values that can be used.

**Expected behavior**
I'd like a method to specify a custom match mode based on a filter value and a row's column value so that I may implement custom filtering.

**Minimal reproduction of the problem with instructions**
Using a p-column as an example:

Html:
```
<p-column field="year" header="Year ({{yearFilter||'No Filter'}})" [filter]="true" filterMatchMode="custom" filterMatchMethod="CUSTOM_METHOD($event)">
```

TS:

```
CUSTOM_METHOD(event: any): boolean {
    // event.filter, event.value, event.global
    // logic goes here, true means the filter matches, false means it does not.
}
```

**What is the motivation / use case for changing the behavior?**
Using this, we could define custom matching logic that allows us to do things like date bounding or list matching for rows that have complex values.

EX:
1. Rows have a start and an end date.  Picking start date can filter rows that begin after a certain date.  Picking end date can filter rows that end after a certain date.
2. Row has an array of items being shown in one column (lets say 3 names).  Filter can show rows where any one of the names match.

The only thing that gets a bit hairy is when you are bounding like point one, which is why I think the event would have to pass in a global flag so that we can optionally always return true if the filter would not be optimal for a global search.

**Comment by cagataycivici** [comment] 2017-10-20 07:50
Duplicate of #3521

**Closed by cagataycivici** 2017-10-20 07:50 UTC
