### ISSUE TITLE
p-dropdown+templates: css class ui-dropdown-item-empty hides template content

### ISSUE THREAD

**Issue by alkismavridis** [primefaces/primeng#7406] opened 2019-03-19 15:19 UTC
I am not sure whether this is a bug or I do something wrong.
I use templates with p-dropdown. This means that I want to render something with **every** option entry that I provide, no matter if there is an explicit label property:

```
<p-dropdown
            [(ngModel)]="myValue"
            [options]="myOptions"
            [placeholder]="'GLOBALS.CHOOSELABEL' | translate">
            <ng-template let-item pTemplate="selectedItem"><div>{{item.label || 'No label for this option'}}</div></ng-template>
            <ng-template let-item pTemplate="item"><div>{{item.label || 'No label for this option'}}</div></ng-template>
          </p-dropdown>
```
The result is that I see the correct number of options, but a weird div with the css class "ui-dropdown-item-empty" hides my template content. The funny thing is that my template content is indeed rendered in the dom (I can see that with inspect element). It is just covered by this ui-dropdown-item-empty div, and thus is useless for the user.

I have spent hours trying to work around this very annoying problem. I just want my template to be **visible in all cases**, no mater what field my item contains, or does not contain. The only "solution" I have found is to globaly apply:
```
p-dropdown .ui-dropdown-item-empty {
  text-indent: 0 !important;
}
```
This makes the job done, but is obviously an ugly hack from my side.

Do I do something wrong or is this a bug?
Thanks is advance

**Comment by stephanie-dm** [comment] 2019-08-07 08:49
Duplicate of #6912

**Comment by cagataycivici** [comment] 2020-03-19 10:45
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Closed by cagataycivici** 2020-03-19 10:45 UTC
