### ISSUE TITLE
p-calendar in p-overlay not opening after couple of times (bootstrap theme)

### ISSUE THREAD

**Issue by mohanskumar** [primefaces/primeng#7458] opened 2019-03-27 14:50 UTC
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

P-Calendar which is in poverlay not opening up after couple of times 

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://angular6-primeng-8yc2jg.stackblitz.io/

**Current behavior**

click on the button to open overlay
set focus on the text box to open the calendar
set focus on the page for the calendar to close

repeat the above steps couple of times. now the calendar wont show up

**Expected behavior**

calendar should work (show up)
**Minimal reproduction of the problem with instructions**

click on the button to open overlay
set focus on the text box to open the calendar
set focus on the page for the calendar to close

repeat the above steps couple of times. now the calendar wont show up

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by JacobSiegle** [comment] 2019-04-01 13:49
This is a duplicate of #6921 which has an example PR #7468.

**Comment by cagataycivici** [comment] 2019-05-10 12:12
Duplicate

**Closed by cagataycivici** 2019-05-10 12:12 UTC
