### ISSUE TITLE
p-calendar add clear button

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#1777] opened 2017-01-10 15:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Please add a link/button inside the control for the user to clear/reset the value after selection. 
I saw that the issue came up in several places on the forum, but no solution...
Thanks!

**Comment by koesper** [comment] 2017-03-21 10:05
The wish for a 'clear' button was also expressed in #506

**Comment by jayordway** [comment] 2017-05-17 16:51
When is this clear button coming, 506 was closed. I still see no clear button.

**Comment by cagataycivici** [comment] 2017-06-19 11:16
Duplicate of #506

**Closed by cagataycivici** 2017-06-19 11:16 UTC
