### ISSUE TITLE
Table: Sorting doesn't work properly if the data source is a signal or observable

### ISSUE THREAD

**Issue by codrut1** [primefaces/primeng#14393] opened 2023-12-19 08:09 UTC
### Describe the bug

When using a table component and the source is an observable or a signal, the sorting does not work

### Environment

Windows 11

### Angular version

17.0.0

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Use a Table component
2. For the `[value]`, use a signal or observable

### Expected behavior

1. Sorting works as expected

**Comment by SaajRP** [comment] 2023-12-19 13:20
Maybe a similar issue to https://github.com/primefaces/primeng/issues/13517

**Comment by cetincakiroglu** [comment] 2023-12-26 07:06
I am closing the issue since a reproducer is not provided.

**Closed by cetincakiroglu** 2023-12-26 07:06 UTC
Labels: Resolution: Cannot Replicate, Resolution: Needs Revision
