### ISSUE TITLE
Component: Calendar MinDate Month is Disabled

### ISSUE THREAD

**Issue by erdenizayd** [primefaces/primeng#12437] opened 2022-12-30 07:00 UTC
### Describe the bug

If a minimum date is given, the month including the minimum date gets disabled too. Probably caused by a mistake in the isMonthDisabled function.

### Environment

Angular 14.2.8

### Angular version

14.2.8

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Give a minDate, say 30.12.2022

2. Select the year as 2022 

3. December is disabled

### Expected behavior

The month including the minimum date should be able to be selected, while days before the minimum date are disabled.

**Comment by cetincakiroglu** [comment] 2023-01-02 13:48
Hi,

This issue is duplicate of https://github.com/primefaces/primeng/issues/12330
Fixed in here https://github.com/primefaces/primeng/pull/12338

Closing the issue, thanks for your effort and support!

**Closed by cetincakiroglu** 2023-01-02 13:48 UTC
Labels: Status: Needs Triage
