### ISSUE TITLE
Table: VirtualScroll + Lazy loading doesn't load items when manually scrolling

### ISSUE THREAD

**Issue by john8329** [primefaces/primeng#12206] opened 2022-11-13 16:20 UTC
### Describe the bug

Using the Table with the aforementioned setup seems to work better than the previous release, but there's still major usability issues that prevent it to be used in production.

In particular, there's two issues:
• The old behavior that pre-emptively loaded content seems to be gone, so when scrolling even slowly, the rows disappear and show the loading body, then they appear again
• When scrolling to a random point with the scrollbar, the chunk sometimes isn't loaded. See the video for more details. Changing the number of loaded rows makes the problem more infrequent, but not solved.[](url)

https://user-images.githubusercontent.com/42315498/201532307-40c2967b-7f5e-4646-948e-6d85d45f59fa.mp4

### Environment

Angular 14, Primeng 14.2.1, see the stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-etlrhw?file=src/app/app.component.html

### Angular version

14.2.10

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

chrome

### Steps to reproduce the behavior

Use the official documentation to build the component with the demo data.

**Comment by mertsincan** [comment] 2022-11-13 20:21
Hi @john8329,

Could you please check a row's height in the browser inspector? I think its height is not 34px and this issue is not related to VirtualScroller. We've made some changes to Table with Scrollable on v14.2.0. 

Please try;
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-megxay?file=src%2Fapp%2Fapp.component.html

**Comment by john8329** [comment] 2022-11-16 13:55
Hi, the problem is perfect reproducible in your code as well, please try the steps that you see in the video, both issues are still there.

**Comment by john8329** [comment] 2022-11-29 16:26
Bumping: any news?

**Comment by john8329** [comment] 2022-12-21 13:08
@mertsincan can you please provide any update on this? I can't be the only one encountering the bug (see the previous issues I posted which gained more traction and were about the same setup), the table implementation seems broken for this use case.

Thanks

**Comment by ruppuluri** [comment] 2023-01-30 18:12
@john8329 Not sure if the issue still exists for you. Can you try adding [virtualScrollDelay]="0" to the p-table and verify if it helps your scenario?

**Comment by john8329** [comment] 2023-01-30 18:17
It does, to the point that I abandoned the table for my implementation. I've added that parameter in the example I created above, and it reproduced the issue immediately.

**Comment by infernet89** [comment] 2023-03-16 08:56
Any news about this issue? We really need a fix for that.

**Comment by cetincakiroglu** [comment] 2024-03-22 15:23
Hi,

Couldn't replicate the issue with latest version (17.12.0). Issue is probably fixed by another commit between mentioned version and the latest. Closing the issue since it doesn't exist anymore. Please open a new issue with a stackblitz reproducer if the issue persists.

Thanks for reporting!

**Closed by cetincakiroglu** 2024-03-22 15:23 UTC
Labels: Status: Pending Review
