### ISSUE TITLE
Table | column resized when the previous column is removed

### ISSUE THREAD

**Issue by maxcabourg** [primefaces/primeng#11237] opened 2022-02-25 10:50 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.
https://primeng-tablecoltoggle-demo-3zpa1p.stackblitz.io/

**Current behavior**
When the user resizes the N-th column and then removes it via column selection, the N+1th column (the one on the right) has its width updated.

**Expected behavior**
When the users resizes the N-th column and then removes it via column selection, the N + 1th column shouldn't be resized.

**Minimal reproduction of the problem with instructions**
On the stackblitz example, resize a column then remove it via column selection, the column on the right is resized

**What is the motivation / use case for changing the behavior?**
It affects the user experience.

**Please tell us about your environment:**
- Windows 10
- Visual Studio Code
- NPM

* **Angular version:** 13.2.2

* **PrimeNG version:** 13.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Node (for AoT issues):** `node --version` =   14.16.0

If I can help, the dynamic CSS rule is not removed after column removal so the new Nth column gets that flex property
![image](https://user-images.githubusercontent.com/15145146/155702449-877626c2-513e-4891-be86-4c4bf3d8c71d.png)

**Comment by maxcabourg** [comment] 2022-03-01 13:34
Hello,

This is the URL generated by Stackblitz.
Maybe with editor URL ? https://stackblitz.com/edit/primeng-tablecoltoggle-demo-3zpa1p?file=src/app/app.component.html

Regards.

**Comment by emamedov2** [comment] 2022-03-29 03:44
Hi,

The root cause is the same as here: [11326](https://github.com/primefaces/primeng/issues/11326)

Regards

**Comment by yigitfindikli** [comment] 2022-03-31 08:36
Fixed in https://github.com/primefaces/primeng/issues/11082

**Closed by yigitfindikli** 2022-03-31 08:36 UTC
