### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in radioButton on reactive form

### ISSUE THREAD

**Issue by Prontsevich** [primefaces/primeng#2761] opened 2017-05-12 13:31 UTC
**I'm submitting a ...**
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/mgP4N2uobMTuUx5XQ1f8

**Current behavior**
Throw exception ExpressionChangedAfterItHasBeenCheckedError

**Expected behavior**
Radio buttons should work

**Minimal reproduction of the problem with instructions**
Look at Plunker demo.
On my page I have a group of radio buttons with colors. I show this group only after clicking on button 'Show more'. If I use reactive form and form control has initial value I get exception after showing radio buttons.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0

* **Browser:** checked in Chrome, but can be in all

 
* **Language:** TypeScript 2.3.2 | ES5

**Comment by fkolar** [comment] 2017-05-13 04:35
I am expiriencing the same problem.  Found this: https://github.com/angular/angular/issues/15464

The plunker does not work for me. 

Will try ngModel in meantime.

**Comment by Prontsevich** [comment] 2017-05-15 14:33
ngModel works good in my example

**Comment by fkolar** [comment] 2017-05-15 15:23
Yes, ngModel does work as a workaround for now.

**Comment by saithis** [comment] 2017-06-13 10:25
We experience the same problem with angular 4.2.1 and primeng 4.0.3

**Comment by cagataycivici** [comment] 2017-06-23 08:06
Duplicate of #2238

**Comment by cagataycivici** [comment] 2017-06-29 08:15
Not a duplicate so reopen.

**Closed** 2017-06-29 08:22 UTC
Labels: defect
