### ISSUE TITLE
datatable error with Checkbox selection combinated with Vertical and Horizontal scrolll

### ISSUE THREAD

**Issue by carlosjcasoc** [primefaces/primeng#1030] opened 2016-10-05 20:47 UTC
the problem I have is that combine multiple selection with checkbox and scroll in the datatable does not appear to me box to select rows in my datatable, but to remove my datatble expands scroll off the page

I use the beta version primeng 17

**Comment by amirch1** [comment] 2016-10-26 08:15
Same here: when using scrollable dataTable with checkbox selection - the checkboxes do not appear in the table.

**Comment by cagataycivici** [comment] 2016-10-28 07:45
Duplicate of #860

**Closed by cagataycivici** 2016-10-28 07:45 UTC
