### ISSUE TITLE
p-calendar timepicker with input fields

### ISSUE THREAD

**Issue by rapptor789** [primefaces/primeng#2315] opened 2017-03-16 10:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The time in timepicker can only changed by the arrows.

**Expected behavior**
The user experience would be better, if it is possible to change the time in timepicker additionally by input fields. Like here: https://nkalinov.github.io/ng2-datetime/

**What is the motivation / use case for changing the behavior?**
The user experience would be better, if it is possible to change the time in timepicker additionally by input fields. It is stressful to change the time only by arrows. Sometime you have to click many times on the arrows to get the wanted time.

I think it is sometimes easier to fill in the correct in input field instead of clicking it...

**Please tell us about your environment:**

* **Angular version:** 2.4.9

* **PrimeNG version:** 2.0.2

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment] 2017-06-20 19:53
Duplicate of #1883

**Closed by cagataycivici** 2017-06-20 19:53 UTC
