### ISSUE TITLE
DROPDOWN is not working properly on form.reset() in ReactiveForms.

### ISSUE THREAD

**Issue by ngadceser** [primefaces/primeng#14158] opened 2023-11-20 21:46 UTC
### Describe the bug

I'm using 16.6.0 because of a dropdown issue.  
After updating to 16.8.0 today, 
the previous options issue was resolved, 
but I am experiencing a new issue.
I think the validator of DROPDOWN is not working properly on form.reset() in ReactiveForms. 

### Environment

"@angular/animations": "^17.0.3",
"@angular/cdk": "^17.0.1",
"@angular/common": "^17.0.4",
"@angular/compiler": "^17.0.4",
"@angular/core": "^17.0.4",
"@angular/forms": "^17.0.4",
 "@angular/material": "17.0.1",
 "@angular/platform-browser": "^17.0.4",
 "@angular/platform-browser-dynamic": "^17.0.4",
 "@angular/router": "^17.0.4",
 "primeng": "~16.8.0",

### Angular version

17.0.4

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Browser(s)

Chrome  119.0.6045.160

### Steps to reproduce the behavior

 the validator is not working properly on form.reset() in ReactiveForms.

**Comment by cetincakiroglu** [comment] 2023-11-21 06:18
Hi, could you please share a stackblitz reproducer so we can identify the issue?

**Comment by arjunreddy-001** [comment] 2023-11-21 13:12
@cetincakiroglu 

AutoComplete is also showing same kind of behavior. When form is reset using reactive forms, form values are getting reset to null. But, in UI label will be showing instead of getting cleared.

**Comment by cetincakiroglu** [comment] 2023-11-21 15:47
Hi,

It actually works on dropdown please see the example below.

https://stackblitz.com/edit/okk7pb?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

**Comment by cetincakiroglu** [comment] 2023-11-21 15:53
> @cetincakiroglu
> 
> AutoComplete is also showing same kind of behavior. When form is reset using reactive forms, form values are getting reset to null. But, in UI label will be showing instead of getting cleared.

Thanks for mentioning the autocomplete, it's fixed now https://github.com/primefaces/primeng/issues/14170

**Comment by ngadceser** [comment] 2023-11-21 23:27
> Hi, could you please share a stackblitz reproducer so we can identify the issue?
I'm sorry, the project is so intertwined that it's hard to break it down and sample just those parts.
But when I do form.reset(), the invalid or valid in the dropdown doesn't work properly.

**Comment by cetincakiroglu** [comment] 2023-11-22 07:16
> > Hi, could you please share a stackblitz reproducer so we can identify the issue?
> > I'm sorry, the project is so intertwined that it's hard to break it down and sample just those parts.
> > But when I do form.reset(), the invalid or valid in the dropdown doesn't work properly.

I've shared an example above, please see it. Dropdown works with the formcontrol.reset() 

Cannot reproduce the mentioned behavior, closing the issue.

**Closed by cetincakiroglu** 2023-11-22 07:16 UTC
Labels: Type: Bug
