### ISSUE TITLE
Steps not appear

### ISSUE THREAD

**Issue by Paul75** [primefaces/primeng#4475] opened 2017-11-18 20:44 UTC
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://embed.plnkr.co/f07kRt0Dd7Zgs4Z5tXvq/

**Current behavior**

Not appear items ....

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Visual Code Studio

Angular version: 5.0.2

PrimeNG version: 5.0.0-rc.0

**Comment by sudheerj** [comment] 2017-11-18 22:57
Not a bug.I can't replicate the issue. Either add the custom style classes in styles property or remove the custom styles assigned to it. Please comment  here to reopen the issue if you find any other concerns.

**Closed by sudheerj** 2017-11-18 22:57 UTC

**Comment by Paul75** [comment] 2017-11-18 23:11
It seams that is the theme the problem i use bootstrap theme if i change to default it appear....

**Comment by sudheerj** [comment] 2017-11-19 03:05
When I used basic steps component it is working for bootstrap as well. There are known issues with bootstrap theme and it planned for some changes.
