### ISSUE TITLE
Table | VirtualScroll makes table header flicker

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#11309] opened 2022-03-16 13:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-4ue1ro

**Current behavior**
When using virtualScroll in table, the table header is flickering on scroll.

**Expected behavior**
No flickering.

You can also compare the PrimeNG examples https://primefaces.org/primeng/#/table/virtualscroll and
https://www.primefaces.org/primeng-v11-lts/#/table/virtualscroll.
You see that in PrimeNG 11 there is no flickering as in PrimeNG 12+.

**Minimal reproduction of the problem with instructions**
Use virtuaScroll in table. As you scroll you will see flickering.
If you remove virtualScroll you see no flickering.

**What is the motivation / use case for changing the behavior?**
I want to use a table with virtualScroll and no flicker on scroll as it is distracting.

* **Angular version:**
13.X

* **PrimeNG version:** 
13.X
As I upgrade from PrimeNG 11 to 12+ and the issue seems new to me, I think this might be caused by the table rework in PrimeNG 12.

* **Browser:**
Tested in firefox and chrome

**Comment by yigitfindikli** [comment] 2022-03-16 15:35
Duplicate of https://github.com/primefaces/primeng/issues/10630

**Closed by yigitfindikli** 2022-03-16 15:36 UTC

**Comment by Kisters-BS** [comment] 2022-03-16 15:39
Sorry for duplication..
