### ISSUE TITLE
Slider not working with dynamic values.

### ISSUE THREAD

**Issue by PardeepJain** [primefaces/primeng#985] opened 2016-09-29 10:21 UTC
Slider (p-slider) is working fine with dynamic values like this

`<p-slider [(ngModel)]="price_range" [style]="{'width':'200px'}" [range]="true" [animate]='true' (onChange)='xyz()'></p-slider>`

But when i provide dynamic value in [min] and [max] than animation is not works as expected but function is calling fine
not working code

`<p-slider [(ngModel)]="price_range" [style]="{'width':'200px'}" [range]="true" [animate]='true' (onChange)='getBrandList()' [min]='price_range[0]' [max]='price_range[1]'></p-slider>`

otherwise works only for default values which is 0,100
is it known bug ?

**Comment by rbasniak** [comment] 2016-10-05 03:34
I can confirm this. Here's a simple example:

`<p-slider [(ngModel)]="positionX" [min]="-10" [max]="10"></p-slider>`

When I drag it to the left, it goes beyond the minimum point:

![image](https://cloud.githubusercontent.com/assets/10734059/19100197/f905ad58-8a92-11e6-84ab-14d001d50d67.png)

When It's at the left end, the value should be -10, but it's 0

![image](https://cloud.githubusercontent.com/assets/10734059/19100210/102ef2d2-8a93-11e6-8e0f-eaf0fa236cd1.png)

Near the middle the value should be 0, but it's 9

![image](https://cloud.githubusercontent.com/assets/10734059/19100221/228d647c-8a93-11e6-8742-8546c187a538.png)

If I try to move beyond this point, the slider jumps straight away to the far right point, with the right value now:

![image](https://cloud.githubusercontent.com/assets/10734059/19100242/5dc6806e-8a93-11e6-8ec5-25b35d616424.png)

**Comment by cagataycivici** [comment] 2016-10-21 23:33
What is your PrimeNG version?

**Comment by PardeepJain** [comment] 2016-10-22 06:37
@cagataycivici `1.0.0-beta.11`

**Comment by cagataycivici** [comment] 2016-11-16 11:47
Duplicate of #1193

**Closed** 2016-11-16 11:47 UTC
