### ISSUE TITLE
TabView Not Scrolling after adding more tabs

### ISSUE THREAD

**Issue by serak** [primefaces/primeng#2076] opened 2017-02-15 06:00 UTC
HI All Dojo , Angular material 1.x and most of full featured Tabview(tabcontainers) scroll horizontally which i think is more needed function when it comes to multitasking webapp 

![image](https://cloud.githubusercontent.com/assets/3592372/22962298/1b76b8ae-f35d-11e6-843e-abd769839103.png)

**Comment by morganRotaStabelli** [comment] 2017-05-16 09:34
I needed too, this! Optimus, calls all Autobots!!

**Comment by imranshafqat** [comment] 2017-06-02 10:41
I need it too
+1

**Comment by cagataycivici** [comment] 2017-06-20 13:06
Duplicate of https://github.com/primefaces/primeng/issues/1701;

We'll do it as we've done it before at PrimeFaces.

**Closed by cagataycivici** 2017-06-20 13:06 UTC
