### ISSUE TITLE
primeflex: please add [xs] breakpoint for small screen 

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeng#12272] opened 2022-11-22 11:03 UTC
### Describe the feature you would like to see added

Hello dears,

please add xs breakpoint for extra small screen.

thanks

**Comment by cetincakiroglu** [comment] 2022-11-22 12:52
Hi,

The issue is irrelevant with PrimeNG, please open this issue on [PrimeFlex Repo](https://github.com/primefaces/primeflex/issues)
Closing the issue, thanks for reporting!

Regards

**Closed by cetincakiroglu** 2022-11-22 12:52 UTC
Labels: Resolution: Invalid
