### ISSUE TITLE
Component: Dropdown TypeError: option.toLowerCase is not a function (PringNG 17.0 + 17.1)

### ISSUE THREAD

**Issue by rburgst** [primefaces/primeng#14370] opened 2023-12-14 17:02 UTC
### Describe the bug

Ever since upgrading to primeng 17.x the dropdown is broken, at the very least when using it with a form control.
Might be related to https://github.com/primefaces/primeng/issues/14241

### Environment

Mac OSX, Chrome

### Reproducer

https://stackblitz.com/edit/hhk8ms?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

### Angular version

17.0.5

### PrimeNG version

17.1.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. open the dropdown
2. enter something in the filter box

### Expected behavior

it should work

**Comment by urielzen** [comment] 2023-12-15 05:25
I have the same issue

**Comment by urielzen** [comment] 2023-12-15 05:27
possible duplicate of:

https://github.com/primefaces/primeng/issues/14311

**Comment by rburgst** [comment] 2023-12-15 06:45
setting the `filterBy` seems to improve the situation just as described in #14311 . I am still experiencing a variant of #14241 where the selected element is not showing up (in a form array).

**Comment by yassine-fy94** [comment] 2023-12-17 20:21
Also the filterBy option is not working

**Comment by IrvingMartinezCAP** [comment] 2023-12-21 14:18
It works for me, i forked your stackblitz [https://stackblitz.com/edit/hhk8ms-gucjhk?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html](url) and it works, only added "filterBy"

**Closed** 2024-01-10 10:12 UTC
Labels: Type: Bug

**Comment by CyleClone** [comment] 2024-01-29 10:49
I've updated my project to 17.4.0 and the filter still throws the same error.
Error appears to happen when you keep the standard setting of reading label.

![image](https://github.com/primefaces/primeng/assets/30074212/bcde8474-bcde-466c-993f-5fc6fa1e0024)

As others have mentioned adding filterBy would solve the issue. Alternatively setting `optionLabel="label"` would also solve it.
But changing attributes for more 100+ dropdowns isn't really viable.

Additionally the Dropdown loses it's chosen value while filtering.
Forked original Stack to update PrimeNG package and show the last point:
https://stackblitz.com/edit/hhk8ms-8g5ykm?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

**Comment by Reflection281** [comment] 2024-01-29 16:04
I must agree, I have the same problem with the same version. The bug of losing its selected value when filtering is really weird. It loses the value when typing, but it reappears when you delete the typed characters.
