### ISSUE TITLE
[Slider] Can't drag handler on handheld devices

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#1183] opened 2016-11-01 22:48 UTC
After some testing, I've found that we can't drag the handler using touch events.
This component works perfectly on Desktop devices, this issue happens only on smartphones and tablets.

**How to simulate the issue:**

- Access the component's demo page: http://www.primefaces.org/primeng/#/slider
- Enable google developer tools, then activate the Device toolbar
- Chose any handheld device
- Try to drag any input

**Comment by sudheerj** [comment] 2017-05-24 12:33
Duplicate of https://github.com/primefaces/primeng/issues/2866

**Closed by sudheerj** 2017-05-24 12:33 UTC
