### ISSUE TITLE
DataView | Custom sort support

### ISSUE THREAD

**Issue by aleroz8** [primefaces/primeng#11754] opened 2022-07-29 08:52 UTC
### Describe the feature you would like to see added

When I assign new `value` to DataView component I would like the new data to be automatically sorted if `sortField` and `sortOrder` properties are set. Right now it is sorted again only if I change `sortField` or `sortOrder` properties or manually call `sort` function.

### Is your feature request related to a problem?

It is a little irritating because the only workaround I found is changing DataView ngOnChanges hook.

### Describe the solution you'd like

I would like the new data assigned to `value` to be sorted if `sortField` and `sortOrder` properties are set to correct values.

**Comment by muuvmuuv** [comment] 2022-08-15 08:49
Duplicate of #9662

**Comment by mertsincan** [comment] 2022-11-09 21:40
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 21:40 UTC
Labels: new feature
