### ISSUE TITLE
Table: The "stack" responsive mode is not working.

### ISSUE THREAD

**Issue by aaron-za-dev** [primefaces/primeng#16664] opened 2024-10-30 01:12 UTC
The documentation describes the responsive "stack" mode but this feature does not work in the demonstrated example and neither in the stackblitz example provided

v 17.18.11

![image](https://github.com/user-attachments/assets/c32f9fea-82cc-4c64-a0be-73b5b62c76a0)

v 16.9.15

![image](https://github.com/user-attachments/assets/72181b2d-0189-490f-a5b2-3fd51ad2290f)

Stackblitz Demo

![image](https://github.com/user-attachments/assets/b236b406-902c-4a63-87ae-c08e482919dc)

### Environment

Any

### Reproducer

https://primeng.org/table#responsive-stack

### Angular version

> 16.X.X

### PrimeNG version

16.X.X

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Browser(s)

Any Browser version

### Steps to reproduce the behavior

1. Go to https://primeng.org/table#responsive-stack or stackblitz demo
2. Try adjust the screen size
3. Not working

### Expected behavior

The table should apply the "stack" responsive mode unless this feature is deprecated.

**Comment by imaksp** [comment] 2024-10-31 06:59
looks like duplicate of #16510

**Closed** 2024-11-19 11:16 UTC
Labels: Resolution: Duplicate
