### ISSUE TITLE
Chinese support for AutoComplete

### ISSUE THREAD

**Issue by giscafer** [primefaces/primeng#2495] opened 2017-04-12 10:01 UTC
**Dropdown \ AutoCompelete** 

First，i am Chinese，so i use english and chinese in our project。

but, **Dropdown and AutoCompelete** component is not support typing chinese，because for the **HeChinese Input Software** 

there is the way solve the problem:

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<input type="text" id="sample" />
<script>
	
var node = document.querySelector('#sample');
var inputLock = false;
node.addEventListener('compositionstart', function(){
    inputLock = true;
})
node.addEventListener('compositionend', function(){
    inputLock = false;
     if(!inputLock)console.log(this.value);
})
node.addEventListener('input', function(){
    if(!inputLock ){
    	console.log(this.value);
    }
    // do something for input limit
});
</script>
</body>
</html>
```
using `compositionstart ` and `compositionend`。

or
```javascript

  onInput(event) {
        let value = event.target.value;
       //--this code put in the delay
//-------start
        if(!this.multiple) {
            this.value = value;
            this.onModelChange(value);
        }
            //-----end
        if(value.length === 0) {
           this.hide();
        }
        
        if(value.length >= this.minLength) {
            //Cancel the search request if user types within the timeout
            if(this.timeout) {
                clearTimeout(this.timeout);
            }

            this.timeout = setTimeout(() => {
                this.search(event, value);
            }, this.delay);
        }
        else {
            this.suggestions = null;
        }
        this.updateFilledState();
    }
    
```

i hope it will support chinese typing 

Forgive my poor English

**Comment by sudheerj** [comment] 2017-11-13 12:27
Duplicate of #1318

**Closed by sudheerj** 2017-11-13 12:27 UTC
Labels: enhancement
