### ISSUE TITLE
Accessibility: Scrollable table: NVDA not able to read table data appropriately in scan mode

### ISSUE THREAD

**Issue by gnagababu** [primefaces/primeng#9724] opened 2021-01-07 11:18 UTC
**Accessibility: Scrollable table: NVDA not able to read table data appropriately in scan mode**

**Current behavior**

  When NVDA focus comes to table it is announcing as 1row and x columns even we have multiple rows in a table

**Expected behavior**

  Any screen reader should able to announce the correct number of rows when focus comes to table.

**Minimal reproduction of the problem with instructions**

  Navigate to https://primefaces.org/primeng/showcase/#/table/scroll
  Start the NVDA and activate scan mode (press insert and spacebar to activate scan mode). Now Press T in keyboard to focus 
  the table(Press T or SHIFT T to navigate between tables), observe screen reader announcing table with 1 row and x columns 
  even though we have more than one row in that table.

  In our initial investigation we observed one issue in scrollable table, it is generating two tables in html markup. one table with 
  header row with empty tbody and another table with rows only. So when focus comes to first table NVDA screen reader 
  announcing first table information only say "table with 1 row and x columns".
  generating two tables is causing this issue. please investigate more on this issue.

**What is the motivation / use case for changing the behavior?**
  Visually impaired users finds difficult in understanding about the table data if narrator does not read its corresponding column 
  header​

**Angular version:** 9.1.12

**PrimeNG version**: 9.1.3 and above, v11.1.0 also

**Browser**: Chrome XX
![scrollable table](https://user-images.githubusercontent.com/266395/103886823-14791580-5108-11eb-8aa8-d7148930a245.JPG)

**Comment by bobanmarkovic** [comment] 2021-01-31 18:32
As you noticed, the problem is that p-table with scrollable="true" renders as two tables: one for the header and one for the body. I'm having the same problem with JAWS and this is very, very confusing for visually impaired users - they think that there are two tables on the page.
My temporarily solution was to have a scrollable wrapper around the  table and set scrollable="false" on p-table.
Hopefully this will be fixed one day by PrimeNG.

**Comment by mertsincan** [comment] 2022-11-09 20:09
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:09 UTC
Labels: enhancement
