### ISSUE TITLE
Styleclass for TreeNode with Horizontal Layout

### ISSUE THREAD

**Issue by cheesgno** [primefaces/primeng#2367] opened 2017-03-23 11:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I'm trying to use the styleClass property for Tree Component (with **Horizontal Layout**) but the rendering of the element doesn't contains my class.
I think my class should be added to the ui-treenode-content component

**Expected behavior**
If you specify the styleClass property of a specific node of the Tree Component (with **Horizontal Layout**). its style will change on the page.

**Minimal reproduction of the problem with instructions**
Setting styleClass property for one node of the Tree Component (with **Horizontal Layout**)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.10

* **PrimeNG version:** 2.0.5

**Comment by cagataycivici** [comment] 2017-06-20 19:59
Duplicate of #1963

**Closed by cagataycivici** 2017-06-20 19:59 UTC
