### ISSUE TITLE
p-tree: onNodeDrop event is not invoked when dropping node on empty tree

### ISSUE THREAD

**Issue by Schmaga** [primefaces/primeng#8999] opened 2020-07-02 17:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Link**
https://stackblitz.com/edit/primeng-treedragdrop-demo-tnpeut

**Current behavior**
When creating two tree controls that share the same drag/drop scope, the onNodeDrop Event is not raised when the second tree is initially empty and then dragging a node from the first to the second tree.

**Expected behavior**
onNodeDrop Event should be raised also on the first drop on an empty tree.

**Minimal reproduction of the problem with instructions**
I put together a small reproduction-demo based on your treenode-drag-drop demo Stackblitz. Please open the above Stackblitz, open the console and move a node from the first tree to the empty second tree. You would expect to see a console output even on the first drop, but the onNodeDrop event is only raised after you drop the second node into the tree.

**What is the motivation / use case for changing the behavior?**
We would like to share nodes between two trees and need to react to the onNodeDrop event even with an initially empty tree. The current workaround I'm trying to use is putting an empty placeholder node into the second tree and hide it using CSS. But this leads to the drop behavior being a bit less user-friendly because the tree offers more "drop"-space if the tree is empty.

**Please tell us about your environment:**
* **Angular version:** 9.1

* **PrimeNG version:** 9.1.2

* **Browser:** tested on latest Chrome, Firefox and Edge, but does probably affect all
 
* **Language:** TypeScript 3.7.5

**Comment by yevhen309** [comment] 2020-11-20 11:32
Same here, version 10.0.3. Any workarounds? There is also closed issue about the same problem https://github.com/primefaces/primeng/issues/8536

**Comment by PaddingtonTheBear** [comment] 2020-11-20 11:49
> Same here, version 10.0.3. Any workarounds? There is also closed issue about the same problem #8536

I ran into this problem earlier this year and I believe I got around it (after much headache) by putting an empty object in the collection the tree is referencing. This allows the onNodeDrop event to trigger for the "empty" tree when you drop a real node onto it. 

The only issue is the first drop has to be in a very specific area at the top of the "empty" tree and you can't just drop it anywhere into the tree container until you finally have a "real" node.

I haven't dug into the underlying PrimeNG code for this but I presume when there is an empty collection for a tree, the events aren't attached and aren't being fired. Either that, or the events themselves are attached to the individual nodes and since you don't have any nodes in the tree yet, nothing gets fired.

**Comment by yevhen309** [comment] 2020-11-20 14:50
I checked the underlying code. Looks like `tree.onNodeDrop` is emitted only from `p-treeNode`. So no node, no event... 
Probably `this.onNodeDrop.emit(...)` somewhere inside `onDrop` method (line 1027, tree.ts) could potentially solve this (unless there is a reason why it's not there, e.g. `onNodeDrop` could be called twice).

**Comment by mrsegen** [comment] 2021-04-10 22:58
My understanding is that #9991 was a duplicate of this. So this may have already been resolved, at least partially.
As of 11.3.2, this is working. However, see #10093 regarding a related issue

**Comment by yigitfindikli** [comment] 2021-06-09 07:41
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Closed by yigitfindikli** 2021-06-09 07:41 UTC
Labels: enhancement
