### ISSUE TITLE
 HeaderCheckboxToggleAllPages does not work with [lazy] = "true"

### ISSUE THREAD

**Issue by jpordonez** [primefaces/primeng#3039] opened 2017-06-09 03:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When **[headerCheckboxToggleAllPages] = "true"** is used with **[lazy] = "true"**, clicking on the header check does not select objects on other pages.

When I click on the check of the rows it works normally, the error happens when I click on the check of the header

**Expected behavior**

The object **[(selection)] = "productosSeleccionados"** should contain all the objects of all pages when clicking on the header check.

**Minimal reproduction of the problem with instructions**

Create a DataTable with pagination, multiple selection, **headerCheckboxToggleAllPages** and **lazy** properties set to true, and fix the method **(onLazyLoad)**.

**.html**

```
<p-dataTable #dtbuscadorCatalogoProductos [value]="productos" [(selection)]="productosSeleccionados"
	[scrollable]="true" scrollHeight="180px" [lazy]="true" [rows]="tamanioPagina" [paginator]="true"
	[totalRecords]="totalRegistrosProductos" (onLazyLoad)="buscarProductosPaginado($event)"
	[emptyMessage]="tablaSinDatos" dataKey="Id" [headerCheckboxToggleAllPages]="true">
		<p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column>
		<p-column field="Id" header="Id"></p-column>
		<p-column field="Nombre" header="Nombre"></p-column>
		<p-column field="PrincipioActivo" header="PrincipioActivo"></p-column>
		<p-column field="Titular" header="Titular"></p-column>
		<p-column field="Presentacion" header="Presentación"></p-column>
		<p-column field="ViaAdministracion" header="Vía Administración"></p-column>
		<p-column field="EsGenerico" header="Es Generico">
			<ng-template let-col let-ent="rowData" pTemplate="body">
				<span>{{ent[col.field] | boolToCadena:'Si':'No'}}</span>
			</ng-template>
		</p-column>
</p-dataTable>
```

**.ts**

```
buscarProductos(pagina: number) {
        if (this.criteriaForm.invalid) {
            this.utilService.mostrarMensaje('Se tiene que ingresar todos los campos obligatorios.');
            return;
        }
        if (!this.criteriaForm.contains('NumeroPagina')) {
            this.criteriaForm.addControl('NumeroPagina', new FormControl('', []));
        }
        this.criteriaForm.controls['NumeroPagina'].setValue(pagina);

        let respuesta = this.buscadorProductoService.listar(this.criteriaForm.value);
        respuesta
            .$observable
            .subscribe(
            (res: any) => {
                this.productos = res.Data;
                if (!this.productos) {
                    this.productos = [];
                }
                this.totalRegistrosProductos = res.TotalRegistros;
                if (!this.totalRegistrosProductos) {
                    this.totalRegistrosProductos = 1;
                }
            }
            );
    }

    buscarProductosPaginado(event: LazyLoadEvent) {
        let pagina = (event.first / event.rows) + 1;
        this.buscarProductos(pagina);
    }
```

**What is the motivation / use case for changing the behavior?**

Select all the objects in all the pages when clicking on the check of the header when it is carried out lazy load.

**Please tell us about your environment:**
Windows 7

**Angular version:** 4.1.0

**PrimeNG version:** 4.0.3

**Browser:** All

**Language:** All

* **Node (for AoT issues):** 7.10.0

**Comment by sudheerj** [comment] 2017-06-10 11:13
The issue is replicated with lazy loading. The selection need to be reset with current page data during pagination.

**Comment by cagataycivici** [comment] 2018-01-13 22:45
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Closed by cagataycivici** 2018-01-13 22:45 UTC
Labels: defect, pending-review

**Comment by MarkPieszak** [comment] 2018-02-15 23:54
@sudheerj Just reading your comment now, is this something that is fixed now?

@jpordonez Did you ever figure out how to get this working?

@cagataycivici I know it is deprecated, is this functionality possible somehow with 4.3.x code?

**Comment by MarkPieszak** [comment] 2018-02-16 00:25
@jpordonez @sudheerj @cagataycivici 
Is this possible to achieve somehow with 4.3.x and datatable?
