### ISSUE TITLE
Turbo table p-table get nested values

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#4967] opened 2018-01-25 10:59 UTC
Hi all, is there a way to get nested value with the new turbo table?
In my data list I have a lot of fields and an object. How can I get a field of my object?

Ex. This is my case
[code]tbl.cols = [
        {field: 'status', header: 'status'},
        {field: 'id', header: 'id'},
        {field: 'nestedObj.id', header: 'NestObjId'},
        {field: 'nestedObj.description', 'NestObjDesc'}
];[/code]

The nested fields aren't showed

**Comment by adama357** [comment] 2018-01-25 16:40
I think this is a duplicate of #4958

**Comment by cagataycivici** [comment] 2018-01-30 12:42
https://github.com/primefaces/primeng/issues/4958

**Closed by cagataycivici** 2018-01-30 12:42 UTC

**Comment by cagataycivici** [comment] 2018-01-30 12:44
This is by design, you have **full** control over the presentation so it is up to you, Table just gives you the metadata, it is in your control on how to display it. Image you are doing a list with *ngFor with this case, how would you display nested fields? Same applies here as well. Probably a helper in your project to resolve fields similar to ObjectUtils.resolveFieldData in PrimeNG.
