### ISSUE TITLE
Virtual scroll and lazy loading table inside dialog not display rows correctly

### ISSUE THREAD

**Issue by zeatan** [primefaces/primeng#9296] opened 2020-09-20 07:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-eqdvnz

**Current behavior**

Virtual scroll and lazy loading table inside dialog not display rows correctly  on dialog shown.
Even once browser resized, works fine.

**Expected behavior**

Virtual scroll and lazy loading works inside dialog too.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 10.0.X

* **PrimeNG version:** 10.0.X

* **Browser:** [ Chrome XX | Firefox XX | Safari XX ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by curciot** [comment] 2020-09-23 15:37
i've got the same problem there's a fix or a workaround

**Comment by pinolombardo** [comment] 2020-09-24 08:10
I have the same issue.... it would be great to have a fix ...

**Comment by mauriziocolica** [comment] 2020-09-24 10:34
I'm facing the same issue. Is there any solution or workaround?

**Comment by mnhock** [comment] 2020-09-25 08:03
Releated to 9298

**Comment by brian428** [comment] 2020-10-02 16:11
This appears to affect any table using virtual scrolling in a dialog, whether it uses lazy loading or not. Here's the same demo case but with only virtual scrolling. Clearly, the table being in a dialog is causing some serious problems for either the PrimeNg ScrollableView and/or the CDK VirtualScrollViewport.

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-jgsrhz?file=src/app/app.component.html

**Comment by viniciuslln** [comment] 2020-11-20 12:58
I noticed that this problem is not just linked to the dialog but to changes in the table's parent, meaning, whenever we change the display property from 'none' to 'block'.

**Comment by yigitfindikli** [comment] 2020-11-25 09:04
duplicate of https://github.com/primefaces/primeng/issues/9298

**Closed by yigitfindikli** 2020-11-25 09:04 UTC

**Comment by hamidh2** [comment] 2022-12-09 13:41
I had the same problem, which I fixed after lots of struggling when I was woking on this, I figured out that if scroll to left it renders the content, so I add the below code at the end of my codes, It's like a bad workaround but I needed to fix that so I ended up with the below workaround!!

```
   const scroll = document.getElementsByClassName("p-scroller-inline")[0] as HTMLElement;
            if (scroll) {
              scroll.scrollLeft += 1;
            }
```
