### ISSUE TITLE
BIG ERROR with DropDown

### ISSUE THREAD

**Issue by ja74687** [primefaces/primeng#13996] opened 2023-11-02 09:47 UTC
### Describe the bug

Hello

Team primeng, after the last update your dropdown not work corretly, placeholder not work, control set default value, on your webpage when I click clear I have error: 
![image](https://github.com/primefaces/primeng/assets/24416487/5612e59e-be61-4139-b347-72b02b9f21d6)

How I can fix it ?? 

### Environment

Drop-down not work corretly, multiselect work fine.

### Angular version

16

### PrimeNG version

16*

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.2

### Browser(s)

All

**Comment by jsdevtom** [comment] 2023-11-02 10:16
I can reproduce

**Comment by adri95cadiz** [comment] 2023-11-02 10:59
In my case this seems to be happening in some cases because the old version had the default optionLabel set to "label" and the default optionValue set to "value", and in some cases we just adapted to these default values. 

In the new version these default values seem to be omitted and are defaulted to null values, forcing to define the optionLabel and optionValue in every case 

![image](https://github.com/primefaces/primeng/assets/10522017/d3eee480-cd1a-44e1-a335-f93a1d464e47)

I solved this by setting optionLabel and optionValue in every p-dropdown and p-multiselect component in my application, hopefully this should work for you too.

**Comment by ja74687** [comment] 2023-11-02 11:35
![image](https://github.com/primefaces/primeng/assets/24416487/7d14c101-ce2c-4ab9-9b4d-0ed45f089499)
This is set Autstralia default, and when i Click clear I have errors, in my App I have that the same error.

**Comment by adri95cadiz** [comment] 2023-11-02 11:40
Yes anyways I have other errors related to this it could be this case, for example I have a multiselect that is not getting the selected values correctly, a lot of things seem to have changed and it's not clear the steps that should be taken to fix the issues with the new version.

For me, I have had to downgrade primeng to version 16.6.0 as there are a lot of issues that break the application and I have tried to go around them but could only fix while others are still ongoing.

**Comment by rosenthalj** [comment] 2023-11-02 11:59
I can also confirm that the dropdown has multiple errors.   Numerous errors can easily be found by "free play".  Use the mouse and the keyboard.

The demo's "Basic" Dropdown example  has an obvious error.  Please see the annotated screenshot listed below.

![Cursor_and_Angular_Dropdown_Component_and_Angular_Dropdown_Component](https://github.com/primefaces/primeng/assets/45439491/d55e1b61-8ece-477e-b02c-158e1d881253)

**Comment by ja74687** [comment] 2023-11-02 12:06
When i downgrade to 16.0.0 i have similar error, its weird, I use Angular 16 and I can't install Prime 15 xD

**Comment by cetincakiroglu** [comment] 2023-11-02 16:03
Hi,

Thanks a lot for reporting the issue, we've just reworked the component logic in multiselect, dropdown, listbox and some of the other input components during the accessibility implementation. Something we do during the accessibility implementation probably causes the issue, it'll be fixed within the next release.

**Comment by jerkovicl** [comment] 2023-11-03 10:47
![image](https://github.com/primefaces/primeng/assets/5444153/4c87ff63-254e-4d64-82d5-0ca5530a8541)

selectedOption was also removed from Dropdown without any info in release notes about breaking changes

**Comment by ailtonbsj** [comment] 2023-11-03 13:22
Hi,

The directive ngModel can't set an item of p-dropdown in version 16.7.0. If a downgrade to 16.6.0 start to work again.

**Comment by cetincakiroglu** [comment] 2023-11-03 15:14
> Hi,
> 
> The directive ngModel can't set an item of p-dropdown in version 16.7.0. If I downgrade to 16.6.0 start to work again.

Could you please open an issue with a reproducer and tag me?

**Comment by cetincakiroglu** [comment] 2023-11-03 15:16
> ![image](https://user-images.githubusercontent.com/5444153/280253948-4c87ff63-254e-4d64-82d5-0ca5530a8541.png)
> 
> selectedOption was also removed from Dropdown without any info in release notes about breaking changes

selectedOption wasn't an input or public property and we don't need to state that as a breaking change. Also, it was not mentioned anywhere in the documentation. But I've realized that there was a missing selectedOption property inside the templates, thanks to your report.

**Comment by cetincakiroglu** [comment] 2023-11-03 15:25
Hello everyone,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!

**Comment by rosenthalj** [comment] 2023-11-03 15:30
After your fix for the dropdown,  Is there a chance you could produce a release candidate version?


From: Çetin ***@***.***>
Reply-To: primefaces/primeng ***@***.***>
Date: Friday, November 3, 2023 at 11:25 AM
To: primefaces/primeng ***@***.***>
Cc: "Rosenthal, Joseph A. (GSFC-474.0)[SAIC]" ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [primefaces/primeng] BIG ERROR with DropDown (Issue #13996)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Hello everyone,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!

**Closed** 2023-11-03 15:36 UTC
Labels: Type: Bug

**Comment by cetincakiroglu** [comment] 2023-11-03 15:47
> After your fix for the dropdown, Is there a chance you could produce a release candidate version?

Planned release date is November 8th

**Comment by ja74687** [comment] 2023-11-03 15:47
> > Hi,
> > The directive ngModel can't set an item of p-dropdown in version 16.7.0. If I downgrade to 16.6.0 start to work again.
> 
> Could you please open an issue with a reproducer and tag me so we can include it to the 16.8.0 release?

I find misake in my package.json I use ^ symbol and node install 16.7 Prime not 16.6 :)

**Comment by ailtonbsj** [comment] 2023-11-03 19:29
> I find misake in my package.json I use ^ symbol and node install 16.7 Prime not 16.6 :)

I had the same problem. I used ~ instead of ^.

**Comment by ailtonbsj** [comment] 2023-11-03 23:23
> > Hi,
> > The directive ngModel can't set an item of p-dropdown in version 16.7.0. If I downgrade to 16.6.0 start to work again.
> 
> Could you please open an issue with a reproducer and tag me so we can include it to the 16.8.0 release?

I just opened an issue in #14023

**Comment by pierocox09** [comment] 2023-11-07 16:28
cuando estan juntas la optionlabel y optionvalue causa un error hasta en su documentacion

**Comment by ailtonbsj** [comment] 2023-11-07 17:14
> cuando estan juntas la optionlabel y optionvalue causa un error hasta en su documentacion

Actualice su versión a 16.7.1

**Comment by pierocox09** [comment] 2023-11-07 17:37
> > cuando estan juntas la optionlabel y optionvalue causa un error hasta en su documentacion
> 
> Actualice su versión a 16.7.1

da un error al mostrar el valor

**Comment by ailtonbsj** [comment] 2023-11-07 17:55
> > Actualice su versión a 16.7.1
> 
> da un error al mostrar el valor

Open an issue with a reproducer on Stackblitz.
