### ISSUE TITLE
p-confirmDialog not centered to browser IE

### ISSUE THREAD

**Issue by MrBogue** [primefaces/primeng#7287] opened 2019-02-25 10:02 UTC
Hello,
I am facing an issue w.r.t the ConfirmDialog. when we perform an action the dialog pop-ups in the left down corner and then gets re centered. 
this was not happening in the previous version of PrimeNg.
[
![issue_primengv7 0 5](https://user-images.githubusercontent.com/37176169/53329648-d34d3300-38ec-11e9-9a5c-615da3ec2c97.png)
](url)
**Current behavior**

On first click of the p-confirmdialog, the dialog is not centered to the page, but then 1 second after the dialog is centered automatically.
The issue happens only on IE

**Expected behavior**

The dialog should be centered to the browser.

**Environment:**

IE Version 11.0.9600.19266

Windows 7

* **Angular version:** 7.0.0
* **Angular Cli version:** 7.1.1

 "@angular/core": "7.1.2"

* **PrimeNG version:** 7.0.5

* **Browser:** [  IE XX   ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    "typescript": "3.1.6"
* **Node (for AoT issues):** `node --version` =
  v10.14.1

Can you please shed some lights on this matter?

Attached is a screenshot of the issue described.

https://www.primefaces.org/primeng/#/confirmdialog

**Comment by rafa-as** [comment] 2019-02-25 10:04
We have the same issue on iOS

**Comment by LarsBergqvist** [comment] 2019-03-18 15:48
I have the same problem with PrimeNG 7.1.0 and Internet Explorer 11. It was not present in version 7.0.4 that I used previously.
The only workaround I've found so far was to set the transition time to 0ms <p-confirmDialog [transitionOptions]="'0ms'">
With this adjustment, the confirmationDialog will be without nice animation/transition, but at least it will not change position when it is opened.

**Comment by earshinov** [comment] 2019-05-03 11:37
I am having this issue in Edge as well. It seems to be fixed in #7597.

**Comment by orangecatmiao** [comment] 2020-03-04 14:24
in .css file or html style 
::ng-deep .ui-dialog-wrapper .ui-dialog{
        position:static;
   }
in .scss
ng-deep .ui-dialog-wrapper .ui-dialog{
        position:static;
   }

**Comment by cagataycivici** [comment] 2020-03-19 09:56
Unable to replicate with PrimeNG 9 which has a new Dialog Impl, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Closed by cagataycivici** 2020-03-19 09:56 UTC

**Comment by jgill248** [comment] 2020-03-24 20:15
I see the same issue happening on PrimeNG 9.0.2 just using the PrimeNG Component site.

![image](https://user-images.githubusercontent.com/8699876/77472649-a1a5e480-6dea-11ea-86f0-29ceada8585c.png)

**Comment by sreevishal** [comment] 2020-04-24 05:23
> in .css file or html style
> ::ng-deep .ui-dialog-wrapper .ui-dialog{
> position:static;
> }
> in .scss
> ng-deep .ui-dialog-wrapper .ui-dialog{
> position:static;
> }

This worked for me. Thanks for posting.

**Comment by yashvantkr** [comment] 2020-05-13 06:41
I am facing the same issue in IE11...the dialogue is going to be the right bottom corner
