### ISSUE TITLE
Conflict with ng2-responsive

### ISSUE THREAD

**Issue by chpasha** [primefaces/primeng#1041] opened 2016-10-07 15:44 UTC
I'm getting a No provider for TemplateRef! error when using datatable as soon as I include ResponsiveModule from ng2-responsive in my project even if I don't use any directives from it. Any idea what could cause the problem?

I'm using angular2 2.0.3, primeng beta 17 and ng2-responsive 0.4.6

**Comment by patriknil90** [comment] 2016-11-01 14:08
I'm also having some issues. Trying to use the ng2-responsive to hide some columns depending on screen size. I can accomplish this as intended matter and without errors. My problem is that it's breaking row expansion.

Code:
```
<p-dataTable [globalFilter]="gp" [value]="projectsArray" expandableRows="true" #dt (onRowClick)="dt.toggleRow($event.data)" styleClass="table table-sm" emptyMessage="Inga poster hittades" [editable]="true" >
    <p-column field="trueId" header="ID" [sortable]="true" [style]="{'width':'2em'}" [filterMatchMode]="contains"></p-column>
    <p-column *responsive="{sizes:{min:700, max:5000}}" field="clientOrderBusinessName" header="Beställare" [sortable]="true" [style]="{'width':'7em'}" [filterMatchMode]="contains"></p-column>
    <p-column *responsive="{sizes:{min:1000, max:5000}}" field="establishmentContactName" header="Arbetställe (Kontakt)" [sortable]="true" [style]="{'width':'8em'}" [filterMatchMode]="contains"></p-column>
    <p-column *responsive="{sizes:{min:600, max:5000}}" field="establishmentAddress" header="Arbetsställe (Address)" [sortable]="true" [style]="{'width':'8em'}" [filterMatchMode]="contains"></p-column>
    <p-column field="mark" [header]="labelsData?.Project.mark" [sortable]="true" [style]="{'width':'12em'}" [filterMatchMode]="contains"></p-column>
    <p-column *responsive="{sizes:{min:1000, max:5000}}" field="color" [header]="labelsData?.Project.status" [sortable]="true" [style]="{'width':'4em'}">
    	<template let-col pTemplate type="header">
            <span>{{col.header}} <i tooltipPosition="left" pTooltip="Beskrivning av färger" class="fa fa-question-circle table-header-question" aria-hidden="true"></i>
			</span>
        </template>
        <!--                 Fixa egna färgklasser i css               -->
    	<template let-col let-project="rowData" pTemplate type="body">
    		<progress *ngIf="!project[col.field]" class="progress progress-striped progress-danger table-progress" value="100" max="100"></progress>
            <!-- <div *ngIf="!project[col.field]" style="width: 1em; height: 1em; background-color: red; border-radius: 50%; margin-left: 1em; margin-top: 0.313em;"></div> -->
    		<progress *ngIf="project[col.field] == '#cd43f0'" class="progress progress-striped progress-warning table-progress" value="75" max="100"></progress>
    		<progress *ngIf="project[col.field] == 'annanFarg'" class="progress progress-striped progress-info table-progress" value="50" max="100"></progress>
    		<progress *ngIf="project[col.field] == 'tredjeFarg'" class="progress progress-striped progress-success table-progress" value="25" max="100"></progress>
        </template>
    </p-column>
    <p-column *responsive="{sizes:{min:1200, max:5000}}" field="" header="Bokmärk" [sortable]="true" [style]="{'width':'6em'}">
    	<template let-col pTemplate type="header">
            <span>{{col.header}} <i tooltipPosition="left" pTooltip="Bokmärkta projekt markeras med stjärna samt visas på startsidan. Bokmärk genom att klicka i kolumnen nedan" class="fa fa-question-circle table-header-question" aria-hidden="true"></i>
			</span>
        </template>
    </p-column>
    <p-column *responsive="{sizes:{min:1200, max:5000}}" field="" header="Aktivitet" [sortable]="true" [style]="{'width':'6em'}">
    	<template let-col pTemplate type="header">
            <span>{{col.header}} <i tooltipPosition="left" pTooltip="Visar antal dagar från det att senaste produkt eller dag rapporterats in" class="fa fa-question-circle table-header-question" aria-hidden="true"></i>
			</span>
        </template>
    </p-column>
	<template let-project>
		<project-content [projectId]="project.id" [projectShortMessage]="project.shortMessage" [projectLabels]="labelsData" [projectStatus]="project.status"></project-content>
	</template>
</p-dataTable>
```

Result:
[Large screen](https://i.gyazo.com/8fd9ed79d728053caac823da17c561af.png)
[Medium screen](https://i.gyazo.com/d050de6efbe689e4062fdc8d01b0d611.png)
[Small screen](https://i.gyazo.com/931e3314f04be22be5080cb556fdbd8c.png)

Problem:
Row expansion doesn't work with [ng2-responsive](https://github.com/ManuCutillas/ng2-responsive)

**Comment by lsegala** [comment] 2016-12-27 21:23
Hi!

I'm passing for a similar issue.
When I install ng2-responsive follwing instructions from official page (https://github.com/ManuCutillas/ng2-responsive) and call an page with p-dataTable component. Nothing is show and the message in console is: EXCEPTION: Uncaught (in promise): Error: Error in app/componentes/view/mypage.html:5:16 caused by: No provider for TemplateRef
When I remove p-dataTable, everthing works.

My enviroment is primeng-ultima v1.0.3, angular 2.1.1, primeng 1.0.0-rc4 and ng2-responsive 0.6.6.

**Comment by cagataycivici** [comment] 2017-03-10 11:32
Should be fixed on ng2-responsive side, PrimeNG Table has its own responsive mode.

**Closed by cagataycivici** 2017-03-10 11:32 UTC
