### ISSUE TITLE
Can't inject environmentInjector into dialog opened by DialogService

### ISSUE THREAD

**Issue by axos88** [primefaces/primeng#14491] opened 2024-01-05 14:03 UTC
### Describe the bug

Opening a standalone dynamic dialog via the DialogService does not inherit the environment injector of the component making the call.
This leads to NullInjection issues if the opened standalone (maybe also non-standalone?) component uses providers that are NOT `{providedIn: root}`, but rather an intermediate module / component was providing them.

I've hacked around a solution locally, to fix the bug two things need to be made:
 1. extend the `DynamicDialogConfig` with an `environmentInjector?: EnvironmentInjector` field.
 2. In the DynamicDialogComponent in `loadChildComponent` method, replace the last line with: 
 
 ```
     this.componentRef = viewContainerRef?.createComponent(componentType, {environmentInjector: this.config.environmentInjector });
```

### Environment

angular 17

### Angular version

17

### PrimeNG version

master

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by Draganlazarev90** [comment] 2024-02-08 12:23
Did you manage to find a workaround for this except from changing the source code?

**Comment by cetincakiroglu** [comment] 2024-02-12 15:11
Related to https://github.com/primefaces/primeng/issues/14730

**Comment by cetincakiroglu** [comment] 2024-02-14 14:18
Hi,

Your workaround solution seems to be correct, could you please open a PR so we can review the solution?

**Comment by Draganlazarev90** [comment] 2024-02-16 07:52
The fix mentioned above requires sending the environment injector in the config, each time you use dialogService.open method. Maybe a different fix can be implemented

**Comment by cetincakiroglu** [comment] 2024-02-22 17:15
The strange thing is it works if I provide DemoService inside the component see the example below. The component ignores the module providers somehow, we're investigating the solutions.

https://stackblitz.com/edit/7qkchf-expefk?file=src%2Fapp%2Fdemo%2Fdialog.component.ts,src%2Fapp%2Fdemo%2Fdemo.service.ts

**Comment by Draganlazarev90** [comment] 2024-02-22 17:48
Correct, somehow it doesn't work only with modules

**Comment by cetincakiroglu** [comment] 2024-02-23 09:21
@Draganlazarev90 

As a workaround, you can try to provide the service on the parent component rather than the module until we fix the issue. Somehow it skips the module providers, we're investigating the issue. It may work with standalone since there isn't a module and services are provided in the component.ts

I'll transfer the issue to the next milestone, we want to solve the issue without adding `environmentInjector` property to the config since it has to be done by the component itself. But in the opposite scenario, we may add it as a quick solution until we fix it for good.

**Comment by cetincakiroglu** [comment] 2024-03-06 07:42
Hi,

After the investigation, we've found the issue caused by injection level difference. You're providing dialogService in the component level and demoService in the module level. Because of this, dialogService fails to find and inject DemoService. It works as expected if both of them are provided at the same level. That's why injecting the DemoService to the component.ts makes it work. Please see the example: https://stackblitz.com/edit/7qkchf-expefk?file=src%2Fapp%2Fdemo%2Fdemo.module.ts

To provide a better guide, we'll update the documentation of DynamicDialog and mention this use. Thanks a lot for reporting the issue!

I am closing the issue since the solution is provided.

**Closed by cetincakiroglu** 2024-03-06 07:42 UTC
Labels: Type: Bug, Resolution: Needs More Information

**Comment by abhijit-chikane** [comment] 2024-12-06 06:56
![image](https://github.com/user-attachments/assets/c34295e9-5216-4687-9754-44fd6cd2a754)

I have provided the dependencies on the route level
and moving the dialogService to this provider doesn't solve this issue
