### ISSUE TITLE
p-dropdown onChange - return null when using keyboard navigation

### ISSUE THREAD

**Issue by AvshT** [primefaces/primeng#10940] opened 2021-12-08 07:55 UTC
When using the keyboard navigation in the dropdown dialog, the **onChange** emits on every Up/Down navigation.
The $event object values are:
**{originalEvent, value}**
The originalEvent returns null, it's supposed to have the keyboard event object.

@yigitfindikli Link to the specific line:
[94e7c5b#r61496329](https://github.com/primefaces/primeng/commit/94e7c5b3fdf816e3cd4f20afcf36467adb15a6bc#r61496329)

Thank you for your support.

**Comment by yigitfindikli** [comment] 2021-12-08 08:44
Hi @AvshT,

Issue reports should be clear and reproducible. Firstly, your commit(You can directly refer to the file. Reason of that commit is v9 and IVY support.) refer is irrelevant and the issue is reproducible with standalone dropdown too. Please create stackblitz example or example project next time. Thanks for the report, will be fixed in the next version.

Regards.

**Comment by yigitfindikli** [comment] 2021-12-08 08:45
https://github.com/primefaces/primeng/commit/5d2ec15cdba1dfad6ef6d5cfb5e39162626b98ae

**Closed by yigitfindikli** 2021-12-08 08:45 UTC
Labels: defect, LTS-PORTABLE
