### ISSUE TITLE
AutoComplete: ArrowDown key no longer opens up the suggestions panel

### ISSUE THREAD

**Issue by timandella** [primefaces/primeng#14163] opened 2023-11-21 11:32 UTC
### Describe the bug

In PrimeNg 16.6.0, pressing the ArrowDown key in the AutoComplete control box would open up the suggestions panel with any previously loaded suggestions.

With 16.7.0 and above does not happen. You have to type some some actual text to get it to show. If you were to press ESC, the panel closes, and ArrowDown can no longer be used to show it again

### Environment

Angular and PrimeNG, running on a Windows 11 box

### Reproducer

https://stackblitz.com/edit/nrt6yx?file=package.json

### Angular version

16.2.12

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.1

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Go to the Stackblitz page shown
2. Click on the searchbox to focus on it
3. Click the Arrow Down
4. Type "un"
5. Press ESC (to close the suggestion panel)
6. Click the Arrow Down again

### Expected behavior

For steps 3 and 6, the suggestions panel should appear, with a list of countries (For step 3, all countries should be listed. For step 6, the 3 matching countries would be listed).

The expected behaviour works fine in 16.6.0

**Comment by timandella** [comment] 2024-01-02 15:35
I see there is a fix for this, but one that seems to be going nowhere (due to the Pull Request containing fixes for other things, it seems).

Would it help if I created a separate pull request, containing just the fix to auto-complete, and nothing else? (The issue is causing a hold-up where I work. We want to update to 17, but our tests fail due to this Arrow Down not working)

**Comment by cetincakiroglu** [comment] 2024-03-22 13:48
Hi,

It's made by design. We've updated all Prime UI Libraries during the accessibility implementation. This behavior is intended. Closing the issue.

**Closed by cetincakiroglu** 2024-03-22 13:48 UTC
Labels: Status: Needs Triage

**Comment by timandella** [comment] 2024-03-22 14:33
I don't suppose you could elaborate as to how removing this functionality is an accessibility improvement? It seems like it makes it less accessible.  How could the drop down be opened (apart from having to typing a new letter, or delete on, unnecessarily)

Also, for dropdown control, when that has focus, pressing arrowdown opens the drop-down, so there seems to be some inconsistency here.

**Comment by RezaMakvandi** [comment] 2024-04-15 06:36
same problem, please fix this issue
