### ISSUE TITLE
Can ‘Dropdown’ add grouping function？

### ISSUE THREAD

**Issue by mokeyish** [primefaces/primeng#3185] opened 2017-06-23 07:03 UTC
![baidushurufa_2017-6-23_14-54-54](https://user-images.githubusercontent.com/16131917/27470060-b2b6d826-5824-11e7-8576-235d6bc697e5.png)

**Comment by cagataycivici** [comment] 2017-06-23 07:08
Duplicate of #1221

**Closed by cagataycivici** 2017-06-23 07:08 UTC
