### ISSUE TITLE
Time in maxDate disregarded when max date range is picked

### ISSUE THREAD

**Issue by Serhatkemal** [primefaces/primeng#5590] opened 2018-04-19 14:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/TRTbEoeoaCmLPsnlMjn1?p=preview

**Current behavior**

Currently, when I pick  max range date as max value, time value is disregarded and is set to "00:00". ("26-04-2018" on plunkr case)

**Expected behavior**

It needs to set time value which is picked.

**Minimal reproduction of the problem with instructions**

1. Go to the plunkr provided above
2. Pick "16-04-2018 16:51" as minDate and "26-04-2018 16:51" as maxDate
3. Notice that the date used as min date contains a time value("16:51") but max date contains "00:00".

**Please tell us about your environment:**
**PrimeNG version:** 4.3.0 and above

**Comment by cagataycivici** [comment] 2018-12-17 07:56
This should be fixed already by @yigitfindikli please review.

**Comment by yigitfindikli** [comment] 2018-12-17 21:37
I think it's not a bug. If you want use all hours and minutes, you should give it maxDate this way
`maxDate: Date = new Date("2018-04-25T20:59:59");` instead of `maxDate: Date = new Date("2018-04-25T21:00:00.000Z");.`

**Closed by yigitfindikli** 2018-12-17 21:37 UTC
Labels: pending-review
