### ISSUE TITLE
dropdown button don´t work

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#3946] opened 2017-09-14 13:19 UTC
[ x ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
when i click on  "dropdown" button the suggestion don´t display

**Expected behavior**
display suggestions when i click on "dropdown" button

**Minimal reproduction of the problem with instructions**
<p-autoComplete [(ngModel)]="value" [dropdown]="true" (onDropdownClick)="complete($event)"  [suggestions]="suggestions" (completeMethod)="complete($event)" (onSelect)="select($event)">
        </p-autoComplete>

* **Angular version:** 4

* **PrimeNG version:** 4.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pecko** [comment] 2017-09-14 15:27
See https://github.com/primefaces/primeng/issues/3829

**Comment by cagataycivici** [comment] 2017-09-15 07:48
Duplicate of 3829

**Closed by cagataycivici** 2017-09-15 07:48 UTC
