### ISSUE TITLE
p-table does not fire sort event when header text is wrapped by html element

### ISSUE THREAD

**Issue by jupin-r** [primefaces/primeng#8642] opened 2020-03-20 13:42 UTC
I'm submitting a bug
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Bug Demo**
https://stackblitz.com/edit/github-2cuk1q

**Current behavior**
The prime table is not sorted if user clicks to header text of the colum and this text is wrapped by html element e.g. span. The table is successfully sorted if you click on sort icon or header except text.

**Expected behavior**
The prime table should sort data if user clicks to header text. It doesn't matter if header text is wrapped by html element or not.

* **Angular version:** 9.X
* **PrimeNG version:** 9.X

* **Browser:** all

**Comment by cagataycivici** [comment] 2020-03-20 16:14
Duplicate of;

https://github.com/primefaces/primeng/issues/8597

**Closed by cagataycivici** 2020-03-20 16:14 UTC
