### ISSUE TITLE
Component: Input OTP backspace not working in Android Mobile

### ISSUE THREAD

**Issue by vikramthangaraj** [primefaces/primeng#15615] opened 2024-05-18 19:19 UTC
### Describe the bug

Input OTP backspace not working in Android Mobile

### Environment

Android Backspace

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Android Browsers

**Comment by cetincakiroglu** [comment] 2024-05-30 12:33
Duplicate of https://github.com/primefaces/primeng/issues/15613

Closing the issue

**Closed by cetincakiroglu** 2024-05-30 12:33 UTC
Labels: Status: Needs Triage
