### ISSUE TITLE
Provide facilities to preserve and restore the full state of the p-dataTable component.

### ISSUE THREAD

**Issue by llech** [primefaces/primeng#1311] opened 2016-11-15 11:16 UTC
The p-dataTable componen has already bindings for sortField/sortOrder, that enable to save the sort state and restore it when the user comes back in navigation, for example from editing a row on separate page.

However, to fully restore the state of the datatable, one need to set column filters and paginator state (what page is selected). Actually, I see in the docs no API method that would allow me to do that. The best way would be providing data bindings for current paginator page and filter column value. It would allow to implement fully professional  behaviour of the component.

**Comment by rmarchiori** [comment] 2016-11-21 20:44
+1 That'd be great to have

**Comment by myElectrical** [comment] 2016-12-01 11:38
+1 This is almost essential if users have large data tables (and switch back and forth to an edit page).

**Comment by ralph-fuechtenkort** [comment] 2016-12-13 00:40
+!. I believe you have that feature in the java version.

**Comment by gregkopp** [comment] 2017-01-13 17:44
Would like to see this native, but I am attempting to implement this manually. Of course, I can save the values of the filters for each column by using my own template, but is there an option to programatically set a filter on a given column? I could enumerate through my columns and manually set the filter.

**Comment by gregkopp** [comment] 2017-01-13 18:43
+1

**Comment by dereklin** [comment] 2017-02-20 08:05
+1

**Comment by hugograf** [comment] 2017-05-05 05:57
+1

**Comment by cagataycivici** [comment] 2017-06-07 06:36
Duplicate of #304

**Closed by cagataycivici** 2017-06-07 06:36 UTC
