### ISSUE TITLE
Datatable sortField Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by newrajneesh** [primefaces/primeng#1792] opened 2017-01-11 19:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The bug has been reproduced in Plunkr below

http://plnkr.co/edit/EHGbs9MdUjvh1CXT11S6?p=preview

**Current behavior**
Providing  sortField value in datatable causes following error :-
TypeError: Cannot read property 'find' of undefined
    at DataTable.ngDoCheck (datatable.ts:633)
    at Wrapper_DataTable.ngDoCheck (wrapper.ngfactory.js:506)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (component.ngfactory.js:175)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (core.umd.js:12584)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (core.umd.js:12731)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (core.umd.js:12569)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (host.ngfactory.js:29)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (core.umd.js:12584)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (core.umd.js:12731)
    at ViewRef_.detectChanges (core.umd.js:9800)

**Expected behavior**
sortField should work without issues

**Minimal reproduction of the problem with instructions**
Reporduced in Plunkr:
http://plnkr.co/edit/EHGbs9MdUjvh1CXT11S6?p=preview

**What is the motivation / use case for changing the behavior?**
Default sorting of column in table

**Please tell us about your environment:**
windows

* **Angular version:** 2.4.2

* **PrimeNG version:** 1.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment] 2017-01-11 20:04
Duplicate of #1789

**Closed by cagataycivici** 2017-01-11 20:04 UTC
