### ISSUE TITLE
 Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by harounchebbi** [primefaces/primeng#8093] opened 2019-08-27 11:06 UTC
When I enabled the ivy renderer in my existing angular app , primeng components stopped working with the following errors. 
![Screenshot from 2019-08-27 11-52-45](https://user-images.githubusercontent.com/24281282/63765588-45fd9200-c8c1-11e9-890a-fe5760878593.png)
Is there anyone here who experienced the same problem when working with ivy renderer?
any help is greatly appreciated.

**Comment by jdell64** [comment] 2019-12-17 19:55
Related issue is closed, this issue remains.

Having this issue on 9.0.0-rc.2 for the SharedModule

**Comment by schungx** [comment] 2020-02-08 09:22
Issue remains on official Angular 9.0.0.

It is happening on an old library.

**Comment by ARTWINPRO** [comment] 2020-02-08 14:32
The same!
![image](https://user-images.githubusercontent.com/16427316/74086954-9c861380-4a90-11ea-9aa4-640fe58b294c.png)

**Comment by FouomaOscar** [comment] 2020-02-09 23:15
I have the same issue with Angular/cli 9.0.1

**Comment by djguzmancslab** [comment] 2020-02-09 23:37
Setting "aot": "false" inside angular.json file worked for me.

**Comment by ARTWINPRO** [comment] 2020-02-10 09:30
Guys, i have some solution but im not sure how currect it is.

```
1. "buildOptimizer": false,
2. "enableIvy": true
3. "aot": false,

```
Before do this refactoring, application size is: 18 440KB;
After: 17 887KB

**Comment by sontisubramanyam** [comment] 2020-02-10 17:22
The problem is Directives are declared in imports (module.ts)
Right way==>directives will import in declarations (module.ts)

same problem was happened for me. now my issue is solved

**Comment by reeshabh-credivia** [comment] 2020-02-11 05:48
> The problem is Directives are declared in imports (module.ts)
> Right way==>directives will import in declarations (module.ts)
> 
> same problem was happened for me. now my issue is solved

Can you elaborate what you did exactly?

**Comment by itstherussian** [comment] 2020-02-11 09:40
> > The problem is Directives are declared in imports (module.ts)
> > Right way==>directives will import in declarations (module.ts)
> > same problem was happened for me. now my issue is solved
> 
> Can you elaborate what you did exactly?

What worked for me was to remove the problematic directive from @NgModule({
  imports: [...]}) 

and add it to

@NgModule({
  declarations: [...]})

**Comment by destus90** [comment] 2020-02-11 11:48
I have just upgraded my project to the newest version of Angular. I get this error too. I search a workaround for this.

**Comment by chaselw** [comment] 2020-02-11 15:56
Same issue on latest. "aot": false in Angular.json worked for me

**Comment by destus90** [comment] 2020-02-12 06:27
I was wrong. I've upgraded `Angular`, but forgot to update `Primeng` to the newest rc's version. `npm-check-updates` doesn't show available unstable packages without  `--newest` flag. 
Now everything works fine.

**Comment by snopbear** [comment] 2020-02-13 12:47
> Setting "aot": false inside angular.json file worked for me.

Yap it was fabulous

**Comment by houdass** [comment] 2020-02-14 08:07
Hi guys, I figured out what going wrong, I had a Angular 8 project (containing a library project) that I have upgraded to Angular 9 (with a lib also: ng generate library core, I created at first a new angular 9 project to compare the differences with my project made with ng 8, i figure out that there is some things missing, here is the steps I followed:
- Delete node_modules
- Delete dist folder
- In the Angular 9 project lib there is a new file called: tsconfig.lib.prod.json 
```
{
  "extends": "./tsconfig.lib.json",
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```
- In your angular.json add the following:
```
{
  ...
  "projects": {
     ...
     "configurations": {
            "production": {
              "tsConfig": "projects/core/tsconfig.lib.prod.json"
             }
      }
  ...
  }
}
```
- run ng build --prod, and everything will work :D

PS: in this case the library is called "core"

**Comment by PritiMaurya** [comment] 2020-02-14 09:27
I have the same issue with Angular/cli 9.0.1

**Comment by destus90** [comment] 2020-02-17 03:53
The same issue is here
https://github.com/angular/angular/issues/35447

**Comment by schungx** [comment] 2020-02-20 01:27
For me, I ended up having to upgrade that particular old library to the latest version (which I should have done ages ago, but hey...  lazy and stuff...)  That library dated back to Angular 2 days.

With the old Angular 2.x library, it only builds with Angular 9 if you sent `aot=false` and do a non-production build.  Production builds or `aot=true` will trigger this error.  Nevertheless, the build will not run as webpack errors will start showing up.

Therefore, my suggestion is to upgrade whatever old dependencies to newer versions.  This sucks because it means that libraries written for older Angular versions now break with Angular 9.  They have all been working flawlessly up till version 8.

**Comment by pklejnowski** [comment] 2020-02-20 13:07
Is there any way to make it work with `aot=true` and Angular 9? 
I have the same problem with UpgradeModule in my Hybrid Application
![image](https://user-images.githubusercontent.com/28590512/74936402-5adb5e00-53ea-11ea-8955-5048eca34f5b.png)

**Comment by andreialecu** [comment] 2020-02-28 08:12
If you use yarn workspaces or lerna, the error might be related to hoisting. Repro at: https://github.com/angular/angular/issues/35747

**Comment by harounchebbi** [comment] 2020-03-04 10:45
The issue is now resolved after upgrading primeng to version ^9.0.0 in package.json.

**Comment by igormap42** [comment] 2020-03-12 11:38
> 
> 
> The issue is now resolved after upgrading primeng to version ^9.0.0 in package.json.

This was my issue, thanks

**Comment by cagataycivici** [comment] 2020-03-29 13:40
Closing as compatible PrimeNG version fixes the case.

**Closed by cagataycivici** 2020-03-29 13:40 UTC

**Comment by blue113** [comment] 2020-06-29 23:29
![image](https://user-images.githubusercontent.com/30907188/86065844-4afb1700-ba79-11ea-8a42-6d4cda192974.png)

I had also like this issue while working on Angular 9.0.2 with Angular Material.
I'd like to know it can't be resolved with angular material.

**Comment by kumaresan-subramani** [comment] 2020-09-22 11:32
This error shows when you add component declaration in `imports: []` instead of `declarations: [],` 

e.g:

```
declarations: [
  AppComponent,
],
imports: [
  BrowserModule,
  AppRoutingModule,
  SomeComponent <-----------wrong
],
```

**Comment by new10ce** [comment] 2020-12-23 17:17
Thanks @kumaresan-subramani.
I got solution from your comment.

**Comment by Boddha** [comment] 2021-04-19 16:23
Thanks @kumaresan-subramani. It was as simple as that.

**Comment by JuniorBaymax** [comment] 2021-11-30 09:41
The best way to solve this problem you can find it on stackoverflow thread

https://stackoverflow.com/questions/66005232/angular-type-pipe-does-not-have-%C9%B5mod-property?newreg=c16eb0cd7ee64d0db16cdaa6d9b0f111

`  declarations: [AppComponent, CoursesComponent, AuthorsComponent, SummaryPipe] // import module in declarations part and put that module in exports array

exports:[SummaryPipe]
,
`
