### ISSUE TITLE
Table: Resize column not working correct in fit mode

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#12289] opened 2022-11-28 09:31 UTC
### Describe the bug

When I try to resize a table column (in fit mode) to a large size, nothing happens and the width does not change.
In "Expand mode" it is working.

Issue also occurs in PrimeNG v8-v15.

### Environment

Windows and Chrome

### Reproducer

https://www.primefaces.org/primeng-v14/table/colresize

### Angular version

14.0.4

### PrimeNG version

14.2.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng-v14/table/colresize
2. Try to move the right handle of the "Code column" into the "Category" or "Quantity" column.
3. Nothing will happen - the column widths will not change. (it only changes when moving the handle into the "Name column")

### Expected behavior

The column resizing should also work when making bigger resizings (over multiple columns).

**Comment by cetincakiroglu** [comment] 2022-12-02 12:14
Hi,

That's not a bug it's by design. However, it is a good enhancement request idea. Opening a new issue and closing this, you can track development progress from [here](https://github.com/primefaces/primeng/issues/12320)

**Closed by cetincakiroglu** 2022-12-02 12:14 UTC
Labels: Resolution: By Design

**Comment by PranKe01** [comment] 2023-07-06 08:12
Still not working with PrimeNG v16.0.2.

**Comment by PranKe01** [comment] 2024-01-09 10:09
@cetincakiroglu  Dropping the resizer on another cloumn still does not work in v17.3! Why is this closed?
