### ISSUE TITLE
AutoComplete Advanced can not type Chinese, but Multiple can

### ISSUE THREAD

**Issue by zhangsanshi** [primefaces/primeng#1317] opened 2016-11-16 03:06 UTC
The test page is
[http://www.primefaces.org/primeng/#/autocomplete](http://www.primefaces.org/primeng/#/autocomplete).
I also test copy word(like: 我是小明) and It's work.

describe:
When I type the word，the Input method will show and hide in a very short time, so I can't select any Chinese.

**Comment by cagataycivici** [comment] 2017-06-07 06:34
Duplicate of #1318

**Closed by cagataycivici** 2017-06-07 06:34 UTC
