### ISSUE TITLE
AutoFocus: Does not work inside dialog

### ISSUE THREAD

**Issue by Urtgard** [primefaces/primeng#12720] opened 2023-03-07 20:21 UTC
### Describe the bug

If AutoFocus is used inside a dialog, focus is not applied to the element.

### Environment

 Stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-dialog-demo-u6rtzk?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.spec.ts,src%2Fapp%2Fapp.component.html

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Steps to reproduce the behavior

Use autofocus inside a dialog.

```html
<p-dialog [(visible)]="displayBasic">
  <input
    type="text"
    pInputText
    placeholder="Automatically focused"
    pAutoFocus
    [autofocus]="true"
  />
</p-dialog>
```

### Expected behavior

Dialog opens and focus is applied to the element.

**Comment by nvkuznetsova** [comment] 2023-04-11 11:53
I have the same issue inside dynamic dialog

**Comment by jgaston5** [comment] 2023-04-18 18:49
I believe that this issue is related to the fix for #12319. It nolonger looks for the autofocus element, but rather just grabs the first focusable item.

**Comment by alvarosinmarca** [comment] 2023-07-02 19:15
Same error with version primeng 16.0.2

**Comment by cetincakiroglu** [comment] 2023-07-21 09:48
This happens because autoFocus is applied on the initial load of the page rather than the component, that's how the autofocus attribute works in a webpage. That directive's sole purpose is to give autofocus property in the correct way, some html attributes need to be assigned in a different way because of virtual dom. In your example, autofocus does the job and focuses on the first element, as I mentioned it does not work in component-wise, component initialization is not the case with HTML autofocus attribute it only works on the initial load of the webpage.

Because of this, autofocus will not work when the component is initialized and that's why the input inside the dialog doesn't receive focus since autofocus is already applied at the initial load to a different element. Instead, you can implement it manually as below, please see the refactored example. 
Closing the issue since it's a misunderstanding of the autofocus attribute, thanks for reporting!

https://stackblitz.com/edit/primeng-dialog-demo-hruxst?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Closed by cetincakiroglu** 2023-07-21 09:48 UTC
Labels: Status: Needs Triage

**Comment by alvarosinmarca** [comment] 2023-07-22 11:05
@cetincakiroglu Thx for you example, but you example use **<p-dialog>** in **html**. I need use **dynamic dialog**. https://primeng.org/dynamicdialog

**Comment by VolodymyrKornetskyi** [comment] 2023-07-27 15:18
@alvarosinmarca I have the same issue with dynamic dialog and don't know how to deal with this issue. Have you found any solutions already?

**Comment by VolodymyrKornetskyi** [comment] 2023-07-27 15:34
@alvarosinmarca I found 2 not good ways to handle this issue. I removed focus css for first focusable item. But from source code it seems you can provide tab-index -1 and then they will skip your items. Not sure it can help you somehow.

**Comment by alvarosinmarca** [comment] 2023-09-12 11:50
@VolodymyrKornetskyi I didn't find a solution, i will try your solution. Thank you!

**Comment by jonesisg1** [comment] 2023-10-04 12:57
There is still an issue with autofocus="true" inside a dialog.
My bodge:
```
    myDialog.value = true;
    await nextTick();
    document.getElementById("myInputText").children[0].focus();
```

**Comment by angelo-v** [comment] 2024-02-26 08:00
I can confirm this is still an issue, please reopen. Here is a reproducer:

https://stackblitz.com/edit/stackblitz-starters-98gaxj?file=src%2Fmain.ts

**Comment by gianluca-moro** [comment] 2024-05-14 11:59
I am currently facing the same issue and it would be really nice if this would work withouth having to implement a weird workaround. Thanks.

**Comment by graficon** [comment] 2024-07-11 18:17
Facing the same issue.

**Comment by dheitzer** [comment] 2025-05-17 17:39
still failing in 2025

**Comment by SamuelKnoch** [comment] 2025-06-03 14:31
Setting the focusOnShow on the dialog to false fixed it for me 

```html
<p-dialog
    [modal]="true"
    [visible]="dialogOpenState()
    [focusOnShow]="false"
>

  <input
    type="text"
    pInputText
    [(ngModel)]="searchTerm"
    [pAutoFocus]="true"
  />

</p-dialog>
```

**Comment by BGBRWR** [comment] 2025-08-14 16:05
The behavior has changed after this commit https://github.com/primefaces/primeng/commit/7e413fdd411aeeef2b7630a05a7da23816d9f35b. It will focus on footer, header, then content. Since the default value of `this.contentViewChild.nativeElement` is removed it doesn't check for the content first on https://github.com/primefaces/primeng/blob/master/packages/primeng/src/dialog/dialog.ts#L993.
