### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#625] opened 2016-07-19 04:27 UTC
Could you please add file upload widget like in primefaces. I need it.

**Comment by GraemeSMiller** [comment] 2016-07-27 17:26
Dupe of this request https://github.com/primefaces/primeng/issues/104

**Comment by sudheerj** [comment] 2017-04-26 07:26
The component is already available.So this issue can be closed.

**Closed by sudheerj** 2017-04-26 07:26 UTC
