### ISSUE TITLE
OverlayPanel - cannot use inside divs with position: relative

### ISSUE THREAD

**Issue by Etchelon** [primefaces/primeng#676] opened 2016-07-28 10:18 UTC
Hello,
I have this html:
```
[... other html]
<div style="position: relative">
    [...]
    <p-dataTable>
        <p-column>
            <template>
                <button type="button" (click)="togglePanel($event, panel)"></button>
            </template>
        </p-column>
    </p-dataTable>
    <p-overlayPanel #panel>
        Content
    </p-overlayPanel>
</div>
```
When clicking the button, the overlay panel appears a bit below the button. This offset is roughly equal to the height of [...other html]. I inspected the div inside the <p-overlayPanel> and noticed a position absolute with something like top: 300px. Obviously the 300px start from its closest non static parent, instead of the window.
Therefore, in order to fix it, I think you should move and append the panel to the <body> element, like kendoNotification from the Telerik kendoUi framework does. Or do something else, because as it is the correct behavior of the OverlayPanel depends on the developer to place it in the correct place.

**Comment by cagataycivici** [comment] 2016-08-02 08:56
Fixed via #679. Try appendTo="body".

**Closed by cagataycivici** 2016-08-02 08:56 UTC
Labels: defect

**Comment by phanisri456** [comment] 2017-05-19 03:43
appendTo="body" is not working. First time it is opening offscreen. Is there any other solution.

**Comment by captainkovalsky** [comment] 2017-06-01 06:28
Issue is still active

**Comment by captainkovalsky** [comment] 2017-06-01 07:04
@phanisri456 I tried, it works fine. Could you provide a reproducible  plunker example?

**Comment by saikiranmandhala** [comment] 2017-06-12 11:57
I am also facing the same issue. I have a label inside a row grouped datatable. Clicking on the label showing overlay-panel far way from button.

**Comment by cagataycivici** [comment] 2017-06-12 12:00
You need appendTo="body" on overlay panel to solve this. It works for me. Provide a plunkr to request a reopen please.

**Comment by saikiranmandhala** [comment] 2017-06-12 13:03
oooffffo!! It is bootstrap which is messing up with the top style property of p-overlaypanel. 
I have inspected it and solved. Basically i have had a bootstrap div class="col-md-12" and <panel> containing the p-datatable and p-overlaypanel. Once i removed them it started working fine.
 So there is no issue with overlay panel.
Thanks **cagataycivici** !

**Comment by cosnochic** [comment] 2017-09-11 18:32
appendTo="body"  works better for me. Only thing is - The content shows up on the left side when I need it on the right side. Anyone know how to do this?

**Comment by jonbarthol** [comment] 2018-03-13 15:54
@cagataycivici it would be nice if p-overlayPanel could do relative positioning like p-dropdown. Using appendTo="body" doesn't work well in the case the p-overlayPanel is inside a p-dialog. This causes z-index problems where the p-overlayPanel ends up underneath the p-dialog.

**Comment by carlesfelix** [comment] 2020-01-15 14:57
I have the same issue. If you append to body the overlay it will stay fixed when you scroll.
For instance:
- I have a list in a relative div (overflow: scroll).
- When I click a button in a item and I scroll this list (with appendTo=body) the overlay won't scroll.
I tried setting a target but the position stills wrong.
I tried to force to set the position to top: 0 !important and left: 0 !important but it doesn't work.
Are there an alternative to fix that without appendTo=body?

**Comment by JavatarJr** [comment] 2023-02-02 07:35
Triggering the event based on element #id worked for me. By doing the toggle from typescript, I was able to pin point the element I need to attach the overlay panel. 

HTML: 
<div>
     <p-table>
          <--loop the data-->
          <button pButton (click)="showOP($event, rowwiseData, 'button'+rowIndex)" [id]="'button'+rowIndex"></button>
      </p-table>
</div>
<--outside of the table add the overlay menu-->
<p-menu #menu [popup]="true" [model]="panelData"></p-menu>

TS File:
panelData: any;
@ViewChild('menu', {static: false}) op: OverlayPanel;

showOverlayPanel($event: MouseEvent, rowwiseData: any, id:string) {
	this.panelData = rowwiseData;
	this.op.toggle($event,document.getElementById(id));
}
