### ISSUE TITLE
Enabling + disabling Tabs in Tabview, view not updated

### ISSUE THREAD

**Issue by keschr** [primefaces/primeng#9386] opened 2020-10-09 12:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://stackblitz.com/edit/primeng-tabview-demo-xwszmj?file=src/app/app.component.html

**Current behavior**
I want to dynamical enable and disable tabs inside the tabview. The status is stored in an attribute, if i update the attribute to true or false the tabview does not update the view. I can click on the Tab and it is working but it still has the class p-disabled.

**Expected behavior**
if the tab is enabled the component should react on the change and remove p-disabled attribute.

* **Angular version:** 10.X

* **PrimeNG version:** 10.X

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by cagataycivici** [comment] 2020-10-11 16:43
Duplicate of https://github.com/primefaces/primeng/issues/9367

**Closed by cagataycivici** 2020-10-11 16:43 UTC
Labels: duplicate
