### ISSUE TITLE
Dialog not closing on escape

### ISSUE THREAD

**Issue by shogogan** [primefaces/primeng#7407] opened 2019-03-19 19:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-erqvb2

**Current behavior**
When you have a dialog with a component that uses domhandler zindex(and increments it), it closeOnEscape stops working.

**Expected behavior**
When there is only the dialog on the screen (changed anything on it, opened calendars and things like that), when escape is pressed, it should close the dialog (if closeOnEscape is true)

**Minimal reproduction of the problem with instructions**
Create a dialog with closeOnEscape true.
put a Calendar in it.
Open de dialog.
click on the calendar.
Escape not working anymore.

https://stackblitz.com/edit/github-erqvb2

* **Angular version:** 7.2

* **PrimeNG version:** 7.1.0

* **Browser:** [all ]

**Comment by noamichael** [comment] 2019-04-09 13:09
[I've found the line that causes the problem](https://github.com/primefaces/primeng/blob/aee61bc2f1c0646b8f24413151e19578b01ba768/src/app/components/dialog/dialog.ts#L594):

```typescript
this.documentEscapeListener = this.renderer.listen('document', 'keydown', (event) => {
    if (event.which == 27) {
            if (parseInt(this.container.style.zIndex) === (DomHandler.zindex + this.baseZIndex)) {
                this.close(event);
            }
        }
});
```

I think the idea is that if you have nested overlay components (like your example with the Dialog and the Calendar), when the escape key is pressed, only the component with the highest zindex should close. So, in this case, the calendar would close but not the dialog. The issue is nothing ever decrements the zindex, so the dialog will never close.

I don't know if it's safe to decrement the last assigned zindex because we always want newly created overlays to be positioned on top, so another possible solution is to have a `LastOpenedOverlay` service (or something to that effect) which would track the last opened overlay and automatically close it on escape. If we go that route, we only need one `documentEscapeListener`. @cagataycivici, thoughts?

**Comment by shogogan** [comment] 2019-04-16 17:54
Maybe one idea would be on focusing on the dialog it sets it as the next closeable with escape key?

**Comment by jiangyh1024** [comment] 2019-05-08 08:25
I have the same problem. And currently, I add my own logic to solve this problem

1. in afterviewinit life cycle, remove default keydown event
2. add my own logic


```
 // remove default escape listener, it has bugs
    this.dialog.unbindDocumentEscapeListener();


    const id = +this.dialog.id.replace('ui-dialog-', '');
    const baseTabIndex = 50000;

    // set tabindex, so we can get it through document.activeElement if focus is on dialog
    this.dialog.el.nativeElement.setAttribute('tabindex', baseTabIndex + id);

    // implement our own logic
    this.removeEscapeListenerFn = this.renderer.listen('document', 'keydown', (event: KeyboardEvent) => {
      if (event.which === 27) {
        if ((document.activeElement === this.dialog.el.nativeElement &&
          document.activeElement.contains((event.target as any))) ||
          (this.dialog.el.nativeElement.contains(document.activeElement))) {
          Dialog.prototype.close.apply(this.dialog, [event]);
        }
      }
    });

```

**Comment by jiangyh1024** [comment] 2019-05-08 09:09
I don't know if it has bugs, but for me, now, it works

**Closed** 2019-06-03 07:43 UTC

**Comment by gmerabishvili** [comment] 2020-04-15 11:37
@cagataycivici Is this issue solved in latest primeNG version?
