### ISSUE TITLE
Feature request: Ability to group rows based on the value of a column

### ISSUE THREAD

**Issue by shahmirn** [primefaces/primeng#612] opened 2016-07-15 16:54 UTC
If a person wants to display a list of countries and cities in that country, it'd be nice to be able to display the name of the country as the group name, with the cities being the values in that group.

For sorting, the row groups should themselves be sortable via parameters on the <p-dataTable> tag, and for the row data, they should respect the rows while sorting.

See https://datatables.net/examples/advanced_init/row_grouping.html for a visual representation (the example doesn't respect the row groups when sorting data, which is not ideal)

**Comment by cagataycivici** [comment] 2016-12-08 08:01
Duplicate of #403

**Closed by cagataycivici** 2016-12-08 08:01 UTC
