### ISSUE TITLE
Carousel displays last page when circular=true

### ISSUE THREAD

**Issue by aviad-chen-apolicy** [primefaces/primeng#8993] opened 2020-07-02 06:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When using the p-carousel with the circular option set to true, the first page displayed is the last page of the carousel. My items are ordered and because of this behavior, they are displayed the exact opposite of what's expected.

**Expected behavior**
Expect to see the first page of items per the numVisible property.

**Minimal reproduction of the problem with instructions**
<p-carousel [value]="recommendations" [numVisible]="4" [numScroll]="4" [circular]="true">
  <ng-template let-car pTemplate="item">
  </ng-template>
</p-carousel>

**What is the motivation / use case for changing the behavior?**
The carousel should be ordered

**Please tell us about your environment:**

* **Angular version:** 5.X
9

* **PrimeNG version:** 5.X
9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS all

**Comment by yigitfindikli** [comment] 2020-11-26 12:04
Duplicate of #8993

**Closed by yigitfindikli** 2020-11-26 12:04 UTC
Labels: pending-review

**Comment by aviad-chen-apolicy** [comment] 2020-11-26 13:19
You wrote that it's a duplicate of the actual issue... @yigitfindikli
