### ISSUE TITLE
Calendar appears over input field on smaller screens

### ISSUE THREAD

**Issue by SammyIsra** [primefaces/primeng#7502] opened 2019-04-04 17:15 UTC
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-zubkf5 (expand the console area so that it covers 3/4 of the preview window)

**Current behavior**
The calendar is opened over the input element, the user cannot see the input field if they decide to type in the date.

**Expected behavior**
Regardless of window size the calendar field should allow the user to see the input field in case they want to type in the 

**Minimal reproduction of the problem with instructions**
Create a calendar field that is not inline, shrink the window and then open the calendar field.

**What is the motivation / use case for changing the behavior?**
In smaller screens and windows the user should still be able to type in a date if they want to. If the calendar field expands over the input field, it is difficult to do so.

**Please tell us about your environment:**

Windows 10
VSCode
NPM for package manager

* **Angular version:** 
7.2.9

* **PrimeNG version:** 
7.1.0

* **Browser:** 
all
 
* **Language:**
all

**Comment by JacobSiegle** [comment] 2019-04-04 22:16
This is a duplicate of #7329

**Comment by cagataycivici** [comment] 2020-03-19 10:20
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Closed by cagataycivici** 2020-03-19 10:20 UTC
