### ISSUE TITLE
RC3 Bug: p-datatable checkboxes don't work with selectionMode="multiple" and [metaKeySelection]="false"

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#3326] opened 2017-07-06 22:36 UTC
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/PZmejV6KWU7Ev7OtKE0R/

**Current behavior**
When both multiple selection mode is enabled and metaKeySelection is set to false, if you click the **checkbox** to select a row, nothing happens. If you watch the events you will see that it was selected and then immediately unselected due to firing a select for both the checkbox and the row click.

Bug is only present in RC3, RC2 and previous worked correctly.

**Expected behavior**
Clicking the checkbox would select the row.

**Minimal reproduction of the problem with instructions**
See plunkr.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:** N/A

* **Angular version:** 2.0.X

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** all
 
* **Language:** all

**Comment by Mrtcndkn** [comment] 2017-07-07 10:19
Duplicate of https://github.com/primefaces/primeng/issues/3277

**Comment by cagataycivici** [comment] 2017-07-11 07:38
Tracked at 3277

**Closed by cagataycivici** 2017-07-11 07:38 UTC

**Comment by rbehun** [comment] 2022-02-16 15:35
It seems like it's still happens (or happen again). Here is the demo: https://stackblitz.com/edit/primeng-tableselection-demo-4lq7hh?file=src%2Fapp%2Fapp.component.html 

Can we reopen it?
