### ISSUE TITLE
DataTable column width not effective when headerColumnGroup has more than 1 header row

### ISSUE THREAD

**Issue by GopiAnnan** [primefaces/primeng#2275] opened 2017-03-10 22:19 UTC
If thead has 2 row header, first row column width can be divided in second row header with required % or px. but the second row header always equally divided. its default HTML behavior if we have more than 1 row in thead. 

Header 
first row has 3 columns, 
second row has 11 columns.  those 11 divided into 3 columns as 2, 4, 5. 

`<p-headerColumnGroup>
            <p-row>
                <p-column header="Projects" [style]="{'width':'30%'}" colspan="2"></p-column>
                <p-column header="Capital ReAllocation" [style]="{'width':'30%'}" colspan="4"></p-column>
                <p-column header="Capital Additional and Actual Spent" [style]="{'width':'40%'}" colspan="5"></p-column>
            </p-row>
            <p-row>
                <p-column header="Project #" [style]="{'width':'25%'}"></p-column>
                <p-column header="Project Description" [style]="{'width':'75%'}"></p-column>`

HTML Solution for this issue can be found here.  But I think, the actual Implementation has to be changed at DataTable. 

http://stackoverflow.com/questions/13841700/how-can-i-set-the-widths-of-a-two-row-header-table-with-table-layout-fixed

**Comment by GopiAnnan** [comment] 2017-03-10 23:19
Some work around, it adds one more empty th row . still the issue exists. 
`
<p-headerColumnGroup>  
            <p-row>
                <p-column  [style]="{'width':'4%'}"></p-column>
                <p-column  [style]="{'width':'24%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
                <p-column  [style]="{'width':'9%'}"></p-column>
            </p-row>
            <p-row>
                <p-column header="Projects" [style]="{'width':'30%'}" colspan="2"></p-column>
                <p-column header="Capital ReAllocation" [style]="{'width':'30%'}" colspan="4"></p-column>
                <p-column header="Capital Additional and Actual Spent" [style]="{'width':'40%'}" colspan="5"></p-column>
            </p-row>
            <p-row>
                <p-column header="Project #" [style]="{'width':'5%'}"></p-column>
                <p-column header="Project Description" [style]="{'width':'25%'}"></p-column>
`

**Comment by cagataycivici** [comment] 2017-06-20 14:10
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Closed by cagataycivici** 2017-06-20 14:10 UTC

**Comment by billfranklin** [comment] 2017-08-10 15:55
Seems to still be an issue

**Comment by billfranklin** [comment] 2017-08-17 14:06
Here is the Plunkr that shows that the problem still exists

[(http://plnkr.co/edit/mqsJIb?p=preview)]

**Comment by SpiderPork** [comment] 2017-09-13 10:04
Confirming issue with PrimeNG 4.2

**Comment by upstreamosGH** [comment] 2017-09-13 10:24
Same to me, also with the new 4.2.0 release. Headers and fields columns width style does not apply when using headerColumnGroup.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by upstreamosGH** [comment] 2017-09-13 10:35
Same to me, also with the new 4.2.0 release. Headers and fields columns width style does not apply when using headerColumnGroup.

http://plnkr.co/edit/r4livh?p=preview

**Comment by UrzaUrza** [comment] 2017-10-12 08:57
Still an issue in 4.2.2

**Comment by UrzaUrza** [comment] 2017-10-12 11:35
Could this issue be reopened ?
Because many peoples state that it is not fixed.

**Comment by billfranklin** [comment] 2017-10-20 20:00
Yes, please reopen, and fix

**Comment by sebaiona** [comment] 2017-11-24 09:46
Yes please reopen, I have the same problem...

**Comment by xpdlf1004** [comment] 2017-12-28 03:17
Still an issue in 5.0.2

**Comment by madvlad** [comment] 2018-03-27 15:15
@cagataycivici This issue needs to be open. It is still an issue in the current release. This is easy to reproduce.

**Comment by Deyn32** [comment] 2018-04-06 08:58
Helped here is this:
<p-dataTable [tableStyle]="{'table-layout':'auto'}"  
-//-
