### ISSUE TITLE
p-datatable | Row Edit on data table?

### ISSUE THREAD

**Issue by NordRagnarok** [primefaces/primeng#3561] opened 2017-08-03 06:30 UTC
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

```
Question
```
There were quite a lot of issues regarding row edit in the data table,  and all of them were closed, said to be added to roadmap - so now it's not there, and I still can't find a way to enable it.
Does the feature exists? if still not - any idea when it should be available?

I'm refering to the first example here:
[https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml](https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml)

**Please tell us about your environment:**
Chrome, running on Windows.

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.1.2

* **Browser:** all 

* **Language:** TypeScript 2.4.0

**Comment by cagataycivici** [comment] 2017-10-04 11:59
Duplicate of https://github.com/primefaces/primeng/issues/2048

**Closed by cagataycivici** 2017-10-04 11:59 UTC
