### ISSUE TITLE
DataTable Selection Issue with custom content

### ISSUE THREAD

**Issue by PrajwalGonsalves07** [primefaces/primeng#3166] opened 2017-06-21 14:22 UTC
I'm submitting a bug report

**Current behavior**
Selection of a table row does not work if the column field is a div. {The column is templated using ngTemplate} 

**Expected behavior**
Selection of a table row should work irrespective of the underlying element specified through ngTemplate. 

**Minimal reproduction of the problem with instructions**
1. Use this sample data table below and try selecting a row. It does not work. It selects a row once in a while.  However, if you change the div to a span, the selection works smoothly.

<p-dataTable [value]="cars" selectionMode="single" >
    <p-column field="color" header="Color">
        <ng-template let-col let-car="rowData" pTemplate="body">
            <div[style.color]="car[col.field]">{{car[col.field]}}</div>
        </ng-template>
    </p-column>
</p-dataTable>

* **Angular version:**  : 4.1.1

* **PrimeNG version:** : 4.0.1

* **Browser:** [all | Chrome Version 58.0.3029.110 (64-bit)
 
* **Language:** [all | TypeScript

**Comment by PrajwalGonsalves07** [comment] 2017-06-27 11:37
Hey guys, 
Any idea on when this will be fixed ?

**Comment by cagataycivici** [comment] 2017-06-28 14:16
Duplicate of #1485

**Closed by cagataycivici** 2017-06-28 14:16 UTC
