### ISSUE TITLE
DataTable filter removes characters if we type fast

### ISSUE THREAD

**Issue by nareshurs** [primefaces/primeng#3225] opened 2017-06-27 19:40 UTC
I recommended Primeng for my project. We are extensively using prime ng datatables. Now we realized that if we type faster in any datatable filter, even 5 characters continuously  some of the characters are getting lost. It appears it is filtering the characters in background and that is removing some characters which user types.  This can be reproduced in official priming data Table demo:
https://www.primefaces.org/primeng/#/datatable/filter

Version: Angular2.0
OS: Windows10

**Comment by oixan** [comment] 2017-06-27 21:45
same as reported here https://github.com/primefaces/primeng/issues/3004

**Comment by cagataycivici** [comment] 2017-06-28 09:36
Duplicate of #1813

**Closed by cagataycivici** 2017-06-28 09:36 UTC
