### ISSUE TITLE
Dropdowns, multiselect/autoselect close needs two clicks - chrome

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3812] opened 2017-09-01 13:33 UTC
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
In Chrome, dropdowns, multiselect/autoselect need two clicks to close (change detection issue?) Also in the https://www.primefaces.org/primeng/#/dropdown they won't close at all.

**Expected behavior**
Takes a single outside click to close.

**Comment by wautersj** [comment] 2017-09-26 15:14
I have the same issue. Using "primeng": "^4.2.1"

**Comment by Ketec** [comment] 2017-09-27 05:45
It listens to the document click - so i assume that is where the problem comes from.
Why not focusout or similar? This would cover any  action that causes focus to be lost (window resize included). Global click listener on document is problematic because often preventpropagation might be used in various places as well.

**Comment by reinpeter** [comment] 2017-10-17 13:18
Same issue here. 4.2.2

**Comment by reinpeter** [comment] 2017-10-19 09:59
This is related to or duplicate of:
https://github.com/primefaces/primeng/issues/4162

**Comment by Ketec** [comment] 2017-10-19 14:09
@reinpeter the issue linked does not mention the need for two clicks outside to close it. So it is not the same bug.

**Comment by reinpeter** [comment] 2017-10-19 14:19
@Ketec i think it does. In that ticket (title) it states that after selecting an item (by first click), you need to click it again or click outside of control.  Both scenario's it requires two clicks to close the dialog.
It does not mention the scenario of not selecting an item and clicking twice outside of control, but it is similar problem

**Comment by cagataycivici** [comment] 2017-10-20 08:29
Tracked at #4162 for 4.2.3

**Closed by cagataycivici** 2017-10-20 08:29 UTC
