### ISSUE TITLE
 Datatable - Can support OnEditBlur EventEmitter ?

### ISSUE THREAD

**Issue by livindg** [primefaces/primeng#2889] opened 2017-05-26 07:17 UTC
```node.js
@angular/cli: 1.0.3
node: 7.8.0
os: win32 x64
@angular/animations: 4.1.2
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/language-service: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2
```

**Comment by sudheerj** [comment] 2017-05-27 06:31
The similar issue is already raised. The onEditComplete should respond for tab, blur and enter events.

https://github.com/primefaces/primeng/issues/2535

**Comment by cagataycivici** [comment] 2017-05-27 21:01
Duplicate of 2535

**Closed by cagataycivici** 2017-05-27 21:01 UTC
