### ISSUE TITLE
Dropdown isn't properly display in Tables

### ISSUE THREAD

**Issue by yukie1412** [primefaces/primeng#12275] opened 2022-11-23 07:34 UTC
### Describe the bug

create a table with a dropdown in one of the columns
with just few rows in table, the dropdown isn't properly displayed:
![image](https://user-images.githubusercontent.com/2449212/203492542-7c3ec932-bf61-4f04-991c-cb8e3d961511.png)

issue is with `overflow: auto` on `.p-datatable>.p-datatable-wrapper`
![image](https://user-images.githubusercontent.com/2449212/203492819-088007d2-9994-4563-9dcc-eceb7ff3adcb.png)
once changed to "visible", dropdown'll properly shown. However, table scroll won't work with `overflow: "visible"`

### Environment

prod

### Reproducer

https://stackblitz.com/edit/primeng-tablesections-demo-qko7vh?file=src/app/app.component.html

### Angular version

15.0.1

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

edge 107.0, chrome 107.0

### Steps to reproduce the behavior

1. go to https://primeng-tablesections-demo-qko7vh.stackblitz.io/
2. click on dropdown

### Expected behavior

dropdown options should be fully visible without scrolling up & down the table
there shouldn't be any scrollbars on the table as all content can fit on the screen.

**Comment by Phil-DS** [comment] 2022-11-23 10:31
Add `appendTo="body"` to your dropdown element.

**Comment by cetincakiroglu** [comment] 2022-11-24 07:14
Hi,

appendTo="body" will solve your problem. Here is a refactored version of your Stackblitz example https://stackblitz.com/edit/primeng-tablesections-demo-petv8l?file=src%2Fapp%2Fapp.component.html

Thanks for your support, closing the issue since the issue is not available.

**Closed by cetincakiroglu** 2022-11-24 07:14 UTC
Labels: Status: Needs Triage
