### ISSUE TITLE
P-Splitter: Does not respect minSizes array after upgrading to 17.16.1

### ISSUE THREAD

**Issue by JCarusWTW** [primefaces/primeng#15637] opened 2024-05-21 10:12 UTC
### Describe the bug

We have a p-splitter in our code, with a minSizes array of [25,25] being passed in. We have recently upgraded the primeng version from 16.9.1 to 17.16.1 and the minSizes array is no longer being respected i.e. whereas you used to be unable to drag the p-splitter handle past the minimum of 25% size for either panel, the user is now allowed full resizing between 0 and 100% of the possible size despite the 25% minimums still being in the code. You can reproduce the issue purely by switching between versions (no code changes).

### Environment

Windows, typescript, version 17.16.1 for primeng

### Reproducer

https://github-7cfjki.stackblitz.io

### Angular version

17.3.8

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0 and/or 21.6.1

### Steps to reproduce the behavior

1. Use splitter on stackblitz and note the fact that you can drag the handle anywhere within the two panels
2.  Go to package.json, change line 9 (version of primeng) to 16.9.1, ensure it rebuilds
3. Use the splitter and note that you cannot resize either panel smaller than 25% (as set in minSizes array in html file)

### Expected behavior

I expect the behaviour from v17 to match that of v16 (and the docs) i.e. if minSizes is set to 25,25 then the user should be unable to resize either panel to smaller than 25%.

**Comment by PranKe01** [comment] 2024-05-22 06:14
I can confirm this bug. It also does not work in primeng components demo page.

**Comment by raiworld81** [comment] 2024-05-23 08:48
+1

**Comment by PranKe01** [comment] 2024-06-04 05:48
@cetincakiroglu Probably a duplicate of issue #15629. Looks like a low hanging fruit, which should be easy to fix. Would be nice if it would get fixed with next version (:

**Closed** 2024-06-13 11:07 UTC
Labels: Type: Bug
