### ISSUE TITLE
datatable - expandableRows - td style

### ISSUE THREAD

**Issue by kben** [primefaces/primeng#2713] opened 2017-05-05 14:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi,

I'd like to use the expandable feature of the datatable, which works. But when including (for example) a dropdown, the menu is hidden. It would be great to have a "expandedstyle" attribute or something else to set the style to "overflow: visible", which would work in my case.

regards
ben

**Comment by guzcon** [comment] 2017-05-16 13:47
I'm also trying to set the active class on the row (.ui-widget-content) that is currently expanded. Is there any easy way to do it?

**Comment by cagataycivici** [comment] 2017-06-23 07:55
Duplicate of #1845

**Closed by cagataycivici** 2017-06-23 07:55 UTC
