### ISSUE TITLE
Component: MenuBar Styles looks wrong

### ISSUE THREAD

**Issue by xccu** [primefaces/primeng#13961] opened 2023-10-26 08:34 UTC
### Describe the bug

When using menubar Component, the style looks incorrect:
1)the default height are too high and items has text decoration
2)menu items are always on the top of the bar and sometimes out of  the bar when set height property smaller

![image](https://github.com/primefaces/primeng/assets/7534189/7fd7c72f-73fd-4370-a6fd-4d53af2a6b41)

```
<div class="card">
  <p-menubar [model]="items"></p-menubar>
</div>
<p></p>
<p-menubar [model]="items" [style]="{width:'800px',height:'40px'}"></p-menubar>
```

package.json like this:
```
{
  "name": "primeng.demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "prestart": "node aspnetcore-https",
    "start": "run-script-os",
    "start:windows": "ng serve --port 44490 --ssl --ssl-cert %APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem --ssl-key %APPDATA%\\ASP.NET\\https\\%npm_package_name%.key",
    "start:default": "ng serve --port 44490 --ssl --ssl-cert $HOME/.aspnet/https/${npm_package_name}.pem --ssl-key $HOME/.aspnet/https/${npm_package_name}.key",
    "build": "ng build",
    "build:ssr": "ng run PrimeNG.Demo:server:dev",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.10",
    "@angular/common": "^16.2.10",
    "@angular/compiler": "^16.2.10",
    "@angular/core": "^16.2.10",
    "@angular/forms": "^16.2.10",
    "@angular/platform-browser": "^16.2.10",
    "@angular/platform-browser-dynamic": "^16.2.10",
    "@angular/platform-server": "^16.2.10",
    "@angular/router": "^16.2.10",
    "bootstrap": "^5.3.2",
    "jquery": "^3.7.1",
    "oidc-client": "^1.11.5",
    "popper.js": "^1.16.0",
    "run-script-os": "^1.1.6",
    "rxjs": "~7.8.1",
    "tslib": "^2.6.2",
    "zone.js": "~0.13.0",
    "primeicons": "^6.0.1",
    "primeng": "^16.5.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.7",
    "@angular/cli": "^16.2.7",
    "@angular/compiler-cli": "^16.2.10",
    "@types/jasmine": "~5.1.1",
    "@types/jasminewd2": "~2.0.12",
    "@types/node": "^20.8.7",
    "jasmine-core": "~5.1.1",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.1",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.1.0",
    "typescript": "~5.1.6"
  },
  "overrides": {
    "autoprefixer": "10.4.5"
  },
  "optionalDependencies": {}
}
```

### Environment

windows 10
Visual Studio 2022

### Angular version

16.2.10

### PrimeNG version

16.5.1

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

v18.12.1

### Browser(s)

Chrome Version 116.0.5845.141 (Official Build) (64-bit)

**Comment by MaciejSzczurek** [comment] 2023-10-26 16:09
This is not a bug, but a major change to the CSS primeng that requires CSS layering. Boostrap doesn't yet implement layering and you'll need to adjust it in your code.

Duplicate of https://github.com/primefaces/primeng/issues/13757

**Closed** 2023-10-27 08:16 UTC
Labels: Status: Needs Triage

**Comment by narciarz** [comment] 2024-02-06 22:55
Your issue could be solved adding bootstrap to primeng layer as described: https://github.com/primefaces/primeng/issues/13757#issuecomment-1790891668
