### ISSUE TITLE
Dynamic dialog onClose event

### ISSUE THREAD

**Issue by lud42** [primefaces/primeng#9384] opened 2020-10-09 09:06 UTC
**I'm submitting a bug report** 

**Current behavior**

I'm with PrimeNG 9.1.3 with angular 9 and with Ivy enabled and I'm trying to catch the close event of a dynamic dialog. It's working well when I'm calling myself `dynamicRef.close()` but when I press escape or click on the times icon The event is not triggered. 

![image](https://user-images.githubusercontent.com/18071487/95564257-1e2fa600-0a51-11eb-9ac8-dae42f897a9e.png)

**Expected behavior**

I should get the event.

**Comment by Ravindra-Naik-Katerra** [comment] 2020-10-09 15:33
Facing the same issue on version 9.1.0

**Comment by cagataycivici** [comment] 2020-10-11 16:46
Seems to be duplicate of;

https://github.com/primefaces/primeng/issues/9345

**Closed by cagataycivici** 2020-10-11 16:46 UTC
Labels: duplicate

**Comment by sotoh** [comment] 2020-12-02 17:11
I wonder how DynamicDialog works with the engine Ivy in Angular 9+?. It seems entryComponents is deprecated and this component needs this "old" feature.

**Comment by tirthgodhni98** [comment] 2022-01-05 16:40
> **I'm submitting a bug report**
> 
> **Current behavior**
> 
> I'm with PrimeNG 9.1.3 with angular 9 and with Ivy enabled and I'm trying to catch the close event of a dynamic dialog. It's working well when I'm calling myself `dynamicRef.close()` but when I press escape or click on the times icon The event is not triggered.
> 
> ![image](https://user-images.githubusercontent.com/18071487/95564257-1e2fa600-0a51-11eb-9ac8-dae42f897a9e.png)
> 
> **Expected behavior**
> 
> I should get the event.

Yes , this event is after close , I need to user click "X" button and I want that event , Any Idea How can I Get this event ?
