### ISSUE TITLE
Dropdown: Keyboard selection doesn't work

### ISSUE THREAD

**Issue by szymonworld** [primefaces/primeng#14059] opened 2023-11-08 10:19 UTC
### Describe the bug

Keyboard selection for dropdown list doesn't work. It's selecting dropdown label instead of list item.

![Screenshot 2023-11-08 at 11 03 53](https://github.com/primefaces/primeng/assets/9286136/48540b72-dd71-46fc-8c1b-28671c3916ee)

Dropdown component has been changed a lot in 16.7.0 - those changes should be marked in release note and it would be nice to have same tips how to switch to new API - e.g. selectItem method has been removed and I'm using it in my project.

### Environment

MacOS

### Reproducer

https://primeng.org/dropdown

### Angular version

16.2

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Arc

### Steps to reproduce the behavior

Open dropdown -> use keyboard arrow to switch to next item

### Expected behavior

Selecting next item

**Comment by GitJacek** [comment] 2023-11-10 07:37
I think the issue is with visual representation of currently focused item. When you focus on dropdown and press enter/space it opens dropdown popup, then when you try to navigate through items with arrow up/down, and press enter, it sets value to input, however, there is no visual representation of switching dropdown items(no outline) while pressing arrow up/down.

**Comment by cetincakiroglu** [comment] 2024-02-13 07:55
Hi,

This issue is fixed in the latest version 17.6.0. See the example https://stackblitz.com/edit/ktfsd8?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

Closing the issue.

**Closed by cetincakiroglu** 2024-02-13 07:55 UTC
Labels: Status: Needs Triage
