### ISSUE TITLE
Updating InputSwitch labels does not change components width 

### ISSUE THREAD

**Issue by chlupaccom** [primefaces/primeng#2339] opened 2017-03-19 12:18 UTC
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When I use the translation in the attribute of your InputSwitch, it does not change the width of it. So when the text of the new selected translation has different length then previous it does not fit.

**Expected behavior**

It changes the width too.

**Comment by cagataycivici** [comment] 2017-06-20 19:57
Duplicate of #1807

**Closed by cagataycivici** 2017-06-20 19:57 UTC
