### ISSUE TITLE
Treenode should be connected using some line in p-tree

### ISSUE THREAD

**Issue by stagging18** [primefaces/primeng#2719] opened 2017-05-06 10:30 UTC
While p-tree is containing huge no of node it is difficult to identify which node is coming under which node.
So please connect the node using line so that node should be connected to each other and it will be easy ti find out.

**Comment by stagging18** [comment] 2017-05-06 10:34
![tree](https://cloud.githubusercontent.com/assets/15700308/25771669/9d3e8b44-3275-11e7-8780-3289d9872d51.png)

PFA

**Comment by sudheerj** [comment] 2017-05-07 08:34
Duplicate of issue https://github.com/primefaces/primeng/issues/2663

**Closed by sudheerj** 2017-05-07 08:34 UTC
