### ISSUE TITLE
Spinner - cursor stays in spinner input field after pressing tab key in Firefox

### ISSUE THREAD

**Issue by dankil** [primefaces/primeng#2018] opened 2017-02-08 07:02 UTC
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
cursor stays in spinner input field after pressing tab key in Firefox

**Expected behavior**
after pressing tab key the up arrow button is seleected

**Minimal reproduction of the problem with instructions**
Go to http://www.primefaces.org/primeng/#/spinner set focus to 'Basic' and press tab key.

This issue can be fixed by adding the keyCode check to onInputKeyPress:

```
onInputKeyPress(event: KeyboardEvent) {
        let inputChar = String.fromCharCode(event.charCode);
        if (!this.keyPattern.test(inputChar) && inputChar != this.decimalSeparator && event.keyCode != 9) {
            event.preventDefault();
        }
    }

```

**Comment by khrise** [comment] 2017-02-08 14:36
Same issue  as / duplicate of #2012

**Closed** 2017-02-10 09:34 UTC
