### ISSUE TITLE
first property isn't input

### ISSUE THREAD

**Issue by banderberg** [primefaces/primeng#6307] opened 2018-08-13 18:18 UTC
https://github.com/primefaces/primeng/blob/071bb615457d7baef49e9cf5a0ea59b9bc3c31a7/src/app/components/dataview/dataview.ts#L97

The first property isn't an input so I am not able to tell the dataview what page to show in the paginator.

**Comment by JacobSiegle** [comment] 2018-08-13 19:41
Duplicate of https://github.com/primefaces/primeng/issues/6210

**Closed** 2018-09-18 10:53 UTC
