### ISSUE TITLE
DataTable with scroll and few data causes headers and table cells to misalign

### ISSUE THREAD

**Issue by sigad** [primefaces/primeng#917] opened 2016-09-19 08:56 UTC
In a datatable with scroll, if the height of the data is smaller than the specified scroll height, the headers and the table cells misalign (there is some gap for the scroll bar in the header, even if no scrollbar is displayed).

Here is the definition of the datable: 

```
<p-dataTable [value]="data"
                         selectionMode="multiple"
                         [(selection)]="selectedItems"
                         [totalRecords]="totalElements"
                         [rows]="size"
                         [lazy]="true"
                         (onLazyLoad)="loadLazy($event)"
                         [responsive]="true"
                         [resizableColumns]="false"
                         scrollable="true" scrollHeight="400px">
```

I am using 1.0.0-beta.15.

**Comment by billdwhite** [comment] 2016-09-19 16:36
Probably a duplicate of [487](https://github.com/primefaces/primeng/issues/487)

**Closed** 2016-11-01 08:07 UTC
Labels: defect

**Comment by GopiAnnan** [comment] 2017-03-06 19:08
@cagataycivici ,

I have tried with 2.0.2 , When Scrollable is true and it has not many records to scroll. still have the issue. 
<div class="ui-datatable-scrollable-header-box"  style="margin-right: 17px;">
This creating issue.

Header has inline style, margin-right: 17px; . this has to be 0 px when there is no Scrollable content.  

Please let me know if I am missing something.

**Comment by PrajwalGonsalves07** [comment] 2017-03-08 09:40
https://github.com/primefaces/primeng/issues/487#issuecomment-277251152

Check the above link. There is a work-around for this.
