### ISSUE TITLE
Customizable "select all" behavior in Table

### ISSUE THREAD

**Issue by MassiveHiggsField** [primefaces/primeng#8139] opened 2019-09-11 15:00 UTC
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-gvyvtp.stackblitz.io/
https://stackblitz.com/edit/github-gvyvtp

**Current behavior**

When switching between pages and selecting single rows or all rows, the selected rows are not correctly retained. Here are some examples:

- Select 3 on the first page, switch to second, select two on the second page, switch back to first --> works correctly, the 3 on the first page are still selected
- Select 3 on the first page, switch to second, use "select all" checkbox, switch back to the first page and the 3 on the first page are not selected anymore (and the "select all" checkbox is checked)

**Expected behavior**

I would expect either of one of these two behaviors: 

1. The "select all" button selects all rows on all pages, basically how it would work on a single page
2. The "select all" button selects only all rows on the current page, but does not reset the selected rows on other pages

I would prefer the second solution or even one that could be configured.

**Comment by libikroizer** [comment] 2020-01-30 14:08
+1

**Comment by cagataycivici** [comment] 2020-03-29 13:50
1 is expected because table can't know data in other pages, so you need to hook-in the event and add data to selection after loading it.

2) We have it in PrimeFaces and will add it to 9.0.4 as well. Like headerCheckboxMode="all or page"

**Comment by bschnabel** [comment] 2020-10-29 14:06
so currently the behaviour is

- withouth lazy loading the p-tableHeaderCheckbox selects all data entries (on all pages)

- with lazy loading the p-tableHeaderCheckbox selects the data from the current page. (however there are still some bugs when selecting all on first page and then moving to second page)

any update on this?

**Comment by gawielgo** [comment] 2020-11-18 23:21
The problem also occurs when I delete all the elements from a page and the table automatically goes to the next page...
Is there any news on possible solutions?

**Comment by bschnabel** [comment] 2020-11-19 08:20
I developed a workaround based  on comments in  https://stackoverflow.com/questions/58692256/primeng-p-table-header-select-all-persistence-with-lazy-loading-and-pagination and https://github.com/primefaces/primeng/issues/1206

You can find the Code as part of our openSource identity management system didmos2: https://gitlab.daasi.de/didmos2/didmos2-frontend-lib/-/blob/develop/shared/src/lib/services/primeNGModifications.service.ts

It has been testes with primeNG v9 and primeNG v6.

You can copy the entire Service and in the ngOnInit() of the component you are using the table in, call `this.primeNGModificationService.overridePrimeNGTableMethodsForCheckboxSelection(true | false);`

**Comment by gawielgo** [comment] 2020-11-19 21:32
I'm using version 11.0.0-rc.1, and unfortunately it doesn't seem to work...

**Comment by gawielgo** [comment] 2020-11-20 09:34
Rather I think I solved it by replacing the one in the header with a simple p-checkbox and managing the status of the model at the page change by invoking this.check.writeValue (false), where check is the reference in question...

It needs to be cleaned, but it seems to work!!!

Obviously managing all the necessary hooks of the various checkboxes...

**Comment by speksy** [comment] 2021-03-01 23:14
I have the same issue. I tried to customize select all with event but still. If select all is checked on second page selection is reset of first one. Without this if I select all on first page, select all checkbox is selected on second one. 

(onHeaderCheckboxToggle)="onTableHeaderCheckboxToggle($event)"

onTableHeaderCheckboxToggle(event: any) {
    console.log(this.selectedUsers);

    if (event.checked === true) {
      for (let m of this.users) {
        if (!this.selectedUsers.find(user => user.id === m.id)) {
          this.selectedUsers.push(m);
        }
      }
    } else {
      for (let m of this.users) {
        this.selectedUsers.pop();
      }
    }
  }

**Comment by ErShubhankar** [comment] 2021-06-17 11:25
still facing the issue if i click on p-tableheadercheckbox and move to another page the p-tableheadercheckbox  i checked by default

**Comment by randy9527** [comment] 2021-08-10 07:59
on latest release 12.0.1 found it also happens during filter without paging. To reproduce:

1. select some rows.
2. do a filter on one column, excluding items on step 1.
3. click "check all" header checkbox to select all rows after filter.
4. clear filter.
5. rows selected in step 1 are unselected. only rows in previous filter persists as selected.

A preferrable behavior for me is to persist existing selection while filtering, paging, or other actions may result in the curent dataview change, or at least has an option to enable/disable it.

**Comment by mertsincan** [comment] 2021-12-14 11:41
Hi,

Fixed in https://github.com/primefaces/primeng/issues/10951. Also, I added a demo related to it on next version.

Best Regard,

**Closed by mertsincan** 2021-12-14 11:41 UTC
Labels: new feature
