### ISSUE TITLE
[BUG] p-dialog error on setting visible property

### ISSUE THREAD

**Issue by L-VE** [primefaces/primeng#2422] opened 2017-03-30 11:21 UTC
[BUG] p-dialog error on setting visible

### Current behavior

Example in plunkr:
[http://plnkr.co/edit/QexEpmnqhuX0HfGL1Ly7?p=preview](http://plnkr.co/edit/QexEpmnqhuX0HfGL1Ly7?p=preview)

But in this case the p-dialog is not shown and we get the following error stacktrace:

```
ERROR TypeError: Cannot read property 'offsetWidth' of undefined
    at DomHandler.getOuterWidth (domhandler.ts:229)
    at Dialog.center (dialog.ts:216)
    at Dialog.show (dialog.ts:143)
    at Dialog.set [as visible] (dialog.ts:134)
    at updateProp (provider.ts:566)
    at checkAndUpdateDirectiveInline (provider.ts:236)
    at checkAndUpdateNodeInline (view.ts:455)
    at checkAndUpdateNode (view.ts:416)
    at debugCheckAndUpdateNode (services.ts:235)
    at debugCheckDirectivesFn (services.ts:294)
    at Object.View_AppComponent_0.co [as updateDirectives] (app.template.html:7)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:273)
    at checkAndUpdateView (view.ts:344)
    at callViewAction (view.ts:699)
    at execComponentViewsAction (view.ts:643)
```

When the visible property is set, the show() function is called which in turn calls the center() function. In this function 'this.container' (line 216 - dialog.ts) is undefined. Because the show() is called before the AfterViewInit() where this.container is defined.

### Expected behavior
The p-dialog is shown.

**- Angular version: 2.0.X**
    4.0.1

**- PrimeNG version: 2.0.X**
    4.0.0-rc.2

**- Language: [all | TypeScript X.X | ES6/7 | ES5]**
    Typescript

Maybe connected to #2416

**Comment by wesray** [comment] 2017-03-30 12:43
Definitely connected.

**Comment by schmuli** [comment] 2017-04-02 14:37
Possible duplicate: #2428

**Comment by GabKas** [comment] 2017-04-04 11:02
Hi,

the following fix: ec06e44
was removed the ngAfterViewChecked lifecycle hook.

And the center() function can not calculate the elementHeight properly.

**Comment by luchillo17** [comment] 2017-04-04 15:53
In my case with version `4.0.1`:
>Also this happens when the page loads with the variable set to `true`, basically initializing before it should.

>It effectively fixes if i put my initialization code into `ngAfterViewInit`.

**Comment by cagataycivici** [comment] 2017-04-13 22:40
Duplicate of 2428

**Closed by cagataycivici** 2017-04-13 22:40 UTC
