### ISSUE TITLE
treetable [feature request] - custom icons

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#2469] opened 2017-04-07 14:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
Would it be possible to cutomize icons like Tree properties :
- icon
- expandedIcon
- collapsedIcon
Thanks

**Comment by cagataycivici** [comment] 2017-06-22 13:33
Duplicate of #2269

**Closed by cagataycivici** 2017-06-22 13:33 UTC
