### ISSUE TITLE
Scroller: Issues loading all visible rows when scrolling quickly to page boundaries

### ISSUE THREAD

**Issue by MikeMatusz** [primefaces/primeng#13192] opened 2023-06-13 12:35 UTC
### Describe the bug

If the scrollbar is dragged quickly down with virtual scroll enabled and the viewport happens to land on a page boundary, the scroller will assume the previous/top page is already loaded and only emit a lazy load event with start/size for the lower page, and the rows above will remain loading.  This behavior can also be reproduced if you scroll to the bottom, then drag the scrollbar quickly up to a page boundary.  In some cases, you can even scroll up slowly and the previous page won't be triggered to load until you've scrolled all loaded rows off-screen.

### Environment

Windows (both native and WSL2) and Mac, all browsers. 

### Reproducer

https://stackblitz.com/edit/9uttel?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts,src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.scss,src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.html

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Steps to reproduce the behavior

The linked StackBlitz automates the scroll position in a timeout to ensure reproduction every time.  Just open the link, wait a second, and note that the top rows never load.  There's an additional `setTimeout` that can be uncommented to demonstrate this can also happen when scrolling up.

Manual repro steps:

1. Have a virtual scroll table with 3+ pages of data.  For the purpose of this example, let's say there are 10 pages, and page size is 100.
2. Drag the scroll bar quickly so that it positions row 300 exactly in the middle of the viewport.
3. Note that a lazy load emits with `{ start: 300, size 100 }`, and the bottom half of the viewport loads.
4. Note that the top half of the viewport still shows the loadingbody.

### Expected behavior

Instead of tracking a single page, the scroller needs to be aware that multiple pages can be in view at once and emit lazy load events accordingly.  So if I scroll down halfway and land on a page boundary, the lazy load event should indicate via start/size that both pages need to be loaded, e.g. by having `start` set to the first index of the upper page, and `size` doubled to account for both.

**Comment by cetincakiroglu** [comment] 2024-03-22 15:23
Hi,

Couldn't replicate the issue with latest version (17.12.0). Issue is probably fixed by another commit between mentioned version and the latest. Closing the issue since it doesn't exist anymore. Please open a new issue with a stackblitz reproducer if the issue persists.

Thanks for reporting!

**Closed by cetincakiroglu** 2024-03-22 15:23 UTC
Labels: Status: Needs Triage

**Comment by cravay** [comment] 2024-06-12 18:26
Hi @cetincakiroglu,

This bug still seems to exist with the newest PrimeNG version (17.18.0) and it is still consistently reproducible with the reproducer after updating the dependencies.

Link to updated StackBlitz reproducer (Using Angular 17 and PrimeNG 17.18.0): https://stackblitz.com/edit/9uttel-6pheqg?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts

Can you please reopen this issue?
