### ISSUE TITLE
ColorPicker: Form elements must have labels

### ISSUE THREAD

**Issue by HellinSunWTW** [primefaces/primeng#14974] opened 2024-03-07 14:03 UTC
### Describe the bug

The Axe Dev Tools for Accessibility is reporting that the 'Form elements must have labels'.
![image](https://github.com/primefaces/primeng/assets/152492138/21b395cd-3897-40c3-a5b5-97ee9b94e1ba)
Can we have appropriate aria label like "Color picker" added please?

### Environment

Windows 10

### Angular version

17.2.3

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by cetincakiroglu** [comment] 2024-03-13 11:49
Hi,

It seems that the issue is already fixed in previous versions. You can see below there is an aria-label bonded to the input. Closing the issue.

https://github.com/primefaces/primeng/blob/6c9a863bc4e0d58e15862dbf6138796350a2245e/src/app/components/colorpicker/colorpicker.ts#L46

**Closed by cetincakiroglu** 2024-03-13 11:49 UTC
Labels: Type: Bug, Component: Accessibility
