### ISSUE TITLE
Dialog height is fixed

### ISSUE THREAD

**Issue by ar53n** [primefaces/primeng#2300] opened 2017-03-15 09:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

[](http://plnkr.co/edit/hEUSqoUdApWiYLQIcYJU?p=preview)

**Current behavior**

When i set property height="400" and resizinig dialog height is not to resize

**Expected behavior**

When resize dialog  and have property height its should be correctly resize

**Minimal reproduction of the problem with instructions**

[](http://plnkr.co/edit/hEUSqoUdApWiYLQIcYJU?p=preview)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 56
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment] 2017-05-29 14:49
Duplicate of 737

**Closed by cagataycivici** 2017-05-29 14:49 UTC
