### ISSUE TITLE
Build error: dropdown.d.ts.Dropdown.html (6,13): Type 'string' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by danny-swimmer** [primefaces/primeng#3781] opened 2017-08-29 13:35 UTC
[x ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
After upgrading primeng from 4.1.3 to 4.2.0-rc.1, I get this build error in my Angular.io project:
ERROR in ng:.../web/ewp/objs/node_modules/primeng/components/dropdown/dropdown.d.ts.Dropdown.html (6,13): Type 'string' is not assignable to type 'boolean'.

**Expected behavior**
Should build without errors

**Please tell us about your environment:**
Linux
Angular.io with angular-cli

Here is my package.json file:
`{
  "name": "d3",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "//": "#################################################################################################################################",
  "//": "Comments go here",
  "//": "#################################################################################################################################",
  "dependencies": {
    "@angular/cli": "1.3.2",
    "@angular/common": "4.3.6",
    "@angular/animations": "4.3.6",
    "@angular/compiler": "4.3.6",
    "@angular/compiler-cli":"4.3.6",
    "@angular/core": "4.3.6",
    "@angular/forms": "4.3.6",
    "@angular/http": "4.3.6",
    "@angular/platform-browser": "4.3.6",
    "@angular/platform-browser-dynamic": "4.3.6",
    "@angular/router": "4.3.6",
    "@angular/material": "2.0.0-beta.8",
    "@angular/cdk": "2.0.0-beta.8",
    "@types/hammerjs": "2.0.35",
    "hammerjs": "2.0.8",
    "core-js": "2.5.0",
    "primeng": "4.2.0-rc.1",
    "rxjs": "5.4.3",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.54",
    "@types/node": "8.0.25",
    "@types/chrome": "0.0.48",
    "angular2-template-loader": "0.6.2",
    "codelyzer": "3.1.2",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-remap-istanbul": "0.6.0",
    "protractor": "5.1.2",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.2",
    "webdriver-manager": "12.0.6"
  }
}
`

* **Angular version:** 2.0.X
4.3.6

* **PrimeNG version:** 2.0.X
4.2.0-rc.1

**Comment by dockleryxk** [comment] 2017-08-29 15:52
I'm pretty sure [this commit](https://github.com/primefaces/primeng/commit/7c517518e185f31f507392f5e5dcb373c88554e6#diff-512ee7449b5a756c473f1d7146c5ee89) broke it, or attempted to fix it and failed.

**Comment by sgomanf** [comment] 2017-08-29 19:08
same issue

**Comment by xiongyayun428** [comment] 2017-08-30 09:45
same issue

**Comment by huineng** [comment] 2017-08-30 15:26
commit didn't fix https://github.com/primefaces/primeng/issues/3780

**Comment by harikrishnan-u01** [comment] 2017-08-30 21:02
Am facing this issue in "primeng": "4.2.0-rc.1",

**Comment by sonnh58** [comment] 2017-08-31 02:06
same issue in "primeng": "4.2.0-rc.1",

**Comment by Ketec** [comment] 2017-08-31 05:44
Confirmed, this issue exists in aot build.

**Comment by upstreamosGH** [comment] 2017-08-31 09:12
Same issue on aot after update primeng to v4.2.0-rc1

**Comment by mtschaffler** [comment] 2017-08-31 09:16
I am having the same issue as well :-) - What would be the latest primeng release where AOT works fine?

**Comment by mtibbo** [comment] 2017-08-31 09:18
Same issue here to after update primeng to 4.2.0-rc.1

**Comment by jiazijing** [comment] 2017-08-31 12:43
same issue

**Comment by dockleryxk** [comment] 2017-08-31 14:40
Commenting that you have the same issue really only clogs up the thread. Unless you have something constructive to say, just thumbs up the issue

**Comment by jesusce21** [comment] 2017-09-01 10:54
Is there any temp solution to build without errors?

**Comment by shalugin** [comment] 2017-09-01 10:56
@jesusce21 revert to 4.1.3 ?

**Comment by rodrigoauglima** [comment] 2017-09-01 14:42
Same problem here. Reverting to 4.1.

**Comment by LucasBrazi06** [comment] 2017-09-01 21:04
I just reverted to 4.1.3 and it built successfully.

**Comment by SpiderPork** [comment] 2017-09-04 15:43
Same

**Comment by wlclass** [comment] 2017-09-05 05:08
same issue

**Comment by kravda** [comment] 2017-09-05 19:31
+1

**Comment by TheWrightDev** [comment] 2017-09-06 16:05
@cagataycivici - It looks like the fix for this has been in place for over a week. Any plans for a release in the near future so we can build again?

**Comment by ratbeard** [comment] 2017-09-06 18:01
THIS ISSUE IS ALSO AFFECTING ME!!!

**Comment by charlatan154** [comment] 2017-09-07 12:03
Any plans for releasing v4.2.0-rc2, fixing this issue?

**Comment by avarndell** [comment] 2017-09-07 16:03
I'm having the same issue

**Comment by cyberrranger** [comment] 2017-09-08 12:43
same problem

**Comment by lafourmirouge** [comment] 2017-09-08 14:05
Same issue

**Comment by dylandechant** [comment] 2017-09-08 22:13
same here

**Comment by stevenxi** [comment] 2017-09-08 22:17
Same here +1.

Thanks.

**Comment by dxpengyi1990** [comment] 2017-09-09 01:04
+1

**Comment by eminoda** [comment] 2017-09-09 14:39
+1

**Comment by saskyagurgel** [comment] 2017-09-09 17:58
+1

**Comment by saskyagurgel** [comment] 2017-09-09 18:21
I fixed replacing *ngIf=\"!editable&&label\" to *ngIf=\"!editable&&!!label\"

**Comment by sebichondo** [comment] 2017-09-10 19:38
Thanks @eminoda downgrading to 4.1.3 worked for me too

**Comment by adityals** [comment] 2017-09-11 11:12
@saskyagurgel can you post your file or tell us the file location to put this code? By the way, if I downgrade to 4.1.3 I can't use the MessageService class. Please help me.

**Comment by saskyagurgel** [comment] 2017-09-11 17:19
@adityals i'm changed the file ...\node_modules\primeng\components\dropdown\dropdown.metadata.json
replacing  *ngIf="!editable&&label" to *ngIf="!editable&&!!label"

**Comment by correasebastian** [comment] 2017-09-11 22:49
+1

**Comment by cagataycivici** [comment] 2017-09-13 07:11
Fixed for 4.2.0 already.

**Closed by cagataycivici** 2017-09-13 07:11 UTC
Labels: defect

**Comment by cagataycivici** [comment] 2017-09-13 08:13
4.2.0 is released now, please try with this one.

**Comment by patriknil90** [comment] 2017-09-13 08:22
No build error now! Thanks!
