### ISSUE TITLE
Tooltip on button stays visible if button gets disabled

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#3537] opened 2017-07-31 09:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/VDZFBkjo0Wgf7I6OCIkS

**Current behavior**
If I have a button which gets disabled on clicking the tooltip freezes and does not disappear. 

**Expected behavior**
The tooltip should also disappear on disabled buttons.

**Minimal reproduction of the problem with instructions**

Open the example and click on the button.

**PrimeNG version:** 
4.1.2

**Browser:**
Chrome 59

**Comment by darek8686** [comment] 2017-08-25 09:32
I can confirm it in 4.1.3. It is frustrating bug.

**Comment by Ninja-Coding-Git** [comment] 2017-09-07 15:38
> I can confirm it in 4.1.3. It is frustrating bug.
x2

**Comment by Manuel57** [comment] 2017-09-25 08:53
Version 4.2.1.:  still not fixed.

**Comment by miniplus** [comment] 2017-09-28 19:36
Heads up @Merve7: issue was in commit message 2b822a4 as fixed, but issue is still open atm

**Comment by cagataycivici** [comment] 2017-09-29 11:14
@Merve7, please take over.

**Comment by cagataycivici** [comment] 2017-09-29 11:22
Seems to be duplicate of #2196

**Closed by cagataycivici** 2017-09-29 11:22 UTC
Labels: defect
