### ISSUE TITLE
minDate maxDate validation for manually inserted date via input

### ISSUE THREAD

**Issue by britvik** [primefaces/primeng#2437] opened 2017-03-31 13:13 UTC
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
MinDate and MaxDate only works inside Calendar (dates are disabled) but date can be changed manually to invalid value by editing input directly.

**Expected behavior**
After editing input value, component should be marked as invalid.

**Comment by KatzeKahn** [comment] 2017-09-26 08:14
Since it's not included in the current releases, is there any update when this is going to be fixed?

**Comment by KatzeKahn** [comment] 2018-02-01 20:14
Any updates on that?

**Comment by CarlosPinedaT** [comment] 2018-04-06 04:15
@cagataycivici any update on the issue?

**Comment by mauromol** [comment] 2018-04-13 10:43
So was the fix for this rolled back?

**Comment by sky007** [comment] 2019-10-28 16:09
any updates on this one?

**Comment by dylanesque** [comment] 2020-03-27 20:27
Any updates on this one? This is really frustrating to try and work around!

**Comment by tmc101** [comment] 2020-12-14 17:16
I think this issue is caused by onUserInput() in calendar.ts ( release 11.0.0):

```Javascript
    onUserInput(event) {
        // IE 11 Workaround for input placeholder : https://github.com/primefaces/primeng/issues/2026
        if (!this.isKeydown) {
            return;
        }
        this.isKeydown = false;

        let val = event.target.value;
        try {
            let value = this.parseValueFromString(val);
            if (this.isValidSelection(value)) {
                this.updateModel(value);
                this.updateUI();
            }
        }
        catch(err) {
            //invalid date
            this.updateModel(null);
        }

        this.filled = val != null && val.length;
        this.onInput.emit(event);
    }
```

It happens for a p-calendar control configured with a date range, but without the [readonlyInput]="true" flag:

```html
<p-calendar [(ngModel)]="dateValue" [minDate]="minDateValue" [maxDate]="maxDateValue"></p-calendar>
```

When the user enters a parsable date outside of the minDate-maxDate range, isValidSelection(value) returns false and the control does not update its model.

It would be more consistent if a manually entered invalid date (outside min-max range) called this.updateModel(null) i.e. treated an out-of-range date the same as an unparsable date.

As it stands now, if you have a valid date (within min-max date) and you manually paste in an invalid date then the model does not update. So the control will display the new value, but keeps its original value and validation state.

However, if you manually type in the same invalid date then the internal value will update to null as you type - because the intermediate contents of the input will be unparsable as a date.

This is not a great user experience, and can lead to difficult to diagnose problems.

For template driven forms (using ngModel) the current work-around in the documentation is to set [readonlyInput]="true":

https://www.primefaces.org/primeng/showcase/#/calendar

If you are using Reactive Forms then another approach is to set validators on your FormControl instance and ignore the minDate and maxDate properties on p-calendar.

But it would be nice if the Calendar control updated its model for manually entered out-of-range dates.

**Comment by Marhc** [comment] 2022-08-15 13:58
Any updates on this one?

**Comment by jgrabowski** [comment] 2022-08-16 13:10
Is there any chance for fix? I'm also relying on calendar min/max date ranges but manual input doesn't take it into account.

**Comment by mertsincan** [comment] 2022-11-09 14:25
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 14:25 UTC
Labels: enhancement
