### ISSUE TITLE
Accessibility not working in when we use Tabview  inside p-dialog 

### ISSUE THREAD

**Issue by anil-giri** [primefaces/primeng#9474] opened 2020-10-30 08:24 UTC
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tabview-demo-mxeawb?file=src%2Fapp%2Fapp.component.html

**Current behavior**
When we have a tab view in the content of p-dialog then tab key behavior(Accessibility) is not working.
For example if we have 3 tabs in tab view inside a dialog then after opening the first tab we are able to navigate inside the content from the tab name using the keyboard tab key but after that if we hit tab we cannot navigate to footer buttons.

**Expected behavior**
Accessibility for tab view should work in similar way inside dialog like it works without the dialog.

**Minimal reproduction of the problem with instructions**
In the below example we have a tab view component inside the content of p-dialog. Now when we are on 1st tab and we press keyboard tab key then we can go inside the content directly using keyboard. But when we pressed tab key again then focus is not shifted to footer button ( Yes/No). 

https://stackblitz.com/edit/primeng-tabview-demo-mxeawb?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**

Please tell us about your environment:
Windows OS

Angular version: 5.X
Angular 9.x

PrimeNG version: 5.X
PrimeNG 9.1.3 but issues is reproducible on PrimeNG 10.x

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

Language: [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by yigitfindikli** [comment] 2020-11-25 10:42
duplicate of https://github.com/primefaces/primeng/issues/9467

**Closed by yigitfindikli** 2020-11-25 10:42 UTC

**Comment by prasadkhegade** [comment] 2021-11-11 06:01
Hello Team,

Is there any update on the issue? is it fixed not fixed? if yes then in which version the fixed is available?

Regards

**Comment by prasadkhegade** [comment] 2021-11-23 07:42
You can set [focusTrap]="false" to fix it, as shown here: https://stackblitz.com/edit/angular-aggrid-pagination-k9xnss?file=src%2Fapp%2Fapp.component.html

But above property is not trap the focus on dialog it goes at background screen and start navigation, instead focus should remain and on dialog itself
