### ISSUE TITLE
Latest version is wrongly set to 16.4.2 instead of 16.7.2

### ISSUE THREAD

**Issue by linkinmedo** [primefaces/primeng#14097] opened 2023-11-13 11:00 UTC
### Describe the bug

Well, it's clear that the latest version of the package is 16.7.2 but version 16.4.2 is shown as latest in both the releases page and in npm. even `npm i primeng@latest` will give you version 16.4.2. 

So technically there is no way of getting the latest version other than by installing it using the version number.

### Environment

all environments 

### Angular version

16.2.9

### PrimeNG version

16.4.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by cetincakiroglu** [comment] 2023-11-13 11:41
Hi,

Last week, we released version 16.4.2 under PRO support. Despite our current version being 16.7.2, unfortunately, npm is tagging the latest version as the one we most recently released and is not providing us with a different option. This was possible before with the --latest tag, and versions released without using this tag were not marked as the latest. NPM has changed this and removed the --latest tag, making it the default. Unfortunately, because of this, version 16.4.2 remains marked as the latest. We will resolve this issue by releasing a new version this Wednesday. 

Please do not use `@latest` on npm packages. You can accidentally download LTS versions, which cause the same effect and we cannot interfere the situation caused by NPM.

**Comment by linkinmedo** [comment] 2023-11-13 15:28
> Hi,
> 
> Last week, we released version 16.4.2 under PRO support. Despite our current version being 16.7.2, unfortunately, npm is tagging the latest version as the one we most recently released and is not providing us with a different option. This was possible before with the --latest tag, and versions released without using this tag were not marked as the latest. NPM has changed this and removed the --latest tag, making it the default. Unfortunately, because of this, version 16.4.2 remains marked as the latest. We will resolve this issue by releasing a new version this Wednesday.
> 
> Please do not use `@latest` on npm packages. You can accidentally download LTS versions, which cause the same effect and we cannot interfere the situation caused by NPM.

got it, thank you for the quick reply 👍

**Comment by jakubnavratil** [comment] 2023-11-13 21:01
https://docs.npmjs.com/adding-dist-tags-to-packages

> To add the "stable" tag to the 1.4.0 version of the "example-package" package, you would run the following command:
> `npm dist-tag add example-package@1.4.0 stable`

I believe you can change it

Also, when pusblish older packages, you can specify `--tag` and use something else then `latest`, effectively not overwriting latest version.

**Closed** 2024-12-04 11:10 UTC
Labels: Status: Needs Triage
