### ISSUE TITLE
Make the lightbox responsive so it will work for a variety of screen sizes

### ISSUE THREAD

**Issue by markleppke** [primefaces/primeng#6457] opened 2018-09-05 17:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation/use case for changing the behavior?**
Currently, the lightbox launches images based on the sizes provided. Since screen sizes are highly variable, it's helpful if the lightbox would be able to adjust to the screen size available. Additionally, it would be helpful to let the developer adjust the relative size to the screen size available.

**Comment by JacobSiegle** [comment] 2018-10-02 14:00
This is a duplicate of #2318.

**Comment by cagataycivici** [comment] 2019-07-04 09:19
Duplicate

**Closed by cagataycivici** 2019-07-04 09:19 UTC
