### ISSUE TITLE
Error with Angular2 RC4: No value accessor for ''

### ISSUE THREAD

**Issue by rktawni** [primefaces/primeng#549] opened 2016-07-04 09:59 UTC
When I migrated my app to angular 2 RC4 I am getting error "No value accessor for "" " on the line where I am using p-calendar.

**Comment by MarkPerryBV** [comment] 2016-07-04 10:27
I am also getting the same error with all the controls.

**Comment by sdmoralesma** [comment] 2016-07-04 11:38
In many cases the problem is that you are using `[(ngModel)]` --I know: the showcase have it like that-, try to change it to: `[(model)]` and should be fixed. The explanation seems to be that `ngModel` was already defined and we can not reuse it (source: http://stackoverflow.com/a/34496633/2011421)

Let me know if this solution suits you.

**Comment by MarkPerryBV** [comment] 2016-07-04 13:41
I have resolved my earlier issue with this error. Turns out I had not updated my libs bundle with the latest RC.4 code.

I am still however getting an error when trying to use a single `<p-checkox>` control.

If I use the following syntax: `<p-checkbox [(ngModel)]="myVal" ></p-checkbox>` I get an error from Angular asking me to add the the `name` attribute to the element.

When I change the syntax to:

`<p-checkbox [(ngModel)]="myVal" name="myName"></p-checkbox>`

The page now loads but when I click on the checkbox to save the value I am getting the following error:

`TypeError: this.model.push is not a function` which is because I think PrimeNG is thinking I have more than one checkbox element because I have supplied the `name` attribute.

**Comment by DaanDD** [comment] 2016-07-04 14:41
I had the same problem, I could solve it by updating to the new form providers in the bootstrap function, like this:

```js
import {bootstrap} from '@angular/platform-browser-dynamic';
import {provide} from '@angular/core';
import {AppComponent} from './app.component'
import {disableDeprecatedForms, provideForms} from '@angular/forms';

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms(),
]);
```

**Comment by rktawni** [comment] 2016-07-05 04:32
@DaanDD after implementing your solution I am getting below error. I'll appreciate if someone can explain the root cause of the issue.

execute	@	main.ts:22
ensureEvaluated	@	system.src.js:3344
execute	@	system.src.js:3494
doDynamicExecute	@	system.src.js:774
link	@	system.src.js:972
doLink	@	system.src.js:631
updateLinkSetOnLoad	@	system.src.js:677
(anonymous function)	@	system.src.js:493
ZoneDelegate.invoke	@	zone.js:323
Zone.run	@	zone.js:216
(anonymous function)	@	zone.js:571
ZoneDelegate.invokeTask	@	zone.js:356
Zone.runTask	@	zone.js:256
drainMicroTaskQueue	@	zone.js:474
ZoneTask.invoke	@	zone.js:426

**Comment by rktawni** [comment] 2016-07-05 04:44
@sdmoralesma Although your solution is good to resolve the error but it makes one way binding. I need my calendar to be two way binded.

**Comment by rktawni** [comment] 2016-07-05 04:48
@DaanDD Your solution resolved my issue. It would be great if you can explain the root cause of the issue for that we all can understand it batter. 

Many Thanks to everyone!

**Comment by nandodrw** [comment] 2016-07-05 19:54
Hi. I'm having the same issue with the autoComplete.

Referencing this [stackoverflow question](http://stackoverflow.com/questions/34496514/ngmodel-no-value-accessor-for), looks like there are some requirements that a component (in this case primeng component) should follow before use [(ngModel)] binding. This was diferent on the rc1.

If you check this [documents from angular 2](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngModel) looks that the way to get the double data binding working is set `(ngModel)="your.Variable"` and `(ngModelChange)="your.Variable=$primengEvent"` on your markup.

Maybe is just me, but since the angular team is doing such deep changes on the framework API, sound crazy using angular2 on production projects for now, specially if we try to use it with external libraries like primeng.

**Comment by sdmoralesma** [comment] 2016-07-05 20:33
Yes you are right, Neither PrimeNG(beta) or Angular2(RC) are production ready by now. However you can still use them in small projects and report bugs/create pull requests so they mature faster. Keep in mind that the release date of both is still undefined (although 4th quarter of the year is probable)

**Comment by nandodrw** [comment] 2016-07-06 20:39
Good point, still playing with the library will help everybody.

**Comment by sievert** [comment] 2016-07-11 08:45
The solution that worked for me:

https://angular.io/docs/ts/latest/guide/forms.html

import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms()

**Comment by mshantic** [comment] 2016-07-13 09:28
Thanks! @DaanDD and @sievert, solved the problem for me after updating to rc4 and the new PrimeNG beta 9 (:

**Comment by PardeepJain** [comment] 2016-07-22 08:54
@sdmoralesma as per your suggestion usage of `[(model)]` removes error but i did't make two way data binding at all in any component. is there any alternate for the same ?

**Comment by sievert** [comment] 2016-07-22 08:57
... use [(ngModel)] and the new forms, as I already said 2 posts before ...

**Comment by PardeepJain** [comment] 2016-07-22 09:02
@sievert already tried still got the same error `No value accessor for ''`

**Comment by cagataycivici** [comment] 2016-07-23 15:08
Please also check;

http://forum.primefaces.org/viewtopic.php?f=35&t=46238

**Closed by cagataycivici** 2016-07-23 15:08 UTC

**Comment by MLC1435** [comment] 2016-07-27 07:22
Hi,
I still have the same error, any one have other suggestions please.

**Comment by MarkPerryBV** [comment] 2016-07-27 08:14
@MLC1435 - Check that you have added the relevant Class into your @Component({directives:[]});

I always miss that. I am using NG RC.4 and PrimeNG beta.11 with no issues.

**Comment by akumar-enbake** [comment] 2016-07-28 08:40
HI ,
I have same error :
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in build/pages/messageDetail/messageDetail.html:23:18
ORIGINAL EXCEPTION: No value accessor for ''
ORIGINAL STACKTRACE:
Error: No value accessor for ''

I use this in IONIC 2 application but i't not working 
import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap(AppComponent, [
disableDeprecatedForms(),
provideForms()

**Comment by aneesazam** [comment] 2016-10-09 17:53
@DaanDD Thank you so much, I was facing same issue which has gone now.

**Comment by aneesazam** [comment] 2016-10-09 17:55
@nandodrw, I am working with autocomplete advance like dropdown which is working well here. I got some issues but now working well. Let me know what can I do for you?

**Comment by guzhi3261** [comment] 2020-09-25 12:57
> @nandodrw, I am working with autocomplete advance like dropdown which is working well here. I got some issues but now working well. Let me know what can I do for you?
i use dropdown in my program, use http get for the data , the data can got but dropdown `s list is nothing
