### ISSUE TITLE
Sorting on PrimeNG DataTable - Row Grouping is not working properly as UI-Grid works.PrimeNg table doesn't support external/internal sorting on grouping rows.

### ISSUE THREAD

**Issue by akashdeepg12** [primefaces/primeng#3699] opened 2017-08-18 12:53 UTC
Sorting on PrimeNG DataTable - Row Grouping is not working properly as UI-Grid works like external/internal sorting on grouping rows.

On sorting , inappropriate  things are happening on PrimeNG DataTable  such as 
=> Sometimes  duplicate rows are generated. 
=> group's rows are getting separated from group.
=> It doesn't support internal sorting on grouping rows.

I couldn't understand  that how sorting works on primeNG table. I think primeNg table 's row grouping 
 sorting should works like UI-grid 's row grouping sorting .

References for In UI-grid,functionality of row grouping sorting : 
http://ui-grid.info/docs/#/tutorial/209_grouping

In UI-grid,functionality of row grouping sorting are following below : 
=> When we apply sorting on Group column ( first column) ,all group rows are sorted externally
     (Note : Only external sorting happens)
=>When we apply sorting on other group column(other than first column),only internal sorting happens  
    on grouping rows .
    (Note : Only interanl sorting happens on grouping rows).

Please provide any solution for internal sorting of row grouping.

**Comment by pavithrancr** [comment] 2017-09-06 19:00
Facing same issue. Internal sorting done programmatically within the grouping also is disregarded when rendered on screen. 
I would have expected the follwing sort function to do the trick, but Data table still looks up keys to render the internal rows within a group?
 sortByName() {
    this.dataList.sort(function (a, b) {
      let aGroup = a['groupField'].toLowerCase();
      let bGroup = b['groupField'].toLowerCase();
      if (aGroup > bGroup) return 1;
      if (aGroup < bGroup) return -1;
      let aSort = a['name'].toLowerCase();
      let bSort = b['name'].toLowerCase();
      if (aSort > bSort) return 1;
      if (aSort < bSort) return -1;
      return 0
    });
  }

**Comment by loicsalou** [comment] 2017-09-10 16:41
same issue for me. 
sorting feature should sort groups when sorting on the grouping column, and should sort the rows in the groups wen sorting on any other column. I think that sorting is applied without caring of the grouping column, that's probably the reason why groups' content is dispatched.

I'll let this down for now, hoping that some solution will come soon... Thanks for your great job, PrimeNg is really great !

**Comment by pavithrancr** [comment] 2017-09-19 17:21
This is actually a major gap in grouped tables. Any data table out there supports this behaviour. Sorting on the field should break up the groups either. 
Sort on group, then within groups. 

I am happy to contribute if a starting point is laid out here by the PrimeNg team. But i think this issue needs to get more priority than it is getting right now.

**Comment by cagataycivici** [comment] 2017-10-20 07:34
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by jilanim** [comment] 2017-12-18 19:03
@cagataycivici  Please see the code for how the table was created. It should be very clear what the issue is from the screenshot. I am new to github and this is my first comment ever so i apologize in advance if i have broken any rules :)

`<p-dataTable [value]="positions" rowGroupMode="subheader" groupField="currency" expandableRowGroups="true"  [sortableRowGroup]="false" [rows]="10" [paginator]="true" [responsive]="true">
    <ng-template pTemplate="rowgroupheader" let-rowData>{{rowData['currency']}}</ng-template>
    <p-column *ngFor="let col of cols" [style]="col.style" [field]="col.field" [header]="col.header" [sortable]="col.sortable" >
        <ng-template let-tmpl let-position="rowData" pTemplate="body">
            <span>{{position[col.field]}}</span>            
        </ng-template>
    </p-column>
</p-dataTable>`

![image](https://user-images.githubusercontent.com/33457705/34122662-338bcaee-e3fb-11e7-8c8d-3221a21fdc8e.png)

**Comment by rldasari** [comment] 2018-01-05 16:54
Having Same issue as @jilanim . Any help would be appreciated

**Comment by cagataycivici** [comment] 2018-01-13 22:34
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Closed by cagataycivici** 2018-01-13 22:34 UTC
Labels: discussion
