### ISSUE TITLE
Multiselect: The class "p-highlight" is not applied to selected items

### ISSUE THREAD

**Issue by PacoMPerez** [primefaces/primeng#15726] opened 2024-05-28 15:29 UTC
### Describe the bug

After updating to version 17.16.0 the class "p-highlight" attached to `<li>` p-multiselect-item is not present on multiselect component after selection options, it also happening on prime ng 17.17.0 as in the documentation site still not present the "p-highlight" class on selected elements:

No class present:
![Captura desde 2024-05-28 17-19-13](https://github.com/primefaces/primeng/assets/32292841/b818b6fe-d33c-4e07-8ae9-9f3bb4390ee0)

I have also checked that the property data-p-highlight changes properly but the class is not applied.

But in Dropdown and Listbox components the class still applying properly after the update:
![Captura desde 2024-05-28 17-20-42](https://github.com/primefaces/primeng/assets/32292841/0da6096b-dee8-4b75-a28e-8a0e3500ebfe)

### Environment

Running on local using Chrome.

### Angular version

17.2.3

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

- Use any type of multiselect.
- Click on an option.
- Check how the "p-highlight" class is not added how it was done in previous versions.

### Expected behavior

- Add again the "p-highlight" class  to the `<li>` p-multiselect-item.

**Comment by cetincakiroglu** [comment] 2024-05-30 07:45
Hi,

We've removed the p-highlight class from all elements with checkbox selection across all Prime UI Libraries. It's not a bug, it was a design decision.

Closing the issue, thanks for reporting!

**Closed by cetincakiroglu** 2024-05-30 07:45 UTC
Labels: Status: Needs Triage

**Comment by laurz94** [comment] 2024-05-30 15:19
So, what is the plan to support keyboard usage? In a dropdown, arrowing between options or typing the value you want does not show which item is selected. Therefore, the user has no idea which item will be selected when they tab out of the control. It looks as though nothing is selected, but then a value appears in the control. This is bad UX.

**Comment by PacoMPerez** [comment] 2024-05-30 15:40
In my case, to don't break styles that I had applied under that class  now I use the attribute as a selector on my styles.

![Captura desde 2024-05-30 17-40-35](https://github.com/primefaces/primeng/assets/32292841/cb6e461d-f015-4d5d-84b2-c943e849ad42)
