### ISSUE TITLE
InputMask with dynamic source

### ISSUE THREAD

**Issue by CarlinhosSousaJunior** [primefaces/primeng#2668] opened 2017-05-02 14:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/i8PXBoQZwcHDjr2pZDBo

**Current behavior**
Today it's not possible to use inputMask with dynamic mask (mask stored in variable), because when component mask initialize with empty string inputMask brakes.

**Expected behavior**
Support an empty string or null and change mask when the source is changed.

**What is the motivation / use case for changing the behavior?**
Allow to use inputMask with dynamic source.

* **Angular version:** 4.1.X

* **PrimeNG version:** 4.0.X

* **Browser:** [ Chrome 58 ]

 
* **Language:** [TypeScript 2.2]

**Comment by cagataycivici** [comment] 2017-06-23 07:37
Duplicate of #2632

**Closed by cagataycivici** 2017-06-23 07:37 UTC
