### ISSUE TITLE
Typed TreeNode and SelectItem

### ISSUE THREAD

**Issue by william-lohan** [primefaces/primeng#2876] opened 2017-05-24 23:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

```ts
let node: TreeNode;
node.data; // <- any

let item: SelectItem;
item.value; // <- any
```

**Expected behavior**
```ts
interface FileSystem { name: string; size: string; type: string; }
interface Column{ field: string; size: header; }

let node: TreeNode<FileSystem>;
node.data.name; // <- string

let item: SelectItem<Column>;
item.value.field; // <- string
```

I can make a pull request for this but there are multiple ways to accomplish this and I don't know which will more likely be accepted.

1. Update api models with generics, causes breaking changes and pull request with significant changes.

```ts
export interface SelectItem<T> {
    label: string;
    value: T;
}

export interface TreeNode<T> {
    label?: string;
    data?: T;
    icon?: any;
    expandedIcon?: any;
    collapsedIcon?: any;
    children?: TreeNode<T>[];
    leaf?: boolean;
    expanded?: boolean;
    type?: string;
    parent?: TreeNode<T>;
    partialSelected?: boolean;
    styleClass?: string;
    draggable?: boolean;
    droppable?: boolean;
    selectable?: boolean;
}
```

2. Update api models with generics with default parameter, no breaking changes, requires typescript 2.3.x.

```ts
export interface SelectItem<T = any> {
    label: string;
    value: T;
}

export interface TreeNode<T = any> {
    label?: string;
    data?: T;
    icon?: any;
    expandedIcon?: any;
    collapsedIcon?: any;
    children?: TreeNode<T>[];
    leaf?: boolean;
    expanded?: boolean;
    type?: string;
    parent?: TreeNode<T>;
    partialSelected?: boolean;
    styleClass?: string;
    draggable?: boolean;
    droppable?: boolean;
    selectable?: boolean;
}
```

3. extend api interface, less desirable.

```ts
export interface TypedSelectItem<T> extends SelectItem{
    value: T;
}

export interface TypedTreeNode<T> extends TreeNode {
    data?: T;
    children?: TypedTreeNode<T>[];
    parent?: TypedTreeNode<T>;
}
```

**Comment by cagataycivici** [comment] 2017-06-22 15:54
Duplicate of #2089

**Closed** 2020-09-30 14:35 UTC
Labels: enhancement
