### ISSUE TITLE
Filter popup on table auto close with keyboard

### ISSUE THREAD

**Issue by nev-21** [primefaces/primeng#10633] opened 2021-09-20 15:43 UTC
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Open this on android device: https://www.primefaces.org/primeng/showcase/#/table/filter

**Current behavior**
When open https://www.primefaces.org/primeng/showcase/#/table/filter 
And click on filter button on a field of the table (i.e. "Name") 
The filter popup appears, but when we want to write something the keyboard appears, immediately after, both, the popup and the keyboard disappear.

**Expected behavior**
When click on filter button, the first inputText get focues, and Keyboard appear. Also the popup must be placed in a correct place on the screen to allow to see Clear and Apply buttons of the filter popup.

**Minimal reproduction of the problem with instructions**
Open on an Android device: https://www.primefaces.org/primeng/showcase/#/table/filter
Click on a field filter button of the first table, and try to write something in the inputText of the popup

**What is the motivation / use case for changing the behavior?**
Filtering totally unuseful on andriod devices.

**Please tell us about your environment:**
Android

* **Angular version:** 5.X
It happens in the original page of primeng: https://www.primefaces.org/primeng/showcase/#/table/filter
Also happens in my app with:
Angular 12.1

* **PrimeNG version:** 5.X
it happens in the original page of primeng
Also happens in my app with:
Primeng 12.0.0

* **Browser:** [Chrome for android| FireFox for android | Opera mobile android]

Thanks for these great components

**Comment by nev-21** [comment] 2021-09-20 16:52
**Workaround**

I tried to do something like this: https://github.com/primefaces/primeng/issues/7260#issuecomment-465434774
but that code its diferent in primeng version 12. I did this and it worked:

copy from dropdown.js
node_modules\primeng\esm2015\dropdown\dropdown.js

```js
   bindDocumentResizeListener() {
        this.documentResizeListener = this.onWindowResize.bind(this);  <----------------- copy this
        window.addEventListener('resize', this.documentResizeListener);
    }

  // -------------- copy this method too --------------
  onWindowResize() {  
        if (!DomHandler.isAndroid()) {
            this.hide();
        }
    }
```

past to primeng-table.ts
node_modules\primeng\fesm2015\primeng-table.js

```js
 bindDocumentResizeListener() {
        this.documentResizeListener = () => this.hide(); <-------------------- here
        window.addEventListener('resize', this.documentResizeListener);
    }
// copy the method here
```

Hope it help to fix this bug.

**Comment by jzpeterson** [comment] 2021-09-27 20:04
I am seeing similar behavior with the p-calendar. Its closed by the window resize event making it unusable for tablet users.

**Comment by elliottregan** [comment] 2022-03-29 22:28
Same. This occurs in the DynamicDialog component.

I've also triggered it in the MultiSelect dropdown component on iOS when the keyboard comes up.

**Comment by mertsincan** [comment] 2022-05-30 14:02
Duplicate of [11567](https://github.com/primefaces/primeng/issues/11567)

**Closed by mertsincan** 2022-05-30 14:02 UTC
