### ISSUE TITLE
Paginator dropdown misaligned when appendTo 'body' using flexbox

### ISSUE THREAD

**Issue by hugonoro** [primefaces/primeng#6486] opened 2018-09-11 10:11 UTC
**I'm submitting a**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-a1qaq6.stackblitz.io

**Current behavior**

It seems there is currently a bug in the calculation of the dropdown when appended to 'body' (absolute position) when working with flexbox. The first opening of the dropdown aligns the overlay with the select box itself. All subsequent calls have an issue with the alignment where the box is pushed a few pixels to the left. It seems to me it's pushed the same amount of pixels as the width of the scrollbar (although it's not visible)

**Expected behavior**

I would expect the dropdown overlay to always be aligned with the select box independently of the layout used approach

**Minimal reproduction of the problem with instructions**

1. Load the provided stackblitz sample
2. Open the rows per page dropdown in the paginator component once and verify it's correctly aligned
3. Open the rows per page dropdown in the paginator component again and verify they are no longer aligned

**What is the motivation / use case for changing the behavior?**

Dropdowns should always have their overlays aligned

**Please tell us about your environment:**

Windows 10, Webstorm, npm

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

Angular version 6.1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   v10.6.0
![firstopening](https://user-images.githubusercontent.com/8047547/45353628-3ce1bb00-b5b3-11e8-87bd-35d8a5b8c64b.PNG)
![afterfirstopening](https://user-images.githubusercontent.com/8047547/45353629-3ce1bb00-b5b3-11e8-8ba4-0c06ed4ae4e2.PNG)

**Comment by JayakarVangeti** [comment] 2019-02-26 10:38
@hugonoro Did you find any solution?

**Comment by Sangameshwarpuramwar** [comment] 2019-05-23 09:23
I am also facing similar issue, any solution yet?

**Comment by mertsincan** [comment] 2019-06-18 08:37
Duplicate of #7808. Fixed for next version.

**Closed by mertsincan** 2019-06-18 08:37 UTC
