### ISSUE TITLE
Give the developers a means to enable/disable "PreventDefault" on KeyDown of UITreeNode

### ISSUE THREAD

**Issue by marcodafonseca** [primefaces/primeng#8030] opened 2019-08-06 21:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-rub4ka

**Current behavior**
Arrow keys are only supported for navigating around the tree irrespective of whether a node may be editable or not. UITreeNode.OnKeyDown functionality fires preventDefault() method which stops the keypress event from propagating down to the input element

**Expected behavior**
If a user is editing a node's name they should be to navigate through the letters with the arrow keys like in any other application/website

**Minimal reproduction of the problem with instructions**
Minimal reproduction steps:
Add a p-tree element to a web-page
Make a node editable
Try navigate the letters of the editable node via the keyboard
https://stackblitz.com/edit/github-rub4ka

**What is the motivation / use case for changing the behavior?**
Improves usability for users

**Please tell us about your environment:**
Windows 10
Visual Studio

* **Angular version:** 5.X
Angular 6.x

* **PrimeNG version:** 5.X
PrimeNg 6.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
9.2.0

**Comment by mertsincan** [comment] 2019-08-18 21:45
Duplicate of #8039

**Closed by mertsincan** 2019-08-18 21:45 UTC
