### ISSUE TITLE
p-dialog can't be dragged freely when you scroll the page down to the bottom

### ISSUE THREAD

**Issue by cicciogeppo88** [primefaces/primeng#10025] opened 2021-03-19 11:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primeng-dialog-demo.stackblitz.io

**Current behavior**
if you display a p-dialog, it can be freely dragged around the page when you are at the top of the page. 
When you scroll down you can drag the p-dialog only in the horizontal axis and often the dialog will stick to the bottom of the window
(please check attached video)

**Expected behavior**
Once displayed the dialog can be dragged freely in each position of the page

**Minimal reproduction of the problem with instructions**
1) go to the primeng dialog demo version 11.3.1 at https://primefaces.org/primeng/showcase/#/dialog
2) Click on the first show button of the basic dialog
3) try to drag around the dialog where it's displayed, you will be able to do that
4) scroll down towards the bottom of the page
5) try to drag around the above dialog , you won't be able to drag it freely, but only to the horizontal axis

**What is the motivation / use case for changing the behavior?**
the p-dialog should move freely as in primeng version 9 https://www.primefaces.org/primeng/v9-lts/#/dialog

**Please tell us about your environment:**
I am using Chrome 64bit version 89.0.4389.90 

* **PrimeNG version:** 5.X
this issue is happening in primeng 10 and 11

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 64bit version 89.0.4389.90 , Edge version 44.18362.449.0
 
Thanks! 

https://user-images.githubusercontent.com/42539160/111776427-e8b5a100-88a9-11eb-88f8-e2a3b1fa5620.mp4

**Comment by CC84** [comment] 2021-03-19 12:40
This is a duplicate of #9775

**Comment by yigitfindikli** [comment] 2021-03-22 07:11
Set blockScroll to true.

**Closed by yigitfindikli** 2021-03-22 07:11 UTC

**Comment by cicciogeppo88** [comment] 2021-03-22 15:49
> Set blockScroll property to true for block the scroll.

Thanks but it won't work in the case the dialog is not toggled from the top of the page, also, I would like to keep the possibility of scroll.
