### ISSUE TITLE
Shrink autoresize textarea instantly

### ISSUE THREAD

**Issue by quekqh** [primefaces/primeng#7978] opened 2019-07-23 02:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://www.primefaces.org/primeng/#/inputtextarea

AutoResize
In autoresize mode, textarea does not shrink instantly if lines are deleted.

**Current behavior**
After typing a paragraph, removing the text (either removing 1 or 2 lines of text or removing the paragraph entirely) does not shrink the textbox instantly. The textbox gradually resizes if backspace is pressed or more text is added.

**Expected behavior**
Textbox shrinks to fit the text instantly

Angular version: 8.0.0

PrimeNG version: 7.1.3

I think its related to this issue #7778

**Comment by JacobSiegle** [comment] 2019-07-23 12:50
The related issue linked has a PR which should fix this - https://github.com/primefaces/primeng/pull/7785

**Comment by yigitfindikli** [comment] 2019-09-04 08:19
duplicate of #7778  .

**Closed by yigitfindikli** 2019-09-04 08:19 UTC
