### ISSUE TITLE
Component: Menu

### ISSUE THREAD

**Issue by Xample** [primefaces/primeng#11968] opened 2022-09-23 13:28 UTC
### Describe the bug

Menu is using a future reserved attribute:

> Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute. This usage will *likely cause site breakage* when the popup API ships: https://chromestatus.com/feature/5463833265045504. <p-menu popup=​"popup" appendto=​"body" class=​"p-element ng-tns-c104-11 ng-star-inserted" ng-reflect-popup=​"popup" ng-reflect-append-to=​"body" ng-reflect-model=​"[object Object]​">​…​</p-menu>​

I would advise deprecating this attribute and providing an alias

### Environment

Any project

### Angular version

14.2.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v16.13.1

### Browser(s)

Chrome Version 103.0.5060.114 (Official Build) (arm64)

### Steps to reproduce the behavior

Just add a menu with the  'popup' attribute
```html
<p-menu  popup="true"></p-menu>
```

**Comment by cetincakiroglu** [comment] 2022-09-30 14:18
Hi,

Does not cause any problems, it's not a bug, defect, or enhancement request. Closing the issue, thank you for your support!

**Closed by cetincakiroglu** 2022-09-30 14:18 UTC
Labels: wontfix

**Comment by Xample** [comment] 2022-09-30 15:26
> This usage will likely cause site breakage when the popup API ships:

I think this is part of the upcoming html6 standard (for native popups).
