### ISSUE TITLE
Grouping Functionality in p-table Breaks After Pagination Navigation Beyond First Page

### ISSUE THREAD

**Issue by EleftheriosTsiridis** [primefaces/primeng#15192] opened 2024-03-28 13:01 UTC
### Describe the bug

Issue Title:

Grouping Functionality in p-table Breaks After Pagination Navigation Beyond First Page

Issue Description:

When integrating paginator logic into the existing PrimeNG <p-table> component, a functionality inconsistency occurs. After navigating beyond the first page using the paginator controls, the grouping functionality ceases to operate correctly. Instead of maintaining the intended grouping structure, each row appears to be grouped individually.

Steps to Reproduce:

    Use the existing PrimeNG example of Row Group Subheader in StackBlitz (accessible via https://primeng.org/table).
    Integrate paginator logic into the PrimeNG <p-table> component.
    Navigate beyond the first page using the paginator controls.
    Observe the breakdown in grouping functionality, where each row seems to be grouped individually.

Expected Behavior:

After navigating to subsequent pages using the paginator, the grouping functionality should remain intact, preserving the original group structure as defined by the groupRowsBy attribute.

Additional Information:

    PrimeNG Version: 17.12.0
    Angular Version: 17.3.1

Note:

This issue significantly impacts user experience and functionality, especially when managing large datasets where pagination and grouping are vital features. Prompt attention and resolution of this matter would be greatly appreciated. Additionally, it's worth noting that this issue may be related to https://github.com/primefaces/primeng/pull/14672.

### Environment

stackblitz.com

### Angular version

17.3.1

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

### Steps to reproduce the behavior

   1) Use the existing PrimeNG example of Row Group Subheader in StackBlitz (accessible via https://primeng.org/table).
   2) Integrate paginator logic into the PrimeNG <p-table> component.
   3) Navigate beyond the first page using the paginator controls.
   4) Observe the breakdown in grouping functionality, where each row seems to be grouped individually.

**Comment by psarno** [comment] 2024-04-04 22:20
This seems like the issue I opened back in 2022 ([11764](https://github.com/primefaces/primeng/issues/11764)).

It's still open (and still broken) last I checked.

**Comment by EleftheriosTsiridis** [comment] 2024-04-05 06:16
> This seems like the issue I opened back in 2022 ([11764](https://github.com/primefaces/primeng/issues/11764)).
> 
> It's still open (and still broken) last I checked.

Hello,

I wanted to update you on the issue. The grouping functionality was working between versions 17.2 to 17.11 but seems to have regressed in the latest version.

Can you reproduce the problem in StackBlitz for those versions? Share the links so we can investigate.

Best regards

**Comment by DSyarovIV** [comment] 2024-04-25 11:54
Hello,
I managed to reproduce it. Here is a stackblitz: https://stackblitz.com/edit/3gpdab?file=src%2Fapp%2Fdemo%2Ftable-subheader-grouping-demo.html

**Comment by EleftheriosTsiridis** [comment] 2024-04-30 10:07
> Hello, I managed to reproduce it. Here is a stackblitz: https://stackblitz.com/edit/3gpdab?file=src%2Fapp%2Fdemo%2Ftable-subheader-grouping-demo.html

Yes, as i told you after navigating beyond the first page using the paginator controls, the grouping functionality ceases to operate correctly. Instead of maintaining the intended grouping structure, each row appears to be grouped individually.

Any help would be appreciated.

Here are some screenshots from your stackblitz link:
![Screenshot_1](https://github.com/primefaces/primeng/assets/112630569/655dd52b-7098-4db8-a96b-ea17bfa20c0b)
![Screenshot_2](https://github.com/primefaces/primeng/assets/112630569/a31e5a91-5a54-4120-aa5d-df6b584a85b7)
![Screenshot_3](https://github.com/primefaces/primeng/assets/112630569/6b9519a7-e05d-4d10-97cb-bacf9935a1c1)

**Comment by marshal-yurii** [comment] 2024-07-05 15:44
> > This seems like the issue I opened back in 2022 ([11764](https://github.com/primefaces/primeng/issues/11764)).
> > It's still open (and still broken) last I checked.
> 
> Hello,
> 
> I wanted to update you on the issue. The grouping functionality was working between versions 17.2 to 17.11 but seems to have regressed in the latest version.
> 
> Can you reproduce the problem in StackBlitz for those versions? Share the links so we can investigate.
> 
> Best regards

Thank you, e.g. v ~17.9.0 works for groups through pagination

**Comment by digeomel** [comment] 2024-07-11 14:55
I can confirm that it seems to be fixed in v `~17.9.0`, but it is broken again on later versions that I tried 🤷🏻‍♂️

**Comment by AyoubTachtouktDekra** [comment] 2024-08-23 02:07
Still got this error

**Comment by Rodesc** [comment] 2024-08-23 09:30
I still have this error in 17.16

**Closed** 2024-09-26 14:40 UTC
Labels: Type: Bug

**Comment by shanmuga-act** [comment] 2025-01-22 14:40
It looks like the expandable row grouping looks fine in all the pages. But the expandable row group footer template getting attached with all the rows on second page onwards. But it looks fine in the first page. Pasted the 'stackblitz' link with this issue for your reference. Let me know if you need any more info.

Angular Version - 17
Primeng version - 17.18.13

https://stackblitz.com/edit/pjmitklr?file=src%2Fapp%2Ftable-expandable-row-group-demo.html

![Image](https://github.com/user-attachments/assets/ab0bf903-e628-4b05-9ec0-15dac1d2fe2c)

**First Page -** 

![Image](https://github.com/user-attachments/assets/41569270-0e93-43a2-9f0f-cbc2ffe30028)
