### ISSUE TITLE
p-fileUpload: after upgrade to primeng 7 there is no possibility to get response

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primeng#7179] opened 2019-01-28 12:50 UTC
there is no possibility to get response
primeng 6:
onUpload(event: any) {
        const uploadedDocuments = JSON.parse(event.xhr.responseText);

primeng 7:
onUpload(event: any) {
        const uploadedDocuments = JSON.parse(event.xhr.responseText); 
        **event.xhr is undefined.**

But i don't see any other possibility to obtain response in primeng7.(in our case response contains file id that was created on the backend side)

**Comment by TriplicateGirl** [comment] 2019-01-28 17:58
I believe this was caused by a change 7.0.5.

https://github.com/primefaces/primeng/pull/7091

I am also curious how to get the response, I was doing something very similar to you.

I was also using event.formData.append in the onBeforeSend, which no longer is working either.

**Comment by andreLagacione** [comment] 2019-01-28 23:47
I had the same issue today in version 7.0.5, the response was an empty formData and hadn't the xhr, I installed the version 7.0.5 and the response it's OK, I needed get the response for add the token in the header in onBeforeSend callback:
public addHeader(event) {
	event.xhr.setRequestHeader('Authorization', `Bearer ${this.uploadService.getToken()}`);
}

I suggest to you use the version 7.0.4, set "primeng": "7.0.4" in package.json

**Comment by vrt2015** [comment] 2019-02-07 19:47
Is there going to be a fix for this? We would like to get access to the response back from our API

**Comment by i255** [comment] 2019-02-09 20:56
Every second minor release breaks something in my app. That is sad. Could you please add the HttpResponse variable to the onUpload event handler like so:
this.onUpload.emit({files: this.files, event: event});
instead of this.onUpload.emit({files: this.files}); in line 329

**Comment by gasparbarancelli** [comment] 2019-02-11 19:41
> I had the same issue today in version 7.0.5, the response was an empty formData and hadn't the xhr, I installed the version 7.0.5 and the response it's OK, I needed get the response for add the token in the header in onBeforeSend callback:
> public addHeader(event) {
> event.xhr.setRequestHeader('Authorization', `Bearer ${this.uploadService.getToken()}`);
> }
> 
> I suggest to you use the version 7.0.4, set "primeng": "7.0.4" in package.json

You can now add the token by the httpclient interceptor.

**Comment by gasparbarancelli** [comment] 2019-02-11 19:52
> there is no possibility to get response
> primeng 6:
> onUpload(event: any) {
> const uploadedDocuments = JSON.parse(event.xhr.responseText);
> 
> primeng 7:
> onUpload(event: any) {
> const uploadedDocuments = JSON.parse(event.xhr.responseText);
> **event.xhr is undefined.**
> 
> But i don't see any other possibility to obtain response in primeng7.(in our case response contains file id that was created on the backend side)

In the previous version of the primeng was not used the httpclient to send the file, it was done by XMLHttpRequest, so the xhr was returned.
Returning the proper event of httpclient I believe it solves this problem for you.

**Comment by eltonmmoreira** [comment] 2019-02-12 16:40
I was having the same problem as you and I just sent a pull request by adding the event to the onUpload event based on the httpclient now used in the component. To retrieve the return body of the request, access the responseEvent.body property.

**Comment by oliverfrost** [comment] 2019-02-20 17:01
As a workaround it is possible to use custom file uploader instead of default. Even with 'base' mode.

Template:
```html
<p-fileUpload
     customUpload="true"
     (uploadHandler)="onFileUpload($event)">
</p-fileUpload>
```

Component:
```typescript
public onFileUpload(): void {
    const formData: FormData = new FormData();

    formData.append('file', file, file.name);
    this.httpClient
        .post<any>(url, formData)
        .subscribe(r => {
            // do what you need here
        })
}
```

**Comment by cagataycivici** [comment] 2019-02-28 13:12
Fixed via PR.

**Closed by cagataycivici** 2019-02-28 13:12 UTC
Labels: defect

**Comment by alan-saar** [comment] 2019-03-13 16:19
https://www.primefaces.org/primeng/#/fileupload
the demo page is not showing the message when the file is uploaded

**Comment by fitness23** [comment] 2019-04-17 09:36
This hasn't been fixed.

**Comment by jcmendez0907** [comment] 2019-04-21 21:00
Hi, you can to get the response like this.
`  public onUpload(event) {
    //here is the response 
    console.log('Response ', event.originalEvent.body);
  }`

**Comment by masoudline** [comment] 2019-05-15 13:25
how can i added interceptor to specific url for p-fileupload

**Comment by marco-digidip** [comment] 2019-05-28 10:02
Before primeNg 7, i was customizing the request http headers OnBeforeSend event. Now it is not possible as from the $event i only get the formData object. 

Any update on this? Do i have to write my own custom file uploader as @oliverfrost  suggests?

The documentation is wrong thou because it says (about the OnBeforeSend event):
"Callback to invoke before file send begins to customize the request such as adding headers."
How?!...

**Comment by marco-digidip** [comment] 2019-05-28 10:25
My workaround to add custom http headers to the upload file post request, was to intercept that request, clone it, and add the custom headers...

**Comment by gasparbarancelli** [comment] 2019-05-28 12:10
To solve your problem, just create the interceptor of the httpClient of the Angular itself. 
https://alligator.io/angular/httpclient-interceptors/

**Comment by AlejandroFlorin** [comment] 2019-05-30 22:16
Yeah, this broke for me as well in 7.x. I managed to tweak my existing interceptor to include my authorization header for file uploads. But there is still an issue because event.formData.append doesn't seem to add values to the request's formData. I need to include various pieces of information with the upload (like the id of the user that did the upload)

**Comment by jaybhanushali3166** [comment] 2020-03-12 18:31
This is the code which i have been working on with:
` <p-fileUpload 
                            mode="basic" 
                            name='field'
                            [auto]='false'

                            accept="image/*" 
                            maxFileSize="1000000" 
                            [showUploadButton]="true"
                            [showCancelButton]="true"
                            (onUpload)="onUpload($event)"
                            >
                        </p-fileUpload>`
Ts File
`  onUpload(event) {
    console.log("file",event);
    for(let file of event.files) {
        this.uploadedFiles.push(file);
    }
    this.messageService.add({severity: 'info', summary: 'File Uploaded', detail: ''});

`

Unable to print event. Can anyone help me with this?
