### ISSUE TITLE
Templates and pagination don't work together.

### ISSUE THREAD

**Issue by jgiro** [primefaces/primeng#1679] opened 2016-12-25 20:25 UTC
Latest version of Angular 2 and PrimeNG.

If I add a template to <p-dataTable> and have the pagination logic running, the column containing the template is not is not refreshed, it remains always showing the data for the first page. Columns without templates are rendered correctly. The way to insert the template was copied from your site.

**Comment by doronnac** [comment] 2016-12-26 13:07
I can confirm this behaviour.
This seems to be a bug in v1.1.2, to solve it I had to revert to v1.0.1.

**Comment by NikitaForm** [comment] 2016-12-26 13:29
Confirm. It's not working in v1.1.2. Critical issue.

**Comment by nate-knight** [comment] 2016-12-27 21:19
Good to know. I will revert to 1.0.1. Hopefully this is resolved soon.

**Comment by bogacg** [comment] 2016-12-28 12:48
I have the same issue. Possibly fix for breaking change made in latest Angular 2 update broke this one.  #1652

**Comment by NikitaForm** [comment] 2016-12-28 12:55
I've fixed it in my project with custom rowTrackBy
`rowTrackBy(index: number, row: any) {
        return row.id;
    }`
Just mapped it to corresponded property of p-dataTable
`[rowTrackBy]="rowTrackBy"`

**Comment by bogacg** [comment] 2016-12-28 13:12
@NikitaForm Instead of `row.id` I've used property in my row object that didn't triger template refresh when expected, and it seems to work. Thanks

**Comment by izll** [comment] 2016-12-29 12:36
Hm, It took me half a day before I realized that this error causing, that not refreshing the table :)

**Comment by rklempert** [comment] 2016-12-30 18:15
Angular 2.4.1 and PrimeNG 1.1.2

Templated columns do not refresh contents when paging or sorting, as mentioned by the original issue creator. Is there an ETA for this to get resolved?

Thank you.

**Comment by CG0323** [comment] 2016-12-30 23:22
my workaround is using rowIndex and access the correct object via your data array, however, this has another issue... when go to the last page (usually not a full page), then come back to previous page, the rowIndex becomes a very large number...  I found that by using rowIndex = rowIndex % pagesize, I can get the correct rowIndex.

This is just an ugly workaround, hope the issue can be fixed soon.

**Comment by sudheerj** [comment] 2017-01-01 10:15
I can replicate the issue with PrimeNG 1.0.0 release as well.

**Comment by on3al** [comment] 2017-01-02 20:39
I have replicated the issue in ^1.1.2.  Any templated column does not refresh when sorting.

**Comment by cagataycivici** [comment] 2017-01-03 16:01
Fixed via #1711, by the way PrimeNG 1.1.3 is released having the fix.

**Closed by cagataycivici** 2017-01-03 16:01 UTC
