### ISSUE TITLE
[BUG] RouterLink not working in p-panelMenu

### ISSUE THREAD

**Issue by igogu** [primefaces/primeng#2420] opened 2017-03-30 09:03 UTC
[ X] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
It's not a working plunkr, but you can see the code
https://plnkr.co/edit/d6BSgRYbBzk7r4NB4bwy?p=info

**Current behavior**
When you set a routerlink to a child menuItem, this is not redirecting to any component. However, when a parent menuItem has a RouterLink, this can redirect to a component

**Expected behavior**
when a child of menuItem has RouterLink, it should redirect to a component.

**Minimal reproduction of the problem with instructions**
```

 this.itemsPrueba = [                      
                      {
                          label: 'Articles',
                          icon: 'fa-edit',
                          items: [
                              {label: 'Articles Gamma', icon: 'fa fa-dot-circle-o fa-fw', routerLink: ['/index/articles']},
                          ]
                      },
                      
                  ];
<p-panelMenu [model]="itemsPrueba" ></p-panelMenu>
```

For more details, go to the plunkr

**What is the motivation / use case for changing the behavior?**
In Angular 2.x.x and primeNG 2.0.5 was working right, 

**Please tell us about your environment:**
OS: Ubuntu 16.04
IDE: Eclipse Neon
package manager: npm 3.10.9
typescript 2.2.2

* **Angular version:** 2.0.X
Angular version: 4.0.0 & 4.0.1 (its not working with no one of those)

* **PrimeNG version:** 2.0.X
PrimeNG version:** 4.0.0-rc.2

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by snowping** [comment] 2017-03-30 11:32
I experience probably the same issue with <p-menubar> using angular 4.0.0 and V4 rc2.  the routerLink redirection was working with angular 4.0.0 and V4 rc1.

**Comment by erlopezh** [comment] 2017-03-30 16:07
The same issue here, using angular 4.0.0 and V4 rc2 the routerLink redirection does not working

**Comment by derchirurg** [comment] 2017-04-03 07:43
Same here using angular 4.0.1 and primeng 4.0.0-rc.2.
The link is incorrect. It has href="#".

**Comment by xyz765** [comment] 2017-04-03 10:21
The same issue with MenuBar used to work fined and stopped working after updating, links shows "/#" not errors in console.

**Comment by Brampage** [comment] 2017-04-03 10:30
@xyz765 Same for me.

**Comment by ImproSnake** [comment] 2017-04-03 11:26
I got the same Issue but only on the SubMenuItems. The routerLink on a top Level MenuItem works just fine.

**Comment by SchneMa** [comment] 2017-04-03 13:47
got the same bug. Is there any workaround for now?

**Comment by kcsahoo** [comment] 2017-04-03 15:31
Use rc.1

**Comment by mamarillo** [comment] 2017-04-03 16:19
@kcsahoo i'm sorry, can you explain? this is my first pull request ever.

**Comment by kcsahoo** [comment] 2017-04-04 10:30
In your application you have to use Primeng V4.0.0-rc.1 with Angulat V4.0.1
I have tested.
All features work.

**Comment by kcsahoo** [comment] 2017-04-04 10:31
I hope Primeng team will resolve this issue in next rc version and rtm version

**Comment by SIlver--** [comment] 2017-04-07 22:00
Also have this bug. `routerlink` just seems to not be getting set at all

**Comment by Czin7** [comment] 2017-04-14 11:18
I have the same problem

**Comment by elega9t** [comment] 2017-04-18 07:31
same bug. routerLink is not correctly set

**Comment by paulkeogh** [comment] 2017-04-23 16:27
And here with PrimeNG v4.0.0-rc3 and Angular 4.0.3

My code is;

`            { label: 'Filesystem', routerLink: ['/filesystemrepository'] },
            { label: 'AWS', url: 'http://www.primefaces.org/primeng' },
`

The AWS menu item works fine. the Filesystem one is rendered with href="#"

No errors in console either.

**Comment by cagataycivici** [comment] 2017-05-02 15:16
Can you try with 4.0 final?

**Comment by cagataycivici** [comment] 2017-05-02 15:26
Duplicate of https://github.com/primefaces/primeng/issues/2522

**Closed by cagataycivici** 2017-05-02 15:26 UTC

**Comment by a496736** [comment] 2017-05-02 16:24
Still happening for me in `4.0.0 final` using angular `4.1`

https://plnkr.co/edit/KlPzhzvFzXfTqL82SIzy?p=preview

(primeng seems to be down atm for plunker)

**Comment by sudheerj** [comment] 2017-05-14 15:11
I can't replicate the issue.It works good in latest version. Please try on latest version. Currently the issue exists for TieredMenu only.

**Comment by cagataycivici** [comment] 2017-05-15 06:16
Is there a filed issue for TieredMenu?

**Comment by sudheerj** [comment] 2017-05-15 07:19
Yes, it was filed here https://github.com/primefaces/primeng/issues/2763 . The child reference variable should be used instead item variable which doesn't exist.Shall I raise the PR?
