### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on newer version on Table

### ISSUE THREAD

**Issue by dimitev** [primefaces/primeng#10886] opened 2021-11-26 09:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-dpdgu9?file=src/app/app.component.ts

**Current behavior**
When the length of the value array changes, the table crashes.

**Expected behavior**
To display the new items

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-dpdgu9?file=src/app/app.component.ts
If the start array has different length than the one after adding the data, the exception occurs

**What is the motivation / use case for changing the behavior?**
So table can work with datasets that vary in length

**Please tell us about your environment:**

* **Angular version:** 13

* **PrimeNG version:** 13
Also occurs on 12, works on 11 and lower

* **Browser:** 
Chrome  96.0.4664.45
 
* **Language:** [TypeScript 4.0.2]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment] 2021-11-30 12:24
Duplicate of https://github.com/primefaces/primeng/issues/10659

**Closed by yigitfindikli** 2021-11-30 12:24 UTC
