### ISSUE TITLE
DataTable resorting itself on mouse move after editing a row in Chrome

### ISSUE THREAD

**Issue by mmalolepszy** [primefaces/primeng#442] opened 2016-06-01 12:43 UTC
The problem occurs when you sort data in datatable by a column containing some identical values and then edit a row. While it is happening you cannot go to another page or select a row, but you can sort by any column. After sorting everything is back to normal. 

Here's a video showing what's happening: https://drive.google.com/file/d/0BwPCl7wxsJm8NmVRWE5JNURIdFE/view?usp=drivesdk

It can be easily reproduced in primeng-quickstart.

Steps to reproduce:

1. Clone primefaces/primeng-quickstart
2. npm install && npm start
3. Sort the Brand column
4. Click any row, edit anything and click save
5. Move your mouse

It affects primeng versions beta.6, beta.7 and beta.8 with Chrome 50.0.2661.102 and 51.0.2704.63. 
Firefox, IE and Edge are not affected.

**Comment by GraemeSMiller** [comment] 2016-06-02 12:12
This is a dupe of this https://github.com/primefaces/primeng/issues/396 - which I also duplicated as https://github.com/primefaces/primeng/issues/402

**Comment by cagataycivici** [comment] 2016-06-28 18:15
Tracking at 396

**Closed by cagataycivici** 2016-06-28 18:15 UTC
