### ISSUE TITLE
p-dropdown: optionValue is not properly working

### ISSUE THREAD

**Issue by SpiderPork** [primefaces/primeng#14141] opened 2023-11-16 15:49 UTC
### Discussed in https://github.com/orgs/primefaces/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **BrayanDevM** November  8, 2023</sup>
# The issue
The `optionValue` of the component is not working correctly. I performed a version migration from PrimeNG 15 to *16.7.2*, and immediately the dropdowns that receive an object but have their value and label specified stopped working. They are displayed correctly, but when selecting an option, the dropdown remains empty, and in the HTML, the value "empty" appears.

![image](https://github.com/primefaces/community/assets/20876438/b6c1b4b0-245e-432d-a799-b45868be5129)

# Code
```
form = this.fb.nonNullable.group({
  identificationTypeId: [1, [Validators.required]],
  identification: ['', [Validators.required, Validators.pattern(/^[0-9]*$/)]]
});

identificationTypeList = [
  { id: 1, shortName: 'CC', description: 'Cedula de ciudadania' },
  { id: 2, shortName: 'CE', description: 'Cedula de extranjeria' }
];
```
```
<p-dropdown
  optionValue="id"
  optionLabel="description"
  formControlName="identificationTypeId"
  [options]="identificationList"
></p-dropdown>
```

</div>
<br>
This is a testcase showing the problem:

https://stackblitz.com/edit/rxgqkz?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

### Environment

    "@angular/animations": "^16.2.0",
    "@angular/cdk": "^16.2.11",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/material": "^16.2.11",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "primeng": "^16.7.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"

### Reproducer

https://stackblitz.com/edit/rxgqkz?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

### Angular version

16.2

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

### Browser(s)

Firefox / Edge

**Comment by Phil-DS** [comment] 2023-11-16 16:13
Yeah, been having issues with this too

**Comment by cetincakiroglu** [comment] 2023-11-16 17:35
Hi,

Duplicate of https://github.com/primefaces/primeng/issues/14094
Already fixed and fix will be available in the upcoming release.

Closing the issue

**Closed by cetincakiroglu** 2023-11-16 17:35 UTC
Labels: Status: Needs Triage

**Comment by pete-mcwilliams** [comment] 2023-11-21 16:02
not fixed, breaking change if not able to specify optionValue then entire option will to be stored in ngModel (label and value) https://github.com/primefaces/primeng/issues/14172

**Comment by kiknadze** [comment] 2024-01-09 15:38
![image](https://github.com/primefaces/primeng/assets/9992978/c18ee0f4-fdd6-4cc8-8a24-9ad2a91b1845)
I use version: 16.9.1 and still have this issue

**Comment by neddyKG** [comment] 2024-01-19 13:20
Not working on the dropdown with filter. When I select an option the dropdown turns blank. If I remove optionValue it works normal, but I need the value to save to database.

``` 
<p-dropdown
              class="md:w-20rem w-full dropdown"
              [options]="diagnosisList"
              [(ngModel)]="diagnosis"
              formControlName="diagnosis"
              optionLabel="name"
              optionValue="value"
              [filter]="true"
              filterBy="name"
              [showClear]="true"
              placeholder="Seleccione el diagnostico">
              <ng-template pTemplate="selectedItem">
                <div class="flex align-items-center gap-2" *ngIf="diagnosis">
                  <div>{{ diagnosis.name }}</div>
                </div>
              </ng-template>
              <ng-template let-diagnosis pTemplate="item">
                <div class="flex align-items-center gap-2">
                  <div>{{ diagnosis.name }}</div>
                </div>
              </ng-template>
            </p-dropdown>
```
