### ISSUE TITLE
p-dropdown: pTemplate="selectedItem" not working as expected

### ISSUE THREAD

**Issue by jerkovicl** [primefaces/primeng#14171] opened 2023-11-21 15:58 UTC
### Describe the bug

`pTemplate="selectedItem"` does not show label when defined with `optionLabel`

```
<div class="card flex justify-content-center">
  <form [formGroup]="formGroup">
    <p-dropdown
      formControlName="city"
      [options]="cities"
      optionValue="code"
      optionLabel="name"
    >
      <!-- selected item will work if .name is removed, but will show the value as label -->
      <!-- pTemplate="item" works with .name -->
      <ng-template let-filterSelectedProperty pTemplate="selectedItem">
        <span>{{ filterSelectedProperty.name }}</span>
      </ng-template>
      <ng-template let-filterProperty pTemplate="item">
        <span>{{ filterProperty.name }}</span>
      </ng-template>
    </p-dropdown>
  </form>
</div>

```

### Environment

angular 17.0.4
primeng v16.8.0
win 11

### Reproducer

https://stackblitz.com/edit/w3qrm1-n1qsfq?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts%2Csrc%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

### Angular version

17.0.4

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

**Comment by pete-mcwilliams** [comment] 2023-11-21 15:59
https://github.com/primefaces/primeng/issues/14172

**Comment by jerkovicl** [comment] 2023-11-21 16:01
@pete-mcwilliams didnt see you reported it already

**Comment by pete-mcwilliams** [comment] 2023-11-21 16:03
Sorry, I meant we both reported it at same time, there are other issues that have been closed related to this.

**Comment by jerkovicl** [comment] 2023-11-21 16:09
yeah so many issue with dropdowns :)

**Comment by cetincakiroglu** [comment] 2023-11-22 06:42
Duplicate of https://github.com/primefaces/primeng/issues/14172 you can track the issue from there. Closing this one.


Thanks a lot for reporting the issue!

**Closed by cetincakiroglu** 2023-11-22 06:42 UTC
Labels: Status: Needs Triage
