### ISSUE TITLE
Set a class to Autocomplete emptyMessage

### ISSUE THREAD

**Issue by csvinhal** [primefaces/primeng#7824] opened 2019-06-19 17:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Autocomplete emptyMessage show's up with the same style of the autocomplete suggestions.

**Expected behavior**
I want to be able to set a class to the autocomplete emptyMessage to style it different from the suggestions.

**What is the motivation / use case for changing the behavior?**
With the emptyMessage styled different will be more visible that it isn't a suggestion.

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment] 2019-06-19 17:48
Duplicate of #7791 https://github.com/primefaces/primeng/issues/7791

**Closed by mertsincan** 2019-06-19 17:48 UTC
