### ISSUE TITLE
button-directive: type button is missing

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#13748] opened 2023-09-26 09:21 UTC
### Describe the bug

using the button directive, the type of the html button is not set to button, it is default submit and has a different behaviour than its counterpart p-button

### Environment

angular and primeng 16

### Angular version

16.2.4

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome

### Expected behavior

It should set type to "button" when using the button directive

**Comment by cetincakiroglu** [comment] 2023-09-26 12:07
You can set type by html. The directive lets you free to set any attribute that you want to the button. 
See the example: https://stackblitz.com/edit/dupzpk?file=src%2Fapp%2Fdemo%2Fbutton-directive-demo.html

Closing the issue since it's not a bug, enhancement or feature request.

**Closed by cetincakiroglu** 2023-09-26 12:07 UTC
Labels: Status: Needs Triage
