### ISSUE TITLE
Autocomplete with onBlur event

### ISSUE THREAD

**Issue by vitorstick** [primefaces/primeng#2256] opened 2017-03-09 12:33 UTC
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Adding onBlur event to Autocomplete**

**Expected behavior**
Get the moment when autocomplete is not selected anymore

**What is the motivation / use case for changing the behavior?**
When user only fills with text and don't select none of the options displayed, we chose the most probable for him on them method called by the onBlur

**Comment by stephanie-dm** [comment] 2017-03-13 08:47
This looks like a duplicate of https://github.com/primefaces/primeng/issues/1387

**Closed** 2017-03-22 11:47 UTC
Labels: new feature
