### ISSUE TITLE
Turbo Table empty message always showing even when table has data

### ISSUE THREAD

**Issue by hugonoro** [primefaces/primeng#8637] opened 2020-03-19 12:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-qvrget?file=src%2Fapp%2Fapp.component.html

from the analysis of the code differences between 9.0.0 and 9.0.1 this is what is different 

**9.0.0**
```
<ng-container *ngIf="dt.isEmpty()">
    <ng-container *ngTemplateOutlet="dt.emptyMessageTemplate; context: {$implicit: columns, frozen: frozen}"></ng-container>
  </ng-container>
```

**9.0.1**
```
<ng-container *ngIf="dt.loading; else empty">
            <ng-container *ngTemplateOutlet="dt.loadingBodyTemplate; context: {$implicit: columns, frozen: frozen}"></ng-container>
        </ng-container>
        <ng-template #empty>
            <ng-container *ngTemplateOutlet="dt.emptyMessageTemplate; context: {$implicit: columns, frozen: frozen}"></ng-container>
        </ng-template>
```

I believe the new version is missing the check if **dt.isEmpty()**

**Current behavior**

The turbo table seems to always be showing the emptymessage template, even though there's data in the table

**Expected behavior**

Empty message should not be showing when the table has data

**Minimal reproduction of the problem with instructions**

The error will be immediately spotted when opening the provided example stackblitz

**What is the motivation / use case for changing the behavior?**

This breaks the correct expected functionality of a table with data

**Please tell us about your environment:**

* **Angular version:** 9.x

* **PrimeNG version:** 9.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gmerabishvili** [comment] 2020-03-19 21:22
Same happens with me on version 9.0.1. I've many tables in my project and it seems really awkward issue : ( Please fix it as soon as possible...

**Comment by cagataycivici** [comment] 2020-03-20 07:47
Looks like a regression that slipped through, we'll do 9.0.2 today.

**Comment by yigitfindikli** [comment] 2020-03-20 09:26
Fixed in https://github.com/primefaces/primeng/commit/c74ad8545f12f02bdf1c4912f0726eb23187b9ca

**Closed** 2020-03-20 09:26 UTC
Labels: defect

**Comment by cagataycivici** [comment] 2020-03-20 09:56
4.0.2 is released with the fix.
