### ISSUE TITLE
ToggleSwitch v18: Missing hover styles

### ISSUE THREAD

**Issue by TaneliTuomola** [primefaces/primeng#16482] opened 2024-10-03 07:37 UTC
### Describe the bug

The styles of the element remain the same when you move the cursor over it.

### Environment

https://v18.primeng.org/toggleswitch

### Reproducer

https://v18.primeng.org/toggleswitch

### Angular version

18.0.5

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

### Steps to reproduce the behavior

https://v18.primeng.org/toggleswitch

### Expected behavior

https://primevue.org/toggleswitch/

**Comment by cetincakiroglu** [comment] 2024-10-15 13:06
Hi,

Thanks a lot for reporting the issue. The issue is fixed in https://github.com/primefaces/primeng/commit/aba2fa5677349beed6e81fe84a3548a209084b5f

**Closed by cetincakiroglu** 2024-10-15 13:06 UTC
Labels: Type: Bug
