### ISSUE TITLE
Add draggable row support to DataTable

### ISSUE THREAD

**Issue by jayeffaar** [primefaces/primeng#926] opened 2016-09-19 21:24 UTC
This has been discussed here, but I couldn't see an existing issue that addresses it directly:
http://forum.primefaces.org/viewtopic.php?f=35&t=45785&p=143165&hilit=draggable#p143165

It is related to https://github.com/primefaces/primeng/issues/504 (_Datatable drag row ( Row reorder ) feature same as PrimeFaces data table_), except that we would like to be able to drag rows out of the DataTable, and drop them unto another component, in this case Tree nodes (which is itself another open issue: https://github.com/primefaces/primeng/issues/683).

**Comment by taivu** [comment] 2017-05-11 17:23
would also love this feature.

**Comment by cagataycivici** [comment] 2017-05-31 08:01
Duplicate of #504

**Closed by cagataycivici** 2017-05-31 08:01 UTC
