### ISSUE TITLE
Confirm Dialog IE 11 errors

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primeng#7577] opened 2019-04-23 14:51 UTC
I get the following error in V7 with IE 11, even on the primeng website I get the same error:

Uncaught (in promise): Error: The animation trigger "animation" has failed to build due to the following errors
 The provided animation property "-webkit-transform" is not a supported CSS property for animations

I rolled back to 7.1.0 with no issues

**Comment by dmoore1181** [comment] 2019-04-23 15:22
Same here, simply commenting out the '-webkit-transform':'translateX(-50%) translateY(-50%)', line in confirmdialog.ts fixes the issue (though the animation is a bit jumpy in IE11, but still works properly in Chrome.

**Comment by mertsincan** [comment] 2019-04-25 13:00
Fixed for 7.1.3. (Duplicate of #7597)

**Closed by mertsincan** 2019-04-25 13:00 UTC

**Comment by mthor** [comment] 2019-05-08 18:18
When is the release of 7.1.3, we need to out, getting complaints

**Comment by SeinopSys** [comment] 2019-05-23 09:16
@mthor I've just ran `npm update` and it appears to have installed 7.1.3

**Comment by mthor** [comment] 2019-05-23 13:49
yes, I have updated, not the break on ie11 is grids don't load, you have to click the mouse or scroll over something and it loads the grid one record at a time
