### ISSUE TITLE
p-button: disabled p-button doesn't work

### ISSUE THREAD

**Issue by theophane-girard** [primefaces/primeng#12692] opened 2023-03-01 10:51 UTC
### Describe the bug

We can click on disabled buttons when using p-button tag: 

[stackblitz](https://stackblitz.com/edit/angular-zkup5y?file=src/main.ts)

disabled works only when using <button pButton> directive

Even if the doc says to use onClick instead of angular native (click),  we shouldn't be able to click on a disabled button

### Environment

basic app

### Reproducer

https://stackblitz.com/edit/angular-zkup5y?file=src/main.ts

### Angular version

15.2

### PrimeNG version

15.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

**Comment by jucasoft** [comment] 2023-03-03 11:23
#12495

**Comment by rcollette** [comment] 2023-03-13 22:55
Duplicate of #12495

**Comment by nur-psoehnlein** [comment] 2023-08-04 07:22
I fell into the same trap and expected `(click)` to just work (like `(onClick)`, which I wasn't aware of until I looked in the issue tracker). That's actually my fault, but I think it's a common one and maybe the PrimeNG folks might consider adjusting this behaviour.

**Comment by mertsincan** [comment] 2023-08-18 15:50
Fixed in https://github.com/primefaces/primeng/commit/919f892af7d4ed95fbe3890b0eaa6d78d346dd0c

**Closed by mertsincan** 2023-08-18 15:50 UTC
Labels: Type: Bug
