### ISSUE TITLE
Column reordering support for Scrollable DataTable

### ISSUE THREAD

**Issue by rokkuci** [primefaces/primeng#2399] opened 2017-03-28 13:19 UTC
Any ideas when it will be fixed for Angular 2?

**Comment by jayordway** [comment] 2017-05-18 22:24
I am still having this problem too

**Comment by mattfaces** [comment] 2017-06-21 22:22
In case it helps... If the datatable did the rearranging of the columns directly in this.scrollableColumns instead of (or maybe in addition to) this.columns then the reordering appears to paint properly. Note that I didn't look into why the drag insertion arrows aren't painting properly (probably something to do with the different DOM structure e.g. frozen vs. unfrozen areas)--I only looked at what the datatable TS code is doing when reordering the column positions in case maybe you want to provide a non-drag-and-drop mechanism for reordering the columns (e.g. an overlay menu).

**Comment by jayordway** [comment] 2017-06-29 16:57
any updates?

**Comment by schmuli** [comment] 2017-10-25 16:36
Duplicate of #3910, which has been fixed and closed.

**Comment by cagataycivici** [comment] 2018-01-13 22:37
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Closed by cagataycivici** 2018-01-13 22:37 UTC
Labels: enhancement
