### ISSUE TITLE
ConfirmDialog: Mask transition not working

### ISSUE THREAD

**Issue by LexanRed** [primefaces/primeng#13015] opened 2023-05-10 11:59 UTC
### Describe the bug

When using the ConfirmDialog, the transition effects are not applied to the mask. 

In the docs it says the default for `transitionOptions` is `400ms cubic-bezier(0.25, 0.8, 0.25, 1)`

That applies to the pop up it self, but not the masking background. 

Especially visible if you set the transition time to an artificially big value like 4000ms. You can watch the pop up unfold, the mask just appears / disappears when closing. 

In other components like the DynamicDialog the background mask is fading in as expected.

### Environment

MacOS 13.3.1

### Angular version

16.0.0

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

When opening and closing a ConfirmDialog, the background mask should fade in and out.

**Comment by cetincakiroglu** [comment] 2023-07-26 13:49
Hi,

Cannot replicate the issue, which does not exist in the live demo. Closing the issue since it cannot reproducible.

**Closed by cetincakiroglu** 2023-07-26 13:49 UTC
Labels: Status: Needs Triage
