### ISSUE TITLE
Calendar have not a manually method for close pop up

### ISSUE THREAD

**Issue by alejandrohn** [primefaces/primeng#2541] opened 2017-04-17 19:13 UTC
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
<!-- Describe how the bug manifests. -->

**Expected behavior**
<!-- Describe what the behavior would be without the bug. -->

**Minimal reproduction of the problem with instructions**
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
-->

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->
**Please tell us about your environment:**

Ubuntu 14.04, Webstorm

* **Angular version:** 4.0.1
<!-- Check whether this is still an issue in the most recent Angular version -->

* **PrimeNG version:** 2.0.3
<!-- Check whether this is still an issue in the most recent Angular version -->

* **Browser:** [all | Chrome 54 | Firefox 52]
<!-- All browsers where this could be reproduced -->
 
* **Language:** [ TypeScript 2.2.1  | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.4

**Comment by sudheerj** [comment] 2017-04-25 10:31
This issue is not a valid one by without describing the issue exactly.It is good provide some description on expected result.

**Comment by cagataycivici** [comment] 2017-06-22 13:53
Duplicate of #2001

**Closed by cagataycivici** 2017-06-22 13:53 UTC
