### ISSUE TITLE
p-autocomplete single-select issues

### ISSUE THREAD

**Issue by miked1090** [primefaces/primeng#3701] opened 2017-08-18 15:16 UTC
**I'm submitting a ...**
[X] bug report

**Current behavior**
Behavior between single and multi-select options is inconsistent. The multi-select works much better, you can clear options and it doesn't affect the model until you select an option. The single-select has no way to clear and sets the model as the searchterm until you select an option. You can then delete characters from the selected item and the model goes back to being the searchterm.

**Expected behavior**
The single-select has a clear icon. The model is only set by selecting an option and you can not alter a selection once it's made.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/6OcudSc6gPDaFwUZjY2m?p=preview

Type in the first box, which is single-select and check out the model that is being output and then do the same with the multi-select.

* **Angular version:** 4.3.5

* **PrimeNG version:** 4.1.3

* **Language:** All

**Comment by alokkarma** [comment] 2017-08-23 07:11
Yeah this functinality is not there but you can create your own clear button for it: 

`<button (click) = "onclick()">Clear</button>`
`onclick() {
    this.selectedItem ='';
  }`

**Comment by cagataycivici** [comment] 2017-10-20 07:35
Duplicate of #3660

**Closed by cagataycivici** 2017-10-20 07:35 UTC
