### ISSUE TITLE
DataTable : Horizontal Scroll issue with resizable and reorderable columns

### ISSUE THREAD

**Issue by rajhiMeher** [primefaces/primeng#3336] opened 2017-07-10 10:39 UTC
Current behavior : 
When using scrollable="true" and fixing scrollHeight or scrollWidth, the functionnalities "resizable and reorderable columns" doesn't work any more.

Expected behavior 
Coexist the Horizontal Scroll with resizable and reorderable columns.

Angular version : 4.2.5
PrimeNG version: 4.1.0-rc.3

**Comment by cagataycivici** [comment] 2017-08-23 07:53
Duplicate of 2399

**Closed by cagataycivici** 2017-08-23 07:53 UTC
