### ISSUE TITLE
p-progressBar : Value not correctly displayed

### ISSUE THREAD

**Issue by titom59280** [primefaces/primeng#11946] opened 2022-09-19 09:12 UTC
### Describe the bug

Since the 13.0.0 version, the value of the progress bar is not displayed in the middle of the bar but in the middle of the colored bar.

The result is that the value is not correctly displayed when the value is inferior to 4% and the value is moving with the progression.

### Environment

Angular CLI: 14.2.2
Node: 16.13.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 14.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.2
@angular-devkit/build-angular   14.2.2
@angular-devkit/core            14.2.2
@angular-devkit/schematics      14.2.2
@schematics/angular             14.2.2
rxjs                            6.5.5
typescript                      4.7.4

### Reproducer

https://stackblitz.com/edit/github-pvrewt?file=src/app/app.component.html

### Angular version

14.2.2

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

Chrome 105.0.5195.102

### Steps to reproduce the behavior

1. Add a progressBar component with a value equals to (1, 2,3).
2. See the result with the value truncated

### Expected behavior

Display the value in the middle of the progressBar in order to see it even when the value is 1%

**Comment by cetincakiroglu** [comment] 2022-09-30 11:05
Hi,

It's by design not a bug or defect so labeling the issue as "wont fix".

**Closed by cetincakiroglu** 2022-09-30 11:05 UTC
Labels: defect

**Comment by AvshT** [comment] 2024-11-05 10:20
Hi, I believe this CSS should resolve your issue:
```

.p-progressbar {
    height: 20px;
    border-radius: 3px;

    .p-progressbar-value {
        position: unset;
    }

    .p-progressbar-label {
        text-align: center;
        height: 100%;
        width: 100%;
        font-weight: 700;

        div {
            position: absolute;
            margin-left: calc(50% - 12px);
            top: 8px;
        }
    }
}

```
