### ISSUE TITLE
columnFilter: unwanted close on mouseup

### ISSUE THREAD

**Issue by Wykks** [primefaces/primeng#14410] opened 2023-12-20 14:03 UTC
### Describe the bug

When you when you want to select a part of the text inside a input of a columnFilter and release the click of the mouse a bit late (when the cursor is outside the filter frame),

PR for fix : https://github.com/primefaces/primeng/pull/14411

### Environment

N/A

### Angular version

17.x

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

**Comment by cetincakiroglu** [comment] 2023-12-28 10:56
Hi,

It closes because you're releasing the mouse button outside of the div which is the intended behavior and should close the filter popup if outside is clicked. The behavior is correct.

**Comment by cetincakiroglu** [comment] 2023-12-28 11:00
Fixed in https://github.com/primefaces/primeng/pull/14411

**Closed by cetincakiroglu** 2023-12-28 11:00 UTC
Labels: Type: Bug
