### ISSUE TITLE
Editor: Not working with quilljs v2.0.0 and above

### ISSUE THREAD

**Issue by asithade** [primefaces/primeng#15741] opened 2024-05-29 21:12 UTC
### Describe the bug

When using p-editor with quilljs v2.0.0 and above, reactive form and ngmodel does not prepopulate the field if you preset its value. 

### Environment

    "@angular/animations": "^17.3.9",
    "@angular/cdk": "17.3.9",
    "@angular/common": "^17.3.9",
    "@angular/compiler": "^17.3.9",
    "@angular/core": "^17.3.9",
    "@angular/forms": "^17.3.9",
    "@angular/platform-browser": "^17.3.9",
    "@angular/platform-browser-dynamic": "^17.3.9",
    "@angular/router": "^17.3.9",
    "primeng": "^17.17.0",
    "quill": "^2.0.1",

### Angular version

17.3.9

### PrimeNG version

17.17.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Browser(s)

Brave

### Steps to reproduce the behavior

- Set a default value via class variable and set it it to p-editor [(ngModel)]
- Set a default value via reactive forms 

https://stackblitz.com/edit/lww9qn?file=src%2Fapp%2Feditor-reactive-forms-demo.ts

### Expected behavior

It should prepopulate the fields with the preset text

**Comment by brucevilo1013** [comment] 2024-06-05 14:31
Yeah, this was working in primeng-editor with quill 1.3.7, but It does not work in quill 2.x.
Now I use quill 1.3.7 as temporary solution, but should be replaced it with quill 2.x.
In quill 1.3.7, the copy/paste of word document does not keep its format and It is broken.
Please address this issue soon.

**Comment by jonatanpetersson** [comment] 2024-06-10 14:42
Have the same issue.

**Comment by PhuocHoangMinhNguyen** [comment] 2024-06-12 00:30
I can confirm this is an issue with quill 2.x compatibility with PrimeNG

**Comment by ThoSap** [comment] 2024-06-14 09:24
Duplicate of #14721

**Comment by zhengangguo** [comment] 2024-07-04 01:43
Have the same issue, please fix.

**Comment by mehmetcetin01140** [comment] 2024-07-04 11:59
Fixed in https://github.com/primefaces/primeng/pull/15764. Thanks for reporting, closing the issue

**Closed by mehmetcetin01140** 2024-07-04 11:59 UTC
Labels: Status: Needs Triage

**Comment by mathankumaryesaian** [comment] 2024-08-30 10:23
if i pasted the copied table data not supported in quill version 1.3.7 and above 2.0.0 also.I am using primen  v14
