### ISSUE TITLE
Type 'TreeNode<any> | TreeNode<any>[] | null' is not assignable to type 'TreeNode<any>'.   Type 'null' is not assignable to type 'TreeNode<any>'Component: Title

### ISSUE THREAD

**Issue by troncomputers** [primefaces/primeng#13364] opened 2023-07-25 10:05 UTC
### Describe the bug

Tree selection not working because of null checking

### Environment

Angular CLI: 16.1.3
Node: 18.16.0
Package Manager: npm 9.7.2
OS: win32 x64

Angular: 16.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server 
... router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@schematics/angular             16.1.3
rxjs                            7.8.1
typescript                      4.9.5

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-9y5an3?file=src%2Fmain.ts
### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

MS Edge

**Comment by cetincakiroglu** [comment] 2023-07-27 09:17
Duplicate of https://github.com/primefaces/primeng/issues/13183
Fixed in 16.1.0

Closing the issue since it's fixed, if the problem persists please re-open the issue.

**Closed by cetincakiroglu** 2023-07-27 09:17 UTC
Labels: Resolution: Duplicate

**Comment by dbdrivenadmin** [comment] 2023-08-25 14:36
I know this was closed, but if you use the strict templates option in your tsconfig angular settings this still occurs in 16.2.0 (  "angularCompilerOptions": { "strictTemplates": true } ).  The selection property of the tree is set to "any" when I believe it should be "TreeNode<any> | TreeNode<any>[] | any[] | any" the same as value.  Typically, I prefer strict options to keep me from making silly mistakes.
