### ISSUE TITLE
LazyLoadEvent interface definition inconsistency

### ISSUE THREAD

**Issue by hasanmutlu** [primefaces/primeng#10294] opened 2021-06-02 11:11 UTC
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tablefilter-demo-wfy8ud?file=src/app/app.component.html

**Current behavior**
In this example (taken from https://primefaces.org/primeng/showcase/#/table/filter), If lazy loading is enabled, for the first table filters values in the LazyLoadEvent is defined as FilterMetadata[] but for the second table is defined FilterMetadata.

**Expected behavior**
filters object of LazyLoadEvent should be defined as 
[s: string]: FilterMetadata | FilterMetadata[]; or 
[s: string]: FilterMetadata[]; 

**Minimal reproduction of the problem with instructions**
using LazyLoad feature in tables that have filtering feature

**Please tell us about your environment:**

* **Angular version:** 11.2.11

* **PrimeNG version:** 11.4.0

* **Browser:** [Chrome 90]

**Comment by m11t** [comment] 2021-08-24 10:31
I think this is a duplicate of #10055

**Comment by nev-21** [comment] 2022-09-17 04:04
duplicate of #11549

**Comment by nev-21** [comment] 2022-09-17 04:06
source code:

https://github.com/primefaces/primeng/blob/043a9d2e3202d0a359d424937c508768158a200e/src/app/components/table/table.ts#L229

https://github.com/primefaces/primeng/blob/f820e626681553162523d3d81853019c158e2629/src/app/components/api/lazyloadevent.ts#L11

**Comment by mertsincan** [comment] 2022-11-09 20:15
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Closed by mertsincan** 2022-11-09 20:15 UTC
Labels: pending-review
