### ISSUE TITLE
Table header hides when scrolling

### ISSUE THREAD

**Issue by dimitev** [primefaces/primeng#10887] opened 2021-11-26 09:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/table/virtualscroll

**Current behavior**
The header of the table hides as you scroll. See attached video

**Expected behavior**
The header to stay visible at the top of the table

**Minimal reproduction of the problem with instructions**
This reproduces on the official site, does not reproduce in stackbiz.

**What is the motivation / use case for changing the behavior?**
<To make scrolling smooth and polished

**Please tell us about your environment:**
Desktop, Windows 10

* **Angular version:** 13

https://user-images.githubusercontent.com/26581552/143562265-aa6c0c72-1a40-4a23-ba3b-98a421c90981.mp4

* **PrimeNG version:** 13
Does not reproduce on 12

* **Browser:** 
Chrome  96.0.4664.45| Firefox XX  and maybe other

**Comment by yigitfindikli** [comment] 2021-11-26 10:22
Duplicate of https://github.com/primefaces/primeng/issues/10630

**Closed** 2021-11-29 14:17 UTC
Labels: defect

**Comment by mcrtricolor** [comment] 2021-12-03 14:04
Hello. This still happens using prime 13.0.1 and angular 13.0.3

If you scroll slowly it does it well, but if you go a little strong on the scroll the header dissapears or go down with all the rows, depending on whether you go up or down.

**Comment by yigitfindikli** [comment] 2021-12-06 10:19
Hi @mcrtricolor,

They are not the same issue. You can track it at https://github.com/primefaces/primeng/issues/10630.
