### ISSUE TITLE
Error 'Maximum call stack size exceeded' angular 12 - Primeng 12

### ISSUE THREAD

**Issue by gzayat** [primefaces/primeng#10577] opened 2021-09-02 23:15 UTC
**I'm submitting a ...**
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
It is not possible to demonstrate on stackblitz because it is a bug at compile time for an angular library.
Find a minimalistic library project here (it is just a ButtonModule importer on an empty library) :
![erro prim](https://user-images.githubusercontent.com/35319782/131927713-31b69045-f818-4dc5-a391-61d0e6e64fe2.png)

**Current behavior**
✖ Compiling with Angular in legacy View Engine compilation mode. Maximum call stack size exceeded

**Expected behavior**
The build should work (it works with primeng11.4.0)

**Minimal reproduction of the problem with instructions**

**Create a project with**
Angular 12 - 12.2.4
Primeng 12 - 12.1.0
typescript 4.3.5
ng-packagr 12.2.1

Then import ButtonModule in the lib module

**Then run :**
ng-packagr -p projects/testlib/ng-package.json

**What is the motivation / use case for changing the behavior?**
Our libraries don't compile anymore

Please tell us about your environment:
terminal

Using as described above to generate component the system generates an error.
BUT using npm run build  not problem !!!
Problem with generate component

**Using the following configuration the error does not happen.**
Angular 12.2.4
Primeng 11.4.0
typescript 4.3.5
ng-packagr 12.2.1

**Comment by yigitfindikli** [comment] 2021-09-03 14:45
Duplicate of https://github.com/primefaces/primeng/issues/10515

**Closed by yigitfindikli** 2021-09-03 14:45 UTC
