### ISSUE TITLE
Datatable: row click event ignored when not on a span

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#1878] opened 2017-01-21 10:24 UTC
primeng 2.0.0-rc.1

When a column body template contains elements other than span, then click events are ignored.
You can check this on the showcase (http://www.primefaces.org/primeng/#/datatable/selection) by editing the html and replacing a column content with the following:
```
<span  class="ui-cell-data">
  <div>1995</div>
  <span style="display:inline-block; width: 20px; height: 20px; border: 1px solid red"></span>
</span>
```
Then clicking on the 1995 label does not work anymore, while clicking on the red span works normally.

**Comment by marcuskrahl** [comment] 2017-01-27 10:18
This behaviour seems to be hardcoded into PrimeNG. This is part of the handler for clicks of rows: 
```
(targetNode == 'TD' || (targetNode == 'SPAN' && !this.domHandler.hasClass(event.target, 'ui-c'))
```

**Comment by cagataycivici** [comment] 2017-06-28 09:51
Duplicate of #1485

**Closed by cagataycivici** 2017-06-28 09:51 UTC
Labels: review
